### ISSUE TITLE
[IOS] incorrect zoomLevel value in onRegionDidChange 

### ISSUE THREAD

**Issue by bboure** [react-native-mapbox-gl/maps#1001]
**Describe the bug**
In the `onRegionDidChange` callback, a Geojson is passed, which should contain the [zoomLevel and other properties](https://github.com/react-native-mapbox-gl/maps/blob/master/index.d.ts#L371-L376)
When I set `defaultSettings` with some bounds, the very first time the function is called (after the map is loaded), the `zoomLevel` value is wrong.
After moving the map, onRegionDidChange is called again, and the value is correct. 
This happens on ISO only. On Android, this is working fine.

**To Reproduce**

Example:
```js
import React from 'react';
import MapboxGL from '@react-native-mapbox-gl/maps';

const Map = () => {
  return (
    <MapboxGL.MapView
      style={{
        flex: 1,
      }}
      styleURL="https://api.maptiler.com/maps/7b709a0c-75e9-416f-abbd-21ab8ba23fb1/style.json?key=pO5SHrAkHnfh9tCaeC6G"
      onRegionDidChange={async ({ properties: { zoomLevel } }) => {
        console.log({ zoomLevel });
      }}
    >
      <MapboxGL.Camera
        defaultSettings={{
          bounds: {
            sw: [2.15124, 41.379844],
            ne: [2.191296, 41.41393],
          },
        }}
      />
    </MapboxGL.MapView>
  );
};

export default Map;
```

With the above example, I get a zoomLevel of `9.95177514813105` after loading the map.
If I pan the map, (zoom did not change), I get  `12.827177868957447`, which seems to be the correct value.

**Expected behavior**
`zoomLevel` should always receive the right value.

**Versions (please complete the following information):**
 - Platform: IOS
 - Device: Simulator (don't have an Iphone, cannot test on a real device)
 - Emulator/ Simulator: yes
 - OS: iOS 13.6
 - react-native-mapbox-gl Version 8.0.0
 - React Native Version 0.63.2

**Comment by ferdicus** [comment]
I know it's a hassle, but please make sure to fill out all required fields of the issue template.
What version of the lib was this for example, was this on the simulator or on a real device. 

Thanks

**Comment by bboure** [comment]
Sorry @ferdicus  I just updated the issue with the required info
