### ISSUE TITLE
Map not loading in Android 

### ISSUE THREAD

**Issue by thanmaic** [react-native-mapbox-gl/maps#1003]
Hi,
I am using mapbox for my react native project. I tried to render a simple map view on both iOS and Android, it loads on iOS but i see blank in Android. I am not sure what the issue is about and I am stuck with this for about 2 days please can anyone help me on this?

**React Native version: 0.51.0
RN mapbox version: 6.0.2**

Since we have an older version of react native in our project to match that i choose a lower version of mapbox that works for it, based on the docs. **I also tried on the RN mapbox 6.1.3 version, i have the same issue map doesn't load in Android but works on iOS.**

Example:

MapboxGL.setAccessToken('pk.eyJ1IjoiaXR6bW******');
const columbusCircleCoordinates = [-73.98197650909422, 40.768793007758816];

<MapboxGL.MapView
        ref={(c) => (this._map = c)}
        style={{ flex: 1 }}
        zoomLevel={15}
        centerCoordinate={columbusCircleCoordinates}
/>

<img width="792" alt="Screenshot 2020-08-24 at 12 45 11 PM" src="https://user-images.githubusercontent.com/50735542/91014839-ba1f6280-e607-11ea-8711-35323d661161.png">

Thanks

**Comment by virtumonde** [comment]
Do do you get any errors? Check the logs.

**Comment by ferdicus** [comment]
Sorry, however we do not have the capacity to verify all previous versions on older RN and android device versions.
Please follow @virtumonde suggestion and check the logs, feel free to post them here. 

Also, please fill out the template correctly, with _all_ fields.
Will close, we can reopen once you've added additional information
