### ISSUE TITLE
React native failed to obtain last location.

### ISSUE THREAD

**Issue by jaaouani-glitch** [react-native-mapbox-gl/maps#1010]
I'm trying to use Mapbox on my app, few days ago it was doing great but then on my react-native project I get this error: Mapbox Error last update unavailable on Android but not on iOS, I'm using Mapbox.UserLocation component like this:

 <MapboxGL.MapView style={{ flex: 1 }} 
    compassEnabled={false} 
    attributionEnabled={false} 
    zoomEnabled 
    logoEnabled={false} 
    onUserLocationUpdate={this.onLocationUpdate}>
        <MapboxGL.UserLocation 
              onUpdate= {this.onLocationUpdate} />
</MapboxGL.MapView>
I'm running and Flipper 0.52.0

"react-native": "^0.62.2",
"@react-native-mapbox-gl/maps": "^8.1.0-rc.2",

PLEASE HELP.

**Comment by ferdicus** [comment]
Please respect the issue template - information is missing

**Comment by jaaouani-glitch** [comment]
Sorry, but the solution was just to enable HighAccuracy on my android phone.
