### ISSUE TITLE
Map Screen Turns into Blue

### ISSUE THREAD

**Issue by johnneuland** [react-native-mapbox-gl/maps#1011]
**Describe the bug**
I have a screen where I show the users current location. Every now and then, the map screen turns into blue. There's no error but its just blue. 

Someone on the Gitter page of react-native-mapbox-gl/Lobby said:
If what you see is a blue screen, it might be that the map does not get the location and you are just in lat and lng 0 which is the middle of the ocean.

If this is the case, then how can we fix this? Why is the location randomly set to lat and long 0?

**To Reproduce**
```
export const MapContainer: React.FunctionComponent = () => {
  const map = useRef<MapboxGL.Camera>(null);
  const [coords, setCoords] = useState([8.213889, 53.14389]); //Oldenburg default
  const dispatch = useDispatch();
  const locationPermissions = useTypedSelector(
    (state) => state.locationPermissions,
  );
  const locations = useTypedSelector((state) => state.locations);
  const mapVariables = useTypedSelector((state) => state.map);

  useEffect(() => {
    showMySelectedJourney();
  }, [mapVariables.bounds]);

  useEffect(() => {
    Geolocation.getCurrentPosition(goToMyLocation);
  }, [locationPermissions.isUseLocationPermitted]);

  const goToMyLocation = (position: GeoPosition) => {
setCoords([position.coords.longitude, position.coords.latitude]);
    map.current?.moveTo([position.coords.longitude, position.coords.latitude]);
    map?.current?.zoomTo(14);
  };


  const showMySelectedJourney = async () => {
if (mapVariables.bounds) {
      map.current?.fitBounds(mapVariables.bounds.ne, mapVariables.bounds.sw, [
        moderateScale(150),
        moderateScale(30),
        moderateScale(30),
        moderateScale(30),
      ]);
    }
  };

  const setCurrentPositionOnMap = (position: GeoPosition) => {
    setCoords([position.coords.longitude, position.coords.latitude]);

  };
  const getCurrentPosition = () => {
    Geolocation.getCurrentPosition(setCurrentPositionOnMap);
  };

  return (
    <View style={styles.mapContainer}>
      <MapboxGL.MapView
        style={styles.map}
        logoEnabled={false}
        onWillStartRenderingMap={getCurrentPosition} 
        localizeLabels={true}>
        <MapboxGL.Camera
          bounds={mapVariables.bounds}
          ref={map}
          zoomLevel={10}
          animationMode={'flyTo'}
          animationDuration={1000}
          followUserLocation={false} 
          followUserMode={'normal'}
          centerCoordinate={coords}
        />
        <MapboxGL.UserLocation
          visible={locationPermissions.isUseLocationPermitted}}
        />
        {locations.endPoint.coordinates.length > 0 &&
        locations.startingPoint.coordinates.length > 0 ? (
          <MapRoute
            destination={locations.endPoint}
            start={locations.startingPoint}
          />
        ) : null}
      </MapboxGL.MapView>
    </View>
  );
};
```

**Expected behavior**
The user location should always be detected. Blue screen should not show up.

**Versions (please complete the following information):**
 - Platform: [Android, iOS]
 - Emulator/ Simulator: [problem occurs in emulator and physical devices both]
 - react-native-mapbox-gl/maps Version [8.1.0-rc.2]
 - React Native Version [3.0.4]

**Comment by ferdicus** [comment]
That can't be a correct React Native Version.

Can you explain your use case please, like when is the issue happening.
Another question: Why are you using an external service to get the current position?

**Comment by johnneuland** [comment]
This is what I get when I check with ```react-native --version```. By external service, do you mean react-native-geolocation-service? How else can I get user location such that I can automatically pass it to my mapView and CameraView every time I visit the screen? 

The user location part generally works fine. However, sometimes when the app crashes due to some other error and we reload it on the simulator, when we visit this screen the map is just a blue screen. It happens randomly. Maybe some timeout would help but not sure where.

**Comment by ferdicus** [comment]
>  This is what I get when I check with react-native --version.
That's the `react-native-cli` tools version. 
We're asking which version of `react-native` you've defined in your projects `package.json`.

> By external service, do you mean react-native-geolocation-service? How else can I get user location such that I can automatically pass it to my mapView and CameraView every time I visit the screen?
You can add a `UserLocation` component to your `MapView` and add a callback function to its `onUpdate` method.
That will fire everytime a location update is triggered by Mapbox. No need for an external dependency to get the users location.

> The user location part generally works fine. However, sometimes when the app crashes due to some other error and we reload it on the simulator, when we visit this screen the map is just a blue screen. It happens randomly. Maybe some timeout would help but not sure where.
My suspicion is, that there is some kind of race condition between grabbing the users location and displaying the map. 
My suggestion: Wait till you get a position before displaying the map

**Comment by johnneuland** [comment]
You mean I should not use the function on ```onDidFinishRenderingMap```? I am already using ```UserLocation```. I am not sure what callback to add within ```onUpdate```. 

Could you suggest how exactly can I "Wait till you get a position before displaying the map"

**Comment by ferdicus** [comment]
> You mean I should not use the function on onDidFinishRenderingMap?
Check which one works best for your useCase, there are other callbacks like `onDidFinishRenderingMapFully` which might work better - trigger correctly.

> I am already using UserLocation. I am not sure what callback to add within onUpdate.
You could add `setCurrentPositionOnMap` as the callback on `UserLocations` `onUpdate`. 
Everytime mapbox gets the user location it would set the coordinates of this component. 


In your components `return` you have a check (pseudocode below):
```js
if (mapFullyRendered && currentUserPositionAvailable) {
  // return my component to be rendered
} else {
  return null;
}
```
