### ISSUE TITLE
ImageSource coordinates do not update

### ISSUE THREAD

**Issue by ewc003** [react-native-mapbox-gl/maps#1013]
**Describe the bug**
I would like to update the coordinates of the ImageSource when the image URL changes.
The image does change when the URL changes, but the coordinates do not change. I have modified the heartbeat function in the example ImageOverlay component and also added the constant variable coordQuads which contains two different sets of coordinates.

**To Reproduce**
Clone maps example app.
Copy new ImageOverlay.js code (below). 
Run yarn android.

Example Code (ImageOverlay.js):
```
import React from 'react';
import MapboxGL from '@react-native-mapbox-gl/maps';

import sheet from '../styles/sheet';
import radar0 from '../assets/radar.png';
import radar1 from '../assets/radar1.png';
import radar2 from '../assets/radar2.png';

import Page from './common/Page';
import BaseExamplePropTypes from './common/BaseExamplePropTypes';

const frames = [radar0, radar1, radar2];
const coordQuads = [
  [
    [-80.425, 46.437], // top left
    [-71.516, 46.437], // top right
    [-71.516, 37.936], // bottom right
    [-80.425, 37.936], // bottom left
  ],
  [
    [-85.425, 45.437], // top left
    [-75.516, 45.437], // top right
    [-75.516, 36.936], // bottom right
    [-85.425, 36.936], // bottom left
  ],
];

class ImageOverlay extends React.Component {
  static propTypes = {
    ...BaseExamplePropTypes,
  };

  constructor(props) {
    super(props);

    this.state = {
      radarFrameIndex: 0,
      coords: coordQuads[0],
    };

    this._timeout = null;
  }

  componentDidMount() {
    this.heartbeat();
  }

  heartbeat() {
    this._timeout = setTimeout(() => {
      requestAnimationFrame(() => {
        let nextFrame = this.state.radarFrameIndex + 1;
        if (nextFrame > 1) {
          nextFrame = 0;
        }
        this.setState({radarFrameIndex: nextFrame, coords: coordQuads[nextFrame]})
        this.heartbeat();
      });
    }, 500);
  }

  componentWillUnmount() {
    if (this._timeout) {
      clearTimeout(this._timeout);
    }
  }

  render() {
    return (
      <Page {...this.props}>
        <MapboxGL.MapView
          ref={(ref) => (this.map = ref)}
          style={sheet.matchParent}
          styleURL={MapboxGL.StyleURL.Satellite}>
          <MapboxGL.Camera
            zoomLevel={5.2}
            centerCoordinate={[-75.789, 41.874]}
          />

          <MapboxGL.Animated.ImageSource
            key="d"
            id="radarSource"
            coordinates={this.state.coords}
            url={frames[this.state.radarFrameIndex]}>
            <MapboxGL.RasterLayer id="radarLayer"
            style={{rasterOpacity: .6}} />
          </MapboxGL.Animated.ImageSource>
        </MapboxGL.MapView>
      </Page>
    );
  }
}

export default ImageOverlay;

```
**Expected behavior**
I expect the ImageSource to change shapes as the heartbeat function continues to run.
Only the image changes (as expected since the URL is changing) and the coordinates stay the same.
I have logged the coordinates (this.state.coords) and they are being updated.

**Versions (please complete the following information):**
 - Platform: Android
 - Device: Pixel 2
 - Emulator/ Simulator: yes
 - OS: Android 28
 - react-native-mapbox-gl Version: 6.4.1
 - React Native Version: 0.62.1

**Additional context**
I have also run this on a physical device.
Samsung Galaxy Tab A

Thanks for your time.

**Comment by ferdicus** [comment]
@ewc003, you don't know by any chance if this is also happening on iOS, do you?

**Comment by ewc003** [comment]
@ferdicus I'm not sure about that one. I only have access to Android as of now.

**Comment by ewc003** [comment]
@ferdicus I have tested the same code on IOS and I have the same issue.
I am running the same ImageOverlay component on iPhone SE (2nd generation) (IOS 13.6).
The image will update but the coordinates that the image covers does not change. Please let me know if you have any ideas on how to fix this.

**Comment by janweigel** [comment]
Same problem here on Android and iOS.
The coordinates of MapboxGL.ImageSource do not update which is a real show stopper for many scenarios.

**Comment by ferdicus** [comment]
@ewc003 , this is partially fixed in #1036.
Unfortunately only for Android as I can't understand the iOS portion of the code 😞 

Can't you maybe give it a spin and verify the fix? 

Thanks 🙇

**Comment by ewc003** [comment]
@ferdicus This is great, just what I wanted! Thanks so much for your time and help, I appreciate it!

**Comment by ferdicus** [comment]
@ewc003 , this is partially fixed in #1036.
Unfortunately only for Android as I can't understand the iOS portion of the code 😞 

Can't you maybe give it a spin and verify the fix? 

Thanks 🙇

**Comment by ferdicus** [comment]
@janweigel, also works for iOS now 👍

**Comment by janweigel** [comment]
@ferdicus, thanks a lot!
Works fine now.
