### ISSUE TITLE
Move from Travis to GH Actions

### ISSUE THREAD

**Issue by ferdicus** [react-native-mapbox-gl/maps#1018]
GH Actions are free for open source projects and together with moving away from `depfu` to `dependabot` we would have a a one stop shop for our repo concerns.

**Comment by mfazekas** [comment]
Not sure about macos container limits. We need that to ci ios version, and not sure how GH actions compares to travis there.

**Comment by ferdicus** [comment]
I haven't done the comparison, but you might be on to something.... 
[Billing link for GH Actions](https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions#about-billing-for-github-actions) states, that free accounts have `2000` minutes at their disposal with, however different containers have different "minute multipliers", and of course OSX is high...


Operating system | Minute multiplier
-- | --
Linux | 1
macOS | 10
Windows | 2

**Comment by ferdicus** [comment]
what we could do though is separate Android (GH Actions) and iOS (Travis CI) builds. 
Then we could run them in parallel :)

**Comment by ferdicus** [comment]
these are now tracked in the wiki
