### ISSUE TITLE
[Android] SymbolLayer not working in release mode / black in debug mode

### ISSUE THREAD

**Issue by alexisrougnant** [react-native-mapbox-gl/maps#102]
**Describe the bug**
SymbolLayer is not working for Android in release mode, nothing is displayed at all.

In debug mode, the image is displayed, but all black.

![image](https://user-images.githubusercontent.com/15233191/59096747-dc9e6080-891b-11e9-9cc1-e196baa532a0.png)

**To Reproduce**
Compile this repo's example project in the corresponding mode and use whatever scene that comes with a SymbolLayer ("Custom Icon" for instance)

**Expected behavior**
We expect SymbolLayer to work the same as for iOS. 
![image](https://user-images.githubusercontent.com/15233191/59097466-ea54e580-891d-11e9-83cb-72b76a0293ad.png)

**Versions (please complete the following information):**
 - Platform: Android
 - Device: any
 - OS: any
 - SDK Version 7.3.2, 8.0.0 
 - React Native Version 0.59

**Comment by alexisrougnant** [comment]
In release mode the `addImage` method of `RCTMGLStyle` returns without downloading the asset. The reason is that `RCTMGLStyleValue`'s `shouldAddImage` always return false.

We have:

```
public boolean shouldAddImage() {
    return isAddImage;
}
```
```
isAddImage = imageURI != null && imageURI.contains("://");
```

But the image uri would fulfil the condition only in debug mode as it is of the following form:
 - debug: "http://10.0.2.2:8081/assets/src/img/image.png?platform=android&hash=6b83f13973da21d525cf33f4c1b17a45"
- release: "src_img_image"

Applying this change fixes the problem, but it might introduce other flaws
```
- isAddImage = imageURI != null && imageURI.contains("://");
+ isAddImage = imageURI != null;
```

**Comment by mfazekas** [comment]
@alexisrougnant Thanks, yes not sure why is the `imageURI.contains("://")` condition there. ImageURI can be a path, uri, bundled image name and maybe base64 images, but in any case we want to decode it.

Regarding the icon, it works fine for me in android simulator. Not sure what's going on in that case. The image is clearly loaded just the colors are screwed up.

**Comment by kristfal** [comment]
FYI, emulator GL rendering can be quite flaky depending on underlying hardware and emulator in use. I suggest you check that against a real device.
