### ISSUE TITLE
App crash with Error: Error While updating property 'androidRenderMode' of view managed by: RCTMGLNativeUserLocation null

### ISSUE THREAD

**Issue by SalihZinaty** [react-native-mapbox-gl/maps#1022]
**Describe the bug**

crashes the app with Error: Error While updating property 'androidRenderMode' of view managed by: RCTMGLNativeUserLocation null
Attemt to invoke virtual method 'com.mapbox.rctmgl.components.location.LocationComponentManager com.mapbox.rctmgl.components.mapview.RCTMGLMapView.getLocationComponentManager()' on null object reference.

**To Reproduce**
just added renderMode={'native'}   and  androidRenderMode={'compass'} to the UserLocation Component
Example:
```
 <MapboxGL.UserLocation renderMode={'native'} 
                                           androidRenderMode={'compass'}
                                           showsUserHeadingIndicator={true} 
                                           visible={true} 
                                           animated={true} />
```

**Expected behavior**
expect to show the native android location with moving heading

**Screenshots**

**Versions (please complete the following information):**
 - Platform: [Android]
 - Device: [Samsung Galaxy S10+]
 - Emulator/ Simulator: [no]
 - OS: [android]
 - react-native-mapbox-gl Version [^8.1.0-rc.4]
 - React Native Version [0.61.5]

**Additional context**

**Comment by ferdicus** [comment]
hey @SalihZinaty, this PR (https://github.com/react-native-mapbox-gl/maps/pull/1026) attempts to fix the crash. 
Can you try it out please? 

Thanks
