### ISSUE TITLE
Any plans for support of newly released Mapbox Search SDK?

### ISSUE THREAD

**Issue by thomasgauvin** [react-native-mapbox-gl/maps#1024]
**Describe the bug**
Feature request.

**To Reproduce**
https://docs.mapbox.com/android/search/overview/ and https://blog.mapbox.com/history-and-favorites-mapbox-search-sdk-for-ios-android-now-in-public-preview-fe1b4e5a0f0

**Additional context**
If this is not the place to ask this question, sorry about that. Do you know where I should be asking this question?

**Comment by ferdicus** [comment]
You can ask general questions in our gitter chat.

This however is outside of the scope of this repo. 
Feel free to open a PR if you feel strongly about it, or feel free to open a separate repo/ dependency and we can check if they could be integrating nicely. 

Cheers
