### ISSUE TITLE
linking in dylib built for iOS, file 'projectroot/node_modules/@react-native-mapbox-gl/maps/ios/Mapbox.framework/Mapbox' for architecture arm64 in XCode 12

### ISSUE THREAD

**Issue by ansarikhurshid786** [react-native-mapbox-gl/maps#1031]
**Describe the bug**
I have update xcode 11.x to xcode 12. Now I am getting error following error while running application in simulator:
"ld: building for iOS Simulator, but linking in dylib built for iOS, file 'rootproject/node_modules/@react-native-mapbox-gl/maps/ios/Mapbox.framework/Mapbox' for architecture arm64"

**To Reproduce**
1) Open project with xcode 12
2) Build project

Example:

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Platform: iOS
 - Device: iPhone SE
 - Emulator/ Simulator: yes
 - OS: iOS 14
 - react-native-mapbox-gl Version: 7.0.8
 - React Native Version : 0.59.10

```
% react-native info
info 
  React Native Environment Info:
    System:
      OS: macOS 10.15.6
      CPU: (16) x64 Intel(R) Xeon(R) CPU E5-1680 v2 @ 3.00GHz
      Memory: 1.93 GB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.14.8 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 23.0.1, 23.0.3, 25.0.1, 25.0.2, 26.0.1, 27.0.1, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 30.0.1, 30.0.2
        System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 4.0 AI-193.6911.18.40.6626763
      Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1

```

**Comment by allthetime** [comment]
I also have this issue after upgrading to Catalina + XCode 12 and am disheartened to not find much information on the problem. 

One "solution" might be to revert to XCode 11 (not sure this is possible in Catalina)

I attempted reverting to the legacy build system for xcode and got the same issue.

**Comment by ghitier** [comment]
Cleaning the build folder did the trick for me (`Product > Clean Build Folder`).

**Comment by allthetime** [comment]
Also to note... Only get this error when building for simulator and "release" build configuration. So it's not a show stopper but just annoying to not be able to test release on simulator. Will try cleaning build tomorrow.

**Comment by ansarikhurshid786** [comment]
Yes after clear build work through xcode. it is still not working by following command:
`react-native run-ios`

**Comment by damathryx** [comment]
I'm also having this problem with xcode 12

**Comment by rvdende** [comment]
Can confirm, make sure you are doing a debug build for the simulator and then it works.

**Comment by Gnative** [comment]
Worth ready this thread if you are hitting this problem with building release versions on the Simulator from xcode 12. 

https://developer.apple.com/forums/thread/657913

**Comment by rvdende** [comment]
I had to update to 12.2 beta 4 after the iphone update...

**Comment by timkuilman** [comment]
Same issue with XCode version 12.2 (12B45b) on MacBook Pro (13-inch, M1, 2020)

Debug build on a fresh Xcode install.

**Comment by ataravati** [comment]
Why is this issue closed?

**Comment by ataravati** [comment]
This worked for me:

https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios/64139830

**Comment by natew** [comment]
@ataravati what worked? Are you on m1/arm?

It was working for me a few days ago after some attempts, but for some reason regressed. I get this error again, tried a few different versions of everything, cleaning, legacy build, lots of config variants. No dice.

Luckily I have an old build on my phone that I can use for now, but any tips appreciated.

**Comment by ataravati** [comment]
@natew This:

> navigate to Build Settings of your project and add `Any iOS Simulator SDK` with value `arm64` inside `Excluded Architecture`.

**Comment by natew** [comment]
@ataravati are you on an M1 mac or on an older mac? I'm having this problem on an M1 mac, I don't think I can exclude arm64.

It does build to my physical device though.

Could we get issue re-opened @mfazekas?

**Comment by bosung90** [comment]
Getting a same problem on a Apple Chip Mac Mini

**Comment by babeone** [comment]
Yeah me too, i'm getting this error on M1 mac and Xcode 12, someone resolved?

**Comment by babeone** [comment]
Hi all, check this https://github.com/react-native-mapbox-gl/maps/issues/1139 for a workaround

**Comment by rvdende** [comment]
I get this error when building for the simulator as release instead of debug.

Solution is to go to Product > Scheme > Edit Scheme

Set Build Configuration to **Debug**
Tick **Debug Executable**

**Comment by babeone** [comment]
@rvdende is this the problem? https://github.com/react-native-mapbox-gl/maps/issues/1097
Downgrade pods to 1.9.3

**Comment by ansarikhurshid786** [comment]
@babeone  yeh #1097 issue. i am facing same issue for archive

**Comment by noway** [comment]
This issue has nothing to do with archiving. This issue is scoped to the linking issue

**Comment by natew** [comment]
I have everything working except for some reason errors on doing react-native Release mode, but that seems to fix with:

```
arch -x86_64 react-native run-ios
```

**Comment by noway** [comment]
@natew that runs the build in Rosetta2 and would not be as performant as Apple Silicon.

**Comment by natew** [comment]
@noway of course. It's a temporary solution I found for anyone else searching,

**Comment by noway** [comment]
Fair enough. 

For anyone else: another temporary solution is to build onto a real device, and not to Simulator. (the error only appears to be when you build for simulator)

**Comment by noway** [comment]
This issue is not stale. It's still happening @stale please remove the label.

As a workaround, we have to completely remove Mapbox in Simulator builds which is a huge pain.

**Comment by ferdicus** [comment]
@noway, with #1311 we started to support MapLibre as a native SDK solution.  
It is actively supported compared to Mapbox's "old" SDKs that are packed into this repo per default.  
[This ticket](https://github.com/maplibre/maplibre-gl-native/issues/4) in their repo mentions this issue specifically.  
Instruction on how to replace the underlying native SDK is described in out installation guides

**Comment by ferdicus** [comment]
I would urge everyone subscribed to this ticket to actually test out what I mentioned in my [earlier comment ](https://github.com/react-native-mapbox-gl/maps/issues/1031#issuecomment-859401469) and report back. 

I can not test this out as I don't have an M1 machine.  
If anyone can point me to a reproduction that's possible without an M1, I'd be glad to give it a go.
