### ISSUE TITLE
Feature Request: ImageSource notify when image is loaded

### ISSUE THREAD

**Issue by chathuri4** [react-native-mapbox-gl/maps#1038]
**Feature Request**
Is it possible to add a onLoadEnd prop to the ImageSource component, so that we know when the image is rendered?  

**Additional context**
I am using Mapbox to display images on the map, and change the image based on a timeline (~every second). The problem I am facing is that when I feed in the url to the ImageSource, it takes a bit of time to load, and when the time moves to the next unit, the image showing is still the old one, until the new one is loaded. Therefore, it would be great is there is a function that triggers when the image is finished loading, so only then will I move to the next unit to load a new image in the app.

**Comment by mfazekas** [comment]
Neither android https://docs.mapbox.com/android/maps/api/9.5.0/index.html nor ios has such feature.

https://docs.mapbox.com/archive/ios/maps/api/6.2.1/Classes/MGLImageSource.html
https://docs.mapbox.com/android/maps/api/9.5.0/index.html

You might be able ot download the files to local storage and use file url as source, but not sure if file url is supported here.

**Comment by chathuri4** [comment]
Alright thanks! I am currently downloading it to local storage and use file url as source. Its working fine. Thanks!
