### ISSUE TITLE
"Native part of Mapbox React Native libraries were not registered properly"

### ISSUE THREAD

**Issue by beingcompiled** [react-native-mapbox-gl/maps#1039]
npx react-native start

```
ERROR Native part of Mapbox React Native libraries were not registered properly, double check our native installation guides.
ERROR TypeError: null is not an object (evaluating 'MapboxGL.StyleURL')
ERROR Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
ERROR Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```

"@react-native-mapbox-gl/maps": "^8.1.0-rc.4",
"react": "16.13.1",
"react-native": "0.63.2"

Simulator: iPhone 11 - 14.0

https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md

"React-Native > 0.60.0 If you are using autolinking feature introduced in React-Native 0.60.0, you just need npm install @react-native-mapbox-gl/maps, followed by pod install from the ios directory."

pod install
```
Auto-linking React Native module for target `ReactNativeNoExpo`: react-native-mapbox-gl
Analyzing dependencies
...ReactNativeNoExpo/node_modules/@react-native-mapbox-gl/maps/react-native-mapbox-gl.podspec:6: warning: already initialized constant Pod::REACT_NATIVE_MAPBOX_MAPBOX_IOS_VERSION
...ReactNativeNoExpo/node_modules/@react-native-mapbox-gl/maps/react-native-mapbox-gl.podspec:6: warning: previous definition of REACT_NATIVE_MAPBOX_MAPBOX_IOS_VERSION was here
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 48 dependencies from the Podfile and 42 total pods installed.
```

**Comment by ferdicus** [comment]
did you try with the `example` app in the repo?

**Comment by beingcompiled** [comment]
@ferdicus `example` works, but not independently as a project outside `maps`, due to dependencies? eg. react-native-mapbox-gl.podspec

**Comment by mfazekas** [comment]
@beingcompiled have you also built the workspace?!

We'd need really detailed steps so we can reproduce.

Something like this:
```
react-native init sample --version react-native@0.63.2
cd sample
npm install react-native-mapbox-gl/maps#master --save
npx pod-install
# open io/sample.xcworkspace
# build and run
```

I'm closing this, happy to reopen with steps to reproduce

**Comment by alex83130** [comment]
I followed the get starting documentation and I have the same issue on window for android, what would be the solution ?
