### ISSUE TITLE
ios/Pods/@react-native-mapbox-gl-mapbox-static/dynamic/MapboxMobileEvents.framework/MapboxMobileEvents' for architecture arm64

### ISSUE THREAD

**Issue by asilbek1305** [react-native-mapbox-gl/maps#1046]
Debug build is working fine but can't make release/archive build on Xcode, android is ok.
Please help

XCode 12
"react": "16.13.1",
"react-native": "0.63.2",
"@react-native-mapbox-gl/maps": "^8.0.0-rc6",

**Comment by mfazekas** [comment]
Hi, thanks for the report! To be able to look into setup related issues we need full steps to reproduce the issue. 
Ideally n a brand new project, in the form of
```
react-native init sample --version react-native@0.60.5
cd sample
npm install react-native-mapbox-gl/maps#master --save
npx pod-install
...
react-native run-ios
```

closing the issue now, will reopen when you provide the steps to reproduce.

**Comment by asilbek1305** [comment]
Hi i made a brand new project but still getting this error while release/archive build
it happened when i upgraded react native from 0.61.3 to 0.63.2
Help please!

"dependencies": {
    "@react-native-mapbox-gl/maps": "github:react-native-mapbox-gl/maps#master",
    "react": "16.13.1",
    "react-native": "0.63.2"
  }

react-native info

System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 214.42 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK:
      API Levels: 18, 22, 25, 26, 28, 29
      Build Tools: 28.0.3, 29.0.2, 30.0.0
      System Images: android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0.1/12A7300 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

ios/Pods/@react-native-mapbox-gl-mapbox-static/dynamic/MapboxMobileEvents.framework/MapboxMobileEvents' for architecture arm64
