### ISSUE TITLE
Render PointAnnotation is stuck on iOS 14

### ISSUE THREAD

**Issue by peterleng** [react-native-mapbox-gl/maps#1047]
Hi, I find when I add the PointAnnotation on the map and run on iOS 14 is very stuck,and there are also more sources and layers, but the same render on the map, if I remove the PointAnnotation then map is smoothly, or I run the app on iOS 13.X, smooth too. Only on the iOS 14.

**"react-native": "0.62.2",**
**"@react-native-mapbox-gl/maps": "^8.1.0-rc.2"**

Any one has the same issue?
thanks

**Comment by hikaru-w** [comment]
I'm struggling with the same thing.
Likewise, it only happens on iOS14; it's very smooth on 13.7; it was the same issue on ReactNative0.61.4.

My current environment is as follows.
    "react-native": "0.63.3"
    "@react-native-mapbox-gl/maps": "^8.1.0-rc.2"

![RPReplay_Final1601814703](https://user-images.githubusercontent.com/16463160/95017086-07283700-0692-11eb-89b5-a353de317e58.gif)

**Comment by mfazekas** [comment]
Can someone pls test with latest MGLIOS ?! See https://github.com/react-native-mapbox-gl/maps/pull/1044 for how to try with MapboxGL IOS 6.2.1. Please note it requires lates RNMBGL (8.1.0-rc5)

**Comment by hikaru-w** [comment]
@mfazekas Thanks for the info!
It worked perfectly for me! Super smooth.
I had a hard time creating a .netrc. 
computer's home directory (not the project's home directory) and that I have pasted my secret token (a new token with the Downloads:Read scope) into the file.

**Comment by ferdicus** [comment]
closing as resolved
