### ISSUE TITLE
`features` method VectorSource is slow and returns duplicate points. 

### ISSUE THREAD

**Issue by stevepepple** [react-native-mapbox-gl/maps#1049]
**Describe the bug**
We are finding that getting points for a VectorSource layer with the `features` method as described here is much slower than the web library. The method was crashing until we filtered the data to be below a few thousand points and adjusted the zoom boundaries. Also the vectorSourceVariable.features() is returning features with duplicate items. It's a little tricky to isolate the issue since the network, processing, and memory on mobile are different, but the same operation that takes a few milliseconds in Mapbox GL take 5-10 seconds on RN.

**To Reproduce**
Steps to reproduce the behavior. 

1. Use VectorSource layer
2. Use feature callback for to parse data for layer. 

Working on a stand along example, but this example gives me a 404. Here's a gist . VectorTile layer points to a tile server on PostGis with Martin. 

Example:
```jsx     
const _mapLoaded = () => {
    console.log('Map Loaded');
    if (placesVector.current) {
          const sourceFeatures = await placesVector.current.features(['public.places_vt' ]);
    }
    mapLoaded();
};

...
 
<MapboxGL.VectorSource
        ref={placesVector}
        id='public.places_vt'
        tileUrlTemplates={['https://api.vibemap.com/tiles/public.places_vt/{z}/{x}/{y}.pbf']}
        // url='https://api.vibemap.com/tiles/public.places_vt.json'
      >
        <MapboxGL.CircleLayer
          id='places_circle'
          sourceID='public.places_vt'
          sourceLayerID='public.places_vt'
          belowLayerID='transit_routes'
          style={{
            circleRadius: [
              'case',
              ['>=', ['get', 'aggregate_rating'], 3],
              2,
              ['>=', ['get', 'aggregate_rating'], 4],
              4,
              ['>=', ['get', 'aggregate_rating'], 5],
              6,
              2,
            ],
            circleColor: '#9100ff',
            circleStrokeColor: '#FFFFFF',
            circleStrokeWidth: 0.4,
            circleStrokeOpacity: 0.4,
            circleOpacity: 0.2,
            circleTranslate: [-2, -2],
          }}
        />
</MapboxGL.VectorSource>

```

**Expected behavior**

- Method doesn't hang or return an object with duplicates. 

**Screenshots**

**Versions (please complete the following information):**
 - Platform: Android and IOS
- Device: iPhone 7, iPhone 11 Pro Simulator, Pixel 3a Emulator
- Emulator/ Simulator: Yes
- OS: iOS13.6 and Android 10
- react-native-mapbox-gl Version: 8.0.0
- React Native Version: 0.61.2

**Additional context**
We think that is that is not the VectorSource that was making the app to crash, I think its the ShapeSource, I think the ShapeSource cannot handle a lot of features or something happens while rendering the points (edited)

**Comment by ferdicus** [comment]
hey @stevepepple, thanks for the submission.
I took the liberty to clean it up a bit, please make sure to _fully_ fill out the template.
For example, you haven't defined what version of the lib it is or what kind of platform. 
Tickets without that info will generally be closed.

Thanks in advance 🙇

**Comment by stevepepple** [comment]
@ferdicus, thanks for cleaning it up. I've been coordinating with our development team to provide more details and context. Added the relevant versions and happy to provide any more info.

**Comment by stevepepple** [comment]
@ferdicus and team, any updates on this issue. Any pointers on how to better implement the library are appreciated. We're also seeing some memory spikes associated with the `<vectorSource>.currrent.features.` method. 

![image](https://user-images.githubusercontent.com/466699/97311734-e7fc6f80-1821-11eb-9c77-5ccecdec9d4d.png)

**Comment by ferdicus** [comment]
@stevepepple, didn't really have time to look into this, sorry. 

I could check it out earliest on friday, however I've got to admit, that I haven't really used it like you do before. 

Can you try to create a working example from the `BugTemplate` in the `example` app please. 
Would make testing/ debugging it way easier - thanks

**Comment by stevepepple** [comment]
Thanks @ferdicus. A demo is here:

https://drive.google.com/u/0/uc?id=1xZYug_B2qnJHD2CgyJikuI2t1_MogkoU&export=download

**Comment by ferdicus** [comment]
reminder to self to check this next week

**Comment by AndresAltomobile** [comment]
Hey @ferdicus just an update.
We recently updated the project, these are the versions we are using:

- react-native-mapbox-gl Version: 8.1.0-rc.9 with mapbox ios sdk: 6.2.2
- React Native Version: 0.63.3

We noticed that in cities with more points it takes between 7 and 10 seconds to query the features, cities with fewer points take between 3 and 5 seconds to query the features. Also, if the viewport doesn't change, it feels a little faster than when the viewport has changed (zoom, move the map, etc.) and we query the features.

We think that removing the duplicates returned by `<vectorSource>.currrent.features` will help improve the time, because it would return less features (therefore less work would be done internally), well, this is what we think, since cities with fewer points to query take less time.

Hope this helps.

**Comment by ferdicus** [comment]
hey @stevepepple, I've just downloaded your demo app - haven't tested anything yet, just saw that you included your mapbox access token in it.
Might want to take the demo down again, before someone is using your token 👍🏿

**Comment by stevepepple** [comment]
Oh thanks @ferdicus. Will fix that ASAP and provide an updated demo without the key.

**Comment by ferdicus** [comment]
hey @stevepepple, just a quick question about the nature of the duplicates.

I've logged out the result of the `.features` call from variable `sourceFeatures` and I got, for example, this result:
```js
{
  features: [
    {
      type: 'Feature',
      geometry: {
        coordinates: [-122.41283029317856, 37.77093947944789],
        type: 'Point',
      },
      properties: {
        name: 'Bootie San Francisco',
        vibes: '["smart", "queer", "dance"]',
        tips:
          '["Best club night in SF. Hands down.", "People prone to seizures and allergic to the sweat of a million people crammed on the dance floor should probably avoid this place. Otherwise it\'s lots of fun!", "Don\'t miss the Saturday night pop mashups.", "Had so much fun at bootie that when it was over I ended up at the endup....... After years of saying that would never happen. Bootie was better."]',
        categories: '[]',
        website: 'http://bootiemashup.com/sf/',
        twitter: 'bootiemashup',
        price: 2,
        id: 'fafd5fdf-45a8-46c4-b754-09f5ca55b5ab',
        aggregate_rating: 3.8,
        facebook: 'BootieSF',
        address: '375 11th St, San Francisco, CA 94103',
        thumbnail_url: 'thumbnail_url',
        subcategories: '["Nightclub"]',
      },
    },
    {
      type: 'Feature',
      geometry: {
        coordinates: [-122.41283096373081, 37.770939081911436],
        type: 'Point',
      },
      properties: {
        name: 'Bootie San Francisco',
        vibes: '["smart", "queer", "dance"]',
        tips:
          '["Best club night in SF. Hands down.", "People prone to seizures and allergic to the sweat of a million people crammed on the dance floor should probably avoid this place. Otherwise it\'s lots of fun!", "Don\'t miss the Saturday night pop mashups.", "Had so much fun at bootie that when it was over I ended up at the endup....... After years of saying that would never happen. Bootie was better."]',
        categories: '[]',
        website: 'http://bootiemashup.com/sf/',
        twitter: 'bootiemashup',
        price: 2,
        id: 'fafd5fdf-45a8-46c4-b754-09f5ca55b5ab',
        aggregate_rating: 3.8,
        facebook: 'BootieSF',
        address: '375 11th St, San Francisco, CA 94103',
        thumbnail_url: 'thumbnail_url',
        subcategories: '["Nightclub"]',
      },
    },
  ],
  type: 'FeatureCollection',
};
```

It looks like a duplicate (`id` is the same), however the coordinates do not match up 🤔 


From the code we're using, I'm not sure what the issue could be, as we basically just passing the method call from JS => Android/ iOS... 

Here the Android part for your viewing pleasure:
https://github.com/react-native-mapbox-gl/maps/blob/7f603397aefaf4adcb292cb41e060011cca3322c/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLVectorSource.java#L47-L56

Then I thought it might be an upstream issue, as there were some fixes concerning `querySourceFeatures`, as you can check in `mapbox-gl-native-android` [changelog](https://github.com/mapbox/mapbox-gl-native-android/blob/main/CHANGELOG.md)


Then I was thinking (lots of thinking over here.... 🤔 ), maybe it's the default `mapbox-android-sdk` version we're shipping in `8.0.0`.
I checked in our [`build.gradle`](https://github.com/react-native-mapbox-gl/maps/blob/8.0.0/android/rctmgl/build.gradle#L35) file for `8.0.0` however it seems it's a version which should have all the fixes for `querySourceFeatures` I mentioned above.
https://github.com/react-native-mapbox-gl/maps/blob/7f603397aefaf4adcb292cb41e060011cca3322c/android/rctmgl/build.gradle#L35


And that's that for now - I can have a look at this at a later time again, let's have this as a kick-off.
Looking forward to some insight from your usage 🤝
