### ISSUE TITLE
moveTo/flyTo fail for coordinates with latitude/longitude of 0

### ISSUE THREAD

**Issue by davegurnell** [react-native-mapbox-gl/maps#1058]
**Describe the bug**
The `moveTo()` and `flyTo()` methods fail if called with a longitude or latitude of zero.

**To Reproduce**
Clone [this repo](https://github.com/davegurnell/react-native-mapbox-gl) and check out the **Camera > Fly To** example in the `examples` folder. I've [modified it](https://github.com/davegurnell/react-native-mapbox-gl-maps/commit/5be1629e2deefa5c6c25c311c68e5353cdc2a1e5) to add a few failing coordinates.

**Expected behavior**
The methods should move/fly to the specified coordinates.

**Screenshots**
N/A

**Versions (please complete the following information):**
iOS (not Android)

**Additional context**
I think the problem is [here](https://github.com/davegurnell/react-native-mapbox-gl-maps/blob/master/ios/RCTMGL/CameraUpdateItem.m#L125). This test doesn't make sense to me. 

I put a minimal fix in a branch called [move-to-fix](https://github.com/davegurnell/react-native-mapbox-gl-maps/commit/5c382639f8ec622a6e7e3acd7d4032b6dd5f1960). The moveTo/flyTo demo works for me with this in place.

I've raised a [PR](https://github.com/react-native-mapbox-gl/maps/pull/1059) containing the demo and fix. My native development is pretty rudimentary so I'm happy to adjust/QA as required.

**Comment by ferdicus** [comment]
closed via #1059
