### ISSUE TITLE
[iOS] SIGSEGV: Crash due to signal: SIGSEGV(SEGV_MAPERR)

### ISSUE THREAD

**Issue by marudy** [react-native-mapbox-gl/maps#1064]
**Describe the bug**
iOS application crashes with SIGSEGV error as mentioned above. The complete error is:

Version 7.0.0:
```
SIGSEGV: Crash due to signal: SIGSEGV(SEGV_MAPERR) at bbe7ef940190
_42-[RCTMGLStyle symbolLayer:withReactStyle:]_block_invoke_2 (RCTMGLStyle.m:208)
```

Version 8.1.0-rc4:
```
SIGSEGV: Crash due to signal: SIGSEGV(SEGV_MAPERR) at 1cf19383e860
_42-[RCTMGLStyle symbolLayer:withReactStyle:]_block_invoke_2 (RCTMGLStyle.m:210)
```

Memory address changes from time to time but line of code has been consistent. It's this one:

`[self->_style setImage:image forName:imageURI];` which is part of block

```
} else if ([prop isEqualToString:@"iconImage"]) {
      if (![styleValue shouldAddImage]) {
        [self setIconImage:layer withReactStyleValue:styleValue];
      } else {
        NSString *imageURI = [styleValue getImageURI];

        [RCTMGLUtils fetchImage:_bridge url:imageURI scale:[styleValue getImageScale] callback:^(NSError *error, UIImage *image) {
          if (image != nil) {
            dispatch_async(dispatch_get_main_queue(), ^{
              [self->_style setImage:image forName:imageURI];
              [self setIconImage:layer withReactStyleValue:styleValue];
            });
          }
        }];
      }
    }
```

of `RCTMGLStyle.m` file

**To Reproduce**
Don't have a concrete example but I have seen the app crashing when running it locally. I can definitely grab some xcode logs if the information above doesn't hint you guys on what could be that is crashing the code in order to protect it.

**Expected behavior**
Application should not crash. The component should handle the error.

**Versions (please complete the following information):**
 - Platform: iOS
 - Device: iPhone 6s, 8, 11
 - Emulator/ Simulator: not sure
 - OS: 12.4.6 , 12.4.7, 12.4.8, 13.5.6, 13.1.x, 13.5.x, 13.6.x, 13.7.x, 14.0.1
 - react-native-mapbox-gl Version: 7.0.0, 8.1.0-rc4
 - React Native Version 0.61.4

**Additional context**

Instabug iOS log:

0 | Mapbox | _hidden#9412_ + 20
-- | -- | --
1 | Mapbox | _hidden#3252_ + 203
2 | Application | _42-[RCTMGLStyle symbolLayer:withReactStyle:]_block_invoke_2 (RCTMGLStyle.m:208)
3 | libdispatch.dylib | _dispatch_call_block_and_release + 23
4 | libdispatch.dylib | _dispatch_client_callout + 15
5 | libdispatch.dylib | _dispatch_main_queue_callback_4CF$VARIANT$armv81 + 859
6 | CoreFoundation | _CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 11
7 | CoreFoundation | _CFRunLoopRun + 1723
8 | CoreFoundation | CFRunLoopRunSpecific + 423
9 | GraphicsServices | GSEventRunModal + 159
10 | UIKitCore | UIApplicationMain + 1931
11 | Application | main (main.m:14)
12 | libdyld.dylib | $start + 3

**Comment by ferdicus** [comment]
Hey @marudy, sorry for the late reply.
Are you still experiencing this with the newest release. 
Also on which iOS SDK version are you?

**Comment by marudy** [comment]
@ferdicus thanks for the reply. 
- yeah it still occurs on latest version `8.1.0.rc9`. Have actually upgraded to this one for a couple of weeks now already but didn't update the issue.
- My CI builds with `Xcode 11.3.0`. On users devices' i see it all the way from iOS 12 to 14 as mentioned.

Cheers and thanks for taking the time to investigate

**Comment by ferdicus** [comment]
sorry, I meant the underlying iOS SDK version. 
It's now possible to update that independently of our wrapper libs version. 
More info here: https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md#mapbox-maps-sdk
Our default packin version is `5.8.0` you could try `6.3.0` and see if you're experiencing the same issue there.

Thanks

**Comment by marudy** [comment]
@ferdicus i can confirm i am using version `5.8.0` for the underlying iOS SDK version. Will try your suggestion and report back.

**Comment by marudy** [comment]
@ferdicus I get 401 Unauthorised while trying to install 6.3.0

![Screenshot 2020-12-06 at 23 23 53](https://user-images.githubusercontent.com/16783589/101292780-44d44800-381a-11eb-83da-1ff8e26d0f41.png)

I simply changed the version in the podspec file and run `pod update`:
```
-default_ios_mapbox_version = '~> 5.8.0'
+default_ios_mapbox_version = '~> 6.3.0'

**Comment by ferdicus** [comment]
Unfortunately it involves more than just changing the version in the `podspec`.
Please refer to the changed iOS installation guides - mapbox has changed the installation process a bit since version 6.X.X.

**Comment by marudy** [comment]
Can you please link me ?

**Comment by ferdicus** [comment]
> Can you please link me ?

https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md
