### ISSUE TITLE
ShapeSource unable to get data list in cluster mode

### ISSUE THREAD

**Issue by Polyrion** [react-native-mapbox-gl/maps#1065]
**Describe the bug**
I'm using ShapeSource with cluster at true so i have everything displayed well, when i press to a single item i got the data of the item.

```data [{"geometry": {"coordinates": [Array], "type": "Point"}, "properties": {"address1": "11 rue du guichet", "city": "Berlin", "country": "Germany", "country_code": null, "distance": 493.593348140211,}, "type": "Feature"}]```

But when i press on a clustered item i got this 

```data [{"geometry": {"coordinates": [Array], "type": "Point"}, "id": 15, "properties": {"cluster": true, "cluster_id": 15, "point_count": 4, "point_count_abbreviated": "4"}, "type": "Feature"}]```

**To Reproduce**
Steps to reproduce the behavior. 

Please include a single standalone React Native component. Use [one of our example](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/BugReportTemplate.js) screens as a starting point.
Please simplify the example as much as possible.

Example:
```js
import React from 'react';
import {
  MapView,
  ShapeSource,
  SymbolLayer,
  LineLayer,
  CircleLayer
  Camera,
  OnPressEvent,
} from '@react-native-mapbox-gl/maps';

const shape = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "address1": "11 rue du guichet", "city": "Berlin", "country": "Germany", "country_code": null, "distance": 493.593348140211,
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          13.3978271484375,
          52.532931647583325
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
         "address1": "Chausseestraße 11", "city": "Berlin", "country": "Germany", "country_code": null, "distance": 750.123432325568, 
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          13.42254638671875,
          52.496159531097106
        ]
      }
    }
  ]
};

const Map: React.FC<Props> = (props) => {
  const handleMapMarkerPress = (data: OnPressEvent) => {
    console.log('data', data.features);
  };

    return (
      <MapView style={{flex: 1}}>
        <Camera zoomLevel={14} />
          <ShapeSource
            id="stations"
            cluster={true}
            clusterRadius={50}
            clusterMaxZoomLevel={14}
            onPress={handleMapMarkerPress}
            shape={shape}>
            <SymbolLayer id="uid" style={layerStyles.layout} />
            <SymbolLayer
              id="single"
              filter={['!', ['has', 'point_count']]}
              style={layerStyles.singleLayout}
            />
            <CircleLayer
              id="clusteredPoints"
              belowLayerID="pointCount"
              filter={['has', 'point_count']}
              style={layerStyles.clusteredPoints}
            />
          </ShapeSource>
      </MapView>
    );
}
```

**Screenshots**

**Versions (please complete the following information):**
 - Platform: [Android & iOS]
 - Device: [iPhone 11 Pro]
 - Emulator/ Simulator: [yes]
 - OS: [iOS13.6]
 - react-native-mapbox-gl Version [8.1.0-rc.2]
 - React Native Version [0.63.2]

**Additional context**
In my use case i need to get an array of all items in the cluster to display them in a modal.

Thank you in advance for the help.

**Comment by krakz999** [comment]
Have you found any solution to get a list of the features wrapped by a cluster?

**Comment by krakz999** [comment]
Submitted a PR that addresses this issue https://github.com/react-native-mapbox-gl/maps/pull/1291
