### ISSUE TITLE
Missing User Indicator

### ISSUE THREAD

**Issue by supremevance** [react-native-mapbox-gl/maps#1080]
**Describe the bug**
The user indicator does not show up
This bug is occurring on iOS simulator and Device
Android not tested

**To Reproduce**
iOS 14 iPhone X

Example:
```ts
//import liraries
import React, { Component } from 'react';
import { View, Text, StyleSheet, Dimensions } from 'react-native';
import MapView from 'react-native-maps';
import MapboxGL from "@react-native-mapbox-gl/maps";
MapboxGL.setAccessToken("");

// create a component
class MapScreen extends Component {
    componentDidMount() {
        
    }

    render() {
        return (
            <View style={{ flex: 1 }}>
                <MapboxGL.MapView style={{ width: "100%", height: "100%", position: "absolute" }} styleURL={"mapbox://styles/chumner/ckedqggo906cb19qmpky0le4e"} userTrackingMode={MapboxGL.UserTrackingModes.Follow} />

                <MapboxGL.UserLocation visible={true} showsUserHeadingIndicator={true} />

                <MapboxGL.Camera
                    zoomLevel={12}
                    followUserLocation={true} 
                />
            </View>
        );
    }
}

//make this component available to the app
export default MapScreen;
```

**Expected behavior**
I expect the user indicator to show.

**Screenshots**
![image](https://user-images.githubusercontent.com/44252138/96394368-6785a100-1187-11eb-88f5-3e9780f7f1cf.png)
![image](https://user-images.githubusercontent.com/44252138/96394382-710f0900-1187-11eb-93dd-4ae89a7bf2ba.png)

**Versions:**
 - Platform: [iOS]
 - Device: [Phone X]
 - Emulator/ Simulator: [yes]
 - OS: [iOS 14]
 - react-native-mapbox-gl Version [e.g. 7.0.9]
 - React Native Version [e.g. 0.59]

**Comment by jun-nguyen-goldenowl** [comment]
@supremevance Have you tried upgrading the libs to the latest version? (Check the git tags)

**Comment by supremevance** [comment]
> @supremevance Have you tried upgrading the libs to the latest version? (8.1.0-rc.5)

I was actually just not putting my elements as Map children elements, if that makes sense.

**Comment by ferdicus** [comment]
closing this as resolved
