### ISSUE TITLE
8.0.0-rc6 doesn't render a map inside MapboxGL.MapView

### ISSUE THREAD

**Issue by lorenc-tomasz** [react-native-mapbox-gl/maps#1083]
Hi,
I have updated the lib from 8.0.0-rc5 to rc6 and now new MapView is grey. I have checked it and the issue is somewhere inside the CameraUpdateItem.m file on iOS. I guess that moveTo stop working properly.

**Comment by jun-nguyen-goldenowl** [comment]
Have you tried updating the lib to version 8.1.0-rc.5?

**Comment by lorenc-tomasz** [comment]
@jun-nguyen-goldenowl  I have reverted the lib into rc5. And it works again as it should.

**Comment by lorenc-tomasz** [comment]
Thanks. rc7 works as intended :)
