### ISSUE TITLE
Interpolate textOffset

### ISSUE THREAD

**Issue by natew** [react-native-mapbox-gl/maps#1099]
**Describe the bug**

Setting textOffset with interpolate value crashes.

**To Reproduce**

Set any CircleLayer to have:

```
textOffset: [
                'interpolate',
                ['exponential', 1.5],
                ['zoom'],
                9,
                [0, 1.5],
                11,
                [0, 1.25],
                16,
                [0, 1],
              ],
```

**Expected behavior**

Should support.

**Versions (please complete the following information):**
 - Platform: iOS
 - Device: iPhone 11
 - Emulator/ Simulator: yes
 - OS: 14.1
 - react-native-mapbox-gl Version 8.1.0-rc9
 - React Native Version 0.63.2

**Additional context**

Without supporting this labels look quite weird as you zoom with interpolated circle sizes.

**Comment by ferdicus** [comment]
Hey @natew, thanks for the report. 
Would you kindly provide a plug & play repro solution with the BugTemplate within the `example` app? 

Much obliged 🙇🏿

**Comment by VladMatvei** [comment]
Hi @natew 
Please try the following expression:
`[
      'interpolate',
      ['exponential', 1.5],
      ['zoom'],
      9, ['literal', [0, 1.5]],
      11, ['literal', [0, 1.25]],
      16, ['literal', [0, 1]],
    ]`
