### ISSUE TITLE
[Android] Error when trying to render multiple PointAnnotations

### ISSUE THREAD

**Issue by laisrhianne** [react-native-mapbox-gl/maps#1104]
**Describe the bug**
I wanted to use data to automatically create PointAnnotations on the map. I have an array of markers but when I use the map function to render them, I get this error: Error: Objects are not valid as a React child (found: object with keys {_U, _V, _W, _X}).

**To Reproduce**
I imported a JSON file as "data" and set the initial state of markers with it. I used console.log to verify that the state is being set correctly.

Code:
```
export default class App extends Component {
  state = {
    markers: data.markers,
  };

  async componentDidMount() {
    MapboxGL.setTelemetryEnabled(false);
  }

  async renderMarkers() {
    if (this.state.markers) {
      const markers = this.state.markers.map((marker) => {
        return (
          <MapboxGL.PointAnnotation
            key={marker.id}
            id={marker.name}
            coordinate={marker.loc.coordinates}>
            <MapboxGL.Callout title={marker.name} />
          </MapboxGL.PointAnnotation>
        );
      });
      return markers;
    }
  }

  render() {
    return (
      <View style={styles.page}>
        <View style={styles.container}>
          <MapboxGL.MapView
            style={styles.map}
            logoEnabled={false}
            attributionEnabled={false}>
            <MapboxGL.Camera
              zoomLevel={12}
              centerCoordinate={[-35.7141556, -9.6554965]}
            />
            {this.renderMarkers()}
          </MapboxGL.MapView>
        </View>
      </View>
    );
  }
}
```

**Expected behavior**
I expected the app would render the markers on the map
Like this:
![3e8530d4-9700-4dad-a1b7-69b937500126](https://user-images.githubusercontent.com/11474951/98449935-df0b7800-2116-11eb-8f6a-2cb4e31054a8.jpeg)
(Managed to get this result by rendering each marker individually without using the map function)

**Screenshots**
![40010b26-d2b5-4267-96ee-a76e6a07f1b2](https://user-images.githubusercontent.com/11474951/98449872-6efcf200-2116-11eb-9edd-e7c9e198df97.jpeg)

**Versions:**
 - Platform: Android
 - Device: Huawei Honor View 10
 - Emulator/ Simulator: no
 - OS: Android10
 - react-native-mapbox-gl Version: 8.1.0
 - React Native Version: 0.63.3

**Comment by mfazekas** [comment]
@laisrhianne thanks for the bug report. Can you please include a complate sample?! The one in report is missing the value of `data.markers` for example.

**Comment by laisrhianne** [comment]
@mfazekas Sorry! I forgot to add it.
The JSON file I'm importing is this one:

```
{
	"markers": [
		{
			"loc": {
				"coordinates": [
					-35.748878479003906,
					-9.600669860839844
				]
			},
			"id": 53301,
			"name": "s1"
		},
		{
			"loc": {
				"coordinates": [
					-35.78432846069336,
					-9.561790466308594
				]
			},
			"id": 53313,
			"name": "s2"
		},
		{
			"loc": {
				"coordinates": [
					-35.75598907470703,
					-9.5689697265625
				]
			},
			"id": 53314,
			"name": "s3"
		},
		{
			"loc": {
				"coordinates": [
					-35.66730880737305,
					-9.579110145568848
				]
			},
			"id": 53320,
			"name": "s4"
		},
		{
			"loc": {
				"coordinates": [
					-35.77033996582031,
					-9.600029945373535
				]
			},
			"id": 53331,
			"name": "s5"
		},
		{
			"loc": {
				"coordinates": [
					-35.71643829345703,
					-9.599590301513672
				]
			},
			"id": 53338,
			"name": "s6"
		},
		{
			"loc": {
				"coordinates": [
					-35.56338882446289,
					-9.486940383911133
				]
			},
			"id": 53364,
			"name": "s7"
		},
		{
			"loc": {
				"coordinates": [
					-35.56644058227539,
					-9.486969947814941
				]
			},
			"id": 53366,
			"name": "s8"
		},
		{
			"loc": {
				"coordinates": [
					-35.5683708190918,
					-9.4868803024292
				]
			},
			"id": 53369,
			"name": "s9"
		},
		{
			"loc": {
				"coordinates": [
					-35.56951141357422,
					-9.486860275268555
				]
			},
			"id": 53371,
			"name": "s10"
		},
		{
			"loc": {
				"coordinates": [
					-35.57395935058594,
					-9.486160278320312
				]
			},
			"id": 53384,
			"name": "s11"
		},
		{
			"loc": {
				"coordinates": [
					-35.57695007324219,
					-9.48643970489502
				]
			},
			"id": 53389,
			"name": "s12"
		},
		{
			"loc": {
				"coordinates": [
					-35.576881408691406,
					-9.486209869384766
				]
			},
			"id": 53392,
			"name": "s13"
		},
		{
			"loc": {
				"coordinates": [
					-35.57648849487305,
					-9.486040115356445
				]
			},
			"id": 53394,
			"name": "s14"
    }
  ]
}
```

The complete App.js file is:

```
import React, {Component} from 'react';
import {StyleSheet, View} from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

import * as data from './Teste2.json';

MapboxGL.setAccessToken(
  'TOKEN',
);

MapboxGL.requestAndroidLocationPermissions();

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  container: {
    height: '100%',
    width: '100%',
    backgroundColor: 'tomato',
  },
  map: {
    flex: 2,
  },
});

export default class App extends Component {
  state = {
    markers: data.markers,
  };

  componentDidMount() {
    MapboxGL.setTelemetryEnabled(false);
  }

  async renderMarkers() {
    if (this.state.markers) {
      const markers = this.state.markers.map((marker) => {
        return (
          <MapboxGL.PointAnnotation
            key={marker.id}
            id={marker.name}
            coordinate={marker.loc.coordinates}>
            <MapboxGL.Callout title={marker.name} />
          </MapboxGL.PointAnnotation>
        );
      });
      return markers;
    }
  }

  render() {
    return (
      <View style={styles.page}>
        <View style={styles.container}>
          <MapboxGL.MapView
            style={styles.map}
            logoEnabled={false}
            attributionEnabled={false}>
            <MapboxGL.Camera
              zoomLevel={12}
              centerCoordinate={[-35.7141556, -9.6554965]}
            />
            {this.renderMarkers()}
          </MapboxGL.MapView>
        </View>
      </View>
    );
  }
}

```

**Comment by ferdicus** [comment]
An obscure error message like this: `object with keys {_U, _V, _W, _X}`
Usually points to a `Promise` issue.

`renderMarkers` is declared as an `async` function, however you're calling it without an `await` within `render`.
You need to resolve the Promise first I think.

**Comment by laisrhianne** [comment]
Thank you @ferdicus 
It worked just now but only with small Json files.
I was using a JSON file because I couldn't fetch the info from backend and I forgot to change the async function. I think the problem now is that there are too many markers to be loaded. The original JSON file I wanted to load has over 800K lines. 
Do you know how I can get the camera bounds coordinates so I can try to render only the markers that are in a visible range?

**Comment by ferdicus** [comment]
> Thank you @ferdicus
> It worked just now but only with small Json files.
> I was using a JSON file because I couldn't fetch the info from backend and I forgot to change the async function. I think the problem now is that there are too many markers to be loaded. The original JSON file I wanted to load has over 800K lines.
> Do you know how I can get the camera bounds coordinates so I can try to render only the markers that are in a visible range?

Good to hear 👍🏿 
Please check the docs - they're your friends :)
https://github.com/react-native-mapbox-gl/maps/blob/master/docs/MapView.md#getvisiblebounds

**Comment by ferdicus** [comment]
closing as resolved
