### ISSUE TITLE
Render MVT with VectorTiles

### ISSUE THREAD

**Issue by DavidGonzalezGutierrez** [react-native-mapbox-gl/maps#1109]
**Describe the bug**
Can't find a way to render mvt or pbf vector tiles. Not appearing anything on the map. No errors in logcat or in react native console.

**To Reproduce**
See code below

Example:
```js
import React from 'react';
import { Dimensions, SafeAreaView, StyleSheet } from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

const MapRender = () => {
  return (
    <SafeAreaView style={styles.mapContainer}>
      <MapboxGL.MapView style={styles.mapView}>
        <MapboxGL.VectorSource
          id={'rasterSource'}
          minZoomLevel={8}
          hitbox={{
            width: 50,
            height: 50,
          }}
          maxZoomLevel={10}
          tileUrlTemplates={[`http://miserver.es/tiles/{z}/{x}/{y}.mvt`]}
          onPress={(e) => {
            console.log(e.features);
          }}
        >
          <MapboxGL.FillLayer
            id={'rasterLayer'}
            sourceID={'rasterSource'}
            sourceLayerID={'rasterSource'}
            layerIndex={999}
            style={{ fillColor: 'red' }}
          />
        </MapboxGL.VectorSource>
      </MapboxGL.MapView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  mapContainer: {
    flex: 1,
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
  mapView: {
    flex: 1,
  },
});

export default MapRender;

```

**Expected behavior**
Appear something in the map.

**Versions (please complete the following information):**
 - Platform: Android
 - Device: Ulefone Power 3S
 - Emulator/ Simulator:  no
 - OS: Android 7.1
 - react-native-mapbox-gl ^8.1.0-rc.9
 - React Native Version 0.63.3

**Comment by DavidGonzalezGutierrez** [comment]
It is probably a good idea to update the examples, or add them in each .md of the corresponding component. The use of this type of component is not very clear.

**Comment by ferdicus** [comment]
@DavidGonzalezGutierrez, please explain - thanks

**Comment by guillemfrancisco** [comment]
@DavidGonzalezGutierrez how did you manage to make it work? Was the problem the format? From MVT to TileJSON?

**Comment by DavidGonzalezGutierrez** [comment]
I had two problems. The first was that by generating the mvt with tipecanoe I was not able to make them work.
The second was that it generated the mvt with a layer name, but this name did not put it in the react native element.
Nowadays im using mvt tile format, and it works.

**Comment by punov** [comment]
@DavidGonzalezGutierrez could you please share the final view of your working solution?
I'm struggling with PBF now, having the same issue: constant 
` LOG  Mapbox [info] Request failed due to a permanent error: Canceled  {"level": "warning", "message": "Request failed due to a permanent error: Canceled ", "tag": "Mbgl-HttpRequest"}`
messages. Feels like smth wrong with the format of PBF I generated (but those files worked fine with DeckGL mvt layer already)
