### ISSUE TITLE
iOS: SymbolLayer icons don't load

### ISSUE THREAD

**Issue by developius** [react-native-mapbox-gl/maps#1112]
**Describe the bug**
On iOS, images added through `MapboxGL.Image` fail to load.
Using a URL (e.g. `https://cdn.onlinewebfonts.com/svg/img_525159.png`) works, but loading from disk seems to result in something else entirely.

**To Reproduce**

Example:
```js
const images = {
  marker_red: require("./markers/marker_red.png"),
  marker_orange: require("./markers/marker_orange.png"),
  marker_yellow: require("./markers/marker_yellow.png"),
  marker_limegreen: require("./markers/marker_limegreen.png"),
  marker_green: require("./markers/marker_green.png"),
}

<MapboxGL.MapView>
  <MapboxGL.Images images={images} />
  <MapboxGL.ShapeSource
    id="reports-source"
    shape={{
      type: "FeatureCollection",
      features: rootStore.reportFeatures,
    }}
  >
    <MapboxGL.SymbolLayer
      id="report-markers"
      style={{
        iconImage: ["get", "icon"],
        iconSize: 0.025,
        iconAllowOverlap: true,
      }}
    />
  </MapboxGL.ShapeSource>
</MapboxGL.MapView>;

```

**Expected behavior**
I expect to see markers on the map, like I do on Android.

The markers are actually present on the map because I can tap on them and get a callback, but they seem to be transparent (or 'missing').

|Android|iOS|
|-|-|
|![Screenshot_20201121-183445](https://user-images.githubusercontent.com/5836587/99868679-67b30980-2c29-11eb-8850-02bbab7b258f.jpg)|![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-21 at 19 30 08](https://user-images.githubusercontent.com/5836587/99869460-06426900-2c30-11eb-86ea-da66bd4e49bc.png)|

**Versions**
 - Platform: iOS
 - Device: iPhone XR (physical device), iPhone 12 Pro Max (simulator)
 - Emulator/Simulator: both
 - OS: iOS 14.1
 - react-native-mapbox-gl Version: `8.1.0-rc.8`
 - React Native Version: `0.63.3`

**Comment by developius** [comment]
I've a feeling this might be related to: https://github.com/facebook/react-native/issues/29279

**Comment by ferdicus** [comment]
@developius, can you please try one of the mentioned solutions and report back to us - thanks in advance 🙇🏿

**Comment by developius** [comment]
Hey @ferdicus,

I tried the patch from: https://github.com/facebook/react-native/issues/29279#issuecomment-658244428
And also the one here: https://github.com/facebook/react-native/issues/29279#issuecomment-657201709

Neither seem to work. I have a standard `<Image>` loading correctly in my app so not sure if it's related or not.

**Comment by developius** [comment]
This is what I now get 😆
<img src="https://user-images.githubusercontent.com/5836587/99900603-5fd09380-2d15-11eb-8ed2-6a5b35dd9ea3.png" width="250px">

**Comment by ferdicus** [comment]
> This is what I now get 😆
> <img alt="" width="250px" src="https://user-images.githubusercontent.com/5836587/99900603-5fd09380-2d15-11eb-8ed2-6a5b35dd9ea3.png">

Oh lovely... 😆 

I'll have a look - might take a few days though, hope that's ok

**Comment by developius** [comment]
@ferdicus no problem 🤓 let me know if you need any more info. I can ship Android anyway 😁

**Comment by developius** [comment]
@ferdicus not sure if it helps, but I'm getting this exception when getting to the `minZoomLayer` of the `SymbolLayer` with failing icons.

<img src="https://user-images.githubusercontent.com/5836587/100007819-7e2bb180-2e31-11eb-8077-5a437be9cb28.PNG" width="250"/>

**Comment by developius** [comment]
Hey @ferdicus, did you get anywhere with this?

**Comment by ferdicus** [comment]
hey, sorry for getting back so late to you. 

Can you do me a favor and try the `/example` app within our repo.
In there is a scene called: `Symbol/CircleLayer` => `Shape Source From Icon`
Source of that file: https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/ShapeSourceIcon.js

I tried it on simulator/ emulator and it works fine on current `master`:

ANDROID | iOS
-|-
![android_screenshot_emulator-5554_21-01-22_15 57 52](https://user-images.githubusercontent.com/26439946/105507806-f1379400-5ccb-11eb-99a2-dbe1a66940e5.png) | 
![ios_screenshot_iPhone11_21-01-22_15 57 52](https://user-images.githubusercontent.com/26439946/105507834-f7c60b80-5ccb-11eb-8a81-ec84b9a9454e.png)

**Comment by ferdicus** [comment]
> @ferdicus not sure if it helps, but I'm getting this exception when getting to the `minZoomLayer` of the `SymbolLayer` with failing icons.

I think you can dismiss this one for the issue at hand.
Seems to be related to an error loading tiles from your map server

**Comment by developius** [comment]
@ferdicus yeah, that appears to work on iOS 14.2 simulator.
I'll see if I can work out what I'm doing differently in my app.

<img src="https://user-images.githubusercontent.com/5836587/105968109-8501c980-60eb-11eb-8a09-02b7be7fc959.png" width="200"/>

**Comment by developius** [comment]
@ferdicus think I figured it out 🤓
My images were _massive_ (like 4500x3000px). Once I realised and scaled them down, everything started looking good again 😁 

<img src="https://user-images.githubusercontent.com/5836587/106088764-681cd300-618b-11eb-8281-433fec74cd22.png" width="200"/>

This is a screenshot from v2 of [Sandfly Map](https://sandfly.app/) which I'm in the midst of rebuilding with this library.

**Comment by ferdicus** [comment]
Cool, glad I could help - looks like a great product. 
Let us know if you find any other issues and contribution are always welcome :)
