### ISSUE TITLE
Logo not adjusted according to contentInset

### ISSUE THREAD

**Issue by magnusburton** [react-native-mapbox-gl/maps#112]
**Describe the bug**
My MapView on iOS doesn't adjust the position of the logo as I set my contentInset to {[0, 0, 200, 0]}.

**To Reproduce**
`<MapboxGL.MapView contentInset={[0, 0, 200, 0]} />`

**Expected behavior**
I want the Mapbox logo (and the ( i ) button) to move up from the bottom to avoid it from being covered by my views and therefor risking breaking their terms etc.

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: iPhone 8
 - OS: 12.4
 - SDK Version: 7.0.0
 - React Native Version: 0.59.8

**Comment by mfazekas** [comment]
It looks that contentInset does not adjust the logo, etc margins any more. They now have different properties

https://github.com/mapbox/mapbox-gl-native/issues/11068#issuecomment-475243612

ios:
https://docs.mapbox.com/ios/api/maps/5.0.0/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)logoViewMargins

android:
https://docs.mapbox.com/android/api/map-sdk/8.0.0/com/mapbox/mapboxsdk/maps/UiSettings.html#setLogoGravity-int-
https://docs.mapbox.com/android/api/map-sdk/8.0.0/com/mapbox/mapboxsdk/maps/UiSettings.html#setLogoMargins-int-int-int-int-

**Comment by jliebrand** [comment]
If this is still an issue, can we please re-open it? I feel there are a lot of bugs being marked as "wontfix" that shouldn't?

e.g. a stale bot is handy when there are true bugs that simply aren't worth fixing. But if there is simply a lot of functionality "still to be done", then they shouldn't be closed by a bot?
