### ISSUE TITLE
[Android] offlineManager.pause doesn't work

### ISSUE THREAD

**Issue by eugeneshe** [react-native-mapbox-gl/maps#1123]
**Describe the bug**
When offline pack downloading is in progress, I can't pause the progress

**To Reproduce**
1. call MapboxGL.offlineManager.createPack for a large area
2. in 5 seconds call pack.pause().
progressListener callback continue getting updated progress (with any tiles source - mapbox and custom)

Example:
```js
import React from 'react';
import {StyleSheet, View} from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

const styles = StyleSheet.create({
    mapView: {flex: 1},
});

class BugExample extends React.Component {
    pack: MapboxGL.OfflinePack;

    componentDidMount(): void {
        console.log('>>>>>>>>>>start creating pack', );
        MapboxGL.offlineManager.createPack(
            {
                name: 'field-1', // any
                bounds: [[32.23782523101579, 46.39912398458027], [33.43887899585923, 47.041693870480955]], // any LARGE area
                styleURL: MapboxGL.StyleURL.Street, // any
                minZoom: 12, // I hope, this can be any also
                maxZoom: 16, // I hope, this can be any also
            },
            (pack, status) => {
                console.log('>>>>>>>>>>pack progress', pack.name, status.percentage, status.completedTileCount);
                this.pack = pack;
            },
            (pack, error) => {
                console.log('>>>>>>>>>>pack error', pack.name, error);
            },
        );

        setTimeout(() => {
            console.log('>>>>>>>>>>pause pack', this.pack && this.pack.name);
            this.pack && this.pack.pause();
        }, 5000);

        setTimeout(() => {
            console.log('>>>>>>>>>>resume pack', this.pack && this.pack.name);
            this.pack && this.pack.resume();
        }, 15000);
    }

    render() {
        return (
            <View style={styles.mapView}>
                <MapboxGL.MapView
                    ref={(c) => (this._map = c)}
                    onPress={this.onPress}
                    style={styles.mapView}
                >
                    <MapboxGL.Camera
                        zoomLevel={9}
                        centerCoordinate={[-73.970895, 40.723279]}
                    />
                </MapboxGL.MapView>
            </View>
        );
    }
}

export default BugExample;
```

**Expected behavior**
progressListener stops getting updated progress.
When call pack.resume() in 10 seconds progressListener get almost the same value of progress as before pausing

Android OnePlus 6T AndroidX (wrong behavior):
```
[Tue Dec 08 2020 12:21:22.989]  LOG      >>>>>>>>>>start creating pack
[Tue Dec 08 2020 12:21:23.491]  LOG      >>>>>>>>>>pack progress field-2 14.285714285714286 0
[Tue Dec 08 2020 12:21:26.683]  LOG      >>>>>>>>>>pack progress field-2 0.025903535234785658 58 <-- value before pausing
[Tue Dec 08 2020 12:21:27.976]  LOG      >>>>>>>>>>pause pack field-2
[Tue Dec 08 2020 12:21:28.890]  LOG      >>>>>>>>>>pack progress field-2 0.051408554542882304 122
[Tue Dec 08 2020 12:21:31.400]  LOG      >>>>>>>>>>pack progress field-2 0.07691357385097895 186
[Tue Dec 08 2020 12:21:33.166]  LOG      >>>>>>>>>>pack progress field-2 0.1024185931590756 250
[Tue Dec 08 2020 12:21:35.402]  LOG      >>>>>>>>>>pack progress field-2 0.12792361246717224 314
[Tue Dec 08 2020 12:21:37.671]  LOG      >>>>>>>>>>pack progress field-2 0.1534286317752689 378
[Tue Dec 08 2020 12:21:37.987]  LOG      >>>>>>>>>>resume pack field-2
[Tue Dec 08 2020 12:21:39.887]  LOG      >>>>>>>>>>pack progress field-2 0.17893365108336554 442 <-- absolutely different value
[Tue Dec 08 2020 12:21:42.121]  LOG      >>>>>>>>>>pack progress field-2 0.20443867039146219 506
[Tue Dec 08 2020 12:21:44.649]  LOG      >>>>>>>>>>pack progress field-2 0.22994368969955883 570
[Tue Dec 08 2020 12:21:46.906]  LOG      >>>>>>>>>>pack progress field-2 0.2554487090076555 634
[Tue Dec 08 2020 12:21:47.344]  LOG      ---> background
[Tue Dec 08 2020 12:21:49.311]  LOG      >>>>>>>>>>pack progress field-2 0.28095372831575216 698
```

Ios simulator IPhone-SE 2nd generation 14.0(just to compare) (correct behavior):
```
[Tue Dec 08 2020 12:30:44.837]  LOG      >>>>>>>>>>start creating pack
[Tue Dec 08 2020 12:30:44.840]  LOG      >>>>>>>>>>pack progress field-2 0 0
[Tue Dec 08 2020 12:30:46.388]  LOG      >>>>>>>>>>pack progress field-2 1 58
[Tue Dec 08 2020 12:30:47.600]  LOG      >>>>>>>>>>pack progress field-2 1 122
[Tue Dec 08 2020 12:30:47.671]  LOG      >>>>>>>>>>pack progress field-2 1 186
[Tue Dec 08 2020 12:30:48.495]  LOG      >>>>>>>>>>pack progress field-2 1 250
[Tue Dec 08 2020 12:30:49.840]  LOG      >>>>>>>>>>pause pack field-2
[Tue Dec 08 2020 12:30:49.896]  LOG      >>>>>>>>>>pack progress field-2 1 314 <-- value before pausing
[Tue Dec 08 2020 12:30:59.850]  LOG      >>>>>>>>>>resume pack field-2
[Tue Dec 08 2020 12:31:00.262]  LOG      >>>>>>>>>>pack progress field-2 1 0
[Tue Dec 08 2020 12:31:01.477]  LOG      >>>>>>>>>>pack progress field-2 1 378 <-- almost the same value as before pausing
[Tue Dec 08 2020 12:31:02.222]  LOG      >>>>>>>>>>pack progress field-2 1 442
[Tue Dec 08 2020 12:31:07.784]  LOG      >>>>>>>>>>pack progress field-2 1 826
[Tue Dec 08 2020 12:31:09.932]  LOG      >>>>>>>>>>pack progress field-2 1 890
[Tue Dec 08 2020 12:31:11.932]  LOG      >>>>>>>>>>pack progress field-2 1 954
[Tue Dec 08 2020 12:31:13.638]  LOG      ---> inactive
[Tue Dec 08 2020 12:31:14.624]  LOG      ---> background
```

**Versions (please complete the following information):**
 - Platform: Android
 - Device: OnePlus 6T
 - Emulator/ Simulator: no
 - OS: Android 10, OxygenOS 10.3.5
 - react-native-mapbox-gl Version: 8.1.0-rc.9
 - React Native Version 0.62.2

**Additional context**
As I know, it might be a bug from native SDK, but I want to have some good workaround at least.
At the moment I delete the pack that must be paused, and if a user tries to download again, mapbox gets previously downloaded tiles from its cache. But if I need to call clearAmbientCache(), the app will delete those tiles from the cache, so I don't really like this workaround.

**Comment by ferdicus** [comment]
Hey @eugeneshe, thanks for reporting this. 
Would you kindly provide a testing ready example with our `BugReportTemplate` within `/example` (and please do make sure it runs). 

So we can spend minimal time on the setup and maximum time on the debugging. 

Thanks in advance

**Comment by eugeneshe** [comment]
I'll do that

**Comment by eugeneshe** [comment]
Updated example. I left MapboxGL.MapView & MapboxGL.Camera because it is required in BugReportTemplate. Not sure it is needed in my case, anyway... I tested that component and it works as described. Pauses ios app and do nothing for android app

**Comment by luciman** [comment]
Hi I have the same problem. Is there any solution, or workaround for this? Thanks

**Comment by systemlevel** [comment]
We're also having an issue with .unsubscribe() in Android along with the .pause().  Not sure if they broke at the same time or if it's related somehow to a recent update.

**Comment by BenjaminWatts** [comment]
Thanks for these observations -- super helpful. Looks like in general it is a bit more reliable on iOS?

Just wondering if anyone has any recommendations / best practices on managing what to do with multiple downloads, and how to handle App State changes during a download?

I had been thinking of registering a listener to hit pause on downloads, and keep the app state (specifically, which packs have been successfully downloaded) in sync with the offline db.

I noticed that getPacks returns partially downloaded packs, but without any flag to distinguish them from those which are fully downloaded, or an option (if needed) to resume.

Any pinpointing or suggestions would be super appreciated?

Awesome library otherwise!

**Comment by ferdicus** [comment]
So, I've looked into this today.
@systemlevel, was this working previously?  
I've never used this myself before :(

@eugeneshe, from what I've investigated, these are my findings:
This method [`setDownloadState`](https://github.com/mapbox/mapbox-gl-native-android/blob/6db4db9fffb7a696feb92438fa4bb6b21b65d117/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java#L332-L347) is what we're working with when we're resuming/ pausing downloads for offline regions.
As is described in mapbox' guides [here](https://docs.mapbox.com/android/maps/guides/offline/#download-a-region) it should be as "easy" as setting downloadState to `inactive`/ `active`, which is what we're indeed doing.

**PAUSE**
https://github.com/react-native-mapbox-gl/maps/blob/a1a95722b4a7f3da35ef48e258785fc79a02b39a/android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.java#L356

**RESUME**
https://github.com/react-native-mapbox-gl/maps/blob/a1a95722b4a7f3da35ef48e258785fc79a02b39a/android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.java#L385


These two are also calling [`setDownloadState`](https://github.com/mapbox/mapbox-gl-native-android/blob/6db4db9fffb7a696feb92438fa4bb6b21b65d117/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/offline/OfflineRegion.java#L332-L347).
Now comes the interesting part, on RESUME it correctly registeres the state as `0` (inactive) and attempts to set it to `1` (active) thus jumping over this clause
```java
if (this.state == state) {
  return;
}
```

However on PAUSE.... `this.state` is again registered as `0` (inactive), although the map is indeed downloading....

We do not seem to be the only ones that have this problem though.  
https://github.com/mapbox/mapbox-gl-native-android/issues/266 discusses the same issue (our very own @kristfal jumped in the discussion :)). 

The mentioned workaround is even implemented in our lib:
https://github.com/react-native-mapbox-gl/maps/blob/a1a95722b4a7f3da35ef48e258785fc79a02b39a/android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLOfflineModule.java#L583-L586

However it doesn't seem to be enough of a remedy for the issue at hand.

[This ticket](https://github.com/mapbox/mapbox-gl-native-android/issues/567) was opened  last year and didn't get much love either - I think mapbox is busy with v10 atm and engineering time is spread thin. 


Having said all that, I'm no Java crack maybe there is a super simple solution which I'm too dumb to find 🤔 

----------

#### RELATED UPSTREAM TICKETS
[Download a map and when open other maps after that get black screen #266](https://github.com/mapbox/mapbox-gl-native-android/issues/266)
[Feature Request: Add ability to pause or stop/cancel Offline Map tile downloading #567](https://github.com/mapbox/mapbox-gl-native-android/issues/567)
