### ISSUE TITLE
moveTo() function don't support center offset

### ISSUE THREAD

**Issue by SalihZinaty** [react-native-mapbox-gl/maps#1131]
moveTo() function don't have center offset.
if i moveTo() an coordinate, it will be centered on the middle of the map and i can't add offset to the center if i want it to be on the bottom of the screen
this graph describes the feature:

![20201215_100456 (1)](https://user-images.githubusercontent.com/47770409/102188210-b4eb6980-3ebd-11eb-8970-d925fe18232d.jpg)

**Comment by ferdicus** [comment]
Try something like `contentInset` from the `MapView` component.
Otherwise this is a feature request, as `moveTo` doesn't support this.

**Comment by dorthwein** [comment]
seems content inset is ignored when programmatically moving to users location by setting followUserLocation: true
