### ISSUE TITLE
mapbox-android-symbol-layer-1 only available when the app is first opened

### ISSUE THREAD

**Issue by stefanjung** [react-native-mapbox-gl/maps#1137]
The following problem exists with Android:
It seems like it does not found the "mapbox-android-symbol-layer-1" when I navigate to the component with the mapview for the second time.

Explanation of my the problem:

The LineLayer covers the PointAnnotations. To get the LineLayer below the PointAnnotations I have added the following to the LineLayer.

` belowLayerID={Platform.OS === 'android' ? 'mapbox-android-symbol-layer-1' : undefined}`

This works wonderfully, see photo

<img src="https://user-images.githubusercontent.com/10809086/103277405-33213300-49c9-11eb-9ba8-9dbc465b4eb3.png" width="200">

but the LineLayer is only visible when opening the app for the first time. If I navigate to the component with the MapView again and add new data for the LineLayer, it is not visible.

<img src="https://user-images.githubusercontent.com/10809086/103276285-67472480-49c6-11eb-80cc-99d5d2c3feb8.png" width="200" >

Without specifying belowLayerId, however, it does appear.
But it looks like this.

<img src="https://user-images.githubusercontent.com/10809086/103276295-71692300-49c6-11eb-9813-9765e9f450a6.png" width="200">

Here is the simplified example of the problem

     <MapboxGL.MapView>
          <MapboxGL.Camera
                zoomLevel={11}
            />
            // line layer who only appears on the first time
            <MapboxGL.ShapeSource id={"shapeSource"} key={key} shape={route}>
                <MapboxGL.LineLayer id={"lineLayer"}
                                    key={key}
                                    style={{lineWidth: 4, lineJoin: 'bevel', lineColor: primaryColor}}
              this is the line ---->  belowLayerID={Platform.OS === 'android' ? 'mapbox-android-symbol-layer-1' : undefined}
                >
                </MapboxGL.LineLayer>
            </MapboxGL.ShapeSource>
            
         // returns a collection of MapboxGL.PointAnnotations
            <DirectionArrows
                zoomLevel={zoomLevel}
                points={routePoints}
            />
        </MapboxGL.MapView>

 - Platform: [Android]
 - Emulator/ Simulator: [no]
 - react-native-mapbox-gl Version [8.1.0-rc10]
 - React Native Version [0.63.3]

Is there any way to change the order or to make sure that the "mapbox-android-symbol-layer-1" is available?

**Comment by stefanjung** [comment]
Fix:
I have found the issue. Every time I navigate to the component with the mapview the "mapbox-android-symbol-layer" increased. That mean the second time I navigate to the component it should be belowLayerId = "mapbox-android-symbol-layer-2" and so on.

Is there any way to get all layer IDs? So that I can find out which is the highest?

**Comment by Hannah-Alto** [comment]
not stale
