### ISSUE TITLE
About the capabilities of the library

### ISSUE THREAD

**Issue by KourpidisParis** [react-native-mapbox-gl/maps#1141]
I recently found your library and it looks quite interesting.

I want to create a simple navigation application, for example from one city to another.

As I am new to mobile development, I want to ask if the final destination can be hidden, ie the user may not be able to see the final destination.All he can see is what the next turn he will need to take and more about navigation.

Is it possible to create something like this with this library?

**Comment by ferdicus** [comment]
hi there, that's a very broad question. 
In general I would suggest to ask something like this rather in the gitter chat or stackoverflow. 
Issue tickets are mainly for ... issues with the lib. 

"Anything" is possible, right? 
You can render arbitrary elements over the map and show icons and lines on the map. 

So I'd say, technically it is possible.
