### ISSUE TITLE
pod install fails - slow download of mapbox iOS SDK

### ISSUE THREAD

**Issue by jayhaluska** [react-native-mapbox-gl/maps#1143]
**Describe the bug**  
I can not execute `pod install`successfully to install react-native-mapbox-gl.

**To Reproduce**  
```
react-native init
npm install @react-native-mapbox-gl/maps --save
cd ios
pod install
```

**Expected behavior**  
The `pod install` command should install without error in a reasonable time.

**Actual behavior**  
`pod install` starts downloading the Mapbox iOS SDK and fails after a long loading time with the following error:

```
Downloading dependencies

-> Installing @react-native-mapbox-gl-mapbox-static (5.9.0)
 > Http download
   $ /usr/bin/curl -f -L -o /var/folders/v1/sy20rf3n3954p61g681mxnc40000gn/T/d20210107-80561-yughlt/file.zip
   https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-5.9.0-dynamic-with-events.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
    49  227M   49  112M    0     0  14032      0  4:43:32  2:20:19  2:23:13   236
   curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

[!] Error installing @react-native-mapbox-gl-mapbox-static
[!] /usr/bin/curl -f -L -o /var/folders/v1/sy20rf3n3954p61g681mxnc40000gn/T/d20210107-80561-yughlt/file.zip https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-5.9.0-dynamic-with-events.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'
```

**Versions:**  
 - Dev OS: macOS Big Sur (MacBook Pro M1 Chip)
 - react-native-mapbox-gl Version ^8.1.0-rc10
 - React Native Version 0.63.4

**Additional context:**
First thing which comes to mind is that my internet connection is bad or in heavy usage. This is not the case, all other services on my machine are running fine and my connection provides up to 250 Mbit/s.

Is anyone having the same problem that the Mapbox iOS SDK download takes so long and eventually fails? It seems like this bug might just be related to the poor connection of the Mapbox servers, but I am still curious if anyone is having the same issue here.

**Comment by ferdicus** [comment]
nope, can't reproduce - maybe just an `aws` hiccup, 
feel free to reopen when it reoccurs
