### ISSUE TITLE
Heatmap Support in 7.0.0

### ISSUE THREAD

**Issue by dhee9000** [react-native-mapbox-gl/maps#115]
#### Context

I am currently writing an app that needs access to the Heatmap Layer provided in the Mapbox SDK for iOS and Android and I spent some time looking at issues on this repo and the previous one and all I could find was nitaliano/react-native-mapbox-gl#1048 explaining how support would be added in 7.0.0. I couldn't find anything in the docs or code indicating that this exists / is ready yet so I decided to go ahead and try and add it to my local fork, and I've been able to get things working on the Android side. 

It turns out the styling code was already there in RCTMGLStyle.java, all I did was clone the RCTMGLCircleLayer.java from the components/styles directory into RCTMGLHeatmapLayer.java and made everything match up and repeated for the RCTMGLCircleLayerManager.java. Then I followed the chain upwards (imports and including in various places) until I was able to access it from the React Native side of things.

#### Error

I tried to go and do the same on the iOS side and initially it seemed straightforward because the project was structured the same but I'm not really familiar with iOS development or Objective C, I was just kind of winging it and I got stuck at a build error

`No visible @interface for RCTMGLStyle declares the selector HeatmapLayer:withReactStyle:`

I checked the RCTMGLStyle.m file and the methods for Heatmaps exist, and I found a method matching what the error says is missing, I cross checked with RCTMGLCircleLayer.m and everything matches up, so I can't figure out why it's throwing that error.

Any help on getting this fixed would be greatly appreciated. Also what is the current status of Heatmaps? If there isn't currently actively development (although the existence of those functions would indicate that there is), I'd be open to adding documentation and examples and submitting a pull request if this works.

#### Environment

react-native@0.59
@react-native-mapbox-gl/maps@7.0.0
Platform: Android and iOS
Devices: Samsung Galaxy S9+, iPhone 6

**Comment by kristfal** [comment]
Hey,

Open up a PR with the code. Tag it as WIP and I’m sure we can get it all tied together. Thanks for your contribution.

**Comment by dhee9000** [comment]
Hey @kristfal,
I've added my changes to a fork and submitted a PR (#125) tagged [WIP]. Let me know if I can add anything else from my side. Thanks!

**Comment by kristfal** [comment]
Thanks for the contribution. We’ll get out a RC with this on NPM soon.
