### ISSUE TITLE
[MapBox in China] Set Coordinates inside China Causes the App to CRASH immediately

### ISSUE THREAD

**Issue by Stefan28BU** [react-native-mapbox-gl/maps#1158]
**Describe the bug**  
I'm building a map application using react-native-mapbox-gl. 

Here is the bug:
I'm using a very simple way to change the Camera View to navigate through the map, which is only by updating the centerCoordinates prop and pass the prop to **MapboxGL.PointAnnotation** to render the location pin. However, I am experiencing **crashing whenever I choose a location that is located inside of China**, I have tried many coords and even the coordinates that are on the edge of the Chinese region, the app always crashes and exits immediately, with no error messages. This also happens when I try to render a **MarkerView** as well. When I remove the **PointAnnotation** and the **MarkerView**, the App wouldn't crash but instead the Camera actions would not be triggered, it stays at the last coordinates. 

**To Reproduce**  
Steps to reproduce the behavior. 

const MapScreen: React.FC<{
    navigation: any,
}> = (props) => {
    const {
        navigation
    } = props;
    const LOCATIONS = [
        [-122.400021, 37.789085],
        [-112.400021, 3.789085],
        [-102.400021, 17.789085],
        [-22.400021, 9.789085],
        [50.400021, 39.789085],
        [39.916668, 116.383331], // Beijing's coords
    ];

    const userInfo = useSelector((state: RootState) => state.userBasicInformationReducer)

    const mapRef = useRef<MapboxGL.MapView>(null);
    const cameraRef = useRef<MapboxGL.Camera>(null);

    const [count, setCount] = useState(0);
    const [userLocation, setUserLocation] = useState(null);
    const [errorMsg, setErrorMsg] = useState(null);
    const [userLatitude, setUserLatitude] = useState(null);
    const [userLongitude, setUserLongitude] = useState(null);
    const [centerCoordinates, setCenterCoordinates] = useState(LOCATIONS[0])
    const [shouldFollowUser, setShouldFollowUser] = useState(true)

    preventTabDismissOnHideAction(navigation)

    useEffect(() => {
        console.log(JSON.stringify(userInfo, null, " "))
        MapboxGL.setTelemetryEnabled(false);
    }, [])

    const onUserLocationPressed = useCallback(() => {
        setShouldFollowUser(true)
    }, [])

    const onPress = useCallback(() => {
        setShouldFollowUser(false)
        if (count === LOCATIONS.length - 1) {
            setCount(0);
        } else {
            setCount(count + 1);
        }
    }, [count])

    useEffect(() => {
        if (!shouldFollowUser) {
            setCenterCoordinates(LOCATIONS[count]);
        }
    }, [count, shouldFollowUser])

    return (
        <View style={styles.container}>
            <MapboxGL.MapView
                ref={mapRef}
                logoEnabled={false}
                compassEnabled={false}
                zoomEnabled={true}
                localizeLabels={true}
                style={[styles.mapContainer, {

                }]}
                styleURL={'mapbox://styles/adrian-xu/ckjmvmxqt29c519pbhgx99m2i'}
            >
                <MapboxGL.PointAnnotation
                    id="USER_LOCATION_MARKER"
                    coordinate={centerCoordinates}
                />
                <MapboxGL.Camera
                    ref={cameraRef}
                    followUserLocation={shouldFollowUser}
                    zoomLevel={15}
                    animationMode={'flyTo'}
                    animationDuration={3500}
                    centerCoordinate={centerCoordinates}
                />

                <MapboxGL.UserLocation
                    onPress={onUserLocationPressed}
                />
                <MapboxGL.BackgroundLayer
                    id={'backgroundLayer'}
                    style={{
                        backgroundColor: Colors.themeColor,
                        backgroundOpacity: 0.1
                    }}
                />
            </MapboxGL.MapView>

            <ButtonCustomized
                onPress={onPress}
                label={'Change location'}
                shouldOpacify
                shouldScale
                enableHaptics
                style={{
                    position: 'absolute',
                    bottom: Layout.BOTTOM_TAB_HEIGHT,
                    height: Layout.BOTTOM_TAB_HEIGHT / 2,
                }}
            />
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center'
    },
    mapContainer: {
        width: '100%',
        height: Layout.height - Layout.BOTTOM_TAB_HEIGHT,
        position: 'absolute',
        top: 0,
    }
})
MapScreen.displayName = 'MapScreen'
export default MapScreen

**Expected behavior**  
The PointAnnotation would render and the Camera would navigate to all six locations without crashing

**Actual behavior**  
The PointAnnotation renders and the Camera navigates to the first fifth locations without a problem but crashs and exits the app the the sixth location, which is inside China

**Screenshots**  

**Versions (please complete the following information):**  
 - Platform: Android, iOS
 - Platform OS: iOS 13, 12
 - Device: iPhone X, 11
 - Emulator/ Simulator: no
 - Dev OS: OSX 10.5.7
 - react-native-mapbox-gl Version [8.1.0]
 - React Native Version [0.63.4]

**Additional context**  
I'm building the app inside China, I don't know if this is anything to do with the Chinese government regulations. Since MapBox.cn was already announced in China I assumed this package is usable in China.

**Comment by ferdicus** [comment]
hey @Stefan28BU, thanks for the bug report. 

In order to process this issue, please follow these additional steps:
* reproduce the issue using our [`BugReportTemplate`](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/BugReportExample.js) within the `/example` project in our repo
* please ensure that it builds
* your edited `BugReportExample` actually works
* your issue is reproducible there

Thanks in advance
Let me know if you have additional questions

**Comment by Stefan28BU** [comment]
@ferdicus Will do later, do I need to add the API key as well?

**Comment by Stefan28BU** [comment]
> hey @Stefan28BU, thanks for the bug report.
> 
> In order to process this issue, please follow these additional steps:
> 
> * reproduce the issue using our [`BugReportTemplate`](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/BugReportExample.js) within the `/example` project in our repo
> * please ensure that it builds
> * your edited `BugReportExample` actually works
> * your issue is reproducible there
> 
> Thanks in advance
> Let me know if you have additional questions

How am I suppose to reproduce the issue if the app just crashes with no stacktrace?

**Comment by DRosen1996** [comment]
哥们，中国大陆数据合规瓦片地图的问题你咋解决的
