### ISSUE TITLE
[ANDROID][8.1.0] User location in native mode crashes

### ISSUE THREAD

**Issue by Alaa-Ben** [react-native-mapbox-gl/maps#1167]
Hi all !
Pretty simple, when adding `renderMode='native`' on android, it crashes.
`<MapboxGL.UserLocation renderMode='native' androidRenderMode='compass' />`

The error I'm getting: 

> Mapbox error Exception in onDidFinishLoadingStyle {"level": "error", "message": "Exception in onDidFinishLoadingStyle", "tag": "Mbgl-MapChangeReceiver"}

Any ideas ?

**Comment by bahung1221** [comment]
Same, I downgraded to v8.0 to use `renderMode='native'`

**Comment by Alaa-Ben** [comment]
That's weird, I thought native user location was added in 8.1.0 because of this line in the changelog:
 

> Native user location #825

**Comment by bahung1221** [comment]
Ah, it seems I have misleading for `renderMode native`, in my case (maybe also your case) I just want to show the user `direction indicator`, so I using below code to achieve it, ofcourse `renderMode native` doesn't work but `showsUserHeadingIndicator` worked:

```
<MapboxGL.MapView
    ref={this.setMapRef}
    styleURL={offlineStyleUri}
    style={styles.map}
>
    <MapboxGL.Camera
        animationDuration={0}
        centerCoordinate={DEFAULT_CENTER_COORDINATE}
        zoomLevel={4.5}
    />
    <MapboxGL.UserLocation
        visible
        renderMode="native"
        showsUserHeadingIndicator
    >
    </MapboxGL.UserLocation>
</MapboxGL.MapView>
```

Sorry for the misleading 🤣

**Comment by ferdicus** [comment]
@Alaa-Ben , can you post your `Camera` Component please?
I think you have to have `followUserLocation` enabled.

THIS: `Mapbox error Exception in onDidFinishLoadingStyle {"level": "error", "message": "Exception in onDidFinishLoadingStyle", "tag": "Mbgl-MapChangeReceiver"}`
```react
<MapView style={styles.mapView}>
  <Camera />
  <UserLocation renderMode='native' androidRenderMode='compass' />
</MapView>
```


THIS: `Works fine`
```react
<MapView style={styles.mapView}>
  <Camera followUserLocation />
  <UserLocation renderMode='native' androidRenderMode='compass' />
</MapView>
```

only difference `followUserLocation`

Give it a spin

Cheers 🍻

**Comment by Alaa-Ben** [comment]
@ferdicus Thanks for you answer, it works. Is the crash expected ? in that case, I think the docs should specify that "renderMode: native" requires followUserLocatrion. If not expected, well a fix would be huge ! 
thanks anyways !

**Comment by ferdicus** [comment]
> @ferdicus Thanks for you answer, it works. Is the crash expected ? in that case, I think the docs should specify that "renderMode: native" requires followUserLocatrion. If not expected, well a fix would be huge !
> thanks anyways !

Glad it helped, 
I guess it makes sense, that it should follow the Location, as the user specified, that she wants a specific version of a UserLocation... however, I do think this could be handled better - especially the message.

**Comment by chuchuva** [comment]
I can reproduce the crash on Android too. It looks very strange to me - if I want native render mode for UserLocation component I need to set `followUserLocation` to true on the Camera component. Why?

**Comment by kabbi** [comment]
I think that's because of the code in `RCTMGLCamera.java`:

```
    @Override
    public void addToMap(RCTMGLMapView mapView) {
    
        // ...

        if (mFollowUserLocation) {
            enableLocation();
        }
    }
```
