### ISSUE TITLE
Understanding SymbolLayer (iconSize / iconImage)

### ISSUE THREAD

**Issue by alex83130** [react-native-mapbox-gl/maps#1168]
I reopen a discussion started on that previous closed PR : #226 because I have faced of the same issue.
In the documentation It's write that `iconSize` is a `number` but within the examples (`ShapeSourceIcon`) there is that case :

```
 iconSize: [
      'match',
      ['get', 'icon'],
      'example',
      1.2,
      'airport-15',
      1.2,
      /!* default *!/ 1,
    ]
```
I have difficulties to understand how this one should work...

**Comment by ferdicus** [comment]
hey @alex83130, this isn't really an issue - for questions like this please refer to our gitter channel (link is in README) or open a ticket in the actual Discussions section of the repo.

As for your question:
Type is a number, however multiple styles also take [`expressions`](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/) as a parameter instead.
[Official style-spec of icon-size](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-icon-size)


Cheers 🍻

**Comment by punov** [comment]
@alex83130 for your question above, the expression means:
if icon name === 'example' then return 1.2 for icon size.
if icon name === 'airport-15', icon size will be also 1.2
by default, it's going to be 1
