### ISSUE TITLE
MapboxGL.UserLocation onUpdate - location param can be undefined

### ISSUE THREAD

**Issue by jirizikmund** [react-native-mapbox-gl/maps#1169]
### Component **MapboxGL.UserLocation**, property **onUpdate**.

**Problem**
When application doesn't have access to the location service, param `location` in function onUpdate is undefined. Typescript annotation wrongly says it is alway defined.
```onUpdate?: (location: MapboxGL.Location) => void;```

https://github.com/react-native-mapbox-gl/maps/blob/b3d82a85cf95fbdae5c5924fdfe967e24aa4b46f/index.d.ts#L480

Tested on iOS 14.3 physical device.

**Comment by ferdicus** [comment]
resolved via https://github.com/react-native-mapbox-gl/maps/commit/da56973c0f1c477a6354fe7ae3346fc755fb3c42
