### ISSUE TITLE
react-native-gesture-handler compatibility

### ISSUE THREAD

**Issue by mrousavy** [react-native-mapbox-gl/maps#1188]
We're building an app which has a similar structure as the Snapchat app. Snapchat's homescreen contains 5 screens, which you can easily navigate using a horizontal swipe gesture.

![image](https://user-images.githubusercontent.com/15199031/105031007-f2ab5700-5a54-11eb-880f-12c967bf232e.png)

This raises the question; How do you want to differentiate between the **horizontal swipe gesture**, and a **map pan gesture** when you're on the left most screen (map)?

Snapchat solves this problem quite elegantly by only activating the **horizontal swipe gesture** handler when the user starts swiping from the _absolute screen edge_ (about a 5 pixel threshold I'd say), everything else is a **map pan gesture**.

Unfortunately this isn't easily achievable using React Native, that's why I'm creating this issue. We're using [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler) to create the horizontal swipe gesture, but since the react-native-mapbox-gl's gesture handlers (UIPanGestureResponder, ..) are not exposed using the react-native-gesture-handler API we cannot easily interop between the two gesture handlers.

This is how it currently behaves:

https://user-images.githubusercontent.com/15199031/105031667-ea075080-5a55-11eb-9ff5-b87a3d3d29f0.mov

As you can see, the **horizontal swipe gesture** often gets activated when the user's intention is to activate the **map pan gesture**, and vice versa. Ideally I only want to activate the **horizontal swipe gesture** if the user starts swiping from the right screen edge.

On Android the gestures are even worse, they sometimes activate both at the same time, causing really weird and unusable UX

That's why I'm thinking about the following two solutions:

1. Export the map's X and Y properties so we can disable the native `UIPanGestureResponder` and wrap the map with our own `<PanGestureHandler>` from react-native-gesture-handler, which effectively allows us to easily specify activation criteria using the JS-developer-friendly RNGH API. X and Y properties of the map are then mapped with reanimated so it feels and performs natively at 60fps.
2. Export activation criteria properties for the native `UIPanGestureResponder`, such as `minDistanceToEdge`. Setting said prop to e.g. `20` will not activate the `UIPanGestureResponder` of the map (**map pan gesture**) when the user started the gesture within 20 pixels from the map view's edge. Since that's not being activated, my **horizontal swipe gesture** handler can then pick up the gesture

**Comment by mrousavy** [comment]
If anyone has a better solution or workaround to this problem, let me know 💡

**Comment by mrousavy** [comment]
I'm working on `minDistFromEdge` here: https://github.com/software-mansion/react-native-gesture-handler/pull/1310

**Comment by ferdicus** [comment]
closing as resolved
