### ISSUE TITLE
[Android] Support for showing custom view over annotation

### ISSUE THREAD

**Issue by MariaSyed** [react-native-mapbox-gl/maps#119]
**Description**
I cannot find a way to show a custom `View` component over an `Annotation` on Map. Something similar to the old deprecated `PointAnnotation` where children of `PointAnnotation` were shown over a point on the map. 

`PointAnnotation` works perfectly on iOS though.

**To Reproduce**

on *Android* 

```
<MapboxGL.Annotation key={key} id={id} coordinates={coordinates}>
     <View style={styles.annotationContainer}>
           <Text>FLOATING ANNOTATION TEXT</Text>
    </View>
</MapboxGL.Annotation>
```

or 

```
<MapboxGL.PointAnnotation key={key} id={id} coordinate={coordinates}>
     <View style={styles.annotationContainer}>
           <Text>FLOATING ANNOTATION TEXT</Text>
    </View>
</MapboxGL.PointAnnotation>
```

**Expected behaviour**
Floating text over coordinates

**Versions (please complete the following information):**
 - Platfrom: Android 
 - Device: OnePlus 6T
 - OS: Android 9
 - SDK Version 7.0.0
 - React Native Version 0.59.8

**Comment by SethTyemill** [comment]
Could someone please help with this issue?

**Comment by stefen** [comment]
Is there any plan to address this? Should applications that rely on this functionality look at migrating away from Mapbox? Any reason why this should work on iOS and not Android?
