### ISSUE TITLE
It's not possible to set compassViewPosition to bottom left on Android 

### ISSUE THREAD

**Issue by ilin-in** [react-native-mapbox-gl/maps#1193]
**The problem:**
When `compassViewPosition` on `MapView` is set to `2`, compass located at right bottom corner

https://github.com/react-native-mapbox-gl/maps/blob/3e22d042ff64ecef3c55e0893a94d4a43c4d02a7/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java#L1091

**Expected behavior:**   
Compass should be located at the left bottom corner

**Solution:** 
Here I've made a PR for this issue: https://github.com/react-native-mapbox-gl/maps/pull/1192

**Comment by ferdicus** [comment]
PR merged - thanks 🙇🏿
