### ISSUE TITLE
Please add the usage of component methods to the docs

### ISSUE THREAD

**Issue by JRafiei** [react-native-mapbox-gl/maps#1206]
Sorry If it is a simple question but I couldn't find a way to use component methods in my app. For example MapView component has a getZoom method, but it is unclear how to use that method in another component like App component.

**Comment by ferdicus** [comment]
You utilize `ref`  and get a handle of that component instance. 
On this `ref` you can call the methods.

Check out the [`ShowPointAnnotation`](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/Annotations/ShowPointAnnotation.js) example

**Comment by alex83130** [comment]
I had the same question, thanks @ferdicus !
Agree with @JRafiei it would be great if these informations could be specified directly within the documention

**Comment by ferdicus** [comment]
this isn't specific for this lib though - that's a react(-native) thing

**Comment by JRafiei** [comment]
thanks a lot @ferdicus, that solved my problem.
You are right, this is a react feature. But I think it is a little confusing when someone see the below code for the first time:
const pointInView = await this._map.getPointInView([-37.817070, 144.949901]);
It is unclear where does this._map come from, especially when you are working with a functional component.

**Comment by ferdicus** [comment]
@JRafiei, feel free to augment the [Getting Started docs](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/GettingStarted.md). PRs always welcome.

**Comment by JRafiei** [comment]
@ferdicus, I would be glad to do it, but first I need to learn about creating and submiting pull requests.
