### ISSUE TITLE
Mapview.Flyto method doesn't work.

### ISSUE THREAD

**Issue by panda919** [react-native-mapbox-gl/maps#121]
I updated mapbox plugin from 6.1.3 to 7.0.0-rc2.
I try to call MapView.flyto method in my app.
But it seems this method is using MapView.setcamear method.
I got SetCamrea method is deprecated.
But API document mentioned MapView compoenet include fl;yto method yet.
And, My app using flyTo method.
I have no idea for it.

**Comment by MariaSyed** [comment]
I think that method is deprecated. There is an example for `FlyTo` : https://github.com/react-native-mapbox-gl/maps/blob/ec27927cd5b544dfdb9c536e7857fd9bb759ccdf/example/src/examples/FlyTo.js

I am following that, by changing `centerCoordinate` via state :) Hope it helps.

**Comment by kristfal** [comment]
@mariaSyed, this is correct. Thanks for clarifying.
