### ISSUE TITLE
iOS crash when adding a HeatmapLayer

### ISSUE THREAD

**Issue by zholmes1** [react-native-mapbox-gl/maps#1211]
**Describe the bug**  
This library appears to crash on iOS any time there is a HeatmapLayer in a map.

**To Reproduce**  
Add any `HeatmapLayer` to a map and `react-native run-ios`. The app will crash

I have created a minimal repository that causes the crash on iOS. https://github.com/zholmes1/MapboxHeatmapExample

Crash report:
https://raw.githubusercontent.com/zholmes1/MapboxHeatmapExample/master/MapboxHeatmapExample_2021-02-08-190724_Zachs-MacBook-Pro.crash

Example:
```js
import React, {Component} from 'react';
import {StyleSheet, View} from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

MapboxGL.setAccessToken('YOUR-ACCESS-TOKEN');

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  container: {
    height: 300,
    width: 300,
    backgroundColor: 'tomato',
  },
  map: {
    flex: 1,
  },
});

export default class App extends Component {
  componentDidMount() {
    MapboxGL.setTelemetryEnabled(false);
  }

  render() {
    return (
      <View style={styles.page}>
        <View style={styles.container}>
          <MapboxGL.MapView style={styles.map}>
            <MapboxGL.VectorSource
              id="occurrence"
              tileUrlTemplates={[
                `https://api.gbif.org/v2/map/occurrence/density/{z}/{x}/{y}.mvt?taxonKey=8671098`,
              ]}>
              <MapboxGL.HeatmapLayer
                id="occurrence"
                sourceID="occurrence"
                sourceLayerID="occurrence"
                style={{
                  heatmapOpacity: 0.5,
                  heatmapRadius: [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    0,
                    2,
                    9,
                    20,
                  ],
                }}
              />
            </MapboxGL.VectorSource>
          </MapboxGL.MapView>
        </View>
      </View>
    );
  }
}

```

**Expected behavior**  
HeatmapLayer works properly on iOS

**Actual behavior**  
App hard crashes

**Versions (please complete the following information):**  
 - Platform: iOS
 - Platform OS: 14.1
 - Device: iPhone 11
 - Emulator/ Simulator: Both
 - Dev OS: macOS 11.1
 - react-native-mapbox-gl Version: 8.1.0
 - React Native Version: 0.63.4
 
**Other**
It appears this crash was documented in 2019 in the `mapbox-gl-native` repository. There was a merged into that repository that was meant to fix this crash. https://github.com/mapbox/mapbox-gl-native/issues/14807

**Comment by ferdicus** [comment]
Hey @zholmes1, thanks for the great bug report. 
I could've a look at this on Friday - in the meantime: 
* what SDK version are you using right now?
* if you are on `5.8.0` which should be the default pack-in, did you try a newer one?

Cheers 🍻

**Comment by zholmes1** [comment]
@ferdicus Thanks for the quick reply! If there's anything else I can do to help don't hesitate to ask. I really love this library and want to see it in all its glory 😄 

I'm on 5.9.0

```
  - react-native-mapbox-gl (8.1.0):
    - "@react-native-mapbox-gl-mapbox-static (~> 5.9.0)"
    - Mapbox-iOS-SDK (~> 5.9.0)
    - React
    - React-Core
    - react-native-mapbox-gl/DynamicLibrary (= 8.1.0)
    - react-native-mapbox-gl/StaticLibraryFixer (= 8.1.0)
  - react-native-mapbox-gl/DynamicLibrary (8.1.0):
    - "@react-native-mapbox-gl-mapbox-static (~> 5.9.0)"
    - Mapbox-iOS-SDK (~> 5.9.0)
    - React
    - React-Core
  - react-native-mapbox-gl/StaticLibraryFixer (8.1.0):
    - "@react-native-mapbox-gl-mapbox-static (~> 5.9.0)"
    - Mapbox-iOS-SDK (~> 5.9.0)
    - React
    - React-Core
```

FYI I do have a fallback in place for iOS using `RasterSource and RasterLayer`. Luckily my data source (GBIF) provides both .mvt and .png raster

**Comment by ferdicus** [comment]
Cool, thanks - that's enough info to debug this issue for sure. 
Can you just do me a solid, and verify if this is still happening in the newer version of the SDK please.

`6.3.0` should be fine I think

**Comment by zholmes1** [comment]
@ferdicus 

So I updated my iOS SDK to 6.3.0 following this guide: https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md

And it seems like this may have solved my issue! I am able to reliably load the heatmap on iOS. Opened and closed the example app 10 times now and no crashes. Unfortunately I'm only working on a simulator right now, so I can't confirm that there are no performance issues.

Also, I'm seeing this warning that I never saw on Android. Not sure if it's related.

```
[Tue Feb 09 2021 11:47:32.111]  WARN     Mapbox warning Falling back to MGLIdeographsRasterizedLocally because  MGLIdeographicFontFamilies are specified. {"filePath": "-[MGLRendererConfiguration glyphsRasterizationOptionsWithLocalFontFamilyName:rasterizationMode:]", "level": "warning", "line": 111, "message": "Falling back to MGLIdeographsRasterizedLocally because  MGLIdeographicFontFamilies are specified."}
```

**Comment by ferdicus** [comment]
Cool 👍🏿 

Unfortunately I'm unfamiliar with this warning... looks like some font is missing? 

Best to check on the ios sdk repo probably for that.

**Comment by zholmes1** [comment]
Okay great! Thanks for the quick resolution to this. I'll leave it up to you whether this issue should be closed or not. It will take care of itself whenever this repo updates to the 6.3 iOS SDK.

**Comment by Degn** [comment]
I'm experiencing the same issue with the same verisons and code as @zholmes1. 

However, if I add a few lines of code in the Render-function before the return of the map, it runs as expected. Maybe there is some async-issues somewhere in the SDK? 

I hope this helps the investigation 🤓 

The exact piece of code that does the difference for me is this:

```
                const rawData = [
                  {name: 'Feature 1', value: 2, latitude: 1.12345, longitude: -3.4567},
                  {name: 'Feature 2', value: 5, latitude: 1.2345, longitude: -5.678},
                ];

                const makeGeoJSON = (data) => {
                  return {
                    type: 'FeatureCollection',
                    features: data.map(feature => {
                      return {
                        "type": "Feature",
                        "properties": {
                          "id": feature.name,
                          "value": feature.value
                        },
                        "geometry": {
                          "type": "Point",
                          "coordinates": [ feature.latitude, feature.longitude]
                        }
                      }
                    })
                  }
                };

                const myGeoJSONData = makeGeoJSON(rawData);
```

**Comment by gokugen** [comment]
> @ferdicus
> 
> So I updated my iOS SDK to 6.3.0 following this guide: https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md
> 
> And it seems like this may have solved my issue! I am able to reliably load the heatmap on iOS. Opened and closed the example app 10 times now and no crashes. Unfortunately I'm only working on a simulator right now, so I can't confirm that there are no performance issues.
> 
> Also, I'm seeing this warning that I never saw on Android. Not sure if it's related.
> 
> ```
> [Tue Feb 09 2021 11:47:32.111]  WARN     Mapbox warning Falling back to MGLIdeographsRasterizedLocally because  MGLIdeographicFontFamilies are specified. {"filePath": "-[MGLRendererConfiguration glyphsRasterizationOptionsWithLocalFontFamilyName:rasterizationMode:]", "level": "warning", "line": 111, "message": "Falling back to MGLIdeographsRasterizedLocally because  MGLIdeographicFontFamilies are specified."}
> ```

Hi, for your warning you can simply dismiss it like that:

```js
import Logger from '@react-native-mapbox-gl/maps/javascript/utils/Logger';

Logger.setLogCallback(log => {
    const { message } = log;

    // expected warnings
    if (message.includes('MGLIdeographsRasterizedLocally'))
        return true;
    return false;
});
```

**Comment by ferdicus** [comment]
@zholmes1 , btw, I've found what's causing the warning - it's based on a change introduced by the upstream SDKs:
[ios](https://github.com/mapbox/mapbox-gl-native-ios/issues/589) / [android](https://github.com/mapbox/mapbox-gl-native-android/issues/649)

It's annoying, however I think it's save to ignore
