### ISSUE TITLE
Heading indicator does not work when map is not facing north

### ISSUE THREAD

**Issue by jaltin** [react-native-mapbox-gl/maps#1214]
The blue ‘cone’ that indicates the user’s heading on the map has a bug.

When the map is ‘north-oriented’ (map direction is 0 degrees), then the heading indicator works as expected.

When the map direction is not ‘north-oriented’ (e.g. when having map follow mode course or compass), then the blue ‘cone’ is not pointing in the same direction as the device.

This is a styling bug and we have created a PR to correct this.

**Comment by mzu** [comment]
I think this touches on [issue #1023](https://github.com/react-native-mapbox-gl/maps/issues/1023)

**Comment by jaltin** [comment]
@mzu yes, and I think that our PR fixes the issue, right?

**Comment by ferdicus** [comment]
resolved via #1215
