### ISSUE TITLE
Support new Mapbox iOS SDK v10

### ISSUE THREAD

**Issue by cbrevik** [react-native-mapbox-gl/maps#1221]
Ref. https://github.com/mapbox/mapbox-gl-native-ios/commit/ddf8e35970d1a8a46171bd798bcfa8f22d2760e0 - it seems like Mapbox is soft-deprecating the old SDK, and moving their development efforts to a new repository: https://github.com/mapbox/mapbox-maps-ios

I've no idea how much work it would be to migrate to this new version. And it's early days still since it's in beta. But there might be reason to start looking into this early?

Since they are introducing improvements to how the SDK works, as well as the architecture, it might remedy some of the issues we've had. Like #1097?

**Comment by systemlevel** [comment]
Check out our discussion about this here https://github.com/react-native-mapbox-gl/maps/discussions/1202

**Comment by cbrevik** [comment]
Ah sorry for the duplicate! Thanks for the heads up.
