### ISSUE TITLE
zoomLevel not working

### ISSUE THREAD

**Issue by prox2** [react-native-mapbox-gl/maps#1227]
When map loading and opned doesn't zoom even though have set zoom level

  ```
  <View style={styles.matchParent}>


                <MapboxGL.MapView
                    surfaceView={true}
                    zoomLevel={15}
                    logoEnabled={false}
                    style={styles.matchParent}>
                    <MapboxGL.UserLocation
                        visible={true}
                        onUpdate={this.onUserLocationUpdate}
                    />
                    <MapboxGL.Camera
                        zoomLevel={15}
                        followUserMode={'normal'}
                        followUserLocation={true}
                        animationDuration={0}
                    />
                </MapboxGL.MapView>
                {this.renderLocationInfo()}

            </View>
```

**Comment by SSead** [comment]
Try to add the zoomLevel in the defaultSettings property for the camera

```
 <MapboxGL.MapView
                  surfaceView={true}
                  zoomLevel={15}
                  logoEnabled={false}
                  style={styles.matchParent}>
                  <MapboxGL.UserLocation
                      visible={true}
                      onUpdate={this.onUserLocationUpdate}
                  />
                  <MapboxGL.Camera
                      defaultSettings={{zoomLevel: 15}}
                      followUserMode={'normal'}
                      followUserLocation={true}
                      animationDuration={0}
                  />
              </MapboxGL.MapView>
```

**Comment by prox2** [comment]
> Try to add the zoomLevel in the defaultSettings property for the camera
> 
> ```
>  <MapboxGL.MapView
>                   surfaceView={true}
>                   zoomLevel={15}
>                   logoEnabled={false}
>                   style={styles.matchParent}>
>                   <MapboxGL.UserLocation
>                       visible={true}
>                       onUpdate={this.onUserLocationUpdate}
>                   />
>                   <MapboxGL.Camera
>                       defaultSettings={{zoomLevel: 15}}
>                       followUserMode={'normal'}
>                       followUserLocation={true}
>                       animationDuration={0}
>                   />
>               </MapboxGL.MapView>
> ```

still same problem

**Comment by ferdicus** [comment]
check `followZoomLevel` in the `Camera` docs

**Comment by prox2** [comment]
> check `followZoomLevel` in the `Camera` docs

I am still facing the same problem i have checked  the camera doc

**Comment by ferdicus** [comment]
then please edit the issue description and use the [bug_template](https://github.com/react-native-mapbox-gl/maps/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) precisely in order for us to help you. 

Test the issue within the example application in `/example` before you submit

**Comment by lockieluke** [comment]
still not fixed
