### ISSUE TITLE
Too much time to install pods Mapbox-iOS-SDK (5.9.0)

### ISSUE THREAD

**Issue by mustafaskyer** [react-native-mapbox-gl/maps#1230]
**Describe the bug**  
installing pods stuck on `Installing Mapbox-iOS-SDK (5.9.0)`, take too long time and it's not done yet
Testing network speed, no issues with my connection

**To Reproduce**  
Steps to reproduce the behavior. 
run `npx pod-install ios` stuck

Please include a single standalone React Native component.  
`No Issues in code`

**Expected behavior**  
Success pods install as usual

**Actual behavior**  
Pods take too much time to install `Mapbox-iOS-SDK (5.9.0)`

**Screenshots**  

**Versions (please complete the following information):**  
 - Platform: iOS
 - Platform OS:  iOS 12.0
 - Device: iPhone Xs Max
 - Emulator/ Simulator: YES
 - Dev OS: macOS 11.2.1
 - react-native-mapbox-gl Version: ^7.2.0 // also tried last version 8.0.1
 - React Native Version: 0.63.3

**Comment by mustafaskyer** [comment]
Updated
```js
[!] Error installing Mapbox-iOS-SDK
[!] /usr/bin/curl -f -L -o /var/folders/mf/0rzvnvhj2y38dfrw8fs050rw0000gn/T/d20210221-5122-fuh3sp/file.zip https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-5.9.0-dynamic.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.9.3 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0  224M    0 1520k    0     0   1295      0 50:28:37  0:20:01 50:08:36     0
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
```

**Comment by ferdicus** [comment]
Hey there, please do search the issues before opening a new one:
https://github.com/react-native-mapbox-gl/maps/issues/837
https://github.com/react-native-mapbox-gl/maps/issues/750

It's downloading the iOS SDK from mapbox - nothing we can do.

**Comment by gigby** [comment]
@mustafaskyer I solved this "issue" by using a VPN service

**Comment by babar-ali-memon** [comment]
any solution for this ?
