### ISSUE TITLE
Can modify of layers/styles of layers added through style.json

### ISSUE THREAD

**Issue by benglass** [react-native-mapbox-gl/maps#1232]
## Problem Statement

We want to be able to dynamically modify the styles of a layer (for example change the opacity of the stroke) when the layer and its styles are being added automatically based on a style.json provided to `<MapView styleURL={...} />`

## Description

We have an application where we want users to be able to dynamically change the styling of features that are rendered through the style json passed to `<MapView styleURL={...} />`

For example, let's say we want the user to be able to change the opacity of a line layer with the id `my-layer` that is defined in the style.json.

In Mapbox iOS SDK, it looks like we could do something like this

```swift
let style = mapView.style
let myLayer = style.layer(withIdentifier: "my-layer") 
myLayer?.lineOpacity = NSExpression(forConstantValue: 0.5)
```

Is there a way to get at/call methods on the underlying `MGLStyleLayer` instances (in this case an `MGLLineStyleLayer` instance for `my-layer`) so that we can manipulate the styles dynamically for layers that are rendered from a style.json? Or to invoke native methods on it?

### Using a ref to the map

```jsx
<MapView ref={map => {
    // This map object doesnt seem to have any way to get layers to show/hide them or manipulate their style
}} />
```

### Using onDidFinishLoadingStyle/Map methods

```jsx
// Neither of these methods passed any arguments to the callback so we did not have any additional access to APIs to get at layers/styles
<MapView onDidFinishLoadingStyle={} />
<MapView onDidFinishLoadingMap={} />
```

Thanks for your assistance in understanding whether this is possible

**Comment by mattijsf** [comment]
Have a look at https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/ShowAndHideLayer.js

**Comment by benglass** [comment]
@mattijsf Thanks for pointing me at that example, it helped me connect the dots that you can use the declarative `<MapboxGL.LineLayer>` API to change the opacity/styles of layers that are defined in the style.json

It sounds like perhaps there is no imperative alternative when using react native where we can do this in code without using the declarative/JSX API. Is that an accurate conclusion?

Thanks again for your time in responding.

**Comment by mattijsf** [comment]
Yes apart from some exceptions this is correct
