### ISSUE TITLE
use userLocation with react native hooks

### ISSUE THREAD

**Issue by prox2** [react-native-mapbox-gl/maps#1235]
I am using `MapBox `library with function component instead of class component as in examples  and when I use  `<MapboxGL.UserLocation` there is a method called  `onUpdate={() => onUserLocationUpdate()}` and `onUserLocationUpdate()` refer to :
```
const onUserLocationUpdate = async (location) => {
        //console.log(location)
        let lat = location.coords.latitude;
        let long = location.coords.longitude;
        let alt = location.coords.altitude;
        setlatitude(lat)
        setlongitude(long)
        setaltitude(alt)
} 
```
 so when `onUserLocationUpdate ` called I am getting this error: 
```
TypeError: undefined is not an object (evaluating 'location.coords')
onUserLocationUpdate$
    
```

**Comment by prox2** [comment]
@ferdicus issue updated with template check it here  #1236

**Comment by ferdicus** [comment]
> @ferdicus issue updated with template check it here #1236

thank you - much obliged, I've replied on the other issue
