### ISSUE TITLE
UserLocation not showing on the screen

### ISSUE THREAD

**Issue by iromjkee** [react-native-mapbox-gl/maps#1237]
**Describe the bug**  
User Location blue dot not showing on the screen.

**To Reproduce**  
```
<MapboxGL.MapView
        styleURL={MapboxGL.StyleURL.Satellite}
        zoomEnabled={true}
        style={styles.map}>
        <MapboxGL.UserLocation visible={true} animated={true} />
        <MapboxGL.Camera
          animimationMode={'flyTo'}
          animationDuration={0}
          followUserLocation={true}
          followUserMode={'normal'}
          zoomLevel={16}
        />
</MapboxGL.MapView>
```
**Expected behavior**  
Show default blue dot accordingly to User Location

**Actual behavior**  
Don`t see user location, even zooming not working, just see default map.

**Screenshots**  
![image](https://user-images.githubusercontent.com/25479692/109143740-6ab21e80-7771-11eb-9af9-4ceae05228b2.png)

**Versions (please complete the following information):**  
 - Platform: iOS
 - Platform OS: iOS 14.4
 - Device: iPhone X
 - Emulator/ Simulator: yes
 - Dev OS: macOS Catalina 10.15.5
 - react-native-mapbox-gl Version 8.1.0
 - React Native Version 0.63.4

**Additional context**  
User Location  doesn't seem to fire. I searched the docs and according to it all should be working.

**Comment by schiller-manuel** [comment]
You need to start the location manager, see this example:

https://github.com/react-native-mapbox-gl/maps/blob/963a77b7ce716d1f5b8b64fd5a45c0fcf90aac61/example/src/examples/Map/ShowMap.tsx#L21-L27

**Comment by ferdicus** [comment]
@schiller-manuel , that shouldn't be necessary - I think I've added that part, because it wouldn't stop the `locationManager` when unmounting the map... 

it works just fine for me within the `/example` app => `ShowMap.tsx` even without starting and stopping locationManager

**Comment by ansarikhurshid786** [comment]
most probably location use description not mentioned in plist in xcode

**Comment by iromjkee** [comment]
@ansarikhurshid786 , @ferdicus Could you please tell what should be enabled in plist in xcode? For now for location have only this
![image](https://user-images.githubusercontent.com/25479692/114377215-129f7200-9b8f-11eb-8414-6501a41b9de4.png)

**Comment by ferdicus** [comment]
@iromjkee, did you check the `/example` app as I've mentioned in previous comments?
Try to replicate your issue there - come back if you can reproduce it there. 
If the issue is not present in the `example` app, check for differences in the plist concerning permissions.

**Comment by iromjkee** [comment]
@ferdicus Yes, I did, but nothing has changed. What  differences in the plist concerning permissions? What should permissions be like? I`ve added this for location permissions.
![image](https://user-images.githubusercontent.com/25479692/115431511-145fda00-a20e-11eb-8f0e-fc11bf1e5edb.png)
