### ISSUE TITLE
Build fail because of MapBox iOS SDK

### ISSUE THREAD

**Issue by iromjkee** [react-native-mapbox-gl/maps#1242]
**Describe the bug**  
React native iOS build fail because of MapBox iOS SDK

**To Reproduce**  
Install latest version of  @react-native-mapbox-gl/maps (currently 8.1.0)

**Expected behavior**  
MapBox package working

**Actual behavior**  
Build fails

**Screenshots**  
![image](https://user-images.githubusercontent.com/25479692/109298194-42472480-7844-11eb-9c36-116f971935cc.png)

**Versions (please complete the following information):**  
 - Platform:  iOS
 - Platform OS:  iOS 14.4
 - Device: iPhone 11
 - Emulator/ Simulator: yes
 - Dev OS: macOS Catalina 10.15.5
 - react-native-mapbox-gl Version: 8.1.0
 - React Native Version: 0.63.4

**Additional context**  
Before MapBox was working normally, now just getting this build error all the time.

**Comment by ferdicus** [comment]
Can you please retry this in the `/example` project? 

Thanks

**Comment by muxton21** [comment]
In the end, I managed to solve this by downgrading Cocoapods to version '1.9.3'

**Comment by Merrick17** [comment]
@muxton21  can you please show me how you did the downgrade ?
