### ISSUE TITLE
(iOS) TypeError: null is not an object (evaluating 'MapboxGL.StyleURL')

### ISSUE THREAD

**Issue by Farhadsaadatpei** [react-native-mapbox-gl/maps#1244]
I'm using Expo, and I keep getting the following error when including MapBox GL in the view.

TypeError: null is not an object (evaluating 'MapboxGL.StyleURL')

<img width="428" alt="Screen Shot 2021-02-27 at 3 01 56 PM" src="https://user-images.githubusercontent.com/10551124/109398794-fad89b00-790c-11eb-92cb-d88307ecfbb9.png">

**Comment by ferdicus** [comment]
@Farhadsaadatpei , we do not support Expo.

**Comment by Farhadsaadatpei** [comment]
@ferdicus Thank you. I roll back to react-native, and it is working. I had to eject the project. 🙏😊
