### ISSUE TITLE
<MapboxGL.Camera /> causes crash in IOS only

### ISSUE THREAD

**Issue by lfaz** [react-native-mapbox-gl/maps#1263]
**Describe the bug:**

The app is crashing when opening a view which contains mapbox map component. This only happens on iOS. If I completely remove <MapboxGL.Camera> and re-run it works all good, and once add again <MapboxGL.Camera> the app does not crash anymore. So it always crashes if I build the app on a new device and <MapboxGL.Camera> is present for the first run time!

**Code sample:**

```
<MapboxGL.MapView
                    styleURL={getMapStyleUrl(lang, {})}
                    attributionEnabled={false}
                    logoEnabled={false}
                    compassEnabled={false}
                    rotateEnabled={false}
                    scrollEnabled={!this.state.suppressEvents}
                    onPress={this.handlePress}
                    onLongPress={this.handleLongPress}
                    {...rest}
                    ref={this.map}
                >
                    <MapboxGL.Camera
                        defaultSettings={{
                            zoomLevel: DEFAULT_ZOOM,
                            centerCoordinate: DEFAULT_CENTER,
                        }}
                        animationDuration={DEFAULT_ANIMATION_DURATION}
                        animationMode="flyTo"
                        maxZoomLevel={MAX_ZOOM}
                        ref={this.camera}
                    />
                </MapboxGL.MapView>
```

**Versions:**

Platfrom: iOS
Device: iPhone 11
OS: iOS 14
Mapbox version: 8.1.0
React Native Version: 0.61

**Comment by ferdicus** [comment]
Hi there, can you replicate this in the `/example` project?
Feel free to use the `BugTemplate` within it to replicate your issue. 

Thanks in advance

**Comment by reyalpsirc** [comment]
In my case this was happening when having `alignItems: 'center'` on the map style, together with a MapBoxGL.Camera that had a **bounds** property defined.
Once I removed the alignItems style, it worked again.
