### ISSUE TITLE
iOS Crash using 8.2.0-beta1

### ISSUE THREAD

**Issue by tinmar33** [react-native-mapbox-gl/maps#1270]
**Describe the bug**  
The app is crashing immediately on launch after build successful on xCode with this error message, any idea ?
The version 8.1.0 was working perfectly

Note: I'm using `$ReactNativeMapboxGLIOSVersion = '~> 6.3'`

```
dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents
  Referenced from: /private/var/containers/Bundle/Application/E4E5D882-DDD0-4A0F-A998-A668979617D5/myapp.app/Frameworks/Mapbox.framework/Mapbox
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
(lldb) 
```

I tried to add `$RNMBGL.pre_install(installer)` and `$RNMBGL.post_install(installer)` even if i'm using `use_frameworks!` on my Podfile and my `pod install` gives me another error:

```
* Changed MapboxMobileEvents to `static library`
[!] An error occurred while processing the post-install hook of the Podfile.

undefined local variable or method `mobile_events_target' for #<Object:0x00007fdc52521e68>

/Users/martin/Projects/myapp/node_modules/@react-native-mapbox-gl/maps/react-native-mapbox-gl.podspec:21:in `block in post_install'
/Users/martin/Projects/myapp/node_modules/@react-native-mapbox-gl/maps/react-native-mapbox-gl.podspec:16:in `each'
/Users/martin/Projects/myapp/node_modules/@react-native-mapbox-gl/maps/react-native-mapbox-gl.podspec:16:in `post_install'
/Users/martin/Projects/myapp/ios/Podfile:131:in `block (3 levels) in from_ruby'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:897:in `run_podfile_post_install_hook'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:885:in `block in run_podfile_post_install_hooks'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:884:in `run_podfile_post_install_hooks'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:329:in `block (2 levels) in create_and_save_projects'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:328:in `block in create_and_save_projects'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:178:in `integrate'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/martin/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/martin/.rbenv/versions/2.6.5/bin/pod:23:in `load'
/Users/martin/.rbenv/versions/2.6.5/bin/pod:23:in `<main>'
```

**To Reproduce**  
Launch an app using the package 8.2.0-beta1

**Versions:**  
 - Platform: iOS
 - Platform OS: iOS 14.4
 - Device: iPhone 11 Pro
 - Emulator/ Simulator: no, real device
 - Dev OS: OSX 11.2.2
 - react-native-mapbox-gl Version 8.2.0-beta1
 - React Native Version: 0.62.2

**Comment by mfazekas** [comment]
@tinmar33 sorry about post_install issue, pls ignore the post_install hook for now. If you have `use_frameworks!` even `pre_install` hook should not make any difference.

**Comment by mfazekas** [comment]
@tinmar33 can you reproduce the issue of not able to launch on a new project created with `react-native init` ?!

**Comment by tinmar33** [comment]
@mfazekas on a new project with `react-native init` I successfully run an app with and without `use_frameworks!` so it's probably something else.. :/

**Comment by tinmar33** [comment]
I found a trick to make it work with my situation by adding this on my pre_install, so it works now :)

```
$dynamic_framework = ['MapboxMobileEvents']

  pre_install do |installer|
    $RNMBGL.pre_install(installer)
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
      if !$dynamic_framework.include?(pod.name)
        def pod.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
 ```

**Comment by NisargTailor** [comment]
hey, I am facing a similar issue
trying to use all methods but did not work for me.

Platform: iOS
Platform OS: iOS 14.5
Device: iPhone 11 Pro
Emulator/ Simulator: iPhone 12
Dev OS: OSX 11.3.1
@react-native-mapbox-gl/maps : ^8.2.0-beta2
react: 17.0.1
react-native : 0.64.1

dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents
  Referenced from: /Users/nisarg/Library/Developer/CoreSimulator/Devices/41C034E6-5153-424E-975D-9F9B52D18057/data/Containers/Bundle/Application/75BC5DC4-0D95-400E-8B76-A265770BD9B7/MapBox.app/Frameworks/Mapbox.framework/Mapbox
 Reason: image not found

**Comment by iamir4g** [comment]
> I found a trick to make it work with my situation by adding this on my pre_install, so it works now :)
> 
> ```
> $dynamic_framework = ['MapboxMobileEvents']
> 
>   pre_install do |installer|
>     $RNMBGL.pre_install(installer)
>     Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
>     installer.pod_targets.each do |pod|
>       if !$dynamic_framework.include?(pod.name)
>         def pod.build_type;
>           Pod::BuildType.static_library
>         end
>       end
>     end
>   end
> ```

Which part of the podfile should I enter this code?
