### ISSUE TITLE
Gradient line does not display properly

### ISSUE THREAD

**Issue by dozGrou** [react-native-mapbox-gl/maps#1272]
**Describe the bug**  
Drawing a gradient line does not display properly.

**To Reproduce**  
Take the geojson from [mapbox documentation](https://docs.mapbox.com/mapbox-gl-js/example/line-gradient/) and set it into the MapboxGL.Style component.

here is an example:
```js
const App = () => {
  return (
    <MapboxGL.MapView style={{flex: 1}}>
      <MapboxGL.Style
        json={{
          version: 1,
          name: 'style-json-example',
          sources: {
            line: {
              type: 'geojson',
              lineMetrics: true,
              data: {
                type: 'FeatureCollection',
                features: [
                  {
                    type: 'Feature',
                    properties: {},
                    geometry: {
                      coordinates: [
                        [-77.044211, 38.852924],
                        [-77.045659, 38.860158],
                        [-77.044232, 38.862326],
                        [-77.040879, 38.865454],
                        [-77.039936, 38.867698],
                        [-77.040338, 38.86943],
                        [-77.04264, 38.872528],
                        [-77.03696, 38.878424],
                        [-77.032309, 38.87937],
                        [-77.030056, 38.880945],
                        [-77.027645, 38.881779],
                        [-77.026946, 38.882645],
                        [-77.026942, 38.885502],
                        [-77.028054, 38.887449],
                        [-77.02806, 38.892088],
                        [-77.03364, 38.892108],
                        [-77.033643, 38.899926],
                      ],
                      type: 'LineString',
                    },
                  },
                ],
              },
            },
          },
          layers: [
            {
              type: 'line',
              source: 'line',
              id: 'line',
              paint: {
                'line-color': 'red',
                'line-width': 4,
                'line-gradient': [
                  'interpolate',
                  ['linear'],
                  ['line-progress'],
                  0,
                  'blue',
                  0.1,
                  'royalblue',
                  0.3,
                  'cyan',
                  0.5,
                  'lime',
                  0.7,
                  'yellow',
                  1,
                  'red',
                ],
              },
              layout: {
                'line-cap': 'round',
                'line-join': 'round',
              },
            },
          ],
        }}
      />
    </MapboxGL.MapView>
  );
};
```

**Expected behavior**  
The gradient line should be blue to red on the entire line.

**Actual behavior**  
The behavior change with the zoom level. The gradient is displayed multiples times and not entirely, we mainly see blue to cyan and sometimes purple.

Not sure if I am doing something wrong or it is actually a bug.

**Screenshots**  
![img](https://user-images.githubusercontent.com/7106470/110968976-72b8b380-8358-11eb-80fb-a31acd39df2e.png)

**Versions:**
- Platform: Android
- Platform OS: Android 10
- Device: Xiaomi Mi 9
- Emulator/ Simulator: no
- Dev OS: Win10
- react-native-mapbox-gl Version 8.2.0-beta1 (also tested on 8.1.0)
- React Native Version 0.63.4

**Comment by julioxavierr** [comment]
@dozGrou hey, did you find a solution for that?

**Comment by dozGrou** [comment]
@julioxavierr Nop sorry

**Comment by NatRousseau** [comment]
Hi @dozGrou , i try to make something like you, but when i write MapboxGL.Styles, he does not find .Styles. How did you go about using it ?

**Comment by dozGrou** [comment]
@NatRousseau Your IDE does not find it? I'm simply importing MapboxGL nothing more.

**Comment by NatRousseau** [comment]
@dozGrou And can we use dynamic latitude and longitude for draw a lineString when location change ?

**Comment by chuchuva** [comment]
I can reproduce this issue in version 8.2.1:

![screenshot](https://user-images.githubusercontent.com/237722/126848438-46b8baf2-79f9-468e-ad27-0c90753b4e1e.png)

**Comment by chuchuva** [comment]
I think this is because Style component ignores `lineMetrics` property.
