### ISSUE TITLE
Switching to MapLibre?

### ISSUE THREAD

**Issue by maxammann** [react-native-mapbox-gl/maps#1273]
Hello community!

I recently implemented a maps feature and found out that Mapbox switched to a proprietary license with Mapbox 10. Afaik you are bound to there TOS now and have to pay their cloud fees even if you do not use them.

A lot of famous people grouped and founded the MapLibre project. Their gl-native fork can be found here: https://github.com/maplibre/maplibre-gl-native

I will soon use react-native-mapbox-gl in an upcoming project. That means we need to have a plan what happens if this repository bumps the Mapbox version to 10. What do the main contributors of this repository think about this? Is this library focused on people who use the Mapbox cloud products?

**Comment by mfazekas** [comment]
Pls open a discussion for this.
