### ISSUE TITLE
[Android] Map markes change color on zoom in/out

### ISSUE THREAD

**Issue by Nykolyn** [react-native-mapbox-gl/maps#1283]
**Describe the bug**  
During zoom in/out at some point markers on the map are turning from their initial color to black.

**To Reproduce**  
```sh
react-native init sample --version react-native@0.61.5
cd sample
npm install @react-native-mapbox-gl/maps@8.1.0 --save
react-native run-android

And try to zoom in/out the map.
```

Example:
```js
import React, { Component } from 'react';
import { StyleSheet, View } from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

MapboxGL.setAccessToken('<<Token>>');

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  container: {
    height: '100%',
    width: '100%',
    backgroundColor: 'tomato',
  },
  map: {
    flex: 1,
  },
});

export default class App extends Component {
  render() {
    return (
      <View style={styles.page}>
        <View style={styles.container}>
          <MapboxGL.MapView
            compassEnabled={false}
            style={{ flex: 1 }}
            attributionEnabled={false}
            logoEnabled={false}
            style={styles.map}
          />
        </View>
      </View>
    );
  }
}
```

**Expected behavior**  
During zoom in/out, Markers color shouldn't change.

**Actual behavior**  
During zoom in/out, Markers color changes from initial to black.

**Screenshots**  
![image](https://user-images.githubusercontent.com/47949740/111481787-f816dc00-873b-11eb-8faf-32e3ee5b2b31.png)
![image](https://user-images.githubusercontent.com/47949740/111481870-0bc24280-873c-11eb-8034-4e5dfc45c454.png)

**Versions (please complete the following information):**  
 - Platform: [Android]
 - Platform OS: [Android 9]
 - Device: [Samsung A8]
 - Emulator/ Simulator: [yes]
 - Dev OS: [Win10]
 - react-native-mapbox-gl Version [8.1.0]
 - React Native Version [0.61.5]

**Comment by ferdicus** [comment]
I couldn't deduct it from your description: Do you also experience this on your physical device, or just on the emulator?

**Comment by thijs-qv** [comment]
I'm also seeing this when using an emulator, but not on a physical device.

**Comment by ferdicus** [comment]
> I'm also seeing this when using an emulator, but not on a physical device.

Thanks for replying 🙇🏿 

This is a known issue from upstream and unfortunately there isn't much we can do. 

Still waiting for @Nykolyn reply though

**Comment by Nykolyn** [comment]
@ferdicus  Just on the emulator, fixed by switching emulator settings to use software rendering.
