### ISSUE TITLE
MapboxGL.MapView setting height (in style) to over 1365 breaks rendering

### ISSUE THREAD

**Issue by Kotpes** [react-native-mapbox-gl/maps#1288]
**Describe the bug**  
Setting height higher than `1365` on `<MapboxGL.MapView style={{height: 1366}} />` will cause map not rendering properly
**To Reproduce**  
Steps to reproduce the behavior. 
1. Launch [example app](https://github.com/react-native-mapbox-gl/maps/tree/master/example)
2. Open, e.g., `src/examples/Map/ShowMapLocalStyle.tsx` and change the style to this `<MapboxGL.MapView style={{height: 1366}} />`
3. Open the app and navigate to Map -> Show Map With Local Style.JSON
4. See that map is not rendering (just grey area). Change (might need restart of the app) `height` to, e.g. `1000` - map renders successfully.
Please include a single standalone React Native component

Example:
https://github.com/react-native-mapbox-gl/maps/blob/383e945ff619785b8fbef1887d18a17f978bc28b/example/src/examples/Map/ShowMapLocalStyle.tsx

**Expected behavior**  
Map would render if height on `MapboxGL.MapView` is more than `1365`

**Actual behavior**  
Map does not render

**Screenshots**  

**Height is over `1365`:**
![image](https://user-images.githubusercontent.com/2579093/111984551-2ddd0b80-8b14-11eb-9200-d730c3f28e47.png)

**Height is `1365` and lower:**
![image](https://user-images.githubusercontent.com/2579093/111985100-df7c3c80-8b14-11eb-9232-a5ab39d26ebb.png)

**Versions (please complete the following information):**  
 - Platform: iOS
 - Platform OS: 14.4, 14.5
 - Device: iPhone 12 Pro Max
 - Emulator/ Simulator: both on sim and real device
 - Dev OS: macOS 11.2.3
 - react-native-mapbox-gl Version 8.1.0
 - React Native Version 0.63

**Comment by ferdicus** [comment]
hi, thanks for this issue report - can you explain what your use-case is exactly?

**Comment by Kotpes** [comment]
@ferdicus We have a map in our app with a calculated height (that depends on other elements on the same screen). So for really big phone (e.g the iPhone Max) height over 1366 breaks the map.
