### ISSUE TITLE
export Logger in index.d.ts

### ISSUE THREAD

**Issue by ferdicus** [react-native-mapbox-gl/maps#1289]
As mentioned [here](https://github.com/react-native-mapbox-gl/maps/issues/943#issuecomment-759220852).
When importing `Logger` in TS one will get an error. 

Add it to our `index.d.ts`

**Comment by ferdicus** [comment]
@ClayC-WeatherBug, maybe you want to jump on this?!

**Comment by ClayC-WeatherBug** [comment]
> @ClayC-WeatherBug, maybe you want to jump on this?!

This seems like a great one for me to hop on! Thanks for thinking of me. If someone else wants to pick it up, definitely don't hold up for me, but I'll see if I can fit this into my schedule this week or next week 👍
