### ISSUE TITLE
npm/ yarn install

### ISSUE THREAD

**Issue by slegal** [react-native-mapbox-gl/maps#129]
**Describe the bug**
Hi have an issue when I try to do the command: npm install in the example folder
**To Reproduce**
npm install

**Expected behavior**
Can you help me to find the problem? 

**Screenshots**

![image](https://user-images.githubusercontent.com/22763889/59424067-96417980-8dd3-11e9-899e-0fe71c3a74c4.png)

**Versions (please complete the following information):**
 - Platfrom: [e.g. Android]
 - SDK Version [e.g. 22]
 - React Native Version [e.g. 0.59]

**Additional context**

**Comment by mfazekas** [comment]
Sorry this requires a shell with bash at the moment. It will not work on regular windows shell.
