### ISSUE TITLE
README file contains broken link

### ISSUE THREAD

**Issue by dancesWithCycles** [react-native-mapbox-gl/maps#1290]
**Describe the bug**  
The [README](https://github.com/react-native-mapbox-gl/maps/blob/master/example/README.md) file contains the following broken link:

[building blocks](https://www.mapbox.com/products/)

**To Reproduce**  
Please go to the above mentioned link and click it.

**Expected behavior**  
The link should lead to a dedicated place.

**Actual behavior**  
The link is leading to a dead end.

**Comment by ferdicus** [comment]
thanks, is fixed

**Comment by dancesWithCycles** [comment]
Did you do any changes in the master branch? Nothing came through when I called `git pull origin master`. What was the issue and what have you done to fix it? Cheers

**Comment by ferdicus** [comment]
> Did you do any changes in the master branch? Nothing came through when I called `git pull origin master`. What was the issue and what have you done to fix it? Cheers

Feel free to check the commit history of `master`
