### ISSUE TITLE
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'react-native-mapbox-gl' from project 'Pods')

### ISSUE THREAD

**Issue by longb1997** [react-native-mapbox-gl/maps#1296]
---------  

```
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.4.99. (in target 'react-native-mapbox-gl' from project 'Pods')
```

---------

Look like this lib not yet supporting for Xcode 12

**Versions (please complete the following information):**  
 - Platform:  iOS
 - Emulator/ Simulator: yes
 - Dev OS: MacOS Catalina
 - react-native-mapbox-gl Version 5.8.0
 - React Native Version 0.63.4

**Comment by ferdicus** [comment]
Nope, it does - do it on a regular basis. This is just a warning.
It's defined [here](https://github.com/react-native-mapbox-gl/maps/blob/master/react-native-mapbox-gl.podspec#L37), feel free to open a PR with a change and an explanation why you would want to edit it. 

Thanks
