### ISSUE TITLE
set bounds does not work if followUserLocation is turned on

### ISSUE THREAD

**Issue by awdhootlele** [react-native-mapbox-gl/maps#130]
When Camera.followUserLocation is true and we try to set the bounds of the camera, the bounds are not set.

When the app loads, I want to show the user location and mark it as centre coordinate, so I am using followUserLocation for that. But when I do that, I cant set the bounds to new coordinates. It does not throw any error, it just ignores the new bounds.

**To Reproduce**
Go to the examples repo and inside FitBounds.js, set the followUserLocation to true for MapboxGL.Camera. The set bounds does not work.

**Expected behavior**
Not sure if this is expected behavior (?)

All I want is to centre the camera to the current user location and update the bounds to new bounds when needed.

** Info**
 - Platfrom: Android
 - Device: I am testing on Mi Max
 - SDK Version  28
 - React Native Version 0.57

**Comment by mfazekas** [comment]
@awdhootlele can you provide a concrete example (eg your modifications to FitBounds.js) that demonstrates the issue?

Also if you set the location why don't you turn set `followUserLocation` to false? I mean you start with `followUserLocation` so it track user location but when some action requires to set new bounds you can set new bounds and also `followUserLocation={false}`

**Comment by mfazekas** [comment]
I'm closing this as right now `followUserLocation` means that camera will not be updated see 

https://github.com/react-native-mapbox-gl/maps/blob/ee11e8e1fa8714cfcbc7ce792ecf685062f3bbfe/ios/RCTMGL/RCTMGLCamera.m#L103-L105

https://github.com/react-native-mapbox-gl/maps/blob/ee11e8e1fa8714cfcbc7ce792ecf685062f3bbfe/javascript/components/Camera.js#L345-L348

We can change this behaviour, but for that we need to have a good usecase, for most cases users should be able to set followUserLocation={false} when they update the camera position manually.

**Comment by awdhootlele** [comment]
@mfazekas I am trying to do just that, but on Android I am getting following error - 
"passive" location provider requires ACCESS_FINE_LOCATION permission.

Here's my code - 
```
<MapboxGL.MapView
        contentInset={20}
        ref={c => (this._map = c)}
        styleURL={Config.MAPBOX_STYLE_URL}>
        <MapboxGL.Camera
          ref={camera => (this._camera = camera)}
          bounds={this.state.bounds}
          animationDuration={this.state.animationDuration}
          zoomLevel={this.state.zoomLevel}
          followUserLocation={this.state.followUserLocation} // true initially, false when trying to set camera bounds
        />
        <MapboxGL.UserLocation visible={true} />
</MapboxGL.MapView>
```

When I remove <MapboxGL.UserLocation visible={true} /> , I dont get that error but the "blue location dot" is not visible.

I have also added explicit location permissions in AndroidManifest.xml - 
```
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```
AM I missing something here? 

Testing on 
device - Mi Max 2
Android version - 7.1.1
RN version - 0.59.9

![Error](https://user-images.githubusercontent.com/14818590/60968443-b284f780-a33a-11e9-9bf8-cac9faa2a285.png)

**Comment by karlguillotte** [comment]
@awdhootlele I am currently fighting with the same error! I have noticed that if I remove `<Mapbox.UserLocation onUpdate={onUserLocationUpdateHandler} />` that error splah screen goes away. In my case, my application was also crashing.

**Comment by awdhootlele** [comment]
@karlguillotte I looked at the examples and found out we need to prompt for location permission to the user as from Android API 23 onwards, "dangerous" permissions need to have user's explicit permission. Here's how to do that - 

```
componentDidMount() {
    this.requestLocationPermission();
  }
async requestLocationPermission() {
    if (isAndroid) {
      const isGranted = await MapboxGL.requestAndroidLocationPermissions();
      console.log('Permission granted...');
      this.setState({
        androidPermissionGranted: isGranted,
      });
    }
  }

render() {
const {androidPermissionGranted} =  this.state;
return (
<MapboxGL.MapView
        contentInset={20}
        ref={c => (this._map = c)}
        onPress={this.onPress}
        onLongPress={this.onLongPress}
        style={genericStyles.absFill}
        styleURL={Config.MAPBOX_STYLE_URL}>
        <MapboxGL.Camera
           ref={camera => (this._camera = camera)}
           bounds={startCoord && destCoord && this.state.bounds}
           animationDuration={this.state.animationDuration}
           zoomLevel={this.state.zoomLevel}
          followUserLocation
          followUserMode={'normal'}
        />
        <MapboxGL.UserLocation />
);
}
```
 
It turns out that the Camera also needs to have "userFollowMode" property defined otherwise the location blue dot is visible but camera does not follow it (In my case, put that dot in the center of the camera)

Hope this helps!

**Comment by karlguillotte** [comment]
Thanks @awdhootlele ! I will give a try to your suggestion.
