### ISSUE TITLE
Crash in RCTMGLMapView only in Release build

### ISSUE THREAD

**Issue by Epick362** [react-native-mapbox-gl/maps#131]
**Describe the bug**
Hello, I have a map that loads geojson from the server and then displays it over the map. It works in debug without any issues but when I compile it for release, the application crashes sort of randomly a few seconds after displaying the geojson data with cryptic error. I am using mobx for state management but I don't know if its related because as I said, the app works in debug build.

```
TypeError: TypeError: undefined is not a function (evaluating 'this.getBuffer()')  This error is located at:     
in l     
in RCTMGLMapView     
in RCTView     
in b     
in RCTView     
in View     
in View     
in View     
in View     
in n     
in inject-n-with-mainStore     
in inject-inject-n-with-mainStore-with-mapObject
--

```

**To Reproduce**
Not sure but it only seems to happen in Release build.

**Expected behavior**
The app doesn't crash.

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: Blackview
 - OS: 8.1.0
 - SDK Version 28
 - React Native Version 0.57.8

**Comment by mfazekas** [comment]
@Epick362 thanks for the report, we'd need a proper stracktrace to be able to help. 
Some tools that might help: https://www.npmjs.com/package/stack-beautifier or error reporting services like sentry.

**Comment by Epick362** [comment]
This is the output from Sentry but I will try to de-minify it, thank you for pointers.

**Comment by mfazekas** [comment]
@Epick362 for sentry make sure you're uploading .map files.

https://docs.sentry.io/clients/react-native/manual-setup/#upload-debug-symbols-to-sentry

https://docs.sentry.io/clients/react-native/sourcemaps/

**Comment by Epick362** [comment]
Well, by trial and error I managed to narrow the issue down a little. Code minification seems to cause the issue. By turning it off I was able to stop the crashing in Release builds aswell.
```
project.ext.react = [
    entryFile: "index.js",
    extraPackagerArgs: [ '--minify=false' ]
]
```
I will investigate further but this is a temporary workaroud if anybody encounters this issue.
