### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference

### ISSUE THREAD

**Issue by ghadeeraqraa1992** [react-native-mapbox-gl/maps#1313]
**Describe the bug**  
in android production app (google store version) , we have NullPointerException Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference
**To Reproduce**  
1- get routeshape from the waypoints using the below code : 

`  const getDirecction = async () => {
      const waypoints = sortedRoutePoints.map(point => {
        return {coordinates: [point.longitude, point.latitude]};
      });
      const {body: directions} = await directionsClient
        .getDirections({
          profile: 'driving',
          geometries: 'geojson',
          waypoints: waypoints,
        })
        .send();
      if (directions.code == 'NoRoute') {
        return;
      }
      const route = directions.routes[0];
      route && route.geometry && setRouteShape(turf.feature(route.geometry));
      mapRef.current.fitToCoordinates(sortedRoutePoints);
    };`

2- draw routeshape using the below component 
`   <MapboxGL.ShapeSource id="routeSource" shape={routeShape}>
      <MapboxGL.LineLayer
        // belowLayerID="poiLayer"
        layerIndex={20}
        id="routeFill"
        style={{
          lineColor: '#13f4ae',
          lineWidth: 5,
        }}
      />
    </MapboxGL.ShapeSource>`

**Expected behavior**  
show the route "route shape" on the map 
**Actual behavior**  
null pointer exception 

**Screenshots**  
<img width="1069" alt="Screen Shot 2021-04-15 at 9 58 42 AM" src="https://user-images.githubusercontent.com/65596246/114827540-7add9600-9dd1-11eb-98fe-4ff183741024.png">

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 11
 - Device: SM-N975U
 - Emulator/ Simulator: no 
 - Dev OS: production version from google store 
 - @react-native-mapbox-gl/maps Version : ^8.0.0
 - @mapbox/mapbox-sdk: ^0.10.0
 - React Native Version: 0.63.4

**Comment by ghadeeraqraa1992** [comment]
any update , it is a production issue

**Comment by ferdicus** [comment]
I'm curious: What makes you think that this is related to this repo?
I can't see any mention of mapbox in the call stack. 

Not saying, that it isn't related, just want to know what makes you think it is?

**Comment by ferdicus** [comment]
For reference: https://github.com/react-native-maps/react-native-maps/issues/2924

**Comment by ghadeeraqraa1992** [comment]
> I'm curious: What makes you think that this is related to this repo?
> I can't see any mention of mapbox in the call stack.
> 
> Not saying, that it isn't related, just want to know what makes you think it is?

as I see on sentry dashboard the issue appears after draw the route on the mapbox

**Comment by ferdicus** [comment]
> > I'm curious: What makes you think that this is related to this repo?
> > I can't see any mention of mapbox in the call stack.
> > Not saying, that it isn't related, just want to know what makes you think it is?
> 
> as I see on sentry dashboard the issue appears after draw the route on the mapbox

Could you please try to set up a test-case with the `example/BugReportExample` that is causing this. 
That way we could try to reproduce this.

Thanks
