### ISSUE TITLE
Android X & React-native-mapbox-gl/maps

### ISSUE THREAD

**Issue by Masoud-kamali** [react-native-mapbox-gl/maps#1314]
Hi guys, I have issue with androidx and react native mapbox. On the other hand, I use example folder well and it works for me.
but when I install @react-native-mapbox-gl/maps for my project. It does not works.

I tried jetifier, jshearer/maps, and the other things you said in "Add support for AndroidX #163" , but it makes no sense.

Please Help me with this issue.

This is my error:
```
Execution failed for task ':react-native-mapbox-gl_maps:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-mapbox-gl_maps:debugCompileClasspath'.
   > Could not find vectordrawable-1.0.1.jar (androidx.vectordrawable:vectordrawable:1.0.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/vectordrawable/vectordrawable/1.0.1/vectordrawable-1.0.1.jar
   > Could not find legacy-support-core-utils-1.0.0.jar (androidx.legacy:legacy-support-core-utils:1.0.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-core-utils/1.0.0/legacy-support-core-utils-1.0.0.jar

```
**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 10
 - Emulator/ Simulator: yes
 - react-native-mapbox-gl/maps Version latest
 - React Native Version "0.64.0"

**Comment by Masoud-kamali** [comment]
> Looks more like a downloding issue with the dependencies.
> Did you clean you caches and all?

Yes I did. but it did not work. for now, I changed react-native version form 0.64.0 to 0.63.4 and it works. but that problem has not been solved.

**Comment by Andarius** [comment]
I think it's becaused the minSdkVersion is harcoded. I had a similar issue while using Detox with RN 0.64.
Try updating `android/build.gradle`with 

```
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
...

minSdkVersion = safeExtGet('minSdkVersion', 16)
```
