### ISSUE TITLE
User Location not displaying iOS

### ISSUE THREAD

**Issue by iromjkee** [react-native-mapbox-gl/maps#1319]
**Describe the bug**  
There is no user location dot on the map, can't get what`s wrong already a lot of time, permissions are also set in plist.

**To Reproduce**  
![image](https://user-images.githubusercontent.com/25479692/115422579-b7602600-a205-11eb-9f78-063d366cc67c.png)

```js
import React from 'react';
import { StyleSheet, View } from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

MapboxGL.setAccessToken(
  'yourAccessToken',
);

import { COLORS } from '@utils/colors';

export const Map = () => {
  return (
    <View style={styles.container}>
      <MapboxGL.MapView
        styleURL={MapboxGL.StyleURL.Satellite}
        zoomEnabled={true}
        zoomLevel={12}
        style={styles.map}>
        <MapboxGL.UserLocation
          visible={true}
          onUpdate={(data) => console.log(data)}
          showsUserHeadingIndicator={true}
        />
        <MapboxGL.Camera
          // followZoomLevel={12}
          followUserMode={'normal'}
          followUserLocation={true}
        />
      </MapboxGL.MapView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.navigationBackgroundColor,
    paddingBottom: 45,
  },
  map: {
    flex: 1,
  },
});
```

**Expected behavior**  
See blue dot of user location on the screen and follow it.

**Actual behavior**  
If **followZoomLevel** property enabled, can't see the map at all, while it's not, just see the default map without user location blue dot.

**Screenshots**  
Without **followZoomLevel** property
![image](https://user-images.githubusercontent.com/25479692/115423291-5d139500-a206-11eb-8771-12f9deb08bbc.png)
With **followZoomLevel** property
![image](https://user-images.githubusercontent.com/25479692/115423689-b7145a80-a206-11eb-8827-fed5f7811d48.png)

**Versions:**  
 - Platform: iOS
 - Platform OS:iOS 14.4
 - Device: iPhone 11
 - Emulator/Simulator: yes
 - Dev OS: MacOs Catalina 10.15.4
 - react-native-mapbox-gl Version [e.g. 7.0.9]
 - Mapbox GL version 8.2.0-beta1
 - React Native Version 0.63.4

**Comment by iromjkee** [comment]
So the problem was in my iOS simulator, didn`t add custom location(by default simulator can`t handle user location). Issue can be closed.

**Comment by ferdicus** [comment]
> So the problem was in my iOS simulator, didn't add custom location(by default simulator can`t handle user location). Issue can be closed.

Would be very benefitial if you add the problem and the solution as an item in the Discussion section of this repo, so others having a similar issue know what they need to do. 

Thanks

**Comment by ferdicus** [comment]
Oh, also post it in the Gitter chat please
