### ISSUE TITLE
[IOS] My Callouts don´t render

### ISSUE THREAD

**Issue by carloscrovara** [react-native-mapbox-gl/maps#133]
Hello. I'm having an error where the callouts don´t appear when I click on the point (the app crashes after this action). This happens only in iOS. Everything works well in Android. 

I am using react-native version 0.59.9 and @react-native-mapbox-gl/maps version 7.0.0

Part of my current code:
![Captura de Pantalla 2019-06-14 a la(s) 17 20 57](https://user-images.githubusercontent.com/19677009/59535992-cc145a00-8ec8-11e9-83d0-65df36d2e9e6.png)

**Comment by mfazekas** [comment]
@carlcraig thanks for the report. Can you please add code as text, it's hard to copy code out of an image?

**Comment by carloscrovara** [comment]
Hi @mfazekas. This is the code:   

renderAnnotation1 () {
    return (
      <MapboxGL.PointAnnotation
        key='pointAnnotation'
        id='pointAnnotation'
        title='Rivadavia 1841, 7º Piso, Of. 749.'
        coordinate={[-58.393109, -34.609279]}>

        <View style={styles.annotationContainer}>
          <View style={styles.annotationFill} />
        </View>
        <MapboxGL.Callout 
          title='Rivadavia 1841, 7º Piso, Of. 749.'
         />
      </MapboxGL.PointAnnotation>      
    )
  }

  render() {
    return (
      <View style={styles.container}>

        <MapboxGL.MapView
            styleURL={MapboxGL.StyleURL.Street}
            style={styles.containerMap}>
            <MapboxGL.Camera centerCoordinate={[-58.393109, -34.609279]} zoomLevel={15} />  
            {this.renderAnnotation1()}
        </MapboxGL.MapView>

      </View>
      
    );
  }
