### ISSUE TITLE
Mapbox error Failed to load source composite: HTTP status code 403

### ISSUE THREAD

**Issue by JorgeQuevedoC** [react-native-mapbox-gl/maps#1331]
**Describe the bug**  
Trying to get the "Getting started" example I started facing the following issue
![image](https://user-images.githubusercontent.com/19591200/116756357-93ed6600-a9d1-11eb-9abf-79a5e49e92d9.png)

**To Reproduce**  
Import the component below into a View and run 'yarn run android 

Please include a single standalone React Native component.  

Example:
```js
import * as React from 'react';
import {View, Text, StyleSheet} from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

MapboxGL.setAccessToken(
    //<MY TOKEN>
);

MapboxGL.setConnected(true);

type MapProps = {
    zoom?: number
    center?: [number, number],
    geojson?: any
}

const styles = StyleSheet.create({
    page: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#F5FCFF',
    },
    container: {
      height: 400,
      width: '100%',
      backgroundColor: 'tomato',
    },
    map: {
      flex: 1,
    },
  });

const Map = ({zoom, center, geojson}: MapProps) => {
    const [zoomLevel, setZoomLevel] = React.useState(10);
    const [centerCoordinate, setCenter] = React.useState([-99.088844, 19.418063]);

    React.useEffect(() => {
        MapboxGL.setTelemetryEnabled(false);
    }, []);

  return (
    <View style={styles.page}>
        <View style={styles.container}>
          <MapboxGL.MapView style={styles.map} styleURL='mapbox://styles/mapbox/streets-v11'>
            <MapboxGL.Camera
            zoomLevel={zoomLevel}
            centerCoordinate={centerCoordinate}
            />
          </MapboxGL.MapView>
        </View>
    </View>
  );
};

export default Map;
```

**Expected behavior**  
Just to see the Map

**Actual behavior**  
Error and gray square with mapbox tags

**Screenshots**  
![WhatsApp Image 2021-04-30 at 4 33 54 PM](https://user-images.githubusercontent.com/19591200/116757114-13c80000-a9d3-11eb-9443-bf5d725a8f0f.jpeg)

**Versions (please complete the following information):**  
 - Platform: Android 
 - Platform OS: Android 9
 - Device: Huawei P10
 - Emulator/ Simulator: no
 - Dev OS: OSX 11.2.3, Win10]
 - react-native-mapbox-gl Version 8.2.0-beta2
 - React Native Version 0.63.4

**Comment by JorgeQuevedoC** [comment]
Hi, nothing happened. Same error is being displayed

**Comment by ferdicus** [comment]
I'm assuming it is an issue with your token then. 
Can you try to replicate it within our `/example` project?

Thanks

**Comment by JorgeQuevedoC** [comment]
Sure, let me try"

**Comment by Hannah-Alto** [comment]
I am still having this issue same code

**Comment by Strapazzon** [comment]
🚀 I solved it using this line 
` MapboxGL.setWellKnownTileServer(MapboxGL.TileServers.Mapbox)`
