### ISSUE TITLE
<UserLocation> doesn't display everytime on Android

### ISSUE THREAD

**Issue by SebSusi** [react-native-mapbox-gl/maps#1340]
**Describe the bug**  
The UserLocation component doesn't work properly, it works some times, sometimes not, ONLY on android emulator and android devices. 

**To Reproduce**  
Call the UserLocation  in MapView

Example : 

```
var Map = () => {
    if (Platform.OS == "android") {
        var temp = await MapboxGL.requestAndroidLocationPermissions()
    }
    return (
        <View style={{ height: "100%", width: "100%" }}>
          <MapboxGL.MapView  >
            <MapboxGL.UserLocation />
          </MapboxGL.MapView>
        </View>
    )
}
```
 i simplify my code like you asked our program is huge, but we tested exactly these line, and it sill not works

**Expected behavior**  
Always see UserLocation on map. 

**Actual behavior**  
The UserLocation Indicator on the map does not display everytimes only on android devices, it sometimes works, sometimes not, when it works, i juste have to close the app and reboot it, it will no longer work, and also on emulator devices.
Camera.current.setCamera() is undefined when my UserLocation Inidicator does not display on the screen. 
you can not see it on the example because i simplify the code you can have more code on my post on stackoverflow : https://stackoverflow.com/questions/67440184/mapboxgl-react-native-userlocation-indicator-do-not-display-on-map
We tested on release versions and debug version on android devices (One plus) 
Work fine on Iphone 

**Screenshots**  
First time open : 
![First time i open the app](https://user-images.githubusercontent.com/50665502/117541249-46957800-b013-11eb-9115-f6311a8d5446.jpeg)
After close it and open it : 

![After close it](https://user-images.githubusercontent.com/50665502/117541276-6a58be00-b013-11eb-834c-c59482f34045.jpeg)

**Versions (please complete the following information):**  
 - Platform: [e.g. Android, iOS]
 - Platform OS: [e.g. Android 9, iOS 10]
 - Device: One plus 7 pro , Iphone 11 pro, emulateur device Pixel 3
 - Emulator/ Simulator: both
  -  expo: "^40.0.0",
 - Dev OS: [e.g. OSX 11.0.1, Win10]
 - react-native-mapbox-gl Version "8.1.0" tested also on "^8.2.0-beta2"
 - React Native Version "0.63.4"

**Comment by ferdicus** [comment]
what happened?
