### ISSUE TITLE
Unit test | _maps.default.setAccessToken is not a function

### ISSUE THREAD

**Issue by perdomofranklin93** [react-native-mapbox-gl/maps#1341]
**Description**
Greetings, this dependency problem has been presented when running the unit tests, in other libraries the list of transformIgnorePatterns or jest.mock configurations is added. I also have to clarify that I am not testing the library, but that it has affected the rest of my tests.

**Expected behavior**  
Run the tests without undefined functions

**Actual behavior**  
This problem has affected the rest of my unit tests. I think this image can say more.
![Captura de pantalla de 2021-05-10 12-42-40](https://user-images.githubusercontent.com/44304729/117694569-4ae5a080-b18d-11eb-8e3f-ad8e9cc0a270.png)

**Versions (please complete the following information):**  
 - Platform: [Android]
 - Platform OS: [Android 9]
 - Emulator/ Simulator: [no]
 - Dev OS: [Linux]
 - react-native-mapbox-gl Version [8.1.0]
 - Mapbox GL version [8.1.0]
 - React Native Version [0.63]

**Comment by ferdicus** [comment]
hi, did you follow this: https://github.com/react-native-mapbox-gl/maps#testing-with-jest

**Comment by ferdicus** [comment]
@perdomofranklin93, did you try like this:

    "setupFilesAfterEnv": [
      "@react-native-mapbox-gl/maps/setup-jest"
    ]

should work

**Comment by perdomofranklin93** [comment]
> @perdomofranklin93, did you try like this:
> 
> ```
> "setupFilesAfterEnv": [
>   "@react-native-mapbox-gl/maps/setup-jest"
> ]
> ```
> 
> should work

Yes i do, in the `jest.config.js` and the `package.json` files. look
![Captura de pantalla de 2021-05-16 16-25-11](https://user-images.githubusercontent.com/44304729/118411900-fd71a380-b664-11eb-907f-4885d5ca93b4.png)

**Comment by perdomofranklin93** [comment]
@ferdicus i found the fix, i put this code in my jest `setup.js` to mock some libraries, i remove this code
```
jest.mock('@react-native-mapbox-gl/maps', () => ({
  GeolocateControl: jest.fn(),
  Map: jest.fn(() => ({
    addControl: jest.fn(),
    on: jest.fn(),
    remove: jest.fn(),
  })),
  NavigationControl: jest.fn(),
}));
```
it work 
![Captura de pantalla de 2021-05-16 17-22-13](https://user-images.githubusercontent.com/44304729/118413042-4c223c00-b66b-11eb-9c53-a92e9771fbb2.png)
