### ISSUE TITLE
Not able to export iOS build after archiving successfully.

### ISSUE THREAD

**Issue by yudiz-vipul** [react-native-mapbox-gl/maps#1353]
I have following version installed in my project:
```"@react-native-mapbox-gl/maps": "^8.1.0",```
```"react-native": "^0.64.1",```

React Native Version 0.64.1 required cocoa pods version 1.10.1, but when I migrate to cocoa pods version 1.10.1 I am not able to export the archive which is successfully built.

**Comment by mfazekas** [comment]
should be fixed in 8.2 betas
