### ISSUE TITLE
Unable to install on RN 0.64.1

### ISSUE THREAD

**Issue by thevishnupradeep** [react-native-mapbox-gl/maps#1356]
I am unable to install the library due to peer dependency conflict.

<img width="922" alt="Screenshot 2021-05-20 at 1 44 05 PM" src="https://user-images.githubusercontent.com/5638461/118957304-7593de00-b971-11eb-98f1-5636310f1f43.png">

**Comment by ferdicus** [comment]
I'm sure you've read the extensive description of how to open a bug ticket - unfortunately I've to close this issue for not following the instructions in said description.

Feel free to open a new ticket, following the instructions.
