### ISSUE TITLE
SymbolLayer iconOpacityTransition don't work

### ISSUE THREAD

**Issue by inmoHwang** [react-native-mapbox-gl/maps#1377]
Hi 
I want fadein animation when SymbolLayer rendering finish.

1. how can i get SymbolLayer rendering finish event?
2. how use iconOpacityTransition?

this is my code
------------------------------------------------------------------------------
<MapboxGL.ShapeSource
            id="featureSource"
            ref={c => setSource(c)}
            shape={{
              type: 'FeatureCollection',
              features: featureCollection.features,
            }}
            onPress={onSourceLayerPress}>

            <MapboxGL.SymbolLayer
              id="loadingLayer"
              style={{
                symbolZOrder: 'auto',
                symbolSortKey: ['get', 'id'],
                iconIgnorePlacement: true,
                iconAllowOverlap: true,
                iconSize: ['step', ['get', 'bitDepth'], 1.2, 16, 1.1, 20, 1],
                iconOffset: [0, -30],
                iconImage: require('../assets/noimage.png'),
                iconOpacity: 1,
                iconOpacityTransition: {
                  duration: 1000,
                },
              }}
            />

            <MapboxGL.SymbolLayer
              id="singlePointLayer"
              aboveLayerID="loadingLayer"
              style={{
                symbolZOrder: 'auto',
                symbolSortKey: ['get', 'id'],
                iconAllowOverlap: true,
                iconSize: ['step', ['get', 'bitDepth'], 1.2, 16, 1.1, 20, 1],
                iconOffset: [0, -30],
                iconImage: ['get', 'icon'],
                iconIgnorePlacement: true,
                iconOpacity: 1,
                iconOpacityTransition: {
                  duration: 1000,
                },
              }}
            />

</MapboxGL.ShapeSource>

version "@react-native-mapbox-gl/maps": "8.2.0-beta2",

**Comment by ferdicus** [comment]
hey @inmoHwang, please make sure to follow the issue template or else we can't help you and I'm going to close this issue.  
The template is pretty straight forward on what information is required and what is optional.  

Thanks
