### ISSUE TITLE
fitBounds padding?

### ISSUE THREAD

**Issue by timhilgenstoehler** [react-native-mapbox-gl/maps#138]
Hello,

My first question is: Is
`this.camera.fitBounds([lng, lat], [lng, lat], 20, 1000)`
 for example deprecated? I am always getting 
`this.camera.fitBounds`

I followed then the examples to flyTo and fitBounds and played with the state like in the examples.. its working for now but what about the `fitBounds` padding?

```
bounds: {
  ne: this.houseBounds[0],
  sw: this.houseBounds[1],
  padding ??
}
```

Thanks for helping.

**Comment by mfazekas** [comment]
@timhilgenstoehler have you tried what's documented on fitBounds?

https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Camera.md#fitboundsnortheastcoordinates-southwestcoordinates-padding-animationduration

if it doesn't works please post a concret sample code.

**Comment by timhilgenstoehler** [comment]
Oh I see I left a sentence out. my bad. 
Like I said I tried `this.camera.fitBounds([lng, lat], [lng, lat], 20, 1000)` but I always getting `this.camera.fitBounds` is not a function.

In the older versions (without camera) just `this.map.fitBounds` where `map` is the MapView Component it worked.

**Comment by mfazekas** [comment]
Which version? Also do you have this.camera defined?

**Comment by timhilgenstoehler** [comment]
`"@react-native-mapbox-gl/maps": "^7.0.0-rc2"`

I am just defining it like I did before wit the MapView:
```
<MapboxGL.Camera
  bounds={bounds}
  ref={ref => (this.camera = ref)}
  animationDuration={500}
/>
```

**Comment by timhilgenstoehler** [comment]
I then followed this example 
https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/FitBounds.js
because I thought the function is deprecated and I can work with this example well. I am just missing the padding there like in the function.

**Comment by mfazekas** [comment]
fitBounds was moved to camera in #122, so you need to use master for now.
Padding should be available as property like 

```js
<Camera
  bounds={
     paddingLeft: 10,
     ...
  }
>
 
</Camera>
```

see https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Camera.md

**Comment by timhilgenstoehler** [comment]
OK thank you a lot, that is working!

**Comment by kristfal** [comment]
Great! I’ll publish a new RC today if I have time.
