### ISSUE TITLE
Calculate Ditance

### ISSUE THREAD

**Issue by zoolle** [react-native-mapbox-gl/maps#1383]
I need to calculate the distance between two points and by using this.

`const time_to_pickup = MapboxGL.geoUtils.calculateDistance(
      [currentLocation.longitude, currentLocation.latitude],
      [order.origin.longitude, order.origin.latitude],
      'meters',
);`

I get this 

`TypeError: undefined is not an object (evaluating '_maps.default.geoUtils.calculateDistance')`

Is there a different setup?

**Comment by ferdicus** [comment]
Please use turf instead: https://turfjs.org/docs/#distance
Our geoutils are subject to change and internally they use turf anyways.
