### ISSUE TITLE
iconImage and ["get", ""] expression causes app to crash

### ISSUE THREAD

**Issue by aurimas535** [react-native-mapbox-gl/maps#140]
**Describe the bug**
Using style iconImage with ['get', ''] expression causes app to crash with error `xception thrown while executing UI block: -[__NSArrayM containsString:]: unrecognized selector sent to instance 0x600002b8f210`. Looks like it receiving array value, but I'm sure that expression should pick string

**To Reproduce**
Use iconImage style and ["get", ""] expression

**Expected behavior**
Image is visible

**Versions (please complete the following information):**
 - Platfrom:iOS
 - Device: iPhone7 and all others iPhones including simulator
 - React Native Version 0.59.5

**Comment by mfazekas** [comment]
The crash is coming from here: 

https://github.com/react-native-mapbox-gl/maps/blob/37f3d5fd9ab6b360811c8476efdec3b0964c3293/ios/RCTMGL/RCTMGLStyleValue.m#L90-L95

https://github.com/react-native-mapbox-gl/maps/blob/37f3d5fd9ab6b360811c8476efdec3b0964c3293/ios/RCTMGL/RCTMGLStyleValue.m#L97-L104

we should be allowing expressions too.

**Comment by aurimas535** [comment]
Any plans to fix this? It blocking pretty much whole map migration to new version for me.

**Comment by mfazekas** [comment]
@aurimas535 as a workaround you might be able to use `{icon}` instead of `['get','icon']`

**Comment by aurimas535** [comment]
@mfazekas thanks works. I thought this was deprecated on new SDK.

**Comment by mfazekas** [comment]
@aurimas535 pls reopen as we still want full expressions to be fixed

**Comment by zhijiec99** [comment]
Is this fixed? I don't get a crash anymore, but nothing happens for me when i try using [get,""], nor {icon}.

**Comment by peternuernberger** [comment]
For me it still crashes with the above error when I do `iconImage: ['get', 'marker-symbol']`
and nothing happens if I do `iconImage: "{marker-symbol}"` instead.

**Comment by zhijiec99** [comment]
@peternuernberger if you pull the latest version of master, it shouldn't crash anymore. But still nothing happens.

**Comment by peternuernberger** [comment]
@zhijiec99 My bad. I was using the npm version and of cause it wasn't merged, yet. Plus, my geojson was malformatted (cooridinates as array of strings). Now everything is fine. Thank you guys.

**Comment by d3vhound** [comment]
This isn't fixed on the version that's on npm.
