### ISSUE TITLE
dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents

### ISSUE THREAD

**Issue by iamir4g** [react-native-mapbox-gl/maps#1404]
hi, get this error after the building project in Xcode.
react-native-mapbox-gl/maps version :
 "@react-native-mapbox-gl/maps": "^8.2.0-beta2"
react-native version :
 "react-native": "~0.63.4",
pod install ok,and open .xcworkspace to run project
android is ok but ios crash.
how to solve this error??

**Comment by ferdicus** [comment]
please search for this in our issues, there are quite some open tickets
