### ISSUE TITLE
Error on npm install - unable to resolve dependency tree (found react@17.0.1, could not resolve react@^16.6.1)

### ISSUE THREAD

**Issue by dancherb** [react-native-mapbox-gl/maps#1407]
**Describe the bug**  
Cannot install the package with npm install on React Native 0.64.

**To Reproduce**  
1. `react-native init`
2. `npm install @react-native-mapbox-gl/maps --save`

Returns error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: hypi@0.0.1
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.6.1" from @react-native-mapbox-gl/maps@8.2.0-beta2
npm ERR! node_modules/@react-native-mapbox-gl/maps
npm ERR!   @react-native-mapbox-gl/maps@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Additional information**

If proceeding with `--force` in the `npm install`, the app builds and the map shows. I later receive `this._runNativeCommand is not a function` when calling the map's showAttribution() method, which may be linked.

**Versions (please complete the following information):**  
 - Platform: Android, but probably both.
 - Platform OS: N/A
 - Device: N/A
 - Emulator/ Simulator: N/A
 - Dev OS: Win10
 - react-native-mapbox-gl Version: 8.2.0
 - Mapbox GL version [e.g. 6.3.0]: N/A
 - React Native Version [e.g. 0.59]: 0.64.0

**Comment by ferdicus** [comment]
hi there,  
are you on top of using react `17+` maybe using `npm 7`?

Would you mind trying out current `master`, I've just merged a PR that's supposed to fix this issue. 

thanks

**Comment by hexadecy** [comment]
> npm WARN @react-native-mapbox-gl/maps@8.2.0-beta2 requires a peer of react@^16.6.1 but none is installed. You must install peer dependencies yourself.

**Versions:**
- npm 6.14.8
- node v12.20.0
- react 17.0.2
- reac-native 0.64.2
- react-native-mapbox-gl/maps: 8.2.0-beta2
- Dev OS: macOS 11.4

I suspect npm 7 because I have just a warning with npm 6.

**Comment by dancherb** [comment]
Indeed I'm on npm 7.9.0 and `npm i -S https://github.com/react-native-mapbox-gl/maps` installed smoothly, thanks ✌

I wouldn't recommend installing with --force if people have similar issues, as this caused weird bugs down the line. The above should do it.

**Comment by ferdicus** [comment]
resolved
