### ISSUE TITLE
 Mapbox-iOS-SDK to  6.0 

### ISSUE THREAD

**Issue by ghadeeraqraa1992** [react-native-mapbox-gl/maps#1408]
**Describe the bug**  
I'm using MapboxNavigation iOS SDK as a native module inside my react native project , I want to upgrade it from 0.4 to 1.4 
after run pod install I got the below error 
```
CocoaPods could not find compatible versions for pod "Mapbox-iOS-SDK":
  In Podfile:
  MapboxNavigation (~> 1.4) was resolved to 1.4.0, which depends on Mapbox-iOS-SDK (~> 6.0)
 react-native-mapbox-gl (from `../node_modules/@react-native-mapbox-gl/maps`) was resolved to 8.1.0, which depends    on Mapbox-iOS-SDK (~> 5.9.0)
```

**To Reproduce**  
1. add   pod 'MapboxNavigation', '~> 1.4' inside pod file 
2. run pod install

**Versions (please complete the following information):**  
 - Platform: [ iOS]
 - Platform OS: [iOS 14.4]
 - Device: [e.g. iPhone8+]
 - Emulator/ Simulator: [yes]
 - Dev OS: [11.2.2]
 - react-native-mapbox-gl Version [8.1.0]
 - React Native Version [e.g. 0.63.4]

**Comment by ferdicus** [comment]
hi there, 
assuming, that you're using the default SDK version (as evident from your logs [`5.9.0`]) for _this_ repo.
You'll have to follow the installation steps on how to increase the iOS SDK within our [installation guide](https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md#mapbox-maps-sdk).

**Comment by ferdicus** [comment]
Additionally, I / others might be interested in how you're using `MapboxNavigation` in concert with this repo. 
Can you share some use cases? Maybe even code?

**Comment by ghadeeraqraa1992** [comment]
> Additionally, I / others might be interested in how you're using `MapboxNavigation` in concert with this repo.
> Can you share some use cases? Maybe even code?

I'm using MapboxNavigation as a native module in iOS in order to display the navigation screen inside my react native project

**Comment by ferdicus** [comment]
> > Additionally, I / others might be interested in how you're using `MapboxNavigation` in concert with this repo.
> > Can you share some use cases? Maybe even code?
> 
> I'm using MapboxNavigation as a native module in iOS in order to display the navigation screen inside my react native project

Ok, I've assumed that much :)   
Care to elaborate a bit more?  

Are you using mapbox api for the routing? 
What part does _this_ repo handle what part does _navigation_ handle?  
Did you write JS bindings for _navigation_ or are you using those parts only withing Obj-C?

**Comment by ghadeeraqraa1992** [comment]
> > > Additionally, I / others might be interested in how you're using `MapboxNavigation` in concert with this repo.
> > > Can you share some use cases? Maybe even code?
> > 
> > 
> > I'm using MapboxNavigation as a native module in iOS in order to display the navigation screen inside my react native project
> 
> Ok, I've assumed that much :)
> Care to elaborate a bit more?
> 
> Are you using mapbox api for the routing?
> What part does _this_ repo handle what part does _navigation_ handle?
> Did you write JS bindings for _navigation_ or are you using those parts only withing Obj-C?

1. Are you using mapbox api for the routing?
Yes I'm using it for the routing 
2.What part does this repo handle what part does navigation handle?
This repository handle another areas in my project using js code (react native): 
below are some features : 
1. display mapbox  
2. display points on the map
3. display routes on the map
The navigation using (  pod 'MapboxNavigation', '~> 1.4') handle the navigation to a specific point or route navigation including waypoints 
3.Did you write JS bindings for navigation or are you using those parts only withing Obj-C?
I'm using it only within Obj-c , but the data like the point/waypoints are sending from js

The main idea is we have a react native project all the functionality related to mapbox are done using this repo. react native code except the navigation

**Comment by ferdicus** [comment]
Thank you for the explanation 🙇🏿

**Comment by ferdicus** [comment]
Oh, also - this issue can be closed? Did you resolve your issue?

**Comment by ghadeeraqraa1992** [comment]
> Oh, also - this issue can be closed? Did you resolve your issue?

 yes , resolved

**Comment by ghadeeraqraa1992** [comment]
@ferdicus 
New issue , all the details are below : 
**VERSIONS** : 
cocopods version 1.9.3
@react-native-mapbox-gl/maps 8.1.0
ReactNativeMapboxGLIOSVersion 6.3 
xCode version 12.4 
add pre,post install to pod file 

RESULT:

1. The project doesn’t work on the real device , we have the below issue : 
```
 building for iOS, but linking in dylib file (/Users/Ghadeer/Library/Developer/Xcode/DerivedData/app-edbvdaczdcdwmhevhqffjyzbcawd/Build/Products/Debug-iphoneos/MapboxAccounts.framework/MapboxAccounts) built for Mac Catalyst, file '/Users/Ghadeer/Library/Developer/Xcode/DerivedData/app-edbvdaczdcdwmhevhqffjyzbcawd/Build/Products/Debug-iphoneos/MapboxAccounts.framework/MapboxAccounts' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
2. works as expected on the simulator 
 Upgrading to CocoaPods 1.10.rc.1 should fix the error in point 1 as they mentioned in the ticket below 
Linker error with Xcode 12 and CocoaPods 1.9.3 — building for iOS, but linking in dylib file · Issue #2674 · mapbox/mapbox-navigation-ios 

after upgrading CocoaPods to 1.10.1 : 
**VERSIONS :** 
cocopods version 1.10.1 
@react-native-mapbox-gl/maps 8.2.0 beta-2 or 8.1.0
ReactNativeMapboxGLIOSVersion 6.3 
xCode version 12.4 
add pre,post install to pod file 
RESULT:
the app doesn’t install , missing ifo.plist file  : 
```
Could not install at this time.
Failed to load Info.plist from bundle at path /Users/Ghadeer/Library/Developer/CoreSimulator/Devices/77062086-4859-4E6A-A712-B029E9DEF6C7/data/Library/Caches/com.apple.mobile.installd.staging/temp.42EX5r/extracted/mappo.app/Frameworks/MapboxMobileEvents.framework; Extra info about plist: ACL=<not found>
```

Any help ?

**Comment by ferdicus** [comment]
have you checked the issues, there are some similar open/ closed issues. 
Are you on an `M1` machine?

**Comment by ghadeeraqraa1992** [comment]
> have you checked the issues, there are some similar open/ closed issues.
> Are you on an `M1` machine?

yeah I checked the issue and I tried all the solution . 
what do you mean with  **M1** machine?

**Comment by ferdicus** [comment]
> > have you checked the issues, there are some similar open/ closed issues.
> > Are you on an `M1` machine?
> 
> yeah I checked the issues and I tried all the solution .
> what do you mean with **M1** machine?

new macbook, with an m1 chipset

**Comment by ferdicus** [comment]
in any case, this is a new issue - either add a comment below one of the existing or open a new one

**Comment by ghadeeraqraa1992** [comment]
> > > have you checked the issues, there are some similar open/ closed issues.
> > > Are you on an `M1` machine?
> > 
> > 
> > yeah I checked the issues and I tried all the solution .
> > what do you mean with **M1** machine?
> 
> new macbook, with an m1 chipset

No

**Comment by ghadeeraqraa1992** [comment]
> @ferdicus
> New issue , all the details are below :
> **VERSIONS** :
> cocopods version 1.9.3
> @react-native-mapbox-gl/maps 8.1.0
> ReactNativeMapboxGLIOSVersion 6.3
> xCode version 12.4
> add pre,post install to pod file
> 
> **RESULT:**
> 
> 1. The project doesn’t work on the real device , we have the below issue :
> 
> ```
>  building for iOS, but linking in dylib file (/Users/Ghadeer/Library/Developer/Xcode/DerivedData/app-edbvdaczdcdwmhevhqffjyzbcawd/Build/Products/Debug-iphoneos/MapboxAccounts.framework/MapboxAccounts) built for Mac Catalyst, file '/Users/Ghadeer/Library/Developer/Xcode/DerivedData/app-edbvdaczdcdwmhevhqffjyzbcawd/Build/Products/Debug-iphoneos/MapboxAccounts.framework/MapboxAccounts' for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
>  1. works as expected on the simulator
>    Upgrading to CocoaPods 1.10.rc.1 should fix the error in point 1 as they mentioned in the ticket below
>    Linker error with Xcode 12 and CocoaPods 1.9.3 — building for iOS, but linking in dylib file · Issue #2674 · mapbox/mapbox-navigation-ios
> 
> after upgrading CocoaPods to 1.10.1 :
> **VERSIONS :**
> cocopods version 1.10.1
> @react-native-mapbox-gl/maps 8.2.0 beta-2 or 8.1.0
> ReactNativeMapboxGLIOSVersion 6.3
> xCode version 12.4
> add pre,post install to pod file
> **RESULT:**
> the app doesn’t install , missing ifo.plist file :
> 
> ```
> Could not install at this time.
> Failed to load Info.plist from bundle at path /Users/Ghadeer/Library/Developer/CoreSimulator/Devices/77062086-4859-4E6A-A712-B029E9DEF6C7/data/Library/Caches/com.apple.mobile.installd.staging/temp.42EX5r/extracted/mappo.app/Frameworks/MapboxMobileEvents.framework; Extra info about plist: ACL=<not found>
> ```
> 
> Any help ?

using cocopods version 1.9.3 already there is an opened issue : https://github.com/mapbox/mapbox-navigation-ios/issues/2674
