### ISSUE TITLE
Fix typescript index.d.ts

### ISSUE THREAD

**Issue by loic-lopez** [react-native-mapbox-gl/maps#141]
**Describe the bug**
Many definitions are missing in index.d.ts.

**Screenshots**
<img width="826" alt="Capture d’écran 2019-06-18 à 17 08 43" src="https://user-images.githubusercontent.com/17724398/59696204-dba6e200-91eb-11e9-9aa5-b461b278b0bb.png">
<img width="484" alt="Capture d’écran 2019-06-18 à 17 09 30" src="https://user-images.githubusercontent.com/17724398/59696206-dba6e200-91eb-11e9-8468-e1deb61ee5fc.png">

**Comment by Hless** [comment]
Have the same issue, and haven't the time to create a proper pull request, but I quickly slapped together the types for Camera at least. You can temporary add a file in your @types directory (e.g. `./@types/@react-native-mapbox-gl/index.d.ts`), with the contents of the gist. Perhaps later I'll get back to creating the actual pull request, but it seems as though Camera is still under under heavy development.

See gist here:
https://gist.github.com/Hless/8c50c8b1b72d41e466a46e283c1dc3d6

**Comment by anfriis** [comment]
I have also found an inconsistency between documentation and `index.d.ts` regarding `VectorSourceProps`. 
![Screenshot 2019-06-26 at 13 44 56](https://user-images.githubusercontent.com/1019341/60177292-ce57ac00-9818-11e9-9cd9-a3cce69d3d64.png)
![Screenshot 2019-06-26 at 13 45 01](https://user-images.githubusercontent.com/1019341/60177293-ce57ac00-9818-11e9-8dcc-f196a2de2c9d.png)

**Comment by jussirantala** [comment]
`    class StyleSheet extends Component {
        static create<T extends NamedStyles<T> | NamedStyles<any>>(styles: T): void;        
        camera(stops: {[key: number]: string}, interpolationMode?: InterpolationMode): void;
        source(stops: {[key: number]: string}, attributeName: string, interpolationMode?: InterpolationMode): void;
        composite(stops: {[key: number]: string}, attributeName: string, interpolationMode?: InterpolationMode): void;

        identity(attributeName: string): number;
    }`

Also this. The _create_ method should return an object not void.

**Comment by anfriis** [comment]
There are many more inconsistencies, especially regarding `MapView` and `Camera`. I am working on a PR that should fix many of them

**Comment by henninghall** [comment]
Some of these issues are fixed and merged by https://github.com/react-native-mapbox-gl/maps/pull/230. Some props and classes are still missing though. UserLocationProps is for instance missing the onPress prop as you have in your example.

**Comment by romixch** [comment]
I guess the original issue that geoUtils is not declared in index.d.ts is still not fixed. Am I right?
