### ISSUE TITLE
Calling setAccessCode on Android isnt working, showing Black Map

### ISSUE THREAD

**Issue by carlos-nunez** [react-native-mapbox-gl/maps#1410]
**Describe the bug**  
On IOS, The package is working perfectly. I can call MapboxGL.setAccessCode(code), and then confirm that it worked by doing MapboxGL.getAccessCode(). It works and returns the access code that I set.

On Android, MapboxGL.setAccessCode(code) does nothing for me. When I call MapboxGL.getAccessCode(), I get an unresolved promise and an error stating that no access code has been set.

**To Reproduce** 
On Android call MapboxGL.setAccessToken(), when trying to load the map component you will get a black screen and an error saying you dont have an access token. When calling getAccessToken, it also says there is no token. 

Please include a single standalone React Native component.  
```
// @flow
import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, Dimensions, FlatList } from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';
import Icon from 'react-native-vector-icons/FontAwesome5';
import { TouchableOpacity } from 'react-native';

const window = Dimensions.get('window');

//In my code, token is replaced with the actual token
MapboxGL.setAccessToken(token);

const MapNavigationView = () => {
  const [location, setLocation] = useState(null);

  const [follow, setFollow] = useState(true);
  const followColor = follow ? '#007AFF' : 'black';

  useEffect(() => {
    const getToken = async () => {
      const tok = await MapboxGL.getAccessToken();
      console.log(tok);
    };
   getToken()
  }, []);

  return (
    <>
      <View style={styles.container}>
        <MapboxGL.MapView style={styles.container} logoEnabled={false}>
          <MapboxGL.UserLocation
            showsUserHeadingIndicator
            onUpdate={loc =>
              setLocation([loc.coords.latitude, loc.coords.longitude])
            }
          />
          <MapboxGL.Camera
            onUserTrackingModeChange={e => {
              setFollow(e.nativeEvent.payload.followUserLocation);
            }}
            followUserLocation={follow}
          />
          <MapboxGL.SymbolLayer id="Map" />
          <View style={styles.button}>
            <TouchableOpacity
              style={{ padding: 10 }}
              onPress={() => setFollow(!follow)}
            >
              <Icon name="location-arrow" size={20} color={followColor} />
            </TouchableOpacity>
          </View>
        </MapboxGL.MapView>
      </View>
    </>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  button: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'white',

    borderRadius: 10,
  },
});

export default MapNavigationView;
```

**Expected behavior**  
I expected MapboxGL.getAccessToken() to return the access token I set and for the map to display like on IOS.

**Actual behavior**  
Black Screen, no access code error.

**Screenshots**  
![Screenshot_1624036351](https://user-images.githubusercontent.com/36340491/122595791-f01a5100-d036-11eb-9f05-427c8f47d32e.png)

**Versions (please complete the following information):**  
 - Platform:Android
 - Platform OS:  Tried 6 and 11
 - Device: Pixel 3, and Samsung Galaxy Physical Device
 - Emulator/ Simulator: Tried both emulator, and on physical device
 - Dev OS:  Mac OSx 11.2.2
 - react-native-mapbox-gl Version 8.1, and also tried 8.2 beta
 - Mapbox GL version
    ```implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.1'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:5.6.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.9.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0'```
 - React Native Version 0.63.0

**Additional context**  
Im also using react-native-mapbox navigation on Android, and have access key setup for that in build.gradle and AndroidManifest.xml and it works fine. Just doesn't work with this package.

**Comment by ferdicus** [comment]
hmm, I've built multiple times today and had no issues with this.  
Can you try with a minimal setup and minimal example please and report back. 

Thanks

**Comment by carlos-nunez** [comment]
I also updated to the latest RN version and im still having the same issue.

**Comment by carlos-nunez** [comment]
I think it may have been an issue with Flipper. Ultimately the easiest fix was to create a new React Native project with the latest versions, and then transfer over my JS files and package.json. On a fresh and updated react native install it worked as expected.
