### ISSUE TITLE
App crash when adding image from unsplash

### ISSUE THREAD

**Issue by ecin-tpk** [react-native-mapbox-gl/maps#1433]
**Describe the bug**
App crash when displaying image from some specific domain like unsplash or countryflags.io

**To Reproduce**
I use the latest example project and try adding an Image component with the source uri from unsplash like
`        <Image
          source={{
            uri: 'https://images.unsplash.com/photo-1625062294679-b15a3bee5d1b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1347&q=80',
          }}
          style={{width: 100, height: 100}}
          resizeMode="cover"
        />`
or from countryflags.io
`<Image
          source={{
            uri: 'https://www.countryflags.io/be/flat/64.png',
          }}
          style={{width: 100, height: 100}}
          resizeMode="cover"
        />`
**Expected behavior**
The image gets displayed

**Actual behavior**
Crashing without any message

**Versions:**
Platform: Android
Platform OS: Android 7
Device: Redmi note 4
Dev OS: Win10
react-native-mapbox-gl Version 8.2.0-beta1
React Native Version 0.63.0

**Comment by ferdicus** [comment]
Image gets displayed where?  

Did you check the documentation for [`Images`](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Images.md)?
What's the usecase, what are you trying to achieve?

**Comment by ecin-tpk** [comment]
I just clone the example project and then only return an Image in App.js because I have experienced the same behavior in my app with the version 8.2.1

**Comment by ferdicus** [comment]
can you please run `adb logcat` and post the stack that is printed during the crash, thanks

**Comment by ecin-tpk** [comment]
> can you please run `adb logcat` and post the stack that is printed during the crash, thanks

Sorry but I don't have time right now. I kinda solve my problem by downgrading to 8.1.0. Thanks for replying, I will do it and let you know later.

**Comment by ferdicus** [comment]
Closing due to lack of feedback
