### ISSUE TITLE
Trying to remove a view index above child count error

### ISSUE THREAD

**Issue by christensenmichael0** [react-native-mapbox-gl/maps#144]
It appears this bug was fixed here but has not made it into this project:

https://github.com/nitaliano/react-native-mapbox-gl/pull/1580/commits/05f8f9a08133d18f76cd822ddab0515bd15eae75

**Comment by mattijsf** [comment]
At the time I was able to reproduce this problem by mounting / unmounting the map rapidly. In the current version I tried doing the same but it works correctly. 

Do you have a way / sample code to reproduce this?

**Comment by aurimas535** [comment]
Happens to when I'm trying to remove `<MapboxGL.ShapeSource />` with features

**Comment by aurimas535** [comment]
@mattijsf any progress on this?

**Comment by kristfal** [comment]
This should be fixed in master. Reopen if issue persists.
