### ISSUE TITLE
After adding react-native-mapbox-gl/maps, cannot "pod install"

### ISSUE THREAD

**Issue by kenjichanhkg** [react-native-mapbox-gl/maps#1449]
**Describe the bug**  
After adding react-native-mapbox-gl/maps, cannot "pod install"

**To Reproduce**  
```
sudo arch -x86_64 gem install ffi
npx react-native init t1
# comment out # use_flipper!() in ios/Podfile
npm install @react-native-mapbox-gl/maps
# and add pre/post_install lines in Podfile as descibed in the "iOS Installation" doc
cd t1/ios && pod install && cd ..
arch -x86_64 npx react-native run-ios
```

Without step 1,3 and the "arch -x86_64", I couldn't get a helloworld working on m1 mac.
I'm stuck on the 2nd last step.

I tried to add "arch -x86_64" to run pod install, but it didn't help:
```
arch -x86_64 pod install 
```

I tried both methods as described in [https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md](https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md)

My Podfile:
```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 't1' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 't1Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
#  use_flipper!()

  #pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'

  post_install do |installer|
    $RNMBGL.post_install(installer)
    react_native_post_install(installer)
  end

  pre_install do |installer|
    $RNMBGL.pre_install(installer)
  end
end
```

**Expected behavior**  
I should be able to run pod install.

**Actual behavior**  
Error. The error message is too long to show here. So I just screen capture the beginning and the end of it.

![image](https://user-images.githubusercontent.com/7701160/124375946-37f7d400-dcd7-11eb-8b67-3bc5292784fa.png)
![image](https://user-images.githubusercontent.com/7701160/124375962-48a84a00-dcd7-11eb-8572-08c4d56f5000.png)

**Versions:**  
 - Machine: Mac mini (M1, 2020)
 - Simulator: yes, iPhone 12 (iOS 14.5)
 - Dev OS: macOS Big Sur v11.4, xcode 12.5.1
 - react-native-mapbox-gl Version 8.2.1
 - React Native Version 0.64.2

**Comment by ferdicus** [comment]
what happens when you try with the `/example` app?

**Comment by mfazekas** [comment]
Sounds like the issue is that `libffi` is installed for x86 only, but likely pod install (or it's subprocess) is not x86 but arm.

**Comment by kenjichanhkg** [comment]
> what happens when you try with the `/example` app?

I got the same error:
![image](https://user-images.githubusercontent.com/7701160/124493527-500b4880-dde8-11eb-89f4-c0b6f2885ea5.png)

**Comment by kenjichanhkg** [comment]
> Sounds like the issue is that `libffi` is installed for x86 only, but likely pod install (or it's subprocess) is not x86 but arm.

I tried using "Rosetta" Terminal to make sure everything is in x86. I don't know what else I could do.
I'm stuck with this issue for months already, hoping someone could fix it.

**Comment by ferdicus** [comment]
Check out these links related to react-native/ ios builds/ ffi - as mfazekas mentioned, seems to be an issue with the later:
* https://stackoverflow.com/questions/65403551/pod-install-failed-on-macos-big-sur
* https://github.com/CocoaPods/CocoaPods/issues/9907
* https://gist.github.com/badsyntax/72c5c965fcaefe66d049a8c2cdf34198
* https://kimpeupeu.tistory.com/10

**Comment by kenjichanhkg** [comment]
I'm not sure why or what I did. But I fixed my pod install issue by running these commands:
```
gem uninstall -aIx
sudo gem uninstall cocoapods
gem install -n /usr/local/bin cocoapods
```

**Comment by ferdicus** [comment]
It's also mentioned here: https://github.com/CocoaPods/CocoaPods/issues/9907#issuecomment-863519652

**Comment by ferdicus** [comment]
I don't want to discourage you from adding more tickets to this repo or anything,  
however this issue could've been solved by a simple google search, which I did [here](https://github.com/react-native-mapbox-gl/maps/issues/1449#issuecomment-874197186) and found 4 viable links
Next time please consider to try that _before_ opening an issue ticket. 

Thanks
