### ISSUE TITLE
Custom MarkerView and Supercluster cause lag

### ISSUE THREAD

**Issue by Pietro-Putelli** [react-native-mapbox-gl/maps#1473]
When I use custom MarkerView and clustering the map starts to lag. For clustering I'm using supercluster (https://github.com/mapbox/supercluster).
```
      <MapView
        onRegionIsChanging={onRegionIsChanging} // everytime region is changing I'm going to update clusters.
      >
        {clusters.map((cluster, index) => {
          const { cluster: isCluster } = cluster.properties;

          if (isCluster) {
            return (
              <Cluster
                key={cluster.id}
                cluster={cluster}
                onPress={onClusterPress}
              />
            );
          }

          return (
            <CustomMarker
              item={cluster}
              onPress={onMarkerPress}
              key={cluster.properties.id}
              {...{ selectedItem, onMomentumScrollEnd }}
            />
          );
        })}
      </MapView>
```
// CustomMarker.js

```
const CustomMarker = ({
  item: {
    properties: { id },
    geometry,
  },
}) => {
  return (
    <MarkerView id={id.toString()} coordinate={geometry.coordinates}>
      <TouchableOpacity onPress={() => onPress(id)}>
        <Animated.View>
          <Image source={require("./assets/cocktail.png")}  />
        </Animated.View>
      </TouchableOpacity>
    </MarkerView>
  );
};

// And I've used .memo to avoid re-renders everytime onRegionIsChangin is called.
export default React.memo(CustomMarker, (prevProps, nextProps) => {
  return (
    prevProps.item.properties.id === nextProps.item.properties.id
  );
});
```

**Comment by ferdicus** [comment]
Hi @Pietro-Putelli, 
I wouldn't recommend using `onRegionIsChanging` instead I'd use `onRegionDidChange` which will fire once when the region change happened. 

`onRegionIsChanging` will fire _A LOT_ when the user pans the map or you initiate a camera movement.  
Especially with expensive calculations this can bog down your whole application. 


Cheers 🍻

**Comment by Pietro-Putelli** [comment]
Hi ferdicus, sorry for answering you now, but I've been a little busy.
Since I want to update my markers when the user zoom-in or zoom-out, it's bettere to use `onRegionIsChanging`, I've used React.memo applied to the Markers in order to update them only when is necessary, thus reducing the lag.

**Comment by Pietro-Putelli** [comment]
> Hi @Pietro-Putelli,
> I wouldn't recommend using `onRegionIsChanging` instead I'd use `onRegionDidChange` which will fire once when the region change happened.
> 
> `onRegionIsChanging` will fire _A LOT_ when the user pans the map or you initiate a camera movement.
> Especially with expensive calculations this can bog down your whole application.
> 
> Cheers 🍻

**Comment by Pietro-Putelli** [comment]
HI ferdicus, one more problem, now after the update, the map still lag also when I add only the user marker position.
How can I solve?
