### ISSUE TITLE
Unhandled event callback type 'didfailoading'

### ISSUE THREAD

**Issue by markspereira** [react-native-mapbox-gl/maps#148]
**Describe the bug**
Receiving error `Unhandled event callback type 'didfailoading'` when navigating to certain screens in the examples folder and in my project. **Notice the typo in 'didfailloading' as well**

This is replicable in the getZoom example.

**Comment by kristfal** [comment]
Platform?

**Comment by markspereira** [comment]
The error seems to be fixed now, can't reproduce.
