### ISSUE TITLE
Setting padding on camera breaks `moveTo` behavior

### ISSUE THREAD

**Issue by doomsower** [react-native-mapbox-gl/maps#150]
Here's my mapbox component:
```tsx
<Mapbox.MapView
  localizeLabels={true}
  pitchEnabled={false}
  rotateEnabled={false}
  compassEnabled={false}
  showUserLocation={showUserLocation}
  styleURL={mapType}
  style={StyleSheet.absoluteFill}
  onPress={onPress}
>
  <Mapbox.Camera ref={cameraRef} bounds={bounds} animationDuration={0} />

  <Mapbox.ShapeSource
    id="sectionsSource"
    shape={sections}
    onPress={detailed ? undefined : onPress}
    hitbox={HIT_BOX}
  >
    {/*...*/}
  </Mapbox.ShapeSource>
</Mapbox.MapView>;
```

where bounds are like this:
```tsx
    const bounds: MapboxBounds = {
      ne: [maxLng, maxLat],
      sw: [minLng, minLat],
      // paddingBottom: theme.margin.single,
      // paddingLeft: theme.margin.single,
      // paddingRight: theme.margin.single,
      // paddingTop: theme.margin.single,
    };
```

and `onPress` handler can move camera:

```tsx
if (cameraRef.current) {
  cameraRef.current.moveTo(/**/);
}
```

**Expected behavior**

User can pan/zoom map, then press on feature to center the map while retaining current zoom level. It works as expected if padding is commented out.
With padding enabled, when user presses on feature the map instead resets to initial bounds and zoom level.

I tried to use new `defaultSettings` feature to set default bounds for uncontrolled behavior, but it doesn't work like controlled `bounds`.
It seems to set center correctly, but zoom doesn't match bounds+padding, it's too wide.

**Screenshots**

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: iPhone SE emulator
 - OS: iOS12.1
 - SDK Version: latest master branch
 - React Native Version

**Additional context**

**Comment by mattijsf** [comment]
I pushed a fix to `master` after which the above example should work with `defaultSettings` and correct zoom. It's not released yet but you can try it by pointing to `master`.
