### ISSUE TITLE
LineLayer showing for only half a second - Android

### ISSUE THREAD

**Issue by OlliePugh** [react-native-mapbox-gl/maps#1500]
I have a scenario where a route is passed to a new screen as a prop, then this route is used in a `LineLayer`. This route will appear for around 100ms then disapear.

**To Reproduce**  
Pass a route as `number[][]` as a prop. (For each individual line in the route)

```
interface mapProps {
    path: number[][],
}

export const OnRouteMap = ({ path }: mapProps) => { 
    MapboxGL.setAccessToken(MAPBOX_KEY);
  
    const [mapLoaded, setMapLoaded] = useState(false)
    const [followUser, setFollowUser] = useState(true) // should the map follow the user
    
    const geoJsonPath = makeGeoJSON(path); 

    return <>
    <MapboxGL.MapView style={styles.map} onDidFinishLoadingMap={()=>{setMapLoaded(true)}}>
        <MapboxGL.UserLocation/>
        {
        !mapLoaded ?
        <MapboxGL.Camera 
        followUserLocation={followUser}
        followUserMode={MapboxGL.UserTrackingModes.FollowWithHeading}  
        onUserTrackingModeChange={(data) => {console.log(data.nativeEvent.payload); setFollowUser(data.nativeEvent.payload.followUserLocation)}}
        />
        :
        <MapboxGL.Camera 
        followUserLocation={followUser} 
        followUserMode={MapboxGL.UserTrackingModes.FollowWithHeading} 
        followZoomLevel={20}  // Map would be zoomed into 0,0 if this was applied before the map was loaded
        followPitch={80}
        />
        }
        
        <MapboxGL.ShapeSource id='finalLine' shape={geoJsonPath}>
            <MapboxGL.LineLayer id="finalPath" style={{lineColor: "blue", lineWidth: 15, lineOpacity: 0.4}} />
        </MapboxGL.ShapeSource>

    </MapboxGL.MapView>
    <Button onPress={() => {setFollowUser(true)}} title={"Recenter"}></Button></>;  // make the map follow the user again
}

```

**Expected behavior**  
The lines to appear and stay

**Actual behavior**  
The lines flash and then disappear.

**Versions (please complete the following information):**  
 - Platform: Android (Working as expected on IOS)
 - Platform OS: Android 10
 - Device: Pixel 3a
 - Emulator/ Simulator: Yes
 - Dev OS: Win 10
 - react-native-mapbox-gl Version 8.3.0
 - Mapbox GL version (Not sure where to find this 😕 )
 - React Native Version 0.64.2

**Additional context**  
If I have loaded the page, and the line appears, then disappears. If I trigger a fast refresh by saving a file, the line appears and stays. So I think the issue is due to it being on a page that is being initiated.

**Comment by OlliePugh** [comment]
To reproduce, you need to pass a 2D array of numbers, e.g.: [[1,1],[2,2],[3,3]], these represent each line on the map.

Then the issue shoud be observed.

**Comment by ferdicus** [comment]
hi @OlliePugh, can you try to reproduce this issue within our `example` app,
`example/src/examples/LineLayer/GradientLine.js` should be a good starting point, 
and report back what your findings are. 

Thanks in advance

**Comment by OlliePugh** [comment]
I have since resolved this by using a useMemo on the ShapeSource so that it does not rerender everytime the screen renders.

**Comment by ferdicus** [comment]
closing as resolved
