### ISSUE TITLE
Need to provide access token when using MapLibre

### ISSUE THREAD

**Issue by konstantinlois** [react-native-mapbox-gl/maps#1513]
I am trying to use MapLibre with React Native. I followed the installation instructions and used the following Code in my App.js:

```
import React from 'react';
import { Text, View } from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

function App() {

  return <View>
    <Text>Test</Text>
    <MapboxGL.MapView style={{
      flex: 1
    }} />
  </View>
};

export default App;
```

With that setup, I get the following error:

![screenshot](https://user-images.githubusercontent.com/36762282/131403799-dd4b881b-2490-42c2-b281-0998d8d9dfd3.png)

Is that intented? My undestanding was that one can use MapLibre without an access token. But I might have gotten that wrong.

Thank you for your help.

**Comment by ferdicus** [comment]
try `MapboxGL.﻿﻿﻿﻿﻿setAccessToken('')`

**Comment by konstantinlois** [comment]
That works, thanks a lot for the quick response.
