### ISSUE TITLE
rendering custom MarkerView lag on zoom in/out and move on the map

### ISSUE THREAD

**Issue by Pietro-Putelli** [react-native-mapbox-gl/maps#1526]
I'm using the latest version of this library - `v. 8.3.0`.
I want to add a MarkerView, which contains a view as a child, to mark the user position, but only this marker cause extreme lag on zoom in/out and move on the map. 

Here's an example of code that in my case cause lag:

```
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@react-native-mapbox-gl/maps';


// I've also try to wrap the marker inside useMemo, to avoid usless reload but it still don't work.
  const User = useMemo(() => {
    return (
      <MapboxGL.MarkerView coordinate={USER_POSITION} id="user.position">
        <View></View>
      </MapboxGL.MarkerView>
    );
  }, []);

    <MapView style={{ width, height }}>
      <Camera ref={cameraRef} {...cameraOptions} />
{User}
    </MapView>

```

Here's a video to clarify the bug:
https://drive.google.com/file/d/1Qni4_xrX7_s0VE1VshVnna3737lxELtT/view?usp=sharing

**Comment by ferdicus** [comment]
Can you please attach videos directly to the ticket?  
Thanks


Is this only on simulator or also on physical devices? 
Did you try with updated native SDKs?

**Comment by Pietro-Putelli** [comment]
Hi ferdicus, thank you for your answer, after trying some version I finally face the issue: the native version.

MapBox SDK version  => 6.3.0
react-native-mapbox-gl version => 8.3.0

By using this 2 versions the performace drop disappear.

**Comment by ferdicus** [comment]
so.... solved?

**Comment by Pietro-Putelli** [comment]
For now, yes.
