### ISSUE TITLE
[Android] compassViewMargin is ignored

### ISSUE THREAD

**Issue by mlecoq** [react-native-mapbox-gl/maps#1527]
# Bug report

## Summary

I have added a `compassViewMargin` on my map, it is well handled on iOS but ignored on android

## Environment info

`react-native info` output:

```bash
react: 16.13.1 => 16.13.1 
react-native: ~0.63.4 => 0.63.4 
@react-native-mapbox-gl/maps: 8.3.0
```

## Steps to reproduce

create a map with a compass
```
const compassViewMargin = {x: 10, y: 70};

<MapboxGL.MapView
        compassViewPosition={3}
        compassViewMargins={compassViewMargin}
        style={mapViewStyle}
     >
</MapboxGL.MapView>
```

Describe what you expected to happen:

The compass is displayed according to displayed margin

Describe what you actually happens:

on iOS it's ok, on android not

## Reproducible sample code

![Simulator Screen Shot - iPhone 11 - 2021-09-07 at 10 30 38](https://user-images.githubusercontent.com/3649784/132312029-a246ff39-6883-483d-b273-c75f42521cbb.png)

![image](https://user-images.githubusercontent.com/3649784/132312089-31ac6539-f43d-4b3c-a732-a1de6866ddb1.png)

**Comment by ferdicus** [comment]
hmm, I can not reproduce this within the `example` project. 
I've tried both on iOS (simulator) and android (physical device). 

Yes a refresh is required, however the margins are respected. 

See below screenshots with these props
```jsx
        compassEnabled={true}
        compassViewPosition={3}
        compassViewMargins={{x: 150, y: 170}}
```

Android | iOS
---|---
![android_screenshot_ZY22BGGHB6_21-09-10_11 22 58](https://user-images.githubusercontent.com/26439946/132832018-160434b9-1ecb-4596-a2e2-5e7833de9e27.png) | ![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-09-10 at 11 23 04](https://user-images.githubusercontent.com/26439946/132832047-e53adbae-f630-4112-9785-7c509abe9e4b.png)

**Comment by mlecoq** [comment]
I will try to make a small example

**Comment by ferdicus** [comment]
> I will try to make a small example

Can you also please try to reproduce within the `example` project

**Comment by mlecoq** [comment]
@ferdicus you're right, with a reload of the app the margin are well applied. Thanks !
