### ISSUE TITLE
How do I run the Mapbox SDK for React Native without errors and warnings?

### ISSUE THREAD

**Issue by Serzol64** [react-native-mapbox-gl/maps#1529]
Good day! The description and essence of this problem [are here](https://translate.yandex.ru/translate?lang=ru-en&url=https%3A%2F%2Fqna.habr.com%2Fq%2F1045742) and at the moment the latest versions of test environments, libraries and development tools are used.

**Comment by ferdicus** [comment]
Hi, thanks for the ticket, please make sure to follow our issue template when creating an issue.
It has extensive explanations and required fields that should be filled out.
