### ISSUE TITLE
[Android] - PointAnnotation doesn't re render after touch on Android

### ISSUE THREAD

**Issue by UmerWarraich95** [react-native-mapbox-gl/maps#1535]
**Describe the bug**  
Pressing on the child component of PointAnnotation doesn't re render on Android while it's working fine on iOS.
I am using a PointAnnotation of mapbox to change Icon color when user pressed the icon. For IOS, its work fine and change the color while for Android, it doesn't re render and changed its color.
Moreover, after pressing icon, functionality works fine.

**To Reproduce**  
Open the example project, add Mapbox, add PointAnnotation and change color of the child componenet in PointAnnotation.

Here is the example code of PointAnnotation:

import React from 'react';
import { View,  TouchableOpacity } from "react-native";
import MapboxGL from "@react-native-mapbox-gl/maps";
import Icon from 'react-native-vector-icons/Feather';

const Token = MAPBOX_API_KEY
MapboxGL.setAccessToken(Token);

const Map = ( props) => {
  return (
    <MapboxGL.MapView
        styleURL={MapboxGL.StyleURL.Satellite}
        style={styles.map}
    >
        <MapboxGL.Camera
          centerCoordinate={cameraCoords}
          zoomLevel={cameraZoom}
        />

        <MapboxGL.PointAnnotation
                  id='south' key='south'
                  coordinate={directionGreenAreaHandler('south')}
        >
          <TouchableOpacity
             onPress={onPress}
             disabled={disabled}
          >
             <View style={{ ...styles.greenDirectionIcons, borderColor: color, backgroundColor: 'grey' }} >
               <Icon name={arrowIconDirectionHandler} size={32} color={color} />
             </View>
          </TouchableOpacity>
        </MapboxGL.PointAnnotation>

    </MapboxGL.MapView >
  );
};

**Expected behavior**  
Icon color of the child componenet of PointAnnotation should be changed.

**Actual behavior**  
Icon color of the child componenet of PointAnnotation is not changed on Android while changed on iOS.

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 11
 - Device: Redmi Note 9
 - react-native-mapbox-gl Version: 8.3.0
 - React Native Version: 0.63.4

**Additional context**  
Functionality works fine after pressing icon of in child component of PointAnnotation for both Android and IOS,

**Comment by mfazekas** [comment]
@UmerWarraich95 this is because the limitations of the native libraries we're using.  Please use the [`refresh`](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/PointAnnotation.md#refresh) method.
