### ISSUE TITLE
Provide instructions on how to include Mapbox 6.x.x using Direct download

### ISSUE THREAD

**Issue by mvanroon** [react-native-mapbox-gl/maps#1553]
- react-native-mapbox-gl can install the official Mapbox SDK as mentioned in the [iOS installation instructions](https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md#new-version---since-81rc5)
 - This requires the existence of a .netrc file in your home directory which might not always be possibly in every CI/CD service (for instance Expo EAS doesn't allow you to add extra scripts to the build steps).
 - Mapbox provides an alternative way: [direct download](https://docs.mapbox.com/ios/maps/guides/install/#add-the-dependency)
 - However when installing the Mapbox SDK manually ánd installing the Mapbox dependencies through pod-installing react-native-mapbox-gl, builds will fail because the SDK was added twice.
 
 How can I prevent react-native-mapbox-gl from installing the Mapbox SDK through cocoapods?

If someone can push me in the right direction, I'll create a PR for adding the instructions in the README.md.

**Comment by mfazekas** [comment]
@mvanroon we already have customisations to include SPM package instead of cocoa pods - see docs on Maplibre. You can include an unrelated SPM package, the mapbox will not be installed from cocoa pods

**Comment by romansf20** [comment]
@mfazekas it would have been nice to get a link to the Maplibre doc you are referencing above. I have not been able to get the eas build working with mapbox so far ):

**Comment by mfazekas** [comment]
@romansf20 I don't think it will help with `eas` build.  

For `#main` branch you can just set `RNMapboxMapsSwiftPackageManager="manual"` and add mapbox libs they way you prefer.

https://github.com/rnmapbox/maps/blob/659972c8a3988ec531078bc6de6407ff968c673f/rnmapbox-maps.podspec#L1-L16
