### ISSUE TITLE
Offline map instruction

### ISSUE THREAD

**Issue by Babar-Memon** [react-native-mapbox-gl/maps#1554]
Anyone help me to download offline map with my custom markers and use downloaded map when user has no internet connectivity.

Thanks.

**Comment by Babar-Memon** [comment]
@ferdicus can you help me out implementing offline map?

**Comment by ferdicus** [comment]
@Babar-Memon , please either start a discussion/ stackoverflow question or ask in our gitter chat. 
Issue tickets are not a place for these kind of questions.
