### ISSUE TITLE
App is not installing in IOS simulator

### ISSUE THREAD

**Issue by Arnab2021** [react-native-mapbox-gl/maps#1555]
I am using 
"@react-native-mapbox-gl/maps": "^8.3.0",
"react": "17.0.2",
"react-native": "0.65.1"
COCOAPODS: 1.10.1

When ever trying to build the project I am getting the below error.
![image](https://user-images.githubusercontent.com/84457641/135095787-6ee64a65-ce16-42e1-a00b-a1f3caa1c2b5.png)

No build time error but the App is not installing in the simulator.
**ANY HELP ?**

**My POD file**
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

$ReactNativeMapboxGLIOSVersion = '~> 5.9'

INHIBIT_WARNING_BY_DEFAULT = true

if INHIBIT_WARNING_BY_DEFAULT
  ORIG_POD = method(:pod)

  def pod(name, *requirements)
    options = requirements.last
    if options.is_a?(Hash)
      options[:inhibit_warnings] = true unless options.has_key?(:inhibit_warnings)
    else
      requirements.push({inhibit_warnings: true})
    end
    ORIG_POD[name, *requirements]
  end
end

target 'HomulaMap' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],   
    :hermes_enabled => false
  )
  pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'

  pre_install do |installer|
    $RNMBGL.pre_install(installer)    
  end

  if !ENV['CI']
    
    use_flipper!()
    post_install do |installer|
      react_native_post_install(installer)
      $RNMBGL.post_install(installer)
    end
  else
  
    post_install do |installer|
      react_native_post_install(installer)
      $RNMBGL.post_install(installer)
    end
  end
end

**Comment by ferdicus** [comment]
are you on an intel or M1 chipset?
On which native SDK version of iOS Mapbox are you on? 
Can you please try to reproduce this within our `/example` app? 


Thanks

**Comment by Arnab2021** [comment]
> are you on an intel or M1 chipset? On which native SDK version of iOS Mapbox are you on? Can you please try to reproduce this within our `/example` app?
> 
> Thanks

It works after reinstalling xcode and reset cache in simulator
