### ISSUE TITLE
getDataNetworkTypeForSubscriber

### ISSUE THREAD

**Issue by Poojamok** [react-native-mapbox-gl/maps#1556]
after installing and adding dependencies it build successfully but when app open it show me  getDataNetworkTypeForSubscriber.
how to solve this, also adding image to show what error I have got
![eeror](https://user-images.githubusercontent.com/69619858/135428999-fb084b46-acfe-4d87-a11b-dc012a36234d.png)

**Comment by nssprite** [comment]
@Poojamok Have you solved this problem? I have the same error.
