### ISSUE TITLE
How to get user location icon on top of lines or other layers?

### ISSUE THREAD

**Issue by btuck044** [react-native-mapbox-gl/maps#1567]
### Discussed in https://github.com/react-native-mapbox-gl/maps/discussions/1566

<div type='discussions-op-text'>

<sup>Originally posted by **btuck044** October  1, 2021</sup>
![image](https://user-images.githubusercontent.com/6107694/135665693-c2327d0d-8071-45e8-89d2-151fc4d20ed0.png)
</div>

**Comment by yaroslav-tormasov** [comment]
you can specify layerIndex = {2} to the layer that lies above the user position
