### ISSUE TITLE
zoomTo does not work after upgrading from version 8.3.0 to 8.4.0

### ISSUE THREAD

**Issue by galkinsden** [react-native-mapbox-gl/maps#1591]
**Describe the bug**

zoomTo does not work after upgrading from version 8.3.0 to 8.4.0

**To Reproduce**

```js
import React, { memo, useCallback } from 'react';
import { TouchableOpacity, Text } from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

const Test = () => {
  const camera = React.createRef(null);
  const map = React.createRef(null);
  const zoom = useCallback(
    async (zoomIn) => {
      const currentZoom = await map.current.getZoom();
      camera.current.zoomTo(currentZoom + (zoomIn ? 1 : -1));
    },
    [map, camera]
  );
  const zoomPlus = useCallback(() => zoom(true), [zoom]);
  const zoomMinus = useCallback(() => zoom(), [zoom]);
  return (
    <>
      <MapboxGL.MapView style={styles.map} ref={map}>
        <MapboxGL.Camera ref={camera} />
      </MapboxGL.MapView>
      <TouchableOpacity onPress={zoomPlus}>
        <Text>zoom plus</Text>
      </TouchableOpacity>
      <TouchableOpacity onPress={zoomMinus}>
        <Text>zoom minus</Text>
      </TouchableOpacity>
    </>
  );
};
```

**Versions**
 - Platform OS: [IOS, Android]
 - "react-native": "0.64.2",
 -  "@react-native-mapbox-gl/maps": "8.4.0"

**Comment by ferdicus** [comment]
@galkinsden, can you please verify with current `master`? 
Thanks 👍🏿

**Comment by dorthwein** [comment]
So we have a similar issue where updating camera properties to adjust the camera don't seem to work anymore (both android & iOS).  

Just tried with current master branch - no luck.  I have a hunch its tied to event emitter changes in react-native v0.66.1

**Comment by whiteHatCip** [comment]
> So we have a similar issue where updating camera properties to adjust the camera don't seem to work anymore (both android & iOS).
> 
> Just tried with current master branch - no luck. I have a hunch its tied to event emitter changes in react-native v0.66.1

I was experiencing the same issue. Been struggling with this all day long yesterday and couldn't find any workaround.
looking through all the commits, I found that the commit a2d46c4f272673e248d574f6bcf65407d1196096 published on November, 3rd changed something related to the camera behavior. Therefore I thought to copy paste the changes of that commit manually to see whether this would have fixed my issue, and thankfully, the app came back to work as expected, like it was before the library updates (last update was using version 8.1.0-rc.9 

Try doing the same as I did. Maybe you will be as "lucky" as I am. I am now bundling a new version and will test it on TestFlight. If you want I will update this issue with definitive confirmation that the app came back to work properly.

**Comment by ferdicus** [comment]
@dorthwein @whiteHatCip @galkinsden, can you all do me a solid and test `master` to see if that fixes your issues - I could create a release on Wednesday when all is fine 👍🏿

**Comment by ShepelE** [comment]
> @dorthwein @whiteHatCip @galkinsden, can you all do me a solid and test `master` to see if that fixes your issues - I could create a release on Wednesday when all is fine 👍🏿

I have the same case: zoomTo is broken (currently testing on android).
I've changed source to master - still broken.

It looks like Camera.js _handleCameraChange method gets false from this._hasCameraChanged(c, n);
investigating js part...

**Comment by ShepelE** [comment]
ok, it looks like android currently requires centerCoordinate for zoomTo method

**Comment by dorthwein** [comment]
@ferdicus - so looking at master, zoomTo seems to be resolved, however the other props, such as setting the device to `followUserMode={true}`, or jumping to the current location by setting center coordinate are still not working.

**Comment by galkinsden** [comment]
@ferdicus, zoomTo from master still doesn't work, but setCamera with centerCoordinate property does. @ShepelE, thx ;)

**Comment by ferdicus** [comment]
@naftalibeder, can you please have a look, thanks

**Comment by naftalibeder** [comment]
Check it out, all ^

**Comment by whiteHatCip** [comment]
guys, I am sorry for the probably silly question, but, how may I reference the master branch inside the dependencies of my app, or even the brand referenced by @naftalibeder right above my comment?
I wanna test the pr in my environment and provide you feedback, but need to know how.

**Comment by ferdicus** [comment]
> guys, I am sorry for the probably silly question, but, how may I reference the master branch inside the dependencies of my app, or even the brand referenced by @naftalibeder right above my comment? I wanna test the pr in my environment and provide you feedback, but need to know how.

not silly at all, although easily searchable - check out this stack post:
https://stackoverflow.com/questions/16350673/depend-on-a-branch-or-tag-using-a-git-url-in-a-package-json

Cheers

**Comment by dorthwein** [comment]
@naftalibeder - zoom adjustments work in your example IF follow user location is true, however they do not work if it is false anymore.  Use case here is a +/- button to zoom the map even when not following the user's location.  Our user base is truck drivers and this is a UI/UX they are used to. 

Additionally, setting followUserLocation={true} & followUserMode="course" does not seem to work.  i.e. the map will not follow the user's location.

**Comment by naftalibeder** [comment]
@dorthwein Please see #1621 .

**Comment by ferdicus** [comment]
@dorthwein , @whiteHatCip, @galkinsden, @ShepelE 

![meme](https://user-images.githubusercontent.com/26439946/142199866-bb7b4e22-c58f-4d5d-94b5-3c215dc88e0c.jpg)

**Comment by kristfal** [comment]
zoomLevel changes were broken on both iOS and Android due to #1538. 

The issue arise from two places: JS side checks were added to propagate camera changes to native side – which lacked checks on `zoomLevel` and native side changes for both iOS and Android resulted in no derived camera change unless centerCoordinate or bounds were passed along with the change event.

I suggest @naftalibeder update PR #1631 to reflect the required changes on the JS side instead of me adding another PR.

This can be fixed on 8.4.0 by applying the following diff (ignore the formatting changes for Android):

```diff
diff --git a/node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraStop.java b/node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraStop.java
index 5ebfe12..3ddbc04 100644
--- a/node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraStop.java
+++ b/node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/CameraStop.java
@@ -102,17 +102,13 @@ public class CameraStop {
         int paddingRight = Double.valueOf(contentInset[2] + mPaddingRight).intValue();
         int paddingBottom = Double.valueOf(contentInset[3] + mPaddingBottom).intValue();
 
-        int[] cameraPadding = {paddingLeft, paddingTop, paddingRight, paddingBottom};
+        int[] cameraPadding = { paddingLeft, paddingTop, paddingRight, paddingBottom };
         int[] cameraPaddingClipped = clippedPadding(cameraPadding, mapView);
 
         if (mLatLng != null) {
             builder.target(mLatLng);
-            builder.padding(
-                cameraPaddingClipped[0],
-                cameraPaddingClipped[1],
-                cameraPaddingClipped[2],
-                cameraPaddingClipped[3]
-            );
+            builder.padding(cameraPaddingClipped[0], cameraPaddingClipped[1], cameraPaddingClipped[2],
+                    cameraPaddingClipped[3]);
             if (mZoom != null) {
                 builder.zoom(mZoom);
             }
@@ -126,21 +122,20 @@ public class CameraStop {
                 builder.zoom(boundsCamera.zoom);
                 builder.padding(boundsCamera.padding);
             } else {
-                CameraUpdate update = CameraUpdateFactory.newLatLngBounds(
-                    mBounds,
-                    cameraPaddingClipped[0],
-                    cameraPaddingClipped[1],
-                    cameraPaddingClipped[2],
-                    cameraPaddingClipped[3]
-                );
+                CameraUpdate update = CameraUpdateFactory.newLatLngBounds(mBounds, cameraPaddingClipped[0],
+                        cameraPaddingClipped[1], cameraPaddingClipped[2], cameraPaddingClipped[3]);
                 return new CameraUpdateItem(map, update, mDuration, mCallback, mMode);
             }
+        } else if (mZoom != null) {
+            builder.zoom(mZoom);
         }
 
-        return new CameraUpdateItem(map, CameraUpdateFactory.newCameraPosition(builder.build()), mDuration, mCallback, mMode);
+        return new CameraUpdateItem(map, CameraUpdateFactory.newCameraPosition(builder.build()), mDuration, mCallback,
+                mMode);
     }
 
-    public static CameraStop fromReadableMap(Context context, @NonNull ReadableMap readableMap, MapboxMap.CancelableCallback callback) {
+    public static CameraStop fromReadableMap(Context context, @NonNull ReadableMap readableMap,
+            MapboxMap.CancelableCallback callback) {
         CameraStop stop = new CameraStop();
 
         if (readableMap.hasKey("pitch")) {
@@ -163,12 +158,7 @@ public class CameraStop {
         paddingBottom = Float.valueOf(paddingBottom * metrics.scaledDensity).intValue();
         paddingLeft = Float.valueOf(paddingLeft * metrics.scaledDensity).intValue();
 
-        stop.setPadding(
-                paddingLeft,
-                paddingRight,
-                paddingTop,
-                paddingBottom
-        );
+        stop.setPadding(paddingLeft, paddingRight, paddingTop, paddingBottom);
 
         if (readableMap.hasKey("centerCoordinate")) {
             Point target = GeoJSONUtils.toPointGeometry(readableMap.getString("centerCoordinate"));
@@ -190,17 +180,17 @@ public class CameraStop {
 
         if (readableMap.hasKey("mode")) {
             switch (readableMap.getInt("mode")) {
-                case CameraMode.FLIGHT:
-                    stop.setMode(CameraMode.FLIGHT);
-                    break;
-                case CameraMode.LINEAR:
-                    stop.setMode(CameraMode.LINEAR);
-                    break;
-                case CameraMode.NONE:
-                    stop.setMode(CameraMode.NONE);
-                    break;
-                default:
-                    stop.setMode(CameraMode.EASE);
+            case CameraMode.FLIGHT:
+                stop.setMode(CameraMode.FLIGHT);
+                break;
+            case CameraMode.LINEAR:
+                stop.setMode(CameraMode.LINEAR);
+                break;
+            case CameraMode.NONE:
+                stop.setMode(CameraMode.NONE);
+                break;
+            default:
+                stop.setMode(CameraMode.EASE);
             }
         }
 
@@ -236,7 +226,7 @@ public class CameraStop {
             resultRight -= (right * extra) / totalPadding;
         }
 
-        return new int[] {resultLeft, resultTop, resultRight, resultBottom};
+        return new int[] { resultLeft, resultTop, resultRight, resultBottom };
     }
 
     private static int getPaddingByKey(ReadableMap map, String key) {
diff --git a/node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL/CameraUpdateItem.m b/node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL/CameraUpdateItem.m
index e257343..533e1b8 100644
--- a/node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL/CameraUpdateItem.m
+++ b/node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL/CameraUpdateItem.m
@@ -106,6 +106,8 @@
             edgePadding: [self _clippedPadding:_cameraStop.padding forView:mapView]];
         nextCamera.centerCoordinate = boundsCamera.centerCoordinate;
         nextCamera.altitude = boundsCamera.altitude;
+    } else if (_cameraStop.zoom != nil) {
+        nextCamera.altitude = [mapView altitudeFromZoom:[_cameraStop.zoom doubleValue] atLatitude:nextCamera.centerCoordinate.latitude atPitch:nextCamera.pitch];
     }
 
     RCTMGLCameraWithPadding* cameraWithPadding = [[RCTMGLCameraWithPadding alloc] init];
diff --git a/node_modules/@react-native-mapbox-gl/maps/javascript/components/Camera.js b/node_modules/@react-native-mapbox-gl/maps/javascript/components/Camera.js
index 628ed04..d5b2a54 100644
--- a/node_modules/@react-native-mapbox-gl/maps/javascript/components/Camera.js
+++ b/node_modules/@react-native-mapbox-gl/maps/javascript/components/Camera.js
@@ -198,10 +198,23 @@ class Camera extends React.Component {
     return false;
   }
 
+  _hasZoomLevelChanged(prev, next) {
+    if (existenceChange(prev, next)) {
+      return true;
+    }
+
+    if (!prev && !next) {
+      return false;
+    }
+
+    return prev !== next;
+  }
+
   _handleCameraChange(currentCamera, nextCamera) {
     const c = currentCamera;
     const n = nextCamera;
 
+
     const hasCameraChanged = this._hasCameraChanged(c, n);
     if (!hasCameraChanged) {
       return;
@@ -250,10 +263,12 @@ class Camera extends React.Component {
       padding: n.padding,
     };
 
+    const zoomChanged = this._hasZoomLevelChanged(c.zoomLevel, n.zoomLevel);
     const boundsChanged = this._hasBoundsChanged(c.bounds, n.bounds);
     const centerCoordinateChanged = this._hasCenterCoordinateChanged(c, n);
     const paddingChanged = this._hasPaddingChanged(c, n);
 
+
     let shouldUpdate = false;
     if (n.bounds && (boundsChanged || paddingChanged)) {
       cameraConfig.bounds = n.bounds;
@@ -264,6 +279,11 @@ class Camera extends React.Component {
     ) {
       cameraConfig.centerCoordinate = n.centerCoordinate;
       shouldUpdate = true;
+    } else if (
+      zoomChanged
+    ) {
+      cameraConfig.zoomLevel = n.zoomLevel;
+      shouldUpdate = true;
     }
 
     if (shouldUpdate) {
```

**Comment by naftalibeder** [comment]
Anybody who needs to apply that patch, try giving [the most recent commit](https://github.com/react-native-mapbox-gl/maps/pull/1631) a shot!

**Comment by whiteHatCip** [comment]
I am sorry for not responding but this has been a really busy week and had no time to put my hands to the project. Will try to find the time to look at it tomorrow.

**Comment by ferdicus** [comment]
> I am sorry for not responding but this has been a really busy week and had no time to put my hands to the project. Will try to find the time to look at it tomorrow.

No worries - we understand, we're all busy too :D 
Take care 👍🏿

**Comment by lionep** [comment]
On my side, upgrading from 8.4.0 to master fixed the issue.

**Comment by ferdicus** [comment]
release `8.5.0` is published - it includes the fix for this issue
