### ISSUE TITLE
Mapbox with Markers & Annotation not working on Android

### ISSUE THREAD

**Issue by AsrarNoorani** [react-native-mapbox-gl/maps#1634]
Hello Developers let me know if you have any ideas......

**Issue :-** 
MapBox has successfully displayed on the App, but when we try to add marker or annotation it is not going to customised as we want... eg.(if we want to add info window for Mapbox marker it's not showing.) 

**Code :-** 
import React, { useEffect, useRef, useState } from "react";
import MapboxGL from '@react-native-mapbox-gl/maps';
import { ACCESSTOKEN } from "../../utils/Constants";

export default function Map(props) {
return(

   <MapboxGL.MapView
                style={{ flex:1 }}
                styleURL={"mapbox://styles/ailebo/ckvhrplb02gjs14lzqfao134z"}
            >
                <MapboxGL.Camera
                    zoomLevel={4}
                    animationMode={'flyTo'}
                    animationDuration={1100}
                    centerCoordinate={[collection[0].coordinate.longitude, collection[0].coordinate.latitude]}
                />
                {renderAnnotations()}
            </MapboxGL.MapView>

)
}

  const renderAnnotations = () => {
        const items = [];
        for (let i = 0; i < collection.length; i++) {
            items.push(renderAnnotation(i));
        }
        return items;
    }

const renderAnnotation = (counter) => {
        const id = `pointAnnotation${counter}`;
        const coordinate = [collection[counter].coordinate.longitude, collection[counter].coordinate.latitude];
        const title = `Longitude: ${collection[counter].coordinate.longitude} Latitude: ${collection[counter].coordinate.latitude}`;

        return (
 <MapboxGL.PointAnnotation
                key={id}
                id={id}
                title='Test'
                anchor={{ y: 1, x: 0.5 }}
                pointerEvents="none"
                coordinate={coordinate}> 
                <>
                    <MapboxGL.Callout style={{ top: Size._15 }}>
                        <TouchableOpacity>
                            <Image
                                source={{ uri: collection[counter].image }}
                                style={{ height: 60, width: 60, borderRadius: 100 }}
                            >
                            </Image>
                        </TouchableOpacity>
                    </MapboxGL.Callout>
                    <View style={{
                        backgroundColor: Colors.transparent,
                        width: 60, height: 60, alignItems: 'center',
                        justifyContent: 'center', overflow: 'hidden',
                    }}>
                        <Image
                            source={Assets.location_icon}
                            resizeMode={'contain'}
                            style={{ height: 35, width: 35 }}
                        />
                    </View>
                </> 
            </MapboxGL.PointAnnotation>

            <MapboxGL.PointAnnotation
                key={id}
                id={id}
                anchor={{ y: 1, x: 0.5 }}
                coordinate={coordinate}> 
                    <Image style={{ height: 15, width:15 }} source={Assets.location_icon} /> 
            </MapboxGL.PointAnnotation>

            <View>
            <MapboxGL.MarkerView
                key={id}
                onSelected={(e) => console.log("marker e", e)}
                // anchor={{ x: 0.5, y: 0.1 }}
                coordinate={coordinate}
            >
                    <Image resizeMode='contain' style={{ height: Size._26, width: Size._26 }} source={Assets.location_icon} />
            </MapboxGL.MarkerView>

            <MapboxGL.MarkerView coordinate={coordinate}>
                {AnnotationContent(collection[counter].image)}
            </MapboxGL.MarkerView>

            </View> 
            <MapboxGL.ShapeSource id='symbolLocationSource'
                shape={{
                    "type": "Point",
                    "coordinates": coordinate

                }}>
                <MapboxGL.SymbolLayer
                    id={id}
                    style={{
                        iconImage: markerBlack,
                        iconAllowOverlap: true,
                        iconIgnorePlacement: true,
                        iconColor: "white",
                        iconSize: 0.4,
                    }}
                />
            </MapboxGL.ShapeSource>
        );
    }

We have following below points for display MapBox Marker & MapBox info window.
**1)MapboxGL.PointAnnotation**
**2)MapboxGL.MarkerView**
**3)MapboxGL.ShapeSource**
**4)MapboxGL.SymbolLayer**

Platform: [ Android, iOS]
 - Platform OS: [Android 10] 
 - Emulator:[yes]
 - Dev OS: [Mac mini]
 - @react-native-mapbox-gl/maps Version [8.4.0] 
 - React Native Version [0.66.1]

Please let me know if you guys have same issues how to make info window on the marker without crash the App, pls let me share you code or examples if you have..

**Comment by ombogdan** [comment]
same problem
