### ISSUE TITLE
iOS: Offline manager progress listener bugs

### ISSUE THREAD

**Issue by silencer07** [react-native-mapbox-gl/maps#1645]
**Describe the bug**  
1. The progressListener in iOS is only called once the download has completed. both `MapboxGL.offlineManager.createPack` and `MapboxGL.offlineManager.subscribe` has the same problem
2. The moment is is called, the stats for the download are all wrong. This breaks any attempt to create a way to visually show to user that there is download limit for offline downloads or progress bars during download. see the sample json below

{ name: 'Offline Map 1',
  state: 2,
  percentage: 0,
  completedResourceSize: 0,
  completedTileCount: 0,
  completedResourceCount: 0,
  requiredResourceCount: -1,
  completedTileSize: 0 
}

**Versions (please complete the following information):**  
 - Platform: iOS. **Android does not have this bug**
 - Platform OS: iOS 15.1
 - Device: iPhone SE
 - Emulator/ Simulator: not tested in simulator
 - Dev OS: MacOS
 - react-native-mapbox-gl Version: 8.4.0
 - Mapbox GL version: tried both 6.3.0 and 5.8.0
 - React Native Version: 0.66

**Comment by silencer07** [comment]
OK i found the issue. seems that i should just use the percentage as a gauge for completeness instead of the status. 2 is the complete status for android but 3 in ios

**Comment by sabarikobagapau** [comment]
@silencer07  how to display downloaded map in offline please help ?
