### ISSUE TITLE
sometimes mapbox give following issue

### ISSUE THREAD

**Issue by Hamidkhan12** [react-native-mapbox-gl/maps#1669]
mapbox No address associated with hostname {"level": "error", "message": "{Thread-16}[Style]: Failed to load tile 9/255/256=>9 for source composite: Unable to resolve host \"api.mapbox.com\": No address associated with hostname", "tag": "Mbgl"}

**Comment by chrissnape** [comment]
Did you ever get to the bottom of this? I am also getting this issue, and can't find any other information about it
