### ISSUE TITLE
react-native-mapbox-gl - Mobile Event Listener issue 

### ISSUE THREAD

**Issue by zreaqqasem** [react-native-mapbox-gl/maps#1692]
### IOS Mapbox Navigation SDK version with react-native-mapbox-gl

2.0.0

### Steps to reproduce

We are currently using MapboxNavigation version 0.40.0 in iOS native component in our project which depends on MapboxMobileEvents currently we are trying to upgrade MapboxNavigation to the latest version 2.0.0 using cocoapod. please note that our project is react native project and we use react-native-mapbox-gl in our project which depends on Mapboxmobileevents too.

### Expected behavior

the expected result was to install MapboxNavigation version successfully after change the version in podfille from 
 ` pod 'MapboxNavigation', '~> 0.40.0'`   to   `pod 'MapboxNavigation', '~> 2.0.0'`

but seems there's a conflict between MapboxMobileEvents version for `react-native-mapbox-gl `and `MapboxMobileEvents` for `MapboxNavigation`
### Actual behavior

the result I still get is -> 

```
`[!] CocoaPods could not find compatible versions for pod "MapboxMobileEvents":
  In snapshot (Podfile.lock):
    MapboxMobileEvents (= 0.10.2, ~> 0.10.2)

  In Podfile:
    MapboxNavigation (~> 2.0.0) was resolved to 2.0.1, which depends on
      MapboxMobileEvents (~> 1.0)

    react-native-mapbox-gl (from `../node_modules/@react-native-mapbox-gl/maps`) was resolved to 8.5.0, which depends on
      Mapbox-iOS-SDK (~> 5.9.0) was resolved to 5.9.0, which depends on
        MapboxMobileEvents (= 0.10.2)

```        
        `

### Is this a one-time issue or a repeatable issue?

repeatable

**Comment by ferdicus** [comment]
ok, let's back up... you are trying to upgrade a lib (not this here our repo lib but `mapbox-navigation-ios`) from version `0.40.0` to freaking `2.0.0` (two major version jumps!) with pages of updates/ fixes and breaking changes which you quite obviously didn't read and then are surprised, that stuff isn't working? 

Additionally you probably haven't read the discussion here, about us not supporting v10 of Mapbox Mobile SDKs yet - a _requirement_ for `mapbox-navigation-ios`. 


Can't help you with your problem.
