### ISSUE TITLE
[Question] FreeCamera 3D Terrain 

### ISSUE THREAD

**Issue by dngconsulting** [react-native-mapbox-gl/maps#1696]
Hello,

Do you think that it's possible to implement River Runner showcase with the current React Native Map Box implementation ? =>https://www.facebook.com/Mapbox/posts/1611639419040720 and https://river-runner.samlearner.com/

Thanks for your answers.

Sami

**Comment by ferdicus** [comment]
why wouldn't you link to the blog post that has actual code examples? 
https://www.mapbox.com/blog/river-runner-how-i-built-it

in short: yes
