### ISSUE TITLE
["get","icon"] doesn't work on android

### ISSUE THREAD

**Issue by zhijiec99** [react-native-mapbox-gl/maps#183]
**Describe the bug**
["get","icon"] doesn't work on android
This is my icon style: 
` iconSize: [
                'match',
                ['get', 'icon'],
                'pin',
                1,
                'pickup',
                0.5,
            ],`
**To Reproduce**
^

**Expected behavior**
One icon is half the size of the other.
**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: OnePlus 5T
 - OS: Android Pie
 - SDK Version 28
 - React Native Version 59

**Comment by mfazekas** [comment]
@zhijiec99 
I was not able to repro with our [example app](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/ShapeSourceIcon.js).

With default scale:
```
const styles = {
  icon: {
    iconImage: ['get', 'icon'],

    iconSize: [
      'match',
      ['get', 'icon'],
      'example',
      1.2,
      'airport-15',
      1.2,
      /* default */ 1,
    ],
  },
};
```

![kép](https://user-images.githubusercontent.com/52435/60391388-67264a00-9aed-11e9-9790-b5f121825ddd.png)


With example icon doubled in size:

```
const styles = {
  icon: {
    iconImage: ['get', 'icon'],

    iconSize: [
      'match',
      ['get', 'icon'],
      'example',
      2.4,
      'airport-15',
      1.2,
      /* default */ 1,
    ],
  },
};
```

![kép](https://user-images.githubusercontent.com/52435/60391394-84f3af00-9aed-11e9-918d-4e8a4dde5ff2.png)
