### ISSUE TITLE
[Question] local vector map.

### ISSUE THREAD

**Issue by ethaqnix** [react-native-mapbox-gl/maps#184]
Hi,

I am currently working on a project asking me for an offline map, preferably vectorial.

I'm currently using [react-native-osmdroid](https://github.com/fqborges/react-native-maps-osmdroid) cause [react-native-maps](https://github.com/react-native-community/react-native-maps) need a token. However, I don't think this is a viable long-term solution (limited by react-native maps, osmdroid and a little community).

I've seen on this issue [1607](https://github.com/nitaliano/react-native-mapbox-gl/issues/1607)  (old repo) that v7 should allows using mapbox without token. Is it still relevant?

**Comment by mfazekas** [comment]
@ethaqnix please use issues for bug reporting not questions, stackoverflow should be better place for questions.

The new repo uses new native libraries, so if new native libs require no access token  this lib should not require either. If you see otherwise please submit a bugreport.
