### ISSUE TITLE
@react-native-mapbox-gl_maps:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by dmlitvinov** [react-native-mapbox-gl/maps#188]
**Describe the bug**
**7.0.0 Release candidate 3**
Project build failed on  :@react-native-mapbox-gl_maps:compileDebugJavaWithJavac FAILED

`
> Task :@react-native-mapbox-gl_maps:compileDebugJavaWithJavac FAILED
/Users/.../node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java:103: error: cannot find symbol
        MapboxMap.OnMarkerClickListener, MapView.OnStyleImageMissingListener {
                                                ^
  symbol:   class OnStyleImageMissingListener
  location: class MapView
/Users/.../node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java:168: error: cannot find symbol
        addOnStyleImageMissingListener(this);
        ^
  symbol:   method addOnStyleImageMissingListener(RCTMGLMapView)
  location: class RCTMGLMapView
/Users/.../node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java:670: error: method does not override or implement a method from a supertype
    @Override
    ^
`

**Versions (please complete the following information):**
 - Platfrom: Android
 - SDK Version 28
 - React Native Version 0.59.8

**Comment by danielkeithw** [comment]
i got this also

**Comment by cjrorvik** [comment]
Same here. For us it happens to appear when we are trying to upgrade Lottie from version 2 to version 3

**Comment by mfazekas** [comment]
addOnStyleImageMissingListener is new in mapbox android libs 8.0.0+. Iguess your build.gradle forces an older mapbox android iib.

**Comment by h-assefi** [comment]
I have the same problem
I couldn't understand how to fix this issue
