### ISSUE TITLE
[Discussion] Consider using depfu for dependency updates

### ISSUE THREAD

**Issue by ferdicus** [react-native-mapbox-gl/maps#20]
Quick synopsis:
Depfu is a service that keeps track of your projects dependencies and (based on your rules)  
automatically opens PRs and thus would run the travis ci tests.

https://depfu.com/for-open-source

It is free for open source projects.

**Comment by ferdicus** [comment]
@kristfal, did you have some time to look at this?
We have quite some dev dependencies, this would definitely ease the pain of updating them.

**Comment by kristfal** [comment]
Hey, I will. I’m unavailable for the this and the next week. Once I’m back, I’ll land this and migration (one way or another). Thanks for raising.

**Comment by kristfal** [comment]
Thanks for this tip. Closed via #93.
