### ISSUE TITLE
UserLocation. onUpdate returns different timestamp units on iOS and Android 

### ISSUE THREAD

**Issue by gogolubev** [react-native-mapbox-gl/maps#204]
**Describe the bug**
onUpdate method of MapboxGL.UserLocation has different behavior depending on the platform.

- iOS. onUpdate returns timestamp in seconds.
- Android. It returns timestamp in miliseconds.
 
**To Reproduce**
Nothing special to do. Just log it.

**Expected behavior**
It must be equal on both platforms.

**Screenshots**

**Versions (please complete the following information):**
 - Platfrom: Android, iOS
 - Device: Xiaomi 6A, iPhone X Simulator
 - OS: Android 8.0, iOS 12
 - SDK Version 28
 - React Native Version 59

**Additional context**

**Comment by Spacarar** [comment]
I also experience this issue, and think that both devices should return the same units.
