### ISSUE TITLE
Incorrect MapView typings

### ISSUE THREAD

**Issue by jussirantala** [react-native-mapbox-gl/maps#206]
**Describe the bug**
styleURL prop for MapView can't be set because the typing doesn't allow a string value. The docs says it could be a string. I have the custom style file on my map server.

onPress function doesn't return the event in the typings. The event could be used for multiple things.

**Versions (please complete the following information):**
 - React Native Version: 0.59
 - react-native-mapbox-gl version: 7.0.0-rc3

**Comment by jussirantala** [comment]
https://github.com/react-native-mapbox-gl/maps/pull/146

**Comment by mfazekas** [comment]
Merged: #146

**Comment by jussirantala** [comment]
Still cant set a string as styleURL.
