### ISSUE TITLE
[ANDROID] followPitch is not working

### ISSUE THREAD

**Issue by ethaqnix** [react-native-mapbox-gl/maps#214]
**Describe the bug**
When setting `followUserLocation` at true, followPitch is not working (pitch neither). 

**To Reproduce**
```
<MapboxGL.Camera
     followZoomLevel={16} // that's working
     followPitch={50} // not working
     followUserLocation={true}
     followUserMode={'course'} // compass or normal don't make it work neither
/>
```

**Expected behavior**
I expect `followPitch` to work like  `pitch` when `followUserLocation` but when is set at true 

**Versions (please complete the following information):**
    Platfrom: Android
    Device: Huawei P9 EVA-L09 / Samsung galaxy S7
    OS: android 6 - 8
    SDK Version: 23
    React Native Version : 0.59

**Comment by marucjmar** [comment]
`followPitch`- for IOS
`pitch` - for Android

if I'm not mistaken

**Comment by RichardLindhout** [comment]
It's passed as followUserPitch in the react component + not implemented in the views.

Add following code in RCTMGLCameraManager
```
    @ReactProp(name="followUserPitch")
    public void setFollowPitch(RCTMGLCamera camera, double value) {
        camera.setFollowPitch(value);
    }
```
And in RCTMLCamera
```
    public void setFollowPitch(double pitch) {
        mPitch = pitch;
        updateCameraPositionIfNeeded(true);
    }

```

**Comment by RichardLindhout** [comment]
See following commits in my branch
https://github.com/RichardLindhout/maps/commit/9c096a2fa745d66b46c0d60bd80900e3f3b82d53
https://github.com/RichardLindhout/maps/commit/e1464ae4842517ed27ef2a51e641101b9e773c5b

**Comment by RichardLindhout** [comment]
Not stale!

**Comment by anttijva** [comment]
Any news on this?

**Comment by badaz** [comment]
It seems to me that this 3 year old issue a real dealbreaker, is this 1.4k stars lib not maintained anymore ?
