### ISSUE TITLE
Position not showing

### ISSUE THREAD

**Issue by GigiRewind** [react-native-mapbox-gl/maps#219]
**Describe the bug**
I'm building a geolocation app that needs to track people walking in the street and draw their path as they walk. I'm using react-native-background-geolocation and a kalman filter. The output of which is saved in my state as my coordinates. I'm having issues with my user position, it is not showing. My zoom level is also not working, I don't know what I'm doing wrong ...

**To Reproduce**
**I call set Center at every new coordinate, it works, then nothing happens**
setCenter(location:Location) {
    if (!this.refs.map) { return; }
    this.refs.map.flyTo([location.coords.longitude, location.coords.latitude], 1000)
  }
        <MapboxGL.MapView
          ref="map"
          zoomLevel={16}
          logoEnabled={false}
          style={styles.flex}
          styleURL={MapboxGL.StyleURL.Street}
          showUserLocation={true}
          scrollEnabled={true}
          userTrackingMode={MapboxGL.UserTrackingModes.Follow}
          centerCoordinate = {this.state.coordinates} >
        </MapboxGL.MapView>

**Expected behavior**
I expect to see my GPS point going from one point to another.

**Screenshots**
<img width="346" alt="Screenshot 2019-07-08 at 15 32 50" src="https://user-images.githubusercontent.com/45896668/60814390-d5c27200-a195-11e9-8701-1d7fe41d3cfb.png">

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: Simulator
 - OS: iOS12.2
 - SDK Version [e.g. 22]
 - React Native Version: 0.59

**Additional context**

**Comment by GigiRewind** [comment]
@nitaliano I have read everything I could find, you're my last hope ! Thank you for your help !

**Comment by DejanBesic** [comment]
@GigiRewind Adding user location is slightly different than on https://github.com/nitaliano/react-native-mapbox-gl. You need to add <MapBoxGL.UserLocation /> tag inside your MapBoxGL.MapView. 
Same thing happens with the zoomLevel. You need to change it to MapBoxGL.Camera and add it inside MapView.
` <MapBoxGL.Camera
            ref={(ref) => (this.camera = ref)}
            zoomLevel={10}
            centerCoordinate={[Lng, Lat]}
            animationDuration={2000}
          />`

**Comment by mfazekas** [comment]
please check out CHANGELOG

**Comment by GigiRewind** [comment]
Thank you both for your answers, I did miss the changes in the changelog !

**Comment by fvieira** [comment]
The fact that you need to add `<MapBoxGL.UserLocation />` is missing from the changelog. This had me confused for quite some time... Thanks @DejanBesic for the tip!

**Comment by mingyeom1** [comment]
Can you tell me how you applied the Kalman filter? @GigiRewind
