### ISSUE TITLE
Understanding SymbolLayer

### ISSUE THREAD

**Issue by arnaudambro** [react-native-mapbox-gl/maps#226]
I have a hard time trying to understand how the `SymbolLayer` works, especially the [style prop](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/SymbolLayer.md#styles), especially the properties `iconSize` and `iconImage` seen in [the ShapeSourceIcon example](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/ShapeSourceIcon.js). 
I understand that there is a lot of WIP in this library, especially regarding the doc, and if I have some time I would be glad to help, but in the meantime I need to sort out my transition from `PointAnnotation` to `SymbolLayer`, and I feel it quite hard to understand the way the whole machinery works without documentation...

Thanks for your help !

**Comment by jimjeffers** [comment]
I'm having trouble too. Willing to help update the docs once I get a better understanding of how the SymbolLayer works. I was using the PointAnnotation to render a custom view that was loading an external image from a uri. It's not clear how to do this via the `SymbolLayer`.

**Comment by tomasamado97** [comment]
@jimjeffers Can you tell me how you changed from the PointAnnotation to the SymbolLayer? My app is working with annotations and i want to change since its deprecated. Having a hard time, since i have a lot of points on the map. Thanks

**Comment by justincrich** [comment]
I'm a bit confused too ... would appreciate some explanation on how this new component works as compared to PinAnnotation

**Comment by alex83130** [comment]
Do we have any update on that one ? 
In the documentation It's write that `iconSize`  is a `number` and in the example (`ShapeSourceIcon`) there is that case : 
```
 iconSize: [
      'match',
      ['get', 'icon'],
      'example',
      1.2,
      'airport-15',
      1.2,
      /!* default *!/ 1,
    ]
```
Following the actual docution, I have difficulties to understand how this one should work...
