### ISSUE TITLE
Images/ShapeSource/SymbolLayer makes the app crash

### ISSUE THREAD

**Issue by arnaudambro** [react-native-mapbox-gl/maps#228]
**Describe the bug**
When I try to use Images or ShapeSource or SymbolLayer, the app crashes during the launch.

**To Reproduce**
You can check [this test repo](https://github.com/arnaudambro/mapboxtest), which is a copy-paste of [ShapeSourceIcon example](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/ShapeSourceIcon.js)

`App.js`

```js

import React from 'react';
import { View } from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';
import variables from './env'
import exampleIcon from './assets/example.png';

MapboxGL.setAccessToken(variables.MAPBOX_API_TOKEN);

const styles = {
  icon: {
    iconImage: ['get', 'icon'],

    iconSize: [
      'match',
      ['get', 'icon'],
      'example',
      1.2,
      'airport-15',
      1.2,
      /* default */ 1,
    ],
  },
};

const featureCollection = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4552',
      properties: {
        icon: 'example',
      },
      geometry: {
        type: 'Point',
        coordinates: [-117.20611157485, 52.180961084261],
      },
    },
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4552',
      properties: {
        icon: 'airport-15',
      },
      geometry: {
        type: 'Point',
        coordinates: [-117.205908, 52.180843],
      },
    },
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4552',
      properties: {
        icon: 'pin',
      },
      geometry: {
        type: 'Point',
        coordinates: [-117.206562, 52.180797],
      },
    },
  ],
};

class ShapeSourceIcon extends React.Component {

  render() {
    return (
      <View style={{ flex: 1 }}>
        <MapboxGL.MapView style={{ flex: 1 }}>
          <MapboxGL.Camera
            zoomLevel={17}
            centerCoordinate={[-117.20611157485, 52.180961084261]}
          />
          <MapboxGL.Images
            images={{example: exampleIcon, assets: ['pin']}}
          />
          <MapboxGL.ShapeSource
            id="exampleShapeSource"
            shape={featureCollection}
          >
            <MapboxGL.SymbolLayer id="exampleIconName" style={styles.icon} />
          </MapboxGL.ShapeSource>
        </MapboxGL.MapView>
      </View>
    );
  }
}

export default ShapeSourceIcon;

```

**Expected behavior**
No crash 

**Versions (please complete the following information):**

expo diagnostics:
```
  Expo CLI 2.21.2 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.1 - /usr/local/bin/node
      Yarn: 1.13.0 - ~/.yarn/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      expo-cli: 2.21.2
```

**Comment by mfazekas** [comment]
@arnaudambro pls include stack trace of the crash

**Comment by Alaa-Ben** [comment]
@arnaudambro 
Replacing iconImage: ['get', 'icon'] with iconImage: '{icon}' and deleting iconSize solved this for me.

**Comment by arnaudambro** [comment]
> @arnaudambro pls include stack trace of the crash

@mfazekas actually I don't have a stack trace of the crash actually, the app just quits before showing the map

![image](https://user-images.githubusercontent.com/31724752/60982837-2b834f80-a339-11e9-9fb3-b2d397448bc9.png)

I can show you the console maybe, but not sure it brings anything

![image](https://user-images.githubusercontent.com/31724752/60982880-41911000-a339-11e9-82aa-c0c9bc1f88ad.png)


> @arnaudambro
> Replacing iconImage: ['get', 'icon'] with iconImage: '{icon}' and deleting iconSize solved this for me.

@Alaa-Ben still the same, no stack trace

**Comment by Alaa-Ben** [comment]
@arnaudambro Then maybe it is because icon 'airport-15' does not exist ? try removing any feature containing this icon as property.

**Comment by arnaudambro** [comment]
@Alaa-Ben I changed and kept only the `example` icon, but it still the same.

I could have the minimum of an error stack-trace by launching the build through XCode, and here is what I have:
```

**Comment by arnaudambro** [comment]
@mfazekas I closed the issue but it was a mistake, I didn't want to... the issue is still there !
did you see the stack trace ?

**Comment by arnaudambro** [comment]
I updated to v7.0.1 and it seems to work now

**Comment by peterleng** [comment]
It still happened in 8.0.0, any suggestion?

**Comment by virtumonde** [comment]
It's still happening

**Comment by virtumonde** [comment]
I suspect it was happening because I didn't link my image on iOS side, now it is working

**Comment by dhairyasenjaliya** [comment]
any solution fot this Class MGLFaux3DUserLocationAnnotationView is implemented in both

**Comment by abhi36456** [comment]
Same issue I'm facing,

objc[66543]: Class MGLFaux3DUserLocationAnnotationView is implemented in both /Users/divya/Library/Developer/CoreSimulator/Devices/D067CB6D-683A-4F7B-ADBD-9BD9AA99E3B1/data/Containers/Bundle/Application/5288A4C7-F880-412C-A0E1-87101E54FC87/PointzOfficialApp.app/Frameworks/Mapbox.framework/Mapbox (0x114ba47d8) and /Users/divya/Library/Developer/CoreSimulator/Devices/D067CB6D-683A-4F7B-ADBD-9BD9AA99E3B1/data/Containers/Bundle/Application/5288A4C7-F880-412C-A0E1-87101E54FC87/PointzOfficialApp.app/PointzOfficialApp (0x105ff7498). One of the two will be used. Which one is undefined.
objc[66543]: Class MGLUserLocationHeadingArrowLayer is implemented in both /Users/divya/Library/Developer/CoreSimulator/Devices/D067CB6D-683A-4F7B-ADBD-9BD9AA99E3B1/data/Containers/Bundle/Application/5288A4C7-F880-412C-A0E1-87101E54FC87/PointzOfficialApp.app/Frameworks/Mapbox.framework/Mapbox (0x114ba4e68) and /Users/divya/Library/Developer/CoreSimulator/Devices/D067CB6D-683A-4F7B-ADBD-9BD9AA99E3B1/data/Containers/Bundle/Application/5288A4C7-F880-412C-A0E1-87101E54FC87/PointzOfficialApp.app/PointzOfficialApp (0x105ff75d8). One of the two will be used. Which one is undefined.
objc[66543]: Class MGLUserLocationHeadingBeamLayer is implemented in both /Users/divya/Library/Developer/CoreSimulator/Devices/D067CB6D-683A-4F7B-ADBD-9BD9AA99E3B1/data/Containers/Bundle/Application/5288A4C7-F880-412C-A0E1-87101E54FC87/PointzOfficialApp.app/Frameworks/Mapbox.framework/Mapbox (0x114ba5d68) and /Users/divya/Library/Developer/CoreSimulator/Devices/D067CB6D-683A-4F7B-ADBD-9BD9AA99E3B1/data/Containers/Bundle/Application/5288A4C7-F880-412C-A0E1-87101E54FC87/PointzOfficialApp.app/PointzOfficialApp (0x105ff7628). One of the two will be used. Which one is undefined.
flipper: FlipperClient::addPlugin Inspector
flipper: FlipperClient::addPlugin Preferences
flipper: FlipperClient::addPlugin React
flipper: FlipperClient::addPlugin Network
(lldb) 

Please help, looks like it's annoying
