### ISSUE TITLE
Can we update compass icon positioning and image?

### ISSUE THREAD

**Issue by awdhootlele** [react-native-mapbox-gl/maps#229]
Not a bug.

I was looking for updating the compass icon positioning to middleRight (default is topRight) and the default image but didn't find any documentation around it. 

I noticed that the native methods are present for android(using MapboxMap#getUiSettings) and for [ios](https://github.com/mapbox/mapbox-gl-native/pull/13556).

Is this feature already present on react native side? If not, is this in the roadmap or any workaround?

Thanks!

**Comment by mfazekas** [comment]
See #112,

PR-s wellcome!

**Comment by awdhootlele** [comment]
@mfazekas thanks for quick response!
Any guide on how to add the missing bindings? I don't have a clue on updating native code but any walkthrough / links would help.
