### ISSUE TITLE
Adding custom callouts to SymbolLayer

### ISSUE THREAD

**Issue by Ibeihl** [react-native-mapbox-gl/maps#231]
Since `PointAnnotations` are deprecated, I have not found a good way to add callouts to symbols that I have added to the map using `SymbolLayer`. It doesn't seem like there is any easy way to add custom callouts with similar functionality to `PointAnnotation`s `Callouts`.  I would really love to use mapbox, but if theres no way to easily add markers and callouts, something that should be very simple, it might not be worth it.

Please help me!! I would love to use mapbox!! Implementing some sort of marker component is crucial for making mapbox a great alternative to google maps.

**Comment by mxhryvo** [comment]
What was your solution to implement this feature?

**Comment by winseyli** [comment]
I have the same question too

**Comment by Ibeihl** [comment]
I was able to figure it out finally by using one of the examples from the mapbox docs that can be found here [https://docs.mapbox.com/android/maps/examples/symbol-layer-info-window/](url).

It took me a little bit to get this working, but the general idea, is to use `SymbolLayer` to add two layers on top of the map.  The first layer is a `marker layer` and the second layer is  an `InfoWindow` layer, which is similar to a callout.   You can override the `onMapClick` method and set a `selected` property for each feature (geoJSON point).  The `InfoWindow` layer has a filter on it so it only displays the info window if its associated feature's selected property is true.  

The docs are all a little conflicting, with a lot of the examples using outdated classes etc. but this one works.

**Comment by SethTyemill** [comment]
Same question here too

**Comment by mxhryvo** [comment]
To clear that up a bit, I mailed him and he said that he had to fork the library and customize it for his needs.
