### ISSUE TITLE
Markers disappear on fast zoom out

### ISSUE THREAD

**Issue by GituBojan** [react-native-mapbox-gl/maps#235]
**Describe the bug**
If you use clusters custom markers disappear after a while on zoom. 

`
<MapboxGL.ShapeSource
            id="symbolLocationSource"
            hitbox={{ width: 20, height: 20 }}
            onPress={clickMap}
            shape={featureCollection }
            cluster
            clusterRadius={50}
            clusterMaxZoomLevel={8}
            images={Markers}
        >
            <MapboxGL.SymbolLayer
                id="pointCount"
                style={layerStyles.clusterCount}
            />
            <MapboxGL.CircleLayer
                id="clusteredPoints"
                belowLayerID="pointCount"
                filter={['has', 'point_count']}
                style={layerStyles.clusteredPoints}
            />
            <MapboxGL.SymbolLayer
                id="customSymbolLayerIcon"
                style={{
                    iconImage: '{icon}',
                    iconAllowOverlap: true,
                    textAllowOverlap: true,
                    iconIgnorePlacement: true,
                    textIgnorePlacement: true,
                    iconSize: 0.2,
                }}
            />
        </MapboxGL.ShapeSource>`

We are using custom markers and standard styling for the clusters from the earthQuake example.

**To Reproduce**
It is hard to reproduce as we have not found a clear pattern. It appears rarely but still often enough to be a problem. What we have found out it happens if the app returns from the background and the featureCollection data gets refreshed (we pull new data every 30s). 

**Expected behavior**
Custom markers should not disappear when you zoom in. 

**Screenshots**
![video](https://user-images.githubusercontent.com/33836904/61036375-48676380-a3c9-11e9-963d-1c1a983b6f6e.gif)
I have managed to reproduce it. You see for a while that at a certain zoom levels the markers are shown but after a while even at this zoom level they disappear. 
I have found some similar issues and added 
`
                    iconAllowOverlap: true,
                    textAllowOverlap: true,
                    iconIgnorePlacement: true,
                    textIgnorePlacement: true,`
with no effect on the behaviour. 

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: iPhone XS Max
 - OS: iOS 12
 - SDK Version 7.0.0 rc3 
 - React Native Version 0.59.3

**Comment by GituBojan** [comment]
**To Reproduce**
We managed to narrow down the issue a bit. It happens if you zoom in (lvl 16 and above) and zoom out fast. I suppose settings like removeOutsideVisibleBounds are not rendering markers outside of the viewport. You see some markers fading in and if you do it several times coming from background state the markers disappear and do not appear again. Hard to find the reason for it. Probably it is useful that we have around 100 custom markers rendered.

**Comment by ricardonogues** [comment]
@GituBojan Hi,
Have you found any solution to this?

**Comment by hassanad94** [comment]
Have you found any solution to this ?
