### ISSUE TITLE
Custom WMTS source

### ISSUE THREAD

**Issue by sheburdos** [react-native-mapbox-gl/maps#250]
I have a local geoserver, that has a vector layer, published from Postgis table (polygons). Geoserver has Vector Tiles extension installed and running. 
According [Publishing a GeoServer Layer for use with Mapbox Styles](https://docs.geoserver.org/stable/en/user/styling/mbstyle/source.html) the URL to be used with mapbox style should be like:

"http://localhost:8080/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS
        &VERSION=1.0.0&LAYER=rwanda:stand&STYLE=&TILEMATRIX=EPSG:3857:{z}
        &TILEMATRIXSET=EPSG:3857&FORMAT=application/vnd.mapbox-vector-tile
        &TILECOL={x}&TILEROW={y}"

If I run this URL from the browser - I get the response with MVT.
However, if I supply this style to the MapboxGL.MapView - no errors, and no data shown on the map. Geoserver logs actually contains information that data is requested and served back.
Is it possible to supply WMTS, served from custom geoserver to the map style?

My style
```
{
	"version": 8,
	"name": "test",
	"sprite": null,
	"glyphs": null,
	"created": "2019-05-06T09:15:56.048Z",
	"id": "cjvc5h0c837gd1fohhk8k5iol",
	"modified": "2019-05-15T10:06:08.876Z",
	"metadata": {
		
	},
	"center": [
		0.0,
		0.0
	],
	"zoom": 8,
	"sources": {
		"vstands": {
  			"type": "vector",
  			"tiles": [
    			"http://localhost:8033/geoserver/gwc/service/wmts?REQUEST=GetTile&SERVICE=WMTS&VERSION=1.0.0&LAYER=rwanda:stand&STYLE=&FORMAT=application/vnd.mapbox-vector-tile&TILEMATRIXSET=EPSG:3857&TILEMATRIX=EPSG:3857:{z}&TILECOL={x}&TILEROW={y}"
  			],
		}
	},
	"layers": [
		{
			"id": "vstands",
			"type": "fill",
			"source": "vstands",
			"layout": {
				"visibility": "visible"
			},
			"paint": {
				"fill-color": "#00ffff"
			},
			"metadata": {
				"label": "Stands (master)",
				"category": "overlay"
			}
		}
	]
}
```

**Comment by kylebarron** [comment]
I'm guessing that this didn't work because you were serving on `localhost`, and the browser had access to `localhost`, but the native device didn't?

**Comment by dominikberta** [comment]
Did you solve this?
