### ISSUE TITLE
How to setup VectorSource url to use my own OpenMapTiles server

### ISSUE THREAD

**Issue by 2f-concept** [react-native-mapbox-gl/maps#253]
I've installed a fresh OpenMapTiles server that i could access with the url http://<MY-SERVER-IP>:8080

I tryed to use your example customVectorSource.js

But I can not configure MapboxGl.VectorSource url to use my server.

Coul'd you please give an example using custom OpenMapTiles server ?

Thanks

**Comment by arnaudambro** [comment]
I don't know if it is what you are looking for, but [trying to implement](https://stackoverflow.com/questions/57026012/mapbox-customcss-styles-converted-to-gl-styles-pirates-pencil) some of mapbox raster tiles, somebody redirected me to [mapbox docs](https://docs.mapbox.com/mapbox-gl-js/example/map-tiles/), quite useful, and then a google search drove me to [#6](https://github.com/react-native-mapbox-gl/maps/issues/6), showing me how to implement, which gives something like that:
```js
<MapboxGL.RasterSource {...rasterSourceProps}>
  <MapboxGL.RasterLayer
    id="stamenWatercolorLayer"
    sourceID="stamenWatercolorSource"
    style={{rasterOpacity: .5}}
  />
</MapboxGL.RasterSource>
```

`rasterSourceProps` being
```js
{
  id: 'stamenWatercolorSource',
  url: 'https://api.mapbox.com/v4/mapbox.pirates/{z}/{x}/{y}.png?access_token={access_token},
  tileSize: 256,
}
```

I hope it'll help

**Comment by ethaqnix** [comment]
On your `MapView` `styleURL` props you can specify a json style for your map.

```
<MapboxGL.MapView
          style={{ flex: 1 }}
          styleURL={'asset://style.json'}
        />
```

Your json need to fill this [specifications](https://docs.mapbox.com/mapbox-gl-js/style-spec/)

```
{
  "version": 8,
  "name": "Basic",
  "metadata": {
   ...
  },
  "sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "https://{your url}/data/v3.json"
    }
  },
  "glyphs": "https://{your url}/fonts/{fontstack}/{range}.pbf",
...
}
```

Here is an [issue](https://github.com/nitaliano/react-native-mapbox-gl/issues/630) on niteliano repo where you should find more details
