### ISSUE TITLE
Referencing to a <MapboxGL.Camera /> causes crash

### ISSUE THREAD

**Issue by alisherakb** [react-native-mapbox-gl/maps#254]
**Describe the bug**
When I'm trying to reference a camera to center it to ShapeSource location - the app is crashing.

**To Reproduce**

```
       <MapboxGL.MapView
          style={styles.container}
        >
          <MapboxGL.UserLocation
            visible
            renderMode="normal"
          />
          <MapboxGL.Camera
            ref={ref => (this.camera = ref)}
            followUserLocation
          />
<MapboxGL.ShapeSource
            id="points"
            key={this.props.map.shapeSourceKey}
            shape={geoJSON}
            cluster
            onPress={async event => {
            const { payload } = event.nativeEvent;

             if (payload.properties.cluster) {
            const zoomLevel = await this.map.getZoom();

            const zoom = zoomLevel > 20 ? zoomLevel : 20;

            this.camera.setCamera({
            centerCoordinate: payload.geometry.coordinates,
            zoom,
            duration: 400
           });
            }
            }}
          >
            {this.getSymbolLayersJsx(geoJSON.features, markerStyles)}
          </MapboxGL.ShapeSource>
        </MapboxGL.MapView>
```

**Versions**
 - Platfrom: iOS and Android
 - Device: iPhone7 and Samsung S9
 - OS: iOS 12.2
 - SDK Version 5.1.0
 - React Native Version: 0.59.5

**Comment by mfazekas** [comment]
@alisherakb pls include a stacktrace

**Comment by alisherakb** [comment]
@mfazekas 
Currently I'm testing on iOS. 
As soon as I press on cluster, the JS fps goes down to 0 and after several minutes it crashes.
This behavior happens not only with ShapeSource but whenever I refer to Camera.

The only message I'm receiving from XCode is:
`Message from debugger: Terminated due to memory issue`

Can you try to reproduce?

I'm on master's last commit.

Thanks in advance!

**Comment by allthetime** [comment]
@alisherakb Your onpress function is doing a lot of work. I think you should first try to simplify it and see if the same thing happens. 

I've noticed `async` functions can have some strange side effects in react components and it's good to avoid them when they are unecessary. 

Get rid of `async` and the request for zoom level. Instead of using `setCamera` you can just use `camera.flyTo` or `camera.moveTo` which will preserve the current zoom level anyways.

That's how I move to specific coordinates in my implementation and I have no memory issues.

**Comment by alisherakb** [comment]
@allthetime We've tried to call camera in simple function and with `camera.flyTo`, but same effect :/ 
Can you share a snippet of your code?

**Comment by allthetime** [comment]
@alisherakb have you reproduced it in clean project with nothing but map code and are sure it's not something else entirely? 

Here is how I have implemented it:

```
export default MapView = (props) => {

    const mapRef = useRef(undefined);
    const cameraRef = useRef(undefined);

    const userContext = useContext(UserContext);
    const userLocation = userContext.location && userContext.location.mapCoordinates;

    return (
        <View
            style={[ styles.cover ]}
        >
            <MapboxGL.MapView
                ref={useCallback((r)=>{ mapRef.current = r; })}
                style={{ flex: 1 }}
            >
                <MapboxGL.Camera
                    ref={useCallback((r)=>{ cameraRef.current = r; })}
                />
                { userLocation && <MapboxGL.PointAnnotation
                    id="USER_LOCATION_MARKER"
                    coordinate={ userLocation }
                /> }
            </MapboxGL.MapView>
            <CircleButton
                onPress={() => {
                    if (cameraRef.current) {
                        cameraRef.current.flyTo(userLocation);
                    }
                }}
            />   
        </View>     
    );
};
```

**Comment by mjm918** [comment]
having the same issue. in Android, it does not fly to user's current location. I tried with a ref but it crashes

**Comment by ebarahona** [comment]
Your ref is not updating, use " let cameraRef = ..." instead of "const cameraRef ="
