### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by peerjollux** [react-native-mapbox-gl/maps#257]
**Describe the bug**
I get the the following error when installing and running the app, like described in the guide. As soon as I import Mapbox with `import MapboxGL from "@react-native-mapbox-gl/maps";` I get the following message. Any one knows what's going on?

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/6756753/61455962-3bb4b380-a965-11e9-93ec-e3127c080e52.png)

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: Simulator 10.2.1

**Comment by mfazekas** [comment]
Check the node modules and the xcode project, either @react-native-mapbox-gl/maps is not installed or outdated or not linked in. That code tries to look up `RCTMGLLocationModule` specifically.

**Comment by pmatias** [comment]
@mfazekas could you explain a bit in more detail? I'm running into the same issue and the package is installed via yarn.

**Comment by pmatias** [comment]
I've fixed this by running `pod install` inside the iOS folder. Basically the iOS libraries were missing from the Xcode project.

**Comment by WrathChaos** [comment]
@pmatias I still having this issue, can you help me about that? I cloned the repo, cd to example. Run the "npm i" command and then cd to ios and run the "pod install" command. Then tried to run it on XCode to run into my real device. However, I could not fix this issue. I can run it on simulator with "react-native run-ios" command.

**Comment by pmatias** [comment]
@WrathChaos  Try running `react native link` in your project root and then `pod install` again. The problem for me was that the Xcode project didn't have the maps library linked. 

This is what gave me the clue https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md
