### ISSUE TITLE
ShapeSource and SymbolLayer as PointAnnotation.

### ISSUE THREAD

**Issue by tomasamado97** [react-native-mapbox-gl/maps#266]
**Problem:**
As the docs say PointAnnotation is deprecated and shouldn't be used so I'm trying to switch to ShapeLayer and SymbolLayer. What I'm trying to do is something like this:
![facebook_blog_image_2](https://user-images.githubusercontent.com/45824903/61551484-b7793380-aa2b-11e9-9c7c-a273ce250555.png)
And the number should change dynamically, according to props.
Any tips? I managed to make the chat icon appear but I have no idea how to add the number.
**What I have so far**:
```
const feature = {
type: 'Feature',
id: marker.id,
      geometry: {
        type: 'Point',
        coordinates: [marker.lat, marker.lng],
      },
};
return (
<MapboxGL.MapView style={sheet.matchParent}>
     <MapboxGL.Camera
          zoomLevel={17}
          centerCoordinate={[loc.lat, loc.lng]}
        />
     <MapboxGL.ShapeSource
         id="exampleShapeSource"
         shape={feature}
       >
        <MapboxGL.SymbolLayer id={markerOne + 1} style={{ iconImage: image, iconSize: 1 }} />
    </MapboxGL.ShapeSource>
</MapboxGL.MapView>);
```
Thanks in advance.

**Comment by arnaudambro** [comment]
@tomasamado97 note that you can add a `<View />` as a `<SymbolLayer>` child. Maybe that's how you would put the number.

**Comment by tomasamado97** [comment]
Cool, its working for IOS but for android it doesn't even show.
![Screenshot_20190722_133546](https://user-images.githubusercontent.com/45824903/61648603-2356d880-ac86-11e9-8491-44e505522342.jpg)
**IOS:**
![Screen Shot 2019-07-22 at 1 38 25 PM](https://user-images.githubusercontent.com/45824903/61648671-441f2e00-ac86-11e9-9c60-746f26c3c854.png)

**Comment by Friis1978** [comment]
@arnaudambro did you know how to implement SymbolLayers ?

Is this the way?

`<MapboxGL.ShapeSource
      id="exampleShapeSource"
      shape={featurelist}
      cluster={false}
    >
      <MapboxGL.SymbolLayer id="exampleIconName" style={layerStyles.iconBlue} />
    </MapboxGL.ShapeSource>`

The points are not shown on my map, anyone have a working example ?

**Comment by arnaudambro** [comment]
you can check these examples from the repo:
- [./example/src/examples/CustomIcon.js](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/CustomIcon.js)
- [./example/src/examples/ShapeSourceIcon.js](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/ShapeSourceIcon.js)

**Comment by Friis1978** [comment]
@arnaudambro 
That is the example i tried to use, but somehow the icon does not show on the android mapview.

**Comment by arnaudambro** [comment]
can you show your code ?

**Comment by tomasamado97** [comment]
I can show you my code. I'm having the same issue as @Friis1978. Plus I'm facing the issue that the markers don't update when I change props.
Image is supposed to change, making the marker change.
I also tried adding a key to the shapeSource to make it update when the key changes, to no result.
**Code:**
![Screen Shot 2019-07-23 at 9 29 56 AM](https://user-images.githubusercontent.com/45824903/61712356-80a56500-ad2c-11e9-8b6d-ab37bf0046bc.png)

**Comment by arnaudambro** [comment]
In the `shape` prop of `ShapeSource`, you are passing a feature whereas you should be passing a feature collection, check again the [ShapeSourceIcon example](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/ShapeSourceIcon.js)

**Comment by tomasamado97** [comment]
Still having the same issue, it shows on IOS but it doesn't on Android

**Comment by tomasamado97** [comment]
I was able to make the markers show and change dynamically by using styles on SymbolLayer but now the view with the amount of matches disappeared.

**Comment by Friis1978** [comment]
@tomasamado97 can you show your new code with the symbollayer styles also?

**Comment by tomasamado97** [comment]
I just added:
```const markerStyle= isMarkerOne ? { iconImage: imageOne, iconSize: 0.55 } ? { iconImage: imageTwo, iconSize: 1 };```

And then add it to the SymbolLayer like: 
```
      <Mapbox.SymbolLayer
          id={insideHoneypot.id + 2}
          styles={markerStyle}
       />
```

**Comment by justincrich** [comment]
Which version of this library deprecated ```PointAnnotation```

**Comment by luisfuertes** [comment]
Maybe not related but if use something like const featureCollection = `MapboxGL.geoUtils.addToFeatureCollection()` map dont re-render

U need clone items like:
```
const featureCollection = _.cloneDeep(MapboxGL.geoUtils.addToFeatureCollection(this.state.featureCollection, feature))
    this.setState({ featureCollection })
```

**Comment by dancherb** [comment]
@arnaudambro @tomasamado97 

Are there any docs or examples for adding custom component children (Views) to SymbolLayers? This is a revelation for me but I can't get it working (maybe because of the same Android issue..)

**Comment by Friis1978** [comment]
@dancherb here is an example of use. This is from my code, and it works perfectly.

`renderAllAnnotations() {
    const { userlist } = this.props;

    return (
      <MapboxGL.ShapeSource
        id="symbolLocationSource"
        hitbox={{ width: 20, height: 20 }}
        onPress={this.onActiveClick}
        shape={userlist}
      >
        <MapboxGL.CircleLayer
          id="pointCircles"
          style={{ circleStrokeColor: this.props.colors.btnColor, circleStrokeWidth: 2, circleRadius: 20, circleColor: this.props.colors.white }}
        />
        <MapboxGL.SymbolLayer
          id="pointSymbols"
          aboveLayerID="pointCircles"
          belowLayerID="homeSymbols"
          filter={['==', 'icon', 'point']}
          style={layerStyles.iconBlue}
        />

        <MapboxGL.SymbolLayer
          id="homeSymbols"
          aboveLayerID="pointCircles"
          filter={['==', 'icon', 'home']}
          style={layerStyles.iconHome}
        />
      </MapboxGL.ShapeSource>
    );
  }`

**Comment by kristfal** [comment]
Nice! Would really appreciate this as an example in the project if you’re
up for it.

**Comment by dancherb** [comment]
> 
> 
> @dancherb here is an example of use. This is from my code, and it works perfectly.
> 
> }`
> 
> Perhaps its not what you are looking for afterall, I can see now, that it was children of symbollayer, and about that I dont know, just wanted to give an example of use.

Ah this is standard practice for symbol layers AFAIK - I was looking to avoid a couple issues (with regards to overlapping, custom text etc) by having each symbol layer made up of more complex shapes (instead of only a circle/icon/text) by feeding children into them, like a couple others have suggested in their code. Thanks for the reply nonetheless :)

**Comment by Friis1978** [comment]
@kristfal you're welcome to use the code in the project, but perhaps an example of the layerstyle, and shape should be there too. 

`
// Png images could be any pictures, without background.
import blueLocation from '../assets/location-marker-blue.png';
import blueHome from '../assets/home_blue.png';

renderAllAnnotations() {
const { userlist } = this.props;

return (
  <MapboxGL.ShapeSource
    id="symbolLocationSource"
    hitbox={{ width: 20, height: 20 }}
    onPress={this.onActiveClick}
    shape={userlist}
  >
    <MapboxGL.CircleLayer
      id="pointCircles"
      style={{ circleStrokeColor: this.props.colors.btnColor, circleStrokeWidth: 2, circleRadius: 20, circleColor: this.props.colors.white }}
    />
    <MapboxGL.SymbolLayer
      id="pointSymbols"
      aboveLayerID="pointCircles"
      belowLayerID="homeSymbols"
      filter={['==', 'icon', 'point']}
      style={layerStyles.iconBlue}
    />

    <MapboxGL.SymbolLayer
      id="homeSymbols"
      aboveLayerID="pointCircles"
      filter={['==', 'icon', 'home']}
      style={layerStyles.iconHome}
    />
  </MapboxGL.ShapeSource>
);

const layerStyles = {
  iconHome: {
    iconAllowOverlap: true,
    iconIgnorePlacement: true,
    iconSize: 0.4,
    iconImage: blueHome,
  },
  iconBlue: {
    iconAllowOverlap: true,
    iconIgnorePlacement: true,
    iconSize: 0.4,
    iconImage: blueLocation,
  },
};`

**Comment by horva** [comment]
Here is full example we can include to repository. 

```
import React, { Component } from "react";
import { StyleSheet, View, Text, Image } from "react-native";
import MapboxGL from "@react-native-mapbox-gl/maps";
import sheet from '../examples/styles/sheet';
import exampleIcon from '../examples/assets/example.png';

const point = {
  id: "1",
  lat: 40.723279,
  lng: -73.970895
}

const featureCollection = {
  "type": "FeatureCollection",
  "features": [
    {
      type: "Feature",
      id: point.id,
      properties: {
        id: point.id
      },
      geometry: {
        type: "Point",
        coordinates: [point.lng, point.lat],
      },
    }
  ]
}

export default class App extends Component {

  state = {
    count: 0
  }

  onPress = async () => {
    this.setState((prevState) => ({
      count: prevState.count + 1
    }));
  }

  render() {
    return (
      <MapboxGL.MapView
        style={sheet.matchParent}
      >
        <MapboxGL.Camera
          zoomLevel={10}
          centerCoordinate={[point.lng, point.lat]}
        />
        <MapboxGL.ShapeSource
          id="symbolLocationSource"
          hitbox={{ width: 30, height: 30 }}
          onPress={this.onPress}
          shape={featureCollection}
        >
          <MapboxGL.CircleLayer
            id="pointCircles"
            style={{
              circleStrokeColor: "#0000FF",
              circleStrokeWidth: 2,
              circleRadius: 30,
              circleColor: "#FFFFFF"
            }}
          />
          <MapboxGL.SymbolLayer
            id="teaCup"
            aboveLayerID="pointCircles"
            style={{
              iconImage: exampleIcon,
              iconSize: 1
            }}
          />
          <MapboxGL.CircleLayer
            id="notificationCircle"
            style={{
              circleColor: "#F00",
              circleRadius: 14,
              circleTranslate: [22, -22]
            }}
          />
          <MapboxGL.SymbolLayer
            id="notificationCount"
            style={{
              iconOptional: true,
              textIgnorePlacement: true,
              textField: this.state.count.toString(),
              textSize: 15,
              textMaxWidth: 50,
              textColor: '#FFF',
              textAnchor: 'center',
              textTranslate: [22, -22],
              textAllowOverlap: true
            }}
          />
        </MapboxGL.ShapeSource>
      </MapboxGL.MapView>
    );
  }
}

```

Usage looks like this - count is updated on icon press

![SymbolLayerUpdates](https://user-images.githubusercontent.com/2076080/65965854-94bdbf00-e45f-11e9-93b5-58ee0fd14467.gif)

**Comment by mxhryvo** [comment]
So do you have to render one "notificationCount"-symbolLayer for each point? if you have multiple points on the map that have different notification counters.

**Comment by tomasamado97** [comment]
@mxhryvo I think you need a feature collection for that, and you set a feature for each of the points of the map you want to render. I think there is an example on the docs of the library.

Apart from that I think this has been resolved so I'm closing the issue. If you need any help, feel free to ask me.

**Comment by drik** [comment]
> 
> 
> So do you have to render one "notificationCount"-symbolLayer for each point? if you have multiple points on the map that have different notification counters.

Hi, @mxhryvo, if you want to dynamically display data on symbolLayers, you have to do it like this : 
<MapboxGL.SymbolLayer
            id="notificationCount"
            style={{
              iconOptional: true,
              textIgnorePlacement: true,
              textField: '**{notificationCount}**',
              textSize: 15,
              textMaxWidth: 50,
              textColor: '#FFF',
              textAnchor: 'center',
              textTranslate: [22, -22],
              textAllowOverlap: true
            }}
          />
where **notificationCount** is a property in your features like this : 
   {
      type: 'Feature',
      id: '11',
      properties: {
        icon: 'exempleIcon',
        name: **dynamicValue**
      },
      geometry: {
        type: 'Point',
        coordinates: [-117.205908, 52.180843],
      },
    }

**Comment by arnaudambro** [comment]
@drik I understand the `SymbolLayer` `textField: {notificationCount}` will render the `dynamicValue` value of the `feature:properties:notificationCount`.
But is there a reason why, or does it matter that the `id` for the `SymbolLayer` is `notificationCount` also ?

**Comment by sauhardar** [comment]
@horva , is this functional for Android to or just iOS?
> Here is full example we can include to repository.
> 
> ```
> import React, { Component } from "react";
> import { StyleSheet, View, Text, Image } from "react-native";
> import MapboxGL from "@react-native-mapbox-gl/maps";
> import sheet from '../examples/styles/sheet';
> import exampleIcon from '../examples/assets/example.png';
> 
> const point = {
>   id: "1",
>   lat: 40.723279,
>   lng: -73.970895
> }
> 
> const featureCollection = {
>   "type": "FeatureCollection",
>   "features": [
>     {
>       type: "Feature",
>       id: point.id,
>       properties: {
>         id: point.id
>       },
>       geometry: {
>         type: "Point",
>         coordinates: [point.lng, point.lat],
>       },
>     }
>   ]
> }
> 
> export default class App extends Component {
> 
>   state = {
>     count: 0
>   }
> 
>   onPress = async () => {
>     this.setState((prevState) => ({
>       count: prevState.count + 1
>     }));
>   }
> 
>   render() {
>     return (
>       <MapboxGL.MapView
>         style={sheet.matchParent}
>       >
>         <MapboxGL.Camera
>           zoomLevel={10}
>           centerCoordinate={[point.lng, point.lat]}
>         />
>         <MapboxGL.ShapeSource
>           id="symbolLocationSource"
>           hitbox={{ width: 30, height: 30 }}
>           onPress={this.onPress}
>           shape={featureCollection}
>         >
>           <MapboxGL.CircleLayer
>             id="pointCircles"
>             style={{
>               circleStrokeColor: "#0000FF",
>               circleStrokeWidth: 2,
>               circleRadius: 30,
>               circleColor: "#FFFFFF"
>             }}
>           />
>           <MapboxGL.SymbolLayer
>             id="teaCup"
>             aboveLayerID="pointCircles"
>             style={{
>               iconImage: exampleIcon,
>               iconSize: 1
>             }}
>           />
>           <MapboxGL.CircleLayer
>             id="notificationCircle"
>             style={{
>               circleColor: "#F00",
>               circleRadius: 14,
>               circleTranslate: [22, -22]
>             }}
>           />
>           <MapboxGL.SymbolLayer
>             id="notificationCount"
>             style={{
>               iconOptional: true,
>               textIgnorePlacement: true,
>               textField: this.state.count.toString(),
>               textSize: 15,
>               textMaxWidth: 50,
>               textColor: '#FFF',
>               textAnchor: 'center',
>               textTranslate: [22, -22],
>               textAllowOverlap: true
>             }}
>           />
>         </MapboxGL.ShapeSource>
>       </MapboxGL.MapView>
>     );
>   }
> }
> ```
> 
> Usage looks like this - count is updated on icon press
> 
> ![SymbolLayerUpdates](https://user-images.githubusercontent.com/2076080/65965854-94bdbf00-e45f-11e9-93b5-58ee0fd14467.gif)
