### ISSUE TITLE
In Android map does not auto zoom to current location

### ISSUE THREAD

**Issue by mjm918** [react-native-mapbox-gl/maps#270]
**Describe the bug**
Auto zoom to user's current location is not working on Android. In iOS it works smooth and fine. I am using v7.0.0rc-3.

**Code**
```
                                 <MapboxGL.MapView 
                                        compassEnabled={true}
                                        styleURL={MapboxGL.StyleURL.Light}
                                        style={styles.map} 
                                        userTrackingMode={1}
                                        showUserLocation={true}>
                                        <MapboxGL.Camera 
                                            zoomLevel={16}
                                            centerCoordinate={[this.state.longitude,this.state.latitude]}
                                            followUserMode={"normal"}
                                            followUserLocation={true} />
                                        <MapboxGL.UserLocation />
                                    </MapboxGL.MapView>
```

**Screenshots**
![WhatsApp Image 2019-07-22 at 10 14 17 AM](https://user-images.githubusercontent.com/17846525/61605448-18954700-ac78-11e9-84ee-2e0ff5e0453a.jpeg)

it's in Android

**Expected**
![image](https://user-images.githubusercontent.com/17846525/61605781-a6bdfd00-ac79-11e9-8646-7395bdf9753f.png)

It's in iOS

**Versions (please complete the following information):**
 - Platfrom: [Android]
 - Device: [Samsung S7 Edge]
 - OS: [Android 8]
 - React Native Version [0.59.9]

**Comment by DavidKHahn** [comment]
@mjm918  hello did you use camera?

**Comment by CrisHemswerthThor** [comment]
i am also facing the same issue. Can you help me in getting out of it.
On ios it is working fine but in case of android it is not and shown in the above asked question screenshots.

**Comment by behi1989** [comment]
@mjm918 

Did you get a result?
I have the same problem
Can you help me please?
