### ISSUE TITLE
Camera flyTo, *To methods are gone after fresh install.

### ISSUE THREAD

**Issue by allthetime** [react-native-mapbox-gl/maps#271]
I'm on RN 0.59.x

I just installed v 7.0.0 of this library. 

Last week `camera.flyTo(coordinates)` would do what it should.

Now I just get `camera.flyTo` is not a function and undefined . 

I changed nothing on my end and just reinstalled this library.

I looked into the library code... `ios/RCTMGL/RCTMGLCamera.h` has no reference at all to any kind of flyTo method. In fact, MANY of the camera methods defined in the ios API are just... not there. 

What am I missing here? What has changed?

As a side note, it was working on Android last week, now it is a black screen.

This is really worrying as I'm about to launch an app that heavily relies on this library.

**Comment by allthetime** [comment]
export default MapView = (props) => {

    const mapRef = useRef(undefined);
    const cameraRef = useRef(undefined);

    const userContext = useContext(UserContext);
    const userLocation = userContext.location && userContext.location.mapCoordinates;

    return (
        <View
            style={[ styles.cover ]}
        >
            <MapboxGL.MapView
                ref={useCallback((r)=>{ mapRef.current = r; })}
                style={{ flex: 1 }}
            >
                <MapboxGL.Camera
                    ref={useCallback((r)=>{ cameraRef.current = r; })}
                />
                <MapboxGL.PointAnnotation
                    id="USER_LOCATION_MARKER"
                    coordinate={ userLocation }
                />
            </MapboxGL.MapView>
            <CircleButton
                onPress={() => {
                    if (cameraRef.current) {
                        cameraRef.current.flyTo(userLocation);
                    }
                }}
            />   
        </View>     
    );

**Comment by mfazekas** [comment]
@allthetime pls check the react-native-mapbox-gl version in your `node_modules`

**Comment by allthetime** [comment]
@mfazekas I have tried both 7.0.0 and 7.0.0-rc3, which is what installs if you just do `npm install...`

**Comment by allthetime** [comment]
@mfazekas it turns out there was a yarn.lock file keeping the old nitaliano/ library. I use npm so it's confusing how that happened, but clearly my build system got a bit messed up. Thanks for your response.

**Comment by allthetime** [comment]
@mfazekas 

If I do `grep -r 'flyTo' .` in `node_modules/@react-native-mapboxgl/maps` this is the entire output:

```
./CHANGELOG.md:* MapView#flyTo, MapView#bitBounds, MapView#flyTo, MapView#moveTo, MapView#zoomTo, MapView#setCamera moved to Camera. There is also experimantal properties, to replace those. See [docs/Camera.md](docs/Camera.md)
./docs/docs.json:        "name": "flyTo",
./docs/docs.json:        "docblock": "Map camera will fly to new coordinate\n\n@example\nthis.camera.flyTo([lng, lat])\nthis.camera.flyTo([lng, lat], 12000)\n\n @param {Array<Number>} coordinates - Coordinates that map camera will jump too\n @param {Number=} animationDuration - Duration of camera animation\n @return {void}",
./docs/docs.json:          "\nthis.camera.flyTo([lng, lat])\nthis.camera.flyTo([lng, lat], 12000)\n\n "
./docs/Camera.md:#### flyTo(coordinates[, animationDuration])
./docs/Camera.md:this.camera.flyTo([lng, lat])
./docs/Camera.md:this.camera.flyTo([lng, lat], 12000)
./ios/Mapbox.framework/Headers/MGLMapView.h:- (void)flyToCamera:(MGLMapCamera *)camera completionHandler:(nullable void (^)(void))completion;
./ios/Mapbox.framework/Headers/MGLMapView.h:- (void)flyToCamera:(MGLMapCamera *)camera withDuration:(NSTimeInterval)duration completionHandler:(nullable void (^)(void))completion;
./ios/Mapbox.framework/Headers/MGLMapView.h:- (void)flyToCamera:(MGLMapCamera *)camera withDuration:(NSTimeInterval)duration peakAltitude:(CLLocationDistance)peakAltitude completionHandler:(nullable void (^)(void))completion;
./ios/Mapbox.framework/Headers/MGLMapViewDelegate.h: `centerCoordinate` property or calling `-flyToCamera:completionHandler:`.
./ios/Mapbox.framework/Headers/MGLMapViewDelegate.h: `centerCoordinate` property or calling `-flyToCamera:completionHandler:`.
Binary file ./ios/Mapbox.framework/Mapbox matches
./ios/RCTMGL/CameraUpdateItem.m:        [self _flyToCamera:mapView withCompletionHandler:completionHandler];
./ios/RCTMGL/CameraUpdateItem.m:- (void)_flyToCamera:(RCTMGLMapView*)mapView withCompletionHandler:(void (^)(void))completionHandler
./ios/RCTMGL/CameraUpdateItem.m:    [mapView flyToCamera:nextCamera withDuration:_cameraStop.duration completionHandler:completionHandler];
./javascript/components/Camera.js:    animationMode: PropTypes.oneOf(['flyTo', 'easeTo', 'moveTo']),
./javascript/components/Camera.js:    Flight: 'flyTo',
./javascript/components/Camera.js:   * this.camera.flyTo([lng, lat])
./javascript/components/Camera.js:   * this.camera.flyTo([lng, lat], 12000)
./javascript/components/Camera.js:  flyTo(coordinates, animationDuration = 2000) {
./index.d.ts:        flyTo(coordinates: Array<number>, duration?: number): void;
```

does that look correct?

**Comment by allthetime** [comment]
Ok. The solution was to clean the metro haste map and cache.

I manually deleted everything related to metro in `$TMPDIR`

and then did `npm cache clean --force`
