### ISSUE TITLE
Mapbox.framework file is missing.

### ISSUE THREAD

**Issue by fhenry-tyemill** [react-native-mapbox-gl/maps#273]
**Describe the bug**
The iOS manual install instructions require adding `node_modules/@react-native-mapbox-gl/maps/ios/Mapbox.framework` to `Embedded Binaries`, but this file is not showing up for me.

**To Reproduce**
Ran `npm install @react-native-mapbox-gl/maps --save` in the root folder of my React Native project. 

**Expected behavior**
After doing that, the file `node_modules/@react-native-mapbox-gl/maps/ios/Mapbox.framework` should exist.

**Screenshots**
![Screen Shot 2019-07-23 at 2 59 28 PM](https://user-images.githubusercontent.com/52674111/61750540-89149480-ad5a-11e9-9c58-181fe658c1d2.png)

**Versions:**
 - Platfrom: iOS
 - Device: iPhone X
 - OS: iOS12.4
 - SDK Version [e.g. 22]
 - React Native Version 0.60.3

**Additional context**
npm throws a few errors on running npm install, but I don't think they are relevant. First are a couple of warnings about eslint needing peer dependencies and then there are "3 high security vulnerabilities" that were generated by native-base (my UI library) which I haven't gotten around to fixing yet. 
The deprecated version of this repo seemed to have an issue similar to this [here](https://github.com/nitaliano/react-native-mapbox-gl/issues/263) with a multi-step process for fixing it. I was able to follow this process until step 4 because I couldn't find the file equivalent to `libRCTMapboxGL.a`.

**Comment by mfazekas** [comment]
There is an preinstall step defined in package.json `"npm run fetch:ios:sdk",` and
`"fetch:ios:sdk": "node ./scripts/download-mapbox-gl-native-ios-if-on-mac.js 
5.0.0",`

try to remove `maps` from node_modules then install again and observe what's wrong with preinstall.
