### ISSUE TITLE
Feature request: mgl_interpolate and mgl_step

### ISSUE THREAD

**Issue by noway** [react-native-mapbox-gl/maps#276]
Being able to do stuff like that: https://github.com/mapbox/ios-sdk-examples/blob/ad656dd6015e03d29feb26225397d423cd87b8c6/Examples/Swift/HeatmapExample.swift#L18 is very important I think. Right now have to do it in javascript on render, and it's way too slow

**Comment by mfazekas** [comment]
You should be able to set `heatmapColor` with an "interpolate" or "step" expression. 

https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-interpolate
https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-step

https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-heatmap-heatmap-color
