### ISSUE TITLE
New Contributor Request

### ISSUE THREAD

**Issue by segheysens** [react-native-mapbox-gl/maps#279]
👋  @kristfal @nitaliano @mattijsf 

I'd like to start helping with this repo. My first step will probably be to begin properly tagging issues - can one of you three add me to the repo and/or [React Native Mapbox GL](https://github.com/react-native-mapbox-gl) Github org?

Also, to put it on your radar, there may be an engineer at one of Mapbox's channel partner companies who will also soon be interested in pitching in! ⚒

**Comment by systemlevel** [comment]
@segheysens Hi!  Thanks so much for reaching out to the repo. That would be wonderful and exciting about the Mapbox channel partner.  Hopefully @kristfal @mfazekas @mattijsf can take a look at your request soon.

**Comment by allthetime** [comment]
This library seems to be desperately in need of some upkeep! Tagging issues would be a good start, but we also need people who actually understand how to use the library responding to issues. I'm currently digging in deep so I can get this working the way I need it to and will be putting in pull requests for documentation updates in the coming months after I figure things out.

**Comment by mfazekas** [comment]
@segheysens i've added you to the repo

**Comment by segheysens** [comment]
@mfazekas Thanks! 👋🏼

I agree, @allthetime - I'm starting with issue cleanup to become more familiar with the repository (and make it easier for others to contribute) and hope to start seeing opportunities where I can actually contribute code 😄
