### ISSUE TITLE
Rendering annotations does not work for android

### ISSUE THREAD

**Issue by SethTyemill** [react-native-mapbox-gl/maps#280]
**Describe the bug**
Whenever I try to render a new annotation, I get an error saying that sourceID of a view managed by RCTMGL.SymbolLayer cannot cast a double to string. I have searched through the documentation and could not find where to fix it. Could anyone help me?

**To Reproduce**
Try to render an annotation on an android device. (Not point annotation)

**Expected behavior**
Annotations load properly

**Screenshots**

![image](https://user-images.githubusercontent.com/52678992/61973935-2f9aa880-af9a-11e9-9ca2-97f0d91cd1e9.png)
**Versions (please complete the following information):**
 - Platfrom: Android
 - React Native Version Current

**Additional context**

**Comment by SethTyemill** [comment]
In addition, I have having a lot of trouble having callouts render for the annotations. Could someone show me the basic syntax to do so?

**Comment by mxhryvo** [comment]
Did you find a solution to render callouts for annotations?

**Comment by ansarikhurshid786** [comment]
I am also facing same issue. Anyone have solution ?
