### ISSUE TITLE
Can ImageSource url support Base64?

### ISSUE THREAD

**Issue by chinesejar** [react-native-mapbox-gl/maps#287]
The image which I want to render on ImageSource need specify http header, so I use fetch to download image as blob or base64, but ImageSource url cannot render it. Any solution?

**Comment by mfazekas** [comment]
@chinesejar base64 is not supported at the moment. Please save image to disk and use an `file://` url.

**Comment by SkySails** [comment]
@mfazekas Has this changed during the last years? And if not, what is currently missing for this to work?

I'm currently finding myself in a situation where I need to show an image on the map while avoiding storing it on the device as far as possible, am I out of luck?
