### ISSUE TITLE
componentWillReceiveProps deprecation warning need to refactor to use getDerivedStateFromProps instead

### ISSUE THREAD

**Issue by ryardley** [react-native-mapbox-gl/maps#289]
**Describe the bug**
react-native-mapbox-gl is using componentWillReceiveProps which is a deprecated React API. 

**To Reproduce**
Create a default React Native app and try the following in App.js

```js
import React, { Component } from "react";
import { StyleSheet, View, Text } from "react-native";
import MapboxGL from "@react-native-mapbox-gl/maps";

MapboxGL.setAccessToken("<API KEY>");

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  container: {
    height: 300,
    width: 300,
    backgroundColor: "tomato"
  },
  map: {
    flex: 1
  }
});

export default class App extends Component {
  componentDidMount() {
    MapboxGL.setTelemetryEnabled(false);
  }

  render() {
    return (
      <View style={styles.page}>
        <View style={styles.container}>
          <MapboxGL.MapView style={styles.map} />
        </View>
      </View>
    );
  }
}

```

**Expected behavior**
No warnings or errors

**Screenshots**
![image](https://user-images.githubusercontent.com/1256409/62222187-37e84e80-b3b3-11e9-939f-c0f9c3812664.png)
![image](https://user-images.githubusercontent.com/1256409/62222198-3f0f5c80-b3b3-11e9-8f75-800145d80ed3.png)

**Versions (please complete the following information):**
 - Platfrom: iOS

**Package.json**

```json
{
  "name": "MyErrorTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-mapbox-gl/maps": "^7.0.0-rc3",
    "react": "16.8.6",
    "react-native": "0.60.4"
  },
  "devDependencies": {
    "@babel/core": "^7.5.0",
    "@babel/runtime": "^7.5.0",
    "@react-native-community/eslint-config": "^0.0.3",
    "babel-jest": "^24.1.0",
    "jest": "^24.1.0",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by ryardley** [comment]
Looks like the class might need to be refactored a little although as we are not setting state but causing sideeffects this might be harder/fiddly. We can remove the warning temporarily by renaming the methods to UNSAFE_componentWillReceiveProps.

**Comment by Fuzzyma** [comment]
@ryardley the warning is back. Seems like nobody got around refactoring this class in the last 5 years :D. Maybe now is a better time to tackle it?

**Comment by Miguel-A-Jara** [comment]
Issue is still happening. Using version `@rnmapbox/maps`
