### ISSUE TITLE
[iOS] Code Signing Issue on Distribute App

### ISSUE THREAD

**Issue by riangeofandy** [react-native-mapbox-gl/maps#296]
- Version: 7.0.0-rc3
- RN Version: 0.59

I got an issue with the uploading app to store.
The error message is 'Code signing "Mapbox.framework" failed'
![Screen Shot 2019-08-04 at 1 34 29 pm](https://user-images.githubusercontent.com/4705492/62419119-9ddb1b80-b6bc-11e9-9c30-226d5228da62.png)

## Build phase has been set and run successfully
![1](https://user-images.githubusercontent.com/4705492/62419112-75532180-b6bc-11e9-9ad7-84c3194a4d89.jpg)

## Distribution log
2019-08-04 03:14:24 +0000  /var/folders/nv/djgpql5d4cz05dvpkq49w0900000gn/T/XcodeDistPipeline.QkU/Root/Payload/Couta.app/Frameworks/Mapbox.framework: replacing existing signature
2019-08-04 03:14:25 +0000  /var/folders/nv/djgpql5d4cz05dvpkq49w0900000gn/T/XcodeDistPipeline.QkU/Root/Payload/Couta.app/Frameworks/Mapbox.framework: code object is not signed at all
2019-08-04 03:14:25 +0000  /usr/bin/codesign exited with 1

Anything else that I missed?

**Comment by mfazekas** [comment]
@riangeofandy was it solved? Does https://github.com/react-native-mapbox-gl/maps/issues/310#issuecomment-520232217 helps?

**Comment by riangeofandy** [comment]
@mfazekas Not I haven't solved it. Thank you for the reference. I will try this tomorrow. Been busy with other projects.

**Comment by riangeofandy** [comment]
@mfazekas I have solved the issue. 
The problem was I'm using incorrect architecture: armv7s, armv7, arm64, arm64e, x86_64, i386. 
I reduced it to armv7s, armv7, arm64 and the signing successful.

**Comment by guhan0** [comment]
> @mfazekas I have solved the issue.
> The problem was I'm using incorrect architecture: armv7s, armv7, arm64, arm64e, x86_64, i386.
> I reduced it to armv7s, armv7, arm64 and the signing successful.

My architecture says: $(ARCHS_STANDARD).
Still I'm facing the same problem. @riangeofandy

**Comment by riangeofandy** [comment]
@guhan0 probably it's a different issue? What is the value of your ARCHS_STANDARD?

**Comment by Jfmetcalf5** [comment]
https://github.com/react-native-mapbox-gl/maps/issues/296#issuecomment-702763724
Ditto

**Comment by ferdicus** [comment]
* Open XCode
* Select `Project Navigator` in the upper left icons
* Select you project
* Select the `Build Settings` Tab 
* In the main viewer set `All` | `Combined`
* Go to `Architectures` => `Architectures`
It probably says something like `$(ARCHS_STANDARD)`

Note, this was on XCode 12.2

**Comment by drewjaja** [comment]
Had the same code signing issue and adding this run script phase solved the issue for me https://stackoverflow.com/a/53267826

Also note that Run Script must be placed AFTER Embed Frameworks under Build Phases (click and drag the phase to arrange the order in which they run).

![image](https://user-images.githubusercontent.com/13476269/115705667-2b3e3200-a3b0-11eb-9db1-b59fa8d52f10.png)

**Comment by gregoryalary** [comment]
<img width="1022" alt="Screenshot 2025-01-15 at 22 44 25" src="https://github.com/user-attachments/assets/3a206940-8f4f-4043-9c0c-6bc62ea39e77" />

```
Invalid Signature. Code failed to satisfy specified code requirement(s). The file at path
"VirtualHike.app/Frameworks/MapboxCoreMaps.framework/MapboxCoreMaps" is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/support/code-signing. (ID: b4abd8f7-0b65-4d92-8329-d979f3f737c2)
```

So i stumbled the same problem when trying to publish a app, the issue was that i wasn't signing my app properly.

Generating a certificate and provisioning profile in a more traditional way, fixed my issue. I followed theses ChatGPT instructions : https://gist.github.com/gregoryalary/471d1f321829ee34852d95c97873d579.
