### ISSUE TITLE
Cluster Properties

### ISSUE THREAD

**Issue by RogerParis** [react-native-mapbox-gl/maps#297]
Is this feature available for RN?

In order to do something like this: https://blog.mapbox.com/clustering-properties-with-mapbox-and-html-markers-bb353c8662ba

**Comment by mfazekas** [comment]
See clustering related props at https://github.com/react-native-mapbox-gl/maps/blob/master/docs/ShapeSource.md 
and https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/EarthQuakes.js
