### ISSUE TITLE
SymbolLayer doesn't display special characters or emojis

### ISSUE THREAD

**Issue by arnaudambro** [react-native-mapbox-gl/maps#299]
This is just a copy paste of https://github.com/nitaliano/react-native-mapbox-gl/issues/1407, as I also have the need of displaying an emoji and I can't.

**Comment by mfazekas** [comment]
@arnaudambro i'm closing as this is likely an upstream issue, we cannot do much about - see https://github.com/nitaliano/react-native-mapbox-gl/issues/1407#issuecomment-474594704
