### ISSUE TITLE
[Infra] Publish 7.0.0 to NPM react-native-mapbox and deprecate old repo

### ISSUE THREAD

**Issue by kristfal** [react-native-mapbox-gl/maps#31]
We need to launch this package to NPM and deprecate the old package.

Todo:

[ ] @nitaliano needs to publish and/or grant org ownership of react-native-mapbox on NPM
[ ] We need to deprecate the old repo
[ ] We need to cherry pick fixes that went into the old repo after the fork into this repo

**Comment by HPieters** [comment]
First off, thanks to driving this project forward!

Is there any way I could help with this? For example with the cherry picking off fixes? What was the date of the fork?

**Comment by mfazekas** [comment]
@HPieters this was the last common commit:
![kép](https://user-images.githubusercontent.com/52435/57449934-73b0c380-725d-11e9-9bc7-1fcb5cc4c12e.png)

In general it would be great if people could try this new repo, migrate their app (see [migration notes](https://github.com/react-native-mapbox/maps/blob/master/CHANGELOG.md)), report missing documentation, regressions and usecases that's no longer supported by the new version.

**Comment by kristfal** [comment]
The date of the fork was 8th of April. We have 2 PRs in the old repo that I think we should get in:

https://github.com/nitaliano/react-native-mapbox-gl/commit/41f487cc56506cd3db2bc0c098b75f0203608b26

https://github.com/nitaliano/react-native-mapbox-gl/commit/c3c028f1f05c1e0e3968c41311ff88f5a2cbcfd8

They fix full support for RN59 on iOS and crashes for Android.

**Comment by dsznajder** [comment]
Hey guys, I'm very grateful that you are working on this one. When do you expect to release `7.0.0`?

**Comment by kristfal** [comment]
Hoestly I don’t know. No word from @nitaliano. If I don’t hear anything from him during the week after next, I’ll release it on NPM under a new org name.

**Comment by dsznajder** [comment]
@kristfal Ok, If you would like to get some help with docs / js oriented stuff, just ping me :)

**Comment by kristfal** [comment]
Hey,

no news from @nitaliano. 

I've created the org `react-native-mapbox-gl` on NPM suggest we rename the org here on github and publish under this namespace. Any thoughts? If not, I'll get started fixing it this week/weekend getting a 7.0.0-RC1 out.

(I know we'll need to update quite a few references around in both code and docs, but I think the time for waiting is over.)

@mfazekas and @sfratini, I'll need your NPM usernames to give you publishing rights.

**Comment by mfazekas** [comment]
I'm fine with `react-native-mapbox-gl` 👍  Username is `mfazekas@szemafor.com`

**Comment by kristfal** [comment]
FYI to all subs: I'm renaming org now, you should update your local repo remotes to the new org.

**Comment by darekg11** [comment]
Amazing, thanks for all the work 🚀

**Comment by kristfal** [comment]
@mfazekas feel free to merge infra PR after your  review. I’m out for the next few hours. Wanna see CI pass but have to leave now. I’ll test Travis -> NPM publishing tonight.

**Comment by kristfal** [comment]
This is now done. 7.0.0-RC1 is now on NPM and Github.

**Comment by ferdicus** [comment]
@kristfal thanks for taking care of this! 👏
