### ISSUE TITLE
Sponsor button

### ISSUE THREAD

**Issue by RichardLindhout** [react-native-mapbox-gl/maps#312]
Can we have donations options or some kind for all the hard work?

**Comment by bigsassy** [comment]
100% agree. I feel awful about how much I've contributed to the source code so far, despite this library being the foundation of my company's mobile app. At least let us show our gratitude with our wallets:

https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository

**Comment by mattijsf** [comment]
I'm personally not a huge fan of sponsorship or donations within an open source project. Anything that is of help to a project / community should come in form of contributions which could be as simple as helping out with issues, bug reports, documentation or code contributions.

**Comment by mfazekas** [comment]
I agree with @mattijsf we definetedly dont want to spend time on deciding stuff like how the money is distributed between contributors, etc.

One thing that might or might not make sense is something like bountysource where you can sponsor a specific bugfix/feature.
