### ISSUE TITLE
Follow user mode can't be set

### ISSUE THREAD

**Issue by RichardLindhout** [react-native-mapbox-gl/maps#319]
Bug description
`followUserMode="compass"` changes back to `null` and `followUserLocation` to  `false`

**To Reproduce**
Steps to reproduce the behavior

```
        <Mapbox.MapView
          style={[
            styles.map,
            { height, borderRadius: theme.roundness, overflow: 'hidden' },
          ]}
          scrollEnabled={true}
          zoomEnabled={true}
          //
          pitchEnabled={true}
          rotateEnabled={false}
          //
          compassEnabled={false}
          attributionEnabled={false}
          localizeLabels={true}
          logoEnabled={false}
          styleURL={styleURL}
          mode={Mapbox.UserTrackingModes.FollowWithHeading}
        >
          <Mapbox.Camera
            followZoomLevel={config.initialZoomLevel}
            followUserLocation={true}
            followUserMode={'compass'}
            onUserTrackingModeChange={onUserTrackingModeChange}
          />

          <Mapbox.UserLocation visible animated />
        </Mapbox.MapView>
```

```
const onUserTrackingModeChange = useCallback(event => {
    event.persist()
    console.log(event)
```

onUserTrackingModeChange result after init
```
nativeEvent:
  payload:
     followUserLocation: false
     followUserMode: null
  type: "usertrackingmodechange"
```

**Expected behavior**
I want to have the same view as in the Mapbox Android example
![Screenshot_20190814-151204](https://user-images.githubusercontent.com/6492229/63024161-f2457e80-bea6-11e9-8577-ee643c79231d.jpg)

**Screenshots**
![Screenshot_20190814-152001](https://user-images.githubusercontent.com/6492229/63024222-1739f180-bea7-11e9-8f5c-5db0832936de.jpg)
I get the wrong heading, no compass on the user location an no following in the rotation of the map.

**Versions:**
 - Platform: Android
 - Device: Oneplus A6003
 - OS: Android 9 
 - React Native Version: 0.60.4

**Context**

UPDATE: after some digging and in RCTMGLCamera and disabling:
```
        MapboxMap.CancelableCallback cameraCallback = new MapboxMap.CancelableCallback() {
            @Override
            public void onCancel() {
//                mUserTrackingState = UserTrackingState.CHANGED;
            }

            @Override
            public void onFinish() {
//                mUserTrackingState = UserTrackingState.CHANGED;
            }
        };
```
It works! Seems like tracking change should not be changed too quick.
updateUserLocationSignificantly
updateUserLocationIncrementally

**Comment by grant1842** [comment]
I wanted to add that only commenting out the onFinish line for updateUserLocationSignificantly worked for me as well.

Instead of modifying the core library, I was also able to get rid of the issue by setting the followUserMode property to a state variable that is false by default.  When the map is fully rendered with my current zoom and coordinates, I set the followUserLocation state variable to true.  Seems to work well so far.

`
state = {
    followUserLocation: false,
}
<MapboxGL.MapView
    style={styles.map}
    onDidFinishRenderingMapFully={(r) => {
        this.setState({followUserLocation: true})
    }}
>
<MapboxGL.Camera                        
    zoomLevel={16}
    followZoomLevel={16}
    followUserLocation={this.state.followUserLocation}
    followUserMode={MapboxGL.UserTrackingModes.FollowWithCourse} <---
/>
</MapboxGL.MapView>`

**Comment by ldunklee** [comment]
I'm struggling to get the compass arrow to show up on the user location point with either of these solutions.  @grant1842 did what you provided above create the arrow/fan effect on the user location disk?

**Comment by RichardLindhout** [comment]
@ldunklee Set this to true https://github.com/react-native-mapbox-gl/maps/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCamera.java#L65

**Comment by ldunklee** [comment]
Thanks @RichardLindhout .  Is there an equivalent for ios?

**Comment by RichardLindhout** [comment]
I'm looking into it ;)

Op vr 27 sep. 2019 22:38 schreef Linda Dunklee <notifications@github.com>:

**Comment by RichardLindhout** [comment]
https://github.com/mapbox/mapbox-gl-native/blob/ios-v5.4.0/platform/ios/src/MGLMapView.h#L479

**Comment by RichardLindhout** [comment]
Looks like we need to set this somewhere

**Comment by RichardLindhout** [comment]
```
if (map == nil && _map) {
        _map.useNativeUserLocationAnnotationView = NO;
        _map.showsUserLocation = NO;
    } else if (map) {
        map.useNativeUserLocationAnnotationView = YES;
        // Toggle off/on showsUserLocation in order for Mapbox to invalidate the
        // current (hidden) user location annotation view. See also: HiddenUserLocationAnnotationView
        map.showsUserLocation = NO;
        map.showsUserLocation = YES;
    }

    _map = map;
```

Probably @mattijsf could help us, because he made this pull request https://github.com/react-native-mapbox-gl/maps/pull/215

**Comment by RichardLindhout** [comment]
@mattijsf Do you know how to enable this on iOS, and build the library. I don't know how to change the source code and building a new cocoapods dep.

**Comment by RichardLindhout** [comment]
Pull request done for iOS: https://github.com/react-native-mapbox-gl/maps/pull/526
