### ISSUE TITLE
onRegionIsChanging is not working on Android.

### ISSUE THREAD

**Issue by irfanshaikh138** [react-native-mapbox-gl/maps#323]
The onRegionIsChanging event is not working for me in android. I am trying to call onRegionIsChanging to get the heading value but it gets called only when the compass heading is zero. For ios, there is no issue.
```
 <MapboxGL.MapView
          onRegionIsChanging={this.onRegionIsChanging}
          onRegionDidChange={this.onRegionDidChange}
          ref={c => (this._map = c)}
          onPress={this.onPress}
          style={{ flex: 1 }}
        >
          <MapboxGL.Camera
            zoomLevel={9}
            centerCoordinate={[-73.970895, 40.723279]}
          />
        </MapboxGL.MapView>

 onRegionIsChanging() {
    const map = await this._map;
    console.log(
      "onRegionIsChanging event",
      map.state.region.properties.heading
    );
  }
```

```
   "@react-native-mapbox-gl/maps": "^7.0.1",
   "react-native": "^0.59.9"
```

I am trying to get heading value from onRegionIsChanging event (event.properties.heading ).
Is there a way to get the heading value as the user rotates/moves the chart?

**To Reproduce**
checkout my [repo](https://github.com/irfanshaikh138/mapboxgl-test) in that I have used the GetZoom example(search for GetZoom.js).It also presents in the mapbox gl example code.

**Comment by dorthwein** [comment]
It is definitely spotty on when the events and how.  A way I got around this was to wrap the map in a view with touch events, then call the `getCenter()` or in your case it would be `getZoom()` on pan move.  Seemed to respond much faster.

**Comment by irfanshaikh138** [comment]
Is there a way to get the heading value as the user rotates/moves the chart? 
I am using onRegionIsChanging event, it gets called for ios when the user rotates/moves the chart but that is not happening for the android(called only on heading value zero).

Basically , all I wanted is to get the heading value as the user rotates/moves the chart.

**Comment by ethaqnix** [comment]
Can you use onRegionWillChange ? looks like heading value is updated in there and you can decide the frequency this event is triggered.

**Comment by kristfal** [comment]
This should be a fairly good first issue to contribute with. You can start by looking at the [region payload](https://github.com/react-native-mapbox-gl/maps/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java#L1021), see if the heading (or bearing) is present in the change handler and follow the stack upwards:

**Comment by frankrowe** [comment]
On android, this library is currently using [MapView.OnCameraIsChangingListener](https://docs.mapbox.com/android/api/map-sdk/8.2.1/com/mapbox/mapboxsdk/maps/MapView.OnCameraIsChangingListener.html) which doesn't fire consistently while the map is moving.

I tried using [MapboxMap.OnMoveListener](https://docs.mapbox.com/android/api/map-sdk/8.2.1/com/mapbox/mapboxsdk/maps/MapboxMap.OnMoveListener.html) instead and it seems to work well.

Here is my commit making that change: https://github.com/frankrowe/maps/commit/66737f43d2812cb3fb8e4879bbd437df9765e40d

**Comment by mahyali** [comment]
Has the fix been merged yet?

**Comment by kristfal** [comment]
@mahyali, no. 

@frankrowe feel free to open a PR. Any idea why those listeners exist? What is the difference? 

If it is more stable, can you migrate all camera events `onWillChange`, `onDidChange` and `onIsChanging` to use the new Android events and open a PR?

**Comment by frankrowe** [comment]
@kristfal I'm not 100% sure what the difference is. I will make a PR and let folks test it out

**Comment by kristfal** [comment]
Can you guys give #367 a go?

**Comment by grant1842** [comment]
So far so good.  The onRegionDidChange seems to be working more consistently so far.

**Comment by kristfal** [comment]
Prior the callback would only fire on programmatic events. Now they also fire on user gestures.
