### ISSUE TITLE
Implement a solution to retrieve the cluster leaves of a cluster

### ISSUE THREAD

**Issue by mikeslinkman** [react-native-mapbox-gl/maps#329]
I think this would benefit a lot of devs trying to handle some action happening when a user clicks on one of the clusters on a map. An example can be to move to a page displaying all the information contained within a cluster. I might be oversimplifying this in my head but the code required mostly already exists in RN code. Since you can click on a cluster and get information from the cluster. The only thing that might need to be ported would be a method that is defined as such in the Android SDK:

`
features = mMapboxMap.queryRenderedFeatures(pixel, layers);
 GeoJsonSource source = mMapboxMap.getStyle().getSourceAs(ROUTE_SOURCE_ID);
`

Then we could use the following methods (using Android in this example) to retrieve all the children.

`
for (Feature feature : features) {
   FeatureCollection collection = source.getClusterLeaves(feature, 100,0);
}
`

Again I might be oversimplifying this in my head but as far as I can imagine (with a little native experience) everything except for the last method `#getClusterLeaves` is already there.

**Comment by pavlo-paliychuk-insighty** [comment]
I would also really appreciate this logic

**Comment by frankrowe** [comment]
These methods exist in the sdks and should be straightforward to add to ShapeSource

Android [GeoJsonSource.getClusterLeaves](https://docs.mapbox.com/android/api/map-sdk/8.2.1/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.html#getClusterLeaves-com.mapbox.geojson.Feature-long-long-)
iOS [MGLShapeSource.leavesOfCluster](https://docs.mapbox.com/ios/api/maps/5.2.0/Classes/MGLShapeSource.html#/c:objc(cs)MGLShapeSource(im)leavesOfCluster:offset:limit:)

**Comment by mikeslinkman** [comment]
Could you share any pointers on how to achieve something like this? Would this require me to do something on the native side of things? For Android I'll probably be able to do so but when it comes to the iOS side of things it will become less trivial for me. Thanks in advance

**Comment by mfazekas** [comment]
@mikeslinkman i think it would be implemented in a similiar way to VectorSource#features  see https://github.com/react-native-mapbox-gl/maps/pull/308/files

**Comment by mikeslinkman** [comment]
I'll take a look at this thanks
