### ISSUE TITLE
Purpose of access_token function on RCTMGLModule.java file

### ISSUE THREAD

**Issue by p1r-a-t3** [react-native-mapbox-gl/maps#339]
I see there is a getAccessToken function on that file. 

> @ReactMethod
>     public void getAccessToken(Promise promise) {
>         WritableMap map = Arguments.createMap();
>         map.putString("accessToken", Mapbox.getAccessToken());
>         promise.resolve(map);
>     }

What is the purpose of this access token? If I am using a custom map, can I send my access token through this? what is the overall purpose of the writeable class?

[I am not an android developer. I am writing the custom map.]

**Comment by kristfal** [comment]
If you use the official mapbox styles, you'll need a mapbox access token to access those maps. This function simply requests the access token you specified in case you need it.

You can't send your accessToken through it, and afaik, the underlying SDKs only sends accessTokens when they are directed to use official mapbox styles.

I don't follow your question about writeable class. I guess you mean WriteableMap, which is a hashMap like a javascript object.
