### ISSUE TITLE
How to add images to the map?

### ISSUE THREAD

**Issue by markfried96** [react-native-mapbox-gl/maps#342]
With mapbox-gl I can use `mapboxgl.Map().addImage(Image)` in my React project to add (multiple) SVG images inside the map. I tried the same with the react-native-mapbox-gl package but unfortunately I had no success... 

Is there any other method to archive this kind of task? In my styleURL I define the needed icons and inside the project I have to feed the image data to the map. 

Thanks for any help.

**Comment by nazarTrynko** [comment]
@markfried96 have you found a solution for this?

**Comment by markfried96** [comment]
@nazarTrynko unfortunately I didn't found a solution to use addImage like in mapbox-gl. We ended adding the image files as assets in the iOS project and then loading the files like this (inside the `<MapboxGL.MapView />` component): 

`<MapboxGL.Images images={{assets: ['image1', 'image2', 'image3', 'image4']}} />`

Maybe that will help you too.
