### ISSUE TITLE
Adding multiple Layers (same type) and Styling them differently

### ISSUE THREAD

**Issue by dalisalvador** [react-native-mapbox-gl/maps#352]
Hi, 
I'm trying to style lines taken from the same source, with a different color. Sound pretty simple but I can't find a way to do it. 
Using the following code:
```

        <MapboxGL.ShapeSource id="myLines" shape={geoJson}>
          {myLines.map((line, i) => (
            <MapboxGL.LineLayer
              key={i}
              id={line.id}
              style={{
                lineColor: line.color,
                lineWidth: 3,
              }}
            />
          ))}
        </MapboxGL.ShapeSource>
```

as a result, ALL lines are styled with the same color as the last line from the array

Also tried filtering:

```
        <MapboxGL.ShapeSource id="myLines" shape={geoJson}>
          {myLines.map((line, i) => (
            <MapboxGL.LineLayer
              key={i}
              id={line.id}
              filter={[
                 '==',
                 '$id',
                 line.id,
               ]}
              style={{
                lineColor: line.color,
                lineWidth: 3,
              }}
            />
          ))}
        </MapboxGL.ShapeSource>
```

But the  result is a single line rendered (the last one from the array)

Any ideas what's wrong??

Thanks!

**Comment by kristfal** [comment]
I think I see what you are trying to do. The solution is to do the following:

Embed the color you want for each line in the geojson source property. Eg line 1 has property color: ‘red’ and line to has color: ‘yellow’. 

From there you declare a single layer for all lines and define color style as an expression with ‘get’ from the color prop. I think there should be examples of this in the example app.

**Comment by kristfal** [comment]
Here is a good example: https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/DataDrivenCircleColors.js
