### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by SaimAhmedSheikh** [react-native-mapbox-gl/maps#354]
**Describe the bug**
this error occurs on npm install:

> '.' is not recognized as an internal or external command,
> operable program or batch file.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! react-native-mapbox-gl-demo@1.0.0 pack:gl: `./scripts/npm_pack_rngl.sh`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the react-native-mapbox-gl-demo@1.0.0 pack:gl script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**To Reproduce**
In example folder, run npm install.

**Expected behavior**
Install all dependencies

**Screenshots**
![image](https://user-images.githubusercontent.com/40424655/64077349-362ee500-cce9-11e9-913f-541da393dfba.png)

**Versions (please complete the following information):**
 - Platfrom: Windows 10
 - Device: PC
 - OS: Windows 10
 - SDK Version [e.g. 22]
 - React Native Version: latest

**Comment by kristfal** [comment]
We don't support windows officially, so the scripts may not work properly there. Happy to accept a PR to fix this.

**Comment by lrpinto** [comment]
I was having this error in WSL Ubuntu. I think is due to control characters. I have opened the script in VS code and changed CRLF to LF with the utility in bottom status bar. Then the script './scripts/npm_pack_rngl.sh ran.

I have got a different error now `maps/example/node_modules/react-native-safe-area-view: Appears to be a git repo or submodule`

It does not seems to be related, so I will search about this one now...

**Comment by tomo54321** [comment]
I too, had this error running Windows 10 however I managed to get the sh scripts to run by running them within [Git Bash](https://gitforwindows.org/) and altering the scripts in the `package.json` file.

To get them to run replace the following
```json
"pack:gl": "./scripts/npm_pack_rngl.sh",
"clean:node:modules": "./scripts/clean_node_modules.sh",
```
to
```json
"pack:gl": "bash ./scripts/npm_pack_rngl.sh",
"clean:node:modules": "bash ./scripts/clean_node_modules.sh",
```

Then cd into the example directory and run `npm install` within Git Bash.
