### ISSUE TITLE
Build gradle fail

### ISSUE THREAD

**Issue by crosskpixel** [react-native-mapbox-gl/maps#355]
I installed mapbox using the document provided in this repository, however I am getting this error, I have done several searches, but none of the solutions was possible, has anyone gone through this?
`
Gradle sync failed: Timeout waiting to lock file hash cache (/home/igor/Documentos/Projetos/van/react-native-firebase-starter/android/.gradle/5.4.1/fileHashes). It is currently in use by another Gradle instance.
				Owner PID: 4973
				Our PID: 31554
				Owner Operation: 
				Our operation: 
				Lock file: /home/igor/Documentos/Projetos/van/react-native-firebase-starter/android/.gradle/5.4.1/fileHashes/fileHashes.lock
				Consult IDE log for more details (Help | Show Log) (1 m 4 s 334 ms)
`

**Comment by kristfal** [comment]
Reboot your system.

**Comment by crosskpixel** [comment]
@kristfal did not work, I did this, and also invalidated the cache and restarted android studio several times :/

**Comment by kristfal** [comment]
Sorry, I’m out of ideas then. The build works for a lot of people and on our CI, so this is likely an issue with your gradle setup and not this repo.

**Comment by crosskpixel** [comment]
I was able to solve yesterday, the problem was due to my negligence and stuck, I'm currently using ubuntu 19.04 and installed android studio but .. I left the AS files in the Downloads folder, and for some reason if this problem, changed the AS to / opt / ... and the issue has been resolved. Thanks for listening.
