### ISSUE TITLE
[Android] Events delays and inconsistensies

### ISSUE THREAD

**Issue by kristfal** [react-native-mapbox-gl/maps#368]
**Describe the bug**
While investigating #367, I noticed duplicate RegionDidChange logged on the javascript side. Logging on native side did not reveal any duplications.

There is also a significant delay between RegionDidChange on the Android native side and the JS side (+1 sec) running on a fast emulator.

**To Reproduce**
1) Log regionDidChange events on the JS side using the regionDidChange example
2) Log the equivalent events in `handleMapChangedEvent` in `RCTMGLMapView.java` 

**Expected behavior**
Short delay and no duplications on JS side

**Screenshots**

**Versions (please complete the following information):**
 - Platfrom: Android

**Comment by kristfal** [comment]
I'm now unable to reproduce this on latest master for Android.

**Comment by Brlja** [comment]
I'm observing up to 1 second delay on ShapeSource onPress event.
This delay is observable on Android and iOS.

Map has only one point loaded and delay is the same so it is not related to data load.

**Comment by kristfal** [comment]
Is this dev or release mode?

**Comment by Brlja** [comment]
It's in dev mode. We are using detached expo (expo kit).

čet, 14. stu 2019. 21:53 Kristian Fallrø <notifications@github.com> je
napisao:

> Is this dev or release mode?
>

**Comment by Brlja** [comment]
I found a similar ticket on old page:
https://github.com/nitaliano/react-native-mapbox-gl/issues/1464
