### ISSUE TITLE
Loading tiles from local source

### ISSUE THREAD

**Issue by ospfranco** [react-native-mapbox-gl/maps#370]
Hey I've been trying to load a local set of tiles, I've been following a string of pearls now but nothing seems to work so far.

I started with this 2 sources:

https://stackoverflow.com/questions/39045059/how-can-i-use-asset-for-non-apk-files-on-android-in-a-mapbox-gl-style

https://github.com/nitaliano/react-native-mapbox-gl/issues/1248

They both seem to suggest loading a local set of tiles is possible, I've been trying different combinations now, trying to load both local tilesets and a sample url tileset, but I've gotten nowhere so far.

My style.json:

```
const styleJSON = {
      "version": 8,
      "name": "Foo",
      "sources": {
        "mapbox": {
          "type": "raster",
          "url": `file://${RNFS.DocumentDirectoryPath}/tile.json`
        }
      },
      "layers": [{
        "id": "background",
        "type": "background",
        "paint": {
          "background-color": "#0A0"
        }
      }, {
        "id": "water",
        "type": "fill",
        "source": "mapbox",
        "source-layer": "water",
        "paint": {
          "fill-color": "#00A"
        }
      }]
    }
```

and my tile.json:

```
const tileJSON = {
      "tilejson": "2.1.0",
      "name": "Layer name",
      "description": "Layer Description",
      "version": "1.0.0",
      "attribution": "attribution",
      "scheme": "xyz",
      "tiles": [
        "https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg" // Known to be working url, needs to be replaced with local path for local tile set, ex: file://path/to/{x}-{y}-{z}-tile.png
      ],
      "minzoom": 0,
      "maxzoom": 11,
      "bounds": [
        -180,
        -85.05112877980659,
        180,
        85.0511287798066
      ]
    }
```

the render code:
```
    const rasterSourceProps = {
      id: 'capmo',
      url: `file://${RNFS.DocumentDirectoryPath}/tile.json`,
      tileSize: 256,
    };

    return (
      <Container>
        <Mapbox.MapView style={{ flex: 1 }} styleURL={`file://${RNFS.DocumentDirectoryPath}/style.json`}>
          <Mapbox.RasterSource {...rasterSourceProps}>
            <Mapbox.RasterLayer
              id="capmoLayer"
              sourceID={'capmo'}
            />
          </Mapbox.RasterSource>
        </Mapbox.MapView>
```

Along many many variations of that, (also omitting the raster layer)

This is all I get:

<img width="487" alt="Screenshot 2019-09-05 at 20 29 47" src="https://user-images.githubusercontent.com/1634213/64406361-e56d1280-d081-11e9-8449-6ca7338270a6.png">

**Expected behavior**
I want to load a local set of tiles (or even remote at this point) when I declare the styleURL and a custom tileJSON file.

In the snippet above I'm trying to display a tile set from a URL I'm sure it works, but my end goal is to replace the `tiles` property from a http url, to a local file://

**Versions (please complete the following information):**
 - Platfrom: Android, iOS
 - Device: iPhone6
 - OS: 12
 - SDK Version 7.0.1
 - React Native Version 0.59.9

**Comment by bigsassy** [comment]
A few questions:

1. Did you try using `asset://` instead of `file://` for iOS?  In the stackoverflow question you link to above, I was only having trouble with Android displaying the files using `asset://`. iOS had been working fine for me.

2. The files your trying to use, are you sure they work?  In other words, do they render correctly from when loaded via URL from a different library (like a webpage using https://github.com/alex3165/react-mapbox-gl)?

3. Have you played with whether the files are stored on the device still gzipped? My memory is hazy on this, but I think that was one thing that bit me in the butt (or that the files are stored uncompressed and I had them compressed).

**Comment by ospfranco** [comment]
1. I did not try asset:// yet, but I think that wouldn't be a solution right? it needs to work for both android and iOS

2. Yes, when I do the following:

```
 const rasterSourceProps = {
      id: 'capmo',
      url: 'https://link/to/my/file/{z}/{x}/{y}/tile.png',
      tileSize: 256,
    };

    return (
      <Container>
        <Mapbox.MapView style={{ flex: 1 }} styleURL={`file://${RNFS.DocumentDirectoryPath}/style.json`}>
          <Mapbox.RasterSource {...rasterSourceProps}>
            <Mapbox.RasterLayer
              id="stamenWatercolorLayer"
              sourceID={'capmo'}
            />
          </Mapbox.RasterSource>
        </Mapbox.MapView>
```

The tile is correctly loaded, only when trying to use a local file is that this stops working

3. They are not gzipped, they are stored as they are

**Comment by ethaqnix** [comment]
I think this is the same issue as [issue 253](https://github.com/react-native-mapbox-gl/maps/issues/253).

arnaudambro's solution or mine should work for you.

**Comment by ospfranco** [comment]
I got it working, but the solution was not straightforward, here is my final `style.json`:

```
const styleJSON = {
      "version": 8,
      "name": "Capmo",
      "sources": {
        "mapbox": {
          "type": "raster",
          "tiles": [
            "file:///Users/osp/Library/Developer/CoreSimulator/Devices/73F89F92-56BC-4136-8A36-FBCB65DB4E29/data/Containers/Data/Application/6C3CC3DC-DC53-42F7-8E83-E3B15735A968/Documents/capmofiles/14097c3a-c8f0-11e9-b467-ef9e2430e227/148ab246-c8f0-11e9-b473-738ce35cb242/{z}-{x}-{y}-tile.png"
          ],
          "tileSize": 256
        }
      },
      "layers": [{
        "id": "plan",
        "type": "raster",
        "source": "mapbox",
      }]
    }
```

and on the react-native component:

```
<Mapbox.MapView style={{ flex: 1 }} styleURL={`file://${RNFS.DocumentDirectoryPath}/style.json`}>
</Mapbox.MapView>
```

As you see, I will dynamically create this json, based on which raster tile set I want to load, closing this issue, thanks for the help!
