### ISSUE TITLE
Allow snapshots without logo

### ISSUE THREAD

**Issue by kristfal** [react-native-mapbox-gl/maps#371]
**New feature**
Allow snapshots from remote sources without logo.

**Additional Context**
Android provides API for this. iOS doesn't.

**Comment by segheysens** [comment]
Hi @kristfal - removing the Mapbox watermark from a static map requires an Enterprise agreement. There is [more information about Mapbox attribution here](https://docs.mapbox.com/help/how-mapbox-works/attribution/), but do you have a particular situation that you're earmarking this feature for?

It would typically be against our Terms of Service without an exception, and this admittedly seems like a lower priority item than implementing a lot of other functionality that exists in our native libraries but isn't yet in the React Native library.

**Comment by kristfal** [comment]
@segheysens see the upstream ticket for use case. It is valid according to TOS and I’ve already added feature support for Android in a PR a few days ago while fixing the iOS snapshot manager. 

This ticket is open to track upstream iOS support so we can have feature parity in the RN wrapper.

**Comment by kristfal** [comment]
Still waiting for upstream support.

**Comment by kristfal** [comment]
Still waiting.

**Comment by ferdicus** [comment]
valid issue, go away stalebot

**Comment by virtumonde** [comment]
stalebot go away
