### ISSUE TITLE
Disable continuous world

### ISSUE THREAD

**Issue by ospfranco** [react-native-mapbox-gl/maps#372]
**Describe the bug**
The javascriptSDK seems to allow to disable world wrapping: https://docs.mapbox.com/mapbox.js/example/v1.0.0/disable-world-wrapping/

But it doesn't seem possible with this SDK, I've scoured around the docs, tried to set a camera with bounds:

```
        <Mapbox.MapView
          style={{ flex: 1 }}
          styleURL={`file://${RNFS.DocumentDirectoryPath}/style.json`}
          logoEnabled={false}
        >
          <Mapbox.Camera
            bounds={{
              ne: [80, 170],
              sw: [-80, -170],
            }}
            animationDuration={300}
            maxZoom={19}
            pitch={60}
          />
        </Mapbox.MapView>
```

But I can still scroll infinitely within the mapview

**Expected behavior**
Being able to turn of world wrapping

**Screenshots**
![Screenshot 2019-09-06 at 13 43 54](https://user-images.githubusercontent.com/1634213/64425610-7a850100-d0ac-11e9-9e0f-368efb474d1f.png)

**Versions:**
Platfrom: Android, iOS
Device: iPhone6
OS: 12
SDK Version 7.0.1
React Native Version 0.59.9

**Comment by kristfal** [comment]
Happy to accept PRs for this. Relevant documentation:

[Android](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/camera/RestrictCameraActivity.java)

and

https://docs.mapbox.com/ios/maps/examples/constraining-gestures/

**Comment by segheysens** [comment]
I was about to recommend the examples that @kristfal shared 😄 @ospfranco note that this library is a wrapper for the native iOS and Android libraries, not any web libraries.

The `bounds` prop is for setting the current bounds of the map, not necessarily the maximum/minimum bounds that a user can navigate to. As you can see in the examples above, that's custom logic that takes overriding the Camera's default functionality and checks whether the new center is inside of the restricted bounds.

**Comment by segheysens** [comment]
@ospfranco Also, it looks like you're setting the bounds to cover nearly the entire map - are you georeferencing this image to cover the entire world?

**Comment by ospfranco** [comment]
Hey! thanks for the reply.

Yes, I know this library is a wrapper for the native libraries, I also came across the provided examples when I was researching how to tackle this issue, so I'm aware of the custom logic, however like you realized, the image is covering the entire map.

The image is a raster tile set, I set it via style json, and did not add any geo reference, just let the sdk take care of handling the bounds, here is the basic code:

```
    // We have the titles locally stored on device, just take one of the file uris and prepare it for mapbox
    let tilesUrl = this.props.plan.getTilesUris().zoomLevels[0].tiles[0].uri;
    tilesUrl = tilesUrl.replace('0-0-0-tile.png', '{z}-{x}-{y}-tile.png');

    const styleJSON = {
      version: 8,
      name: 'Capmo',
      sources: {
        mapbox: {
          type: 'raster',
          tiles: [tilesUrl],
          tileSize: 256,
        },
      },
      layers: [
        {
          id: 'plan',
          type: 'raster',
          source: 'mapbox',
        },
      ],
    };

    await RNFS.writeFile(
      `${RNFS.DocumentDirectoryPath}/style.json`,
      JSON.stringify(styleJSON),
      'utf8',
    );
  }
```

later in the render function:

```
        <Mapbox.MapView
          ref={this.mapRef}
          style={{ flex: 1 }}
          styleURL={`file://${RNFS.DocumentDirectoryPath}/style.json`}
          onRegionWillChange={this.regionDidChange}
        >
          <Mapbox.Camera
            bounds={this.props.mapBounds}
            animationDuration={300}
          />
        </Mapbox.MapView>
```

I guess I could add bounds to the style json when adding the raster set and then apply the custom logic? I'll give it a go, and let you know how it goes

**Comment by ospfranco** [comment]
It seems setting bounds on the stylejson bound property for the layer does not affect rendering at all, the tile set is still displayed completely over the entire world, any other options?

**Comment by ospfranco** [comment]
So, I ended up implementing a very simple bound checking algorithm, it kinda works, but it definitely not smooth and sometimes you can still escape the bounding limits (because the tileset is covering the entire map).

Here is the code:

```
private regionIsChanging = (regionFeature: any) => {
    const { initialBounds, setInitialBounds } = this.props;

    /**
     * Visible bounds is array of to LNG/LAT coordinates
     * [0]: is the north east corner
     * [1]: is the south west corner
     */

    const visibleBounds: any = regionFeature.properties.visibleBounds;

    if (!initialBounds) {
      setInitialBounds(visibleBounds);
      return;
    } else {
      /**
     * Remember latitude is vertical (ex: germany is in a high positive latitude)
     * and longitue is horizontal (ex: south america is in a negative longitude)
     * 
     * We need to disable world wrapping, which is not possible in the RN, ios and android mapbox sdks
     * So this is a very simple proof to prevent the user from scrolling where he is not supposed to
     */
      const ne = visibleBounds[0];
      const sw = visibleBounds[1];

      const initialNe = initialBounds[0];
      const initialSw = initialBounds[1];
      /**
       * Another remark, only horizontal infinite scrolling is happening, so we only need to check the longitude
       */
      // NE corner difference to bounding box
      const neDiff = ne[0] - initialNe[0];
      // SW corner difference to bounding box;
      const swDiff = sw[0] - initialSw[0];

      // console.warn('neDiff', neDiff, 'swDiff', swDiff);



      if (neDiff > 0 || swDiff < 0) {
        const camera = this.cameraRef.current!;


        if (neDiff > 0) {
          // basically move camera to the left, until it fits the bounds
          const newNe = [ne[0] - neDiff, ne[1]];
          const newSw = [sw[0] - neDiff, sw[1]];
          const center = [(newNe[0] + newSw[0]) / 2, (newNe[1] + newSw[1]) / 2];

          camera.moveTo(center, 100)
        }

        if (swDiff < 0) {
          // console.warn('setting camera bounds 2');
          // basically move camera to the right, until it fits the bounds
          const newNe = [ne[0] - swDiff, ne[1]];
          const newSw = [sw[0] - swDiff, sw[1]];
          const center = [(newNe[0] + newSw[0]) / 2, (newNe[1] + newSw[1]) / 2];


          camera.moveTo(center, 100)
        }
      }
    }
  }
```

```
<Mapbox.MapView
          ref={this.mapRef}
          style={{ flex: 1 }}
          styleURL={`file://${RNFS.DocumentDirectoryPath}/style.json`}
          logoEnabled={false}
          onRegionIsChanging={this.regionIsChanging}
        >
          <Mapbox.Camera
            animationDuration={100}
            ref={this.cameraRef}
          />
        </Mapbox.MapView>
```
