### ISSUE TITLE
Cannot change icon image based on points attributes. CRASHES without trace

### ISSUE THREAD

**Issue by SethTyemill** [react-native-mapbox-gl/maps#373]
**Describe the bug**
![image](https://user-images.githubusercontent.com/52678992/64454627-4dcaec80-d0a0-11e9-91ca-33f78522839d.png)
I am attempting to change the Icon on my symbol layer based on attributes from my points. I am unable to do this because it results in a crash every time. I was able to do this successfully changing the text color.

**Versions (please complete the following information):**
 - Platfrom: IOS
 - Device: IPhone X
 - React Native Version: Current

**Comment by kristfal** [comment]
Connect Xcode debugger and show log output.

**Comment by SethTyemill** [comment]
![image](https://user-images.githubusercontent.com/52678992/64463360-98586300-d0b8-11e9-924b-dc5ee00eddb7.png)
Here is the output I received. I see that it is erroring because I am passing in a number for the image since that is how react handles preloading image locations.

**Comment by SethTyemill** [comment]
And if I toString() the image, the application will run but no icons appear and the points are invisible to the user

**Comment by mfazekas** [comment]
@SethTyemill see #358
