### ISSUE TITLE
Setting scrollEnabled to false while the map is being dragged doesn't freeze the map

### ISSUE THREAD

**Issue by tayyabshabab** [react-native-mapbox-gl/maps#377]
**Describe the bug**
Setting `scrollEnabled` property is working fine in normal scenarios. However, the issue arises when scrolling was already started and then `scrollEnabled` is set to `false`, it doesn't freeze the map right away but only after the dragging is finished.

![field-drawing](https://user-images.githubusercontent.com/1446474/64481831-537e1a80-d1e5-11e9-9732-26fc1e27b980.gif)

I am working on this field drawing thing and when a user taps and drag the marker the boundary of field should be updated but the map should not move. I am setting the `scrollEnabled` property to `false` but since the tap was already detected on map it starts to drag and doesn't freeze. Any help would be highly appreciated.

**To Reproduce**
Setting `scrollEnabled` to `false` while dragging the map doesn't freeze the map

**Versions:**
 - Platfrom: Android
 - Device: All android phones
 - React Native Version: 0.59

**Comment by kristfal** [comment]
The solution here is likely to call an interrupt on all gestures when we switch to scrollEnabled false. 

See https://docs.mapbox.com/android/maps/overview/gestures/

Happy to accept a PR for this.

**Comment by tayyabshabab** [comment]
@kristfal Thanks for the suggestion. I am going to create a PR for this.
