### ISSUE TITLE
[iOS] onRegionDidChange not called after camera.setCamera

### ISSUE THREAD

**Issue by Gp2mv3** [react-native-mapbox-gl/maps#380]
**Describe the bug**
The function passed as props in onRegionDidChange isn't called after a setCamera on iOS.

**To Reproduce**
call setCamera() and add a log in onRegionDidChange.

**Expected behavior**
The log is displayed after the movment is finished. It's not the case.

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: iPhone Xr & 6s at least (not relevant I think)
 - OS: 12.4.1
 - React Native Version 0.60.3

**Additional context**
I'll try to create a PR for that issue tomorrow if I find time. I think it's related to https://github.com/react-native-mapbox-gl/maps/issues/368

**Comment by kristfal** [comment]
That is weird, we use this quite actively in production on 7.0.4. and I haven’t experienced anything like this on iOS.

Would be awesome if you could build a minimum reproduction based off the regionChange example. I’ll have a look at #368 next week btw.

**Comment by L-Yeiser** [comment]
I am seeing this on ios
