### ISSUE TITLE
onRegionDidChange is not called when location changed with followUserLocation

### ISSUE THREAD

**Issue by parkdcom** [react-native-mapbox-gl/maps#385]
**Describe the bug**
The onRegionDidChange callback is not called when the location changes when followUserLocation is on. Only when you move the map interactively it is called. The callsbacks for onRegionIsChanging and onRegionWillChange are fired properly

Not sure if this is a duplicate for #380

Did not test on android.

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: Simulator
 - React Native Version 0.59.4
 - Version library: 7.0.4

**Comment by kristfal** [comment]
@parkdcom please check on latest version, I believe it should be fixed via #413
