### ISSUE TITLE
zIndex support

### ISSUE THREAD

**Issue by calypsow777** [react-native-mapbox-gl/maps#392]
Is there a way to force a specific layer to always be on top ?

**Comment by One-Q** [comment]
I'm looking for this feature too. It would be great

**Comment by kristfal** [comment]
You can use belowLayerId and aboveLayerId to specify the order. Is this what you are looking for?

**Comment by Gp2mv3** [comment]
The problem with belowLayerId and aboveLayerId is that if there are, let's say, a bunch of layers that we want to be displayed above a bunch of other layers, it'll become a mess pretty rapidly, no ?

With a zIndex like, we could set zIndex to 1000 for one of the group and 10 for the second one without any issue.

**Comment by kristfal** [comment]
While I understand the use case, I don't think there is any kind of concept of zIndex in the [style spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/). Support for this would mean:

1) A request to Mapbox for updating the style spec
2) Wait for Mapbox to implement zIndex for iOS and Android SDKs
3) Expose zIndex in the react native wrapper

If you manage to get the ball rolling on this (file a ticket at the [native SDK repo](https://github.com/mapbox/mapbox-gl-native/issues)), we're happy to support this on the RN side if it makes it into the native side. If this happens, open an issue here and we'll make sure it gets added.

**Comment by frankrowe** [comment]
I wonder if `layerIndex` could serve this purpose? The problem right now, as far as I can tell, is that if you specify a layer index that's larger than the amount of layers on the map, you get an index out of bounds crash. Could we change that so that if you put a layer index of 9999, it would insert the layer at the end of the array?
