### ISSUE TITLE
[SymbolLayer] iconAllowOverlap not working when textField exists

### ISSUE THREAD

**Issue by arnaudambro** [react-native-mapbox-gl/maps#393]
**Describe the bug**
On a `SymbolLayer`, when the `iconAllowOverlap` property is set along with the `textField` property, the  `iconAllowOverlap` is not working anymore.

**To Reproduce**
In the `CustomIcon` example, add any `textField` you want in the `styles.icon` object and see that the `iconAllowOverlap` is not working anymore.

**Expected behavior**
All the icons should overlap even with a `textField` property defined.

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: any
 - OS: any
 - SDK Version: 7.0.4
 - React Native Version: 0.59

**Comment by kristfal** [comment]
I don’t remember on top of my head the details, but I believe you’ll need to add textAllowOverlap in addition when you pass a text string. There is also a prop for allowing icon to be shown without text iirc. Reopen if this doesn’t work.

**Comment by arnaudambro** [comment]
I didn't see that `textAllowOverlap` prop, perfect thanks !

**Comment by lpfunding** [comment]
@kristfal do you have any idea how you would customize textField to include an icon? I want to do something like this:

textField: [littleImage + ['get', 'name']]

**Comment by kristfal** [comment]
You should use symbol layer with text/icon offsets.
