### ISSUE TITLE
Enable iconAllowOverlap only "within" a symbol layer, so symbols from different layers can overlap?

### ISSUE THREAD

**Issue by dancherb** [react-native-mapbox-gl/maps#394]
Currently, if you have multiple symbol layers within a ShapeSource and set `iconAllowOverlap: false` on both layers (or even just one), only one symbol will show if a symbol from one layer collides with a symbol from another layer. I'm looking to only disallow overlap between symbols in the same layer.

My use case: effectively, I want to render 2 images per feature (e.g. each feature has a background and a marker, and I don't want to compile individual images for every variation). I want to disable iconAllowOverlap when features clash with each other, but I don't want the background and marker of the same feature to clash. (I'm currently planning on using careful image sizes/padding to ensure a background clashes with another background and fades out at the same time as its corresponding marker clashes with the corresponding marker for this other background and also fades out. This is a bit hacky, so alternative solutions about how to render two icons for one feature would be appreciated!

Simplified example:

```              
               <Mapbox.MapView >
                    <Mapbox.ShapeSource
                        id='items'
                        shape={this.state.featureCollection}
                    >
                        <Mapbox.SymbolLayer
                            id="backgrounds"
                            style={{
                                iconImage: ["get", "backgroundIcon"],
                                iconAllowOverlap: false, 
                            }}
                        />

                        <Mapbox.SymbolLayer
                            id="markers"
                            style={{
                                iconImage: ["get", "markerIcon"],
                                iconAllowOverlap: false,
                            }}
                        />
                    </Mapbox.ShapeSource>
                </Mapbox.MapView>
```

**Comment by kristfal** [comment]
As far as I know, this is not possible with the way Mapbox handles styling. Any solution to this (composite symbols) would have to be implemented upstream in the native iOS and Android libraries.

I suggest you post a ticket in mapbox-gl-native repo. If/once support is in from the native side, please open a ticket here and we’ll expose the feature in the react native wrapper.

**Comment by dancherb** [comment]
Observation:

If both layers have iconAllowOverlap: false, only the second layer shows.

If the first layer has iconAllowOverlap: false and second layer has iconAllowOverlap: true, only the second layer shows.

If the first layer has iconAllowOverlap: true and the second layer has iconAllowOverlap: false, _then both layers successfully overlap_. When items on the second layer clash with other items on the second layer, the fade effect occurs successfully - however, this is not the case for items on the first layer (which do overlap without fading).

I guess this is also more explainable by mapbox-gl-native but maybe someone here will have some insight/find this helpful nonetheless :)
