### ISSUE TITLE
3D MapView 

### ISSUE THREAD

**Issue by HemanthSurimani** [react-native-mapbox-gl/maps#395]
![Screenshot_20190920-100206~2](https://user-images.githubusercontent.com/40192235/65299775-84b7fc80-db8e-11e9-9a2f-47430abca8e1.png)

How can i enable 3D mapview?
@Kristian Fallrø @Nick Italiano

**Comment by kristfal** [comment]
This is an issue tracker, not a place for seeking general purpose help. Use stackoverflow for those things.

**Comment by HemanthSurimani** [comment]
Thanks for your quick reply..!

i Checked every where is there any option to enable 3d map View in react-native-mapbox-gl  ?

**Comment by taylorjosephgriffin** [comment]
@HemanthSurimani did you ever figure this out? i've been workin on trying to get 3d maps to work for days.

**Comment by systemlevel** [comment]
@taylorjosephgriffin Are you suggesting this is a new feature in the iOS SDK from Mapbox?

**Comment by taylorjosephgriffin** [comment]
@systemlevel what do you mean? I was suggesting that I was having a hard time figuring out how to get a 3D view map with this package. But I got it working using mapbox studio.

**Comment by systemlevel** [comment]
@taylorjosephgriffin That's great to hear.  I was curious what you meant by "3D".  Are you just referring to the 3D models that can be placed or are you referring to a new 3D mapping feature highlighted by mapbox :

<img width="1441" alt="Screen Shot 2019-10-28 at 9 01 18 PM" src="https://user-images.githubusercontent.com/894983/67734279-3801e580-f9c6-11e9-8516-42a07a767b7d.png">

**Comment by taylorjosephgriffin** [comment]
@systemlevel i was actually just referring to using height data to show 3D buildings

**Comment by shoaib2527** [comment]
@taylorjosephgriffin  Can you share any link or snip, how and where to add mapbox studio styles in this package.
Thanks in advance.

**Comment by kbvac** [comment]
any solution for this ?

i got this black screen when i use custom style uri 
![Simulator Screenshot - iPhone 15 - 2024-06-09 at 11 19 05](https://github.com/rnmapbox/maps/assets/38617811/2ca8209d-d6c9-4e09-9d64-a42696ac08c1)
