### ISSUE TITLE
Superimpose multiple images for one icon

### ISSUE THREAD

**Issue by arnaudambro** [react-native-mapbox-gl/maps#397]
Hi there,
Is it possible to superimpose two images for one `SymbolLayer` - and if it is, how ? - to create some pins like the one used in Mapstr (a colored background and thematic foreground)  ?

![image](https://user-images.githubusercontent.com/31724752/65305054-7d8af180-db82-11e9-9ef9-96c9080171d3.png)

**Comment by kristfal** [comment]
It is possibly using two different symbol layers, one for background and one for foreground. However you would have to disable clustering (set both iconAllowOverlap and iconIgnorePlacement to true) , so icons will collide when they overlap.
