### ISSUE TITLE
SymbolLayer icons are not visible on Android

### ISSUE THREAD

**Issue by alexandrethorigny** [react-native-mapbox-gl/maps#403]
**Describe the bug**
SymbolLayer icons aren't visible on Android devices (on iOS, no problem).

_iOS_
![Simulator Screen Shot - iPhone Xʀ - 2019-09-23 at 16 08 20](https://user-images.githubusercontent.com/46195850/65433455-54d25880-de1d-11e9-9823-5465f5870cda.png)

_Android_
![Screenshot_1569247703](https://user-images.githubusercontent.com/46195850/65433462-5a2fa300-de1d-11e9-9c47-10c1a85e2296.png)

**To Reproduce**
Bellow, the code I used.

`import * as React from 'react';
import { View, Image } from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';
import Axios from "axios";

import museum from './map_musee.png'
import uncategorized from './map_uncategorized.png';

MapboxGL.setAccessToken("***");

const layerStyles = {
    icoMuseum: {
        iconAllowOverlap: true,
        iconIgnorePlacement: true,
        iconSize: 0.4,
        iconImage: museum,
    },
    icoUncategorized: {
        iconAllowOverlap: true,
        iconIgnorePlacement: true,
        iconSize: 0.4,
        iconImage: uncategorized,
    },
};

class App extends React.Component {

    state = {
        markers: {}
    };

    updateClusters = async (values) => {
        const searchRegion = {
    		params: {
    			ne_lat: values.properties.visibleBounds[0][1],
    			ne_lng: values.properties.visibleBounds[0][0],
    			sw_lat: values.properties.visibleBounds[1][1],
    			sw_lng: values.properties.visibleBounds[1][0],
    			lat: 47.383333,
    			lng: 0.683333,
    		}
    	};

    	await Axios({ method: "post", url: "***", data: searchRegion.params })
        .then( (responseJson) => {
    		console.log("updateClusters function - responseJsonMap : ", responseJson.data);
            this.setState({
                markers: responseJson.data,
            });
    	})
    	.catch( (error) => {
    		alert("Erreur serveur, veuillez réessayer ultérieurement");
    	});
    }

    render() {
        return (
            <View style={{ flex: 1 }}>
                <MapboxGL.MapView
                    ref={c => (this._map = c)}
                    zoomEnabled
                    style={[{ flex: 1 }]}
                    styleURL={'mapbox://styles/mapbox/streets-v9'}
                    onRegionDidChange={ (values) => this.updateClusters(values) }
                >
                    <MapboxGL.Camera 
                        centerCoordinate={[0.683333, 47.383333]}
                        zoomLevel={12}
                    />
                    <MapboxGL.ShapeSource
                        id="shapedatas"
                        shape={this.state.markers}
                    >
                        <MapboxGL.SymbolLayer id="singlePoint" filter={['!=', 'marker', 'uncategorized']} style={layerStyles.icoMuseum} />
                        <MapboxGL.SymbolLayer id="singlePoint" filter={['==', 'marker', 'uncategorized']} style={layerStyles.icoUncategorized} />
                    </MapboxGL.ShapeSource>
                </MapboxGL.MapView>
            </View>
        );
    }
}

export default App;`

And an extract of the API:

`{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    0.6897966266,
                    47.3832740784,
                    3.5
                ]
            },
            "properties": {
                "name": "Musée du Compagnonnage",
                "marker": "uncategorized",
            },
            "id": "PCUCEN0370000163"
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    0.7366718054,
                    47.4087562561,
                    3.5
                ]
            },
            "properties": {
                "name": "Chapelle Saint-Georges",
                "marker": "uncategorized",
            },
            "id": "PCUCEN0370000125"
        }
    }
}`

**Versions**
React Native Version: 0.60.5
@react-native-mapbox-gl/maps: 7.0.4

**Comment by mfazekas** [comment]
Please use the Images component. We should be deprecating the use of direct images as at iconImage.

**Comment by alexandrethorigny** [comment]
Sorry, I tried but it didn't work.
Do you mean like this ?

<MapboxGL.SymbolLayer ... >
<Image src={...} />
</MapboxGL.SymbolLayer>

**Comment by Spillane** [comment]
Seems like this might be your issue? https://github.com/react-native-mapbox-gl/maps/issues/300
