### ISSUE TITLE
Getting warning Message while installing app.

### ISSUE THREAD

**Issue by saurabh-nandan** [react-native-mapbox-gl/maps#409]
**Describe the bug**
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - @react-native-mapbox-gl/maps: https://github.com/react-native-mapbox-gl/maps#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

**Comment by kristfal** [comment]
Duplicate of #391. Closing.
