### ISSUE TITLE
Unable to use Camera without followUserLocation

### ISSUE THREAD

**Issue by alexiri** [react-native-mapbox-gl/maps#41]
I'd like to set the bounds of a map with the Camera component, but the Camera component doesn't seem to work unless you define followUserLocation like this:

```
<MapboxGL.Camera
  followUserLocation
...
```
Setting `followUserLocation={false}` stops the map from showing any tiles on Android, although things in SymbolLayer still seem to show up. Curiously, `followUserLocation={true}` also has the same behavior.

**Comment by mfazekas** [comment]
@alexiri  can you clarify your issue? A concrete example would be the best.

The FitBounds example doesn't use `followUserLocation` and it works:

https://github.com/react-native-mapbox/maps/blob/18fc03c73fb208612e2a6713fdefa489cb57163c/example/src/examples/FitBounds.js#L57-L61

**Comment by kristfal** [comment]
Closing as issue is stale.

**Comment by martinezguillaume** [comment]
Same for the prop `heading`, it only works if I specify the prop `followUserLocation` to true
