### ISSUE TITLE
[iOS] Images very slow to load on real device

### ISSUE THREAD

**Issue by arnaudambro** [react-native-mapbox-gl/maps#412]
**Describe the bug**
The loading of `Images` is very slow on a real device. In my app, I need to load a full emojis keyboard, and it takes ages on a real device.

**To Reproduce**
Download the images from this repo https://github.com/arnaudambro/mapbox-rn-images.
Put the folder in the `exmaple/src/assets` folder.
In any example, add the images to the map. 
Example with `CustomIcon.js`, you can copy/paste the whole following code:

```js
import React from 'react';
import {Text} from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

import sheet from '../styles/sheet';

import BaseExamplePropTypes from './common/BaseExamplePropTypes';
import Page from './common/Page';
import Bubble from './common/Bubble';
import myImages from '../assets/myImages'; // to add

const styles = {
  icon: {
    iconImage: ['get', 'icon'], // to modify
    iconAllowOverlap: true,
  },
};

class CustomIcon extends React.Component {
  static propTypes = {
    ...BaseExamplePropTypes,
  };

  constructor(props) {
    super(props);

    this.state = {
      featureCollection: MapboxGL.geoUtils.makeFeatureCollection(),
    };

    this.onPress = this.onPress.bind(this);
    this.onSourceLayerPress = this.onSourceLayerPress.bind(this);
  }

  async onPress(e) {
    const feature = MapboxGL.geoUtils.makeFeature(e.geometry);
    feature.id = `${Date.now()}`;
    feature.properties = {};
    feature.properties.icon = 'smiley01';

    this.setState({
      featureCollection: MapboxGL.geoUtils.addToFeatureCollection(
        this.state.featureCollection,
        feature,
      ),
    });
  }

  onSourceLayerPress(e) {
    const feature = e.nativeEvent.payload;
    console.log('You pressed a layer here is your feature', feature); // eslint-disable-line
  }

  render() {
    return (
      <Page {...this.props}>
        <MapboxGL.MapView
          ref={c => (this._map = c)}
          onPress={this.onPress}
          style={sheet.matchParent}
        >
          <MapboxGL.Camera
            zoomLevel={16}
            centerCoordinate={[-73.970895, 40.723279]}
          />
         {/* to add */}
          <MapboxGL.Images images={myImages} />
          <MapboxGL.ShapeSource
            id="symbolLocationSource"
            hitbox={{width: 20, height: 20}}
            onPress={this.onSourceLayerPress}
            shape={this.state.featureCollection}
          >
            <MapboxGL.SymbolLayer
              id="symbolLocationSymbols"
              minZoomLevel={1}
              style={styles.icon}
            />
          </MapboxGL.ShapeSource>
        </MapboxGL.MapView>

        <Bubble>
          <Text>Tap to add an icon</Text>
        </Bubble>
      </Page>
    );
  }
}

export default CustomIcon;
```
**Expected behavior**
For a good UX, it is necessary that `Images` loads faster, especially when the images are not fetched from the internet, but exist locally.

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: iPhone SE
 - OS: iOS12.4.1
 - SDK Version 7.0.4
 - React Native Version 0.59.9

**Comment by kristfal** [comment]
Hey,

this is an extreme use case for two reasons: 

1) You are loading hundreds of images
2) Each image is very high res

I honestly don't think we will or even can do do anything to support this. 

If you do want to pursue this, I'd recommend building a custom sprite sheet with your images. That way you'll load those spites on startup. Keep in mind that there are size limitations for these sprites, so you'll need to drastically reduce image size and potentially also image count.

See:
https://docs.mapbox.com/studio-manual/examples/custom-icon/
https://docs.mapbox.com/help/glossary/sprite/

**Comment by arnaudambro** [comment]
@kristfal thanks for the tips, I am gonna look !

Though I don't agree with your analysis : in general, the load of images should not happen at the same time as the load of the map itself. Maybe the loaded images should be the one used on the map only, or whatever. Even if my case is a bit extreme, the general principle remains weird. 
It is something understandable to let the user choose an icon from multiple choice, like [Mapstr](https://mapstr.com) does for instance. It's too bad that there is no easy option yet, or that the option is to allow only a certain short amount of available icons to the map, don't you think so ?

In [react-native-maps](https://github.com/react-native-community/react-native-maps), the Pointer chooses what it wants to load, there is no preloading of sets of images before, isn't it possible to do the same ?
