### ISSUE TITLE
[Android] Marker not showing in android 

### ISSUE THREAD

**Issue by saurabh-nandan** [react-native-mapbox-gl/maps#415]
**Describe the bug**
<MapboxGL.Images images={{ assets:['example'] }} />
it's working fine in ios but marker didn't show in android. I have placed 'example.png' in drawable & assets directory. Only map shows without any marker.

**source code**

<MapboxGL.MapView
        style={{ flex: 1 }}
        zoomEnabled={true}
      >
        <MapboxGL.Camera
          zoomLevel={9}
          centerCoordinate={[72.87, 19.07]}
        />

        <MapboxGL.Images
          images={{ assets:['example'] }}
        />

        <MapboxGL.ShapeSource
          id="my-position"
          shape={point}
          
        >
          <MapboxGL.SymbolLayer
            id="my-position"
            minZoomLevel={1}
            style={styles.fivestar}
          />

        </MapboxGL.ShapeSource>
      </MapboxGL.MapView>

** Expected behavior
Should show marker.

** Versions :

    Platfrom: Android
    Device: Emulator
    OS: Android 9
    SDK Version: 28
    React Native Version 0.60.5
    react-native-mapbox-gl/maps version: 7.0.6

**Comment by Alaa-Ben** [comment]
Same issue.

**Comment by ethaqnix** [comment]
Can you show `styles.fivestar` ?

**Comment by saurabh-nandan** [comment]
const styles = {
  fivestar: {
    iconImage: '{icon}',
    iconAllowOverlap: true,
    iconIgnorePlacement: true,
    iconSize: 0.8,
  },
};

**Comment by arnaud-zg** [comment]
I also have the same issue with `<MapboxGL.PointAnnotation ... />`

**Comment by kristfal** [comment]
Try using the image component.

**Comment by ethaqnix** [comment]
You are using the old styles, now you have to use 

```
const styles = {
  icon: {
    iconAllowOverlap: true,
    iconImage: ['get', 'icon'],

    iconSize: [
      'match',
      ['get', 'icon'],
      'example',
      0.1, /* size of 10% */
      /* default */ 1,
    ],
  },
}
```

and Images  look's like that :
`<MapboxGL.Images key="markerKey" images={{ example: myMarker, assets: ['pin'] }} />`

**Comment by arnaud-zg** [comment]
> Try using the image component.

Actually I have dynamic text on each marker, that's why i'm using `PointAnnotation`.

**Comment by Alaa-Ben** [comment]
> You are using the old styles, now you have to use
> 
> ```
> const styles = {
>   icon: {
>     iconAllowOverlap: true,
>     iconImage: ['get', 'icon'],
> 
>     iconSize: [
>       'match',
>       ['get', 'icon'],
>       'example',
>       0.1, /* size of 10% */
>       /* default */ 1,
>     ],
>   },
> }
> ```
> 
> and Images look's like that :
> `<MapboxGL.Images key="markerKey" images={{ example: myMarker, assets: ['pin'] }} />`
> 
> PS : `PointAnnotation` is deprecated

That solved my problem, thanks !

**Comment by saurabh-nandan** [comment]
Working Fine in Android & IOS. Thanks for the support.

**Comment by matifriaz** [comment]
This issue is still occurring. I am on 10.0.8. Here's the code for loading the images
`<MapboxGl.Images
            images={{
              'field-pin': {
                uri: 'https://ricult-development.s3-ap-southeast-1.amazonaws.com/map-pin.png',
              },
              'field-pin-light': {
                uri: 'https://ricult-development.s3-ap-southeast-1.amazonaws.com/map-red-pin.png',
              },
            }}
          />`
