### ISSUE TITLE
Cannot read property 'StyleURL' of undefined (on iOS) 

### ISSUE THREAD

**Issue by sarray23** [react-native-mapbox-gl/maps#416]
**Describe the bug**
 <MapboxGL.MapView
                        ref={this.map}
                        style={{width: "100%", height: 138, position: 'relative'}}
                        logoEnabled={false}
                        attributionEnabled={false}
                        zoomEnabled={false}
                        styleURL={MapboxGL.StyleURL.Satellite}
                        scrollEnabled={false}>
                        <MapboxGL.Camera
                            centerCoordinate={[lng,lat]}
                            zoomLevel={12}
                        />
                        {/* Display Mapbox.MapshapeSoure And MaboxGL.LineLayer*/}
                    </MapboxGL.MapView>

I only get the result with android but when I test it with iOS i get this error : Cannot read property 'StyleURL' of undefined

**Versions**
 - Platfrom: iOS
 - Device: All
 - React Native Version : 0.60

**Comment by kristfal** [comment]
This happens when the native side code is not installed properly. Please follow the install instructions closely.
