### ISSUE TITLE
[Android] Autolinking not working

### ISSUE THREAD

**Issue by bpouzet** [react-native-mapbox-gl/maps#421]
**Describe the bug**
Build failed when I launch `react-native run-android`

**Expected behavior**
Should build.

**Versions :**
 - Platfrom: Android
 - Device: Emulator
 - OS: Android 9
 - SDK Version: 28
 - React Native Version 0.60.5
- react-native-mapbox-gl/maps version: 7.0.6

**Additional context**

```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :@react-native-mapbox-gl_maps.
     Required by:
         project :app
      > Unable to find a matching configuration of project :@react-native-mapbox-gl_maps:
          - None of the consumable configurations have attributes.
```

**Comment by kristfal** [comment]
Have you tried manually linking?

**Comment by bpouzet** [comment]
I just try manually linking by adding this in settings.gradle file

```
include ':@react-native-mapbox-gl_maps'
project(':@react-native-mapbox-gl_maps').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-mapbox-gl/maps/android/rctmgl')

```

and it works!

It's a workaround, there is still a bug with the autolinking

**Comment by kristfal** [comment]
Ok. Can you confirm iOS autolinking works?

**Comment by Misioka** [comment]
@bpouzet can you share your build.gradle and MainApplication.java files?
I have same issue as you but adding these lines into settings.gradle did not help.

iOS linking works well for me.

**Comment by bpouzet** [comment]
@kristfal yes, IOS autolinking works

**Comment by kristfal** [comment]
Ok, feel free to explore why autolinking fails for Android. In the interim, we'll keep this ticket open.

I'll also have a look at updating the example app to RN61 next week and can review things then as well.

**Comment by bpouzet** [comment]
@kristfal thanks

**Comment by bpouzet** [comment]
@Misioka I don't edit MainApplication.java or build.gradle

https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.60.5/RnDiffApp/android/app/src/main/java/com/rndiffapp/MainApplication.java

https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.60.5/RnDiffApp/android/app/build.gradle

I just modify settings.gradle
```
rootProject.name = 'my_app'

apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)

include ':@react-native-mapbox-gl_maps'
project(':@react-native-mapbox-gl_maps').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-mapbox-gl/maps/android/rctmgl')

include ':app'
```

**Comment by Misioka** [comment]
@bpouzet thanks a lot. Now I see. 
Line order in settings.gradle is important. 
When I put `apply from...` above `include`. It starts to work.

**Comment by Alaa-Ben** [comment]
@bpouzet I had the same problem. I discovered this repo "@react-native-mapbox-gl/maps": "jshearer/maps" It fixes autolinking.

**Comment by kristfal** [comment]
@Alaa-Ben I can't really see any commits in that repo that should fix Android autolinking. Any idea why that one is working and not this main one?

**Comment by Alaa-Ben** [comment]
@kristfal Unfortunately no. I would say it's something in this commit:
https://github.com/jshearer/maps/commit/cdeb03231e3c8d53ffeeda7527fd7a715ad5291b

I read that using this repo resolves the: 
`Could not resolve project :@react-native-mapbox-gl_maps.
`
I read the commits, didn't believe it, but gave it a try eventually: it works for me.

**Comment by makirby** [comment]
Bizarrely to get this to work for me all I had to do was add a trailing slash to the include in settings.gradle.

i.e:
```apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)

include ':@react-native-mapbox-gl_maps'
project(':@react-native-mapbox-gl_maps').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-mapbox-gl/maps/android/rctmgl/')
```

**Comment by Alaa-Ben** [comment]
With the repo I mentionned above, I don't even need to touch the settings.gradle file

**Comment by codeithuman** [comment]
@makirby's fix worked for me. I just needed to add a trailing `/` to the `project` line.

```
include ':@react-native-mapbox-gl_maps'
project(':@react-native-mapbox-gl_maps').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-mapbox-gl/maps/android/rctmgl/')
```

**Comment by codeithuman** [comment]
@bpouzet's [fix](https://github.com/react-native-mapbox-gl/maps/issues/421#issuecomment-535447790) worked for me, but I also need to install and use [jetifier](https://github.com/mikehardy/jetifier). 

I was updating my app from React Native 0.59.10 to React Native 0.60.0. I also needed Jetifier for `react-native-auth0`.

**Comment by MrScorp** [comment]
Turns out the react native configuration file (react-native.config.js) is named as "react-native-config.js" in the package ! Renaming the file fixed autolinking issues for me. But you'll have to do it everytime you update any package.

**Comment by kristfal** [comment]
@MrScorp thanks for finding this issue. That was a silly typo/oversight from me. Opened a PR and merging this as soon as CI is good.
