### ISSUE TITLE
panning/bounds restriction

### ISSUE THREAD

**Issue by sincraianul** [react-native-mapbox-gl/maps#422]
Is possible to restrict panning to a specific area only?

There are some examples in the docs:
https://docs.mapbox.com/android/maps/examples/restrict-map-panning/
https://docs.mapbox.com/mapbox-gl-js/example/restrict-bounds/

Thanks.

**Comment by kristfal** [comment]
Duplicate of https://github.com/react-native-mapbox-gl/maps/issues/372

Happy to accept PRs for this.
