### ISSUE TITLE
map still shows POIs (and other labels) in iOS when using styleURL

### ISSUE THREAD

**Issue by sincraianul** [react-native-mapbox-gl/maps#424]
In iOS POIs, airport labels etc are still showing up even if they are hidden in the custom style. [Here](https://api.mapbox.com/styles/v1/sincraianul/ck10s7enz01sv1cqdom48x4g0.html?fresh=true&title=true&access_token=pk.eyJ1Ijoic2luY3JhaWFudWwiLCJhIjoiY2sxMHBnNzk5MDdwZDNucDY3M29pb255biJ9.QTUkmANMHehwG8sFM3541A#13.25/46.77287/23.58957)'s a copy of the style that I am using to test this.

**Comment by sincraianul** [comment]
Fixed by re-running `react-native run-ios`.

**Comment by ferdicus** [comment]
hey @sincraianul, just a heads-up, that you're sharing an `access_token` within your link
