### ISSUE TITLE
Issue creating full featureCollection for use in ShapeSource 

### ISSUE THREAD

**Issue by ksulia** [react-native-mapbox-gl/maps#427]
**Describe the bug**

Creating a featureCollection (of 126 features) as a state variable only stores the last feature, all others are missing. 

**To Reproduce**
Steps to reproduce the behavior

` this.state = {
            featureCollection: MapboxGL.geoUtils.makeFeatureCollection()}`

`this.state.dataSource.map((nm, key) => {
                    this.setState({
                        featureCollection: MapboxGL.geoUtils.addToFeatureCollection(
                            this.state.featureCollection,
                            MapboxGL.geoUtils.makeFeature({type: 'Point', coordinates: location}, {
                                key: key,
                                data: nm,
                            })
                        ),
                    })
                });`

`<View>
                                            <MapboxGL.Images
                                                images={this.state.iconImages}
                                            />
                                            <MapboxGL.ShapeSource
                                                id='images'
                                                shape={this.state.featureCollection}
                                                key={this.state.iconImages.ADDI.uri}
                                            >
                                                <MapboxGL.SymbolLayer key='{img}' id='{img}'
                                                                      style={({
                                                                          iconAllowOverlap: true,
                                                                          iconImage: ['get','img']
                                                                      })}
                                                />
                                            </MapboxGL.ShapeSource>
                                        </View>`

**Expected behavior**

All 126 features to be displayed.

**Screenshots**

Tested on MPGL versions 7.0.4, 7.0.5, and 7.0.6:
![IMG_1713](https://user-images.githubusercontent.com/16404910/65726742-cad7f900-e083-11e9-959f-3fd4f6a0aa6a.PNG)

Working on version 7.0.1
![IMG_1712](https://user-images.githubusercontent.com/16404910/65726761-d4f9f780-e083-11e9-82df-5cd94a8d7acf.PNG)

**Versions (please complete the following information):**
 - Platfrom:  Android, iOS
 - Device: Lenovo TB-x704V; iPhone X
 - OS: Android 7.1.1; iOS12.4.1
 - SDK Version 34
 - React Native Version 0.59

**Additional context**

**Comment by anttijva** [comment]
The geoutils recently got a breaking change, I didn't have time to look into it so I just use the old functions.

`addToFeatureCollection = (featureCollection, feature) => {
  const shallowFeatureCollection = Object.assign({}, featureCollection);
  shallowFeatureCollection.features.push(feature);
  return featureCollection;
}`
