### ISSUE TITLE
Support sort-key style properties for layers

### ISSUE THREAD

**Issue by frankrowe** [react-native-mapbox-gl/maps#430]
In the mapbox style spec, each layer type (symbol, fill, line, circle) has a `sort-key` property that is used to sort features within the layer. 

https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-symbol-sort-key

This style property needs to be added to SymbolLayer, FillLayer, LineLayer, and CircleLayer.

**Comment by frankrowe** [comment]
Fill, line, and circle need to be added to the native SDKs first. Symbol sort key has already been added.

**Comment by tr3v3r** [comment]
> Fill, line, and circle need to be added to the native SDKs first. Symbol sort key has already been added.

Could you please suggest where I can find info how I can use it with SymbolLayer? 

I’ve tried to put symbolSortKey into styles but it throws error that property doesn’t exist.

**Comment by mfazekas** [comment]
@tr3v3r we need to regen code with updated v8.json...
As in the current this feature is js only.


https://github.com/react-native-mapbox-gl/maps/blob/179d35b736fd9dfc38e6728810576d06482694fe/style-spec/v8.json#L965-L970

**Comment by mfazekas** [comment]
See #679 it now adds symbolSortKey

**Comment by tr3v3r** [comment]
@mfazekas
Wow cool! Thanks for such a quick response! Looking forward to approving the pr and future release
