### ISSUE TITLE
Filtering does not work on `queryRenderedFeaturesAtPoint` or `queryRenderedFeaturesInRect`.

### ISSUE THREAD

**Issue by jesus-deepblocks** [react-native-mapbox-gl/maps#431]
**Describe the bug**
When querying a mapbox layer by using either `MapView.queryRenderedFeaturesAtPoint` or `MapView.queryRenderedFeaturesInRect` everything works fine as long as no filter is passed but as soon as a filter is used the application crashes.

**To Reproduce**
In the example, `queryWithRect.js` replace `null` by `['==', 'type', 'Point']` in line 51 and run the example.

**Expected behavior**
I would expect an empty `featureCollection` as none of the features on `nyc_geojson.json` file have a property named `type`, but instead the application crashes.

**Screenshots**
![Simulator Screen Shot - iPhone X - 2019-09-27 at 15 07 50](https://user-images.githubusercontent.com/37085576/65795680-cd485a80-e138-11e9-987d-c8b87fc7bd4c.png)

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: iPhone X
 - OS: iOS 12.2
 - SDK Version 7.0.4
 - React Native Version 0.60.5

**Additional context**
I was able to pinpoint a fix to this issue but I have zero confidence that this is the right solution due that I'm new to react-native and have zero knowledge of objective-c. In any case,  in `ios/RCTMGL/RCTMGLMapViewManager.m` I replaced `withFilter:(NSArray<NSDictionary<NSString *, id> *> *)filter` by `withFilter:(NSArray *)filter`

The changes in #173 even when related to a different filtering issue pointed me into my supposed "fix". Filtering queries is of tremendous importance for our team and in the meantime, we are linear searching the features that we need.

Thanks in advance and keep the good job.

**Comment by jesus-deepblocks** [comment]
This issue is only stale because it hasn't even been acknowledged by the creators/community (not bitching at all, I think that they are doing an amazing job). If this isn't happening to anyone else and this won't be fixed, the issue may as well be closed and we'll continue to do our own (most likely inefficient) in-house filtering.

**Comment by chrisparton1991** [comment]
@jesus-deepblocks this issue is affecting me as well, I was just about to raise a ticket.

My code runs fine on Android, but I get the exact same error as you on iOS.

For context:
 - Platfrom: iOS
 - Device: iPhone X Simulator
 - OS: 13.2
 - React Native Version: 0.60.5
 - Library version: 7.0.8 (also fails in 7.0.7)

**Comment by chrisparton1991** [comment]
@kristfal `RCTMGLMapViewManager.m` expects to receive the filter as an array of dictionaries:
```
RCT_EXPORT_METHOD(queryRenderedFeaturesInRect:(nonnull NSNumber*)reactTag
                  withBBox:(NSArray<NSNumber*>*)bbox
                  withFilter:(NSArray<NSDictionary<NSString *, id> *> *)filter
                  withLayerIDs:(NSArray<NSString*>*)layerIDs
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
```

The JS side is passing through an array of strings, and this mismatch is what's causing the error. This also applies to `queryRenderedFeaturesAtPoint`.

I'll raise a PR shortly.
