### ISSUE TITLE
[QUESTION] Is there a way to display the direction arrow on UserLocation ?

### ISSUE THREAD

**Issue by tinmar33** [react-native-mapbox-gl/maps#437]
I need to display the user direction on his location (without moving the camera).
Is there a way to do that ? I can't find anything on the Readme

Here's an example:
![image](https://user-images.githubusercontent.com/7252474/65882852-2660fa00-e396-11e9-841b-25d7cf74dcc6.png)

Thanks

**Comment by RichardLindhout** [comment]
We need this pull request: https://github.com/react-native-mapbox-gl/maps/pull/215
In this thread you will find a way to enable this on Android https://github.com/react-native-mapbox-gl/maps/issues/319

**Comment by ethaqnix** [comment]
While waiting for the feature, you can display a custom icon, get phone orientation of your phone with magnetometer and rotate the icon : 

```
<MapboxGL.UserLocation
        renderMode={'custom'}
      >
        <MapboxGL.SymbolLayer
          id={`ownPosition-symbol`}
          style={{
            iconImage: userDirectionMarker,
            iconSize: 0.1,
            iconRotate: this.state.phoneOrientation,
            iconRotationAlignment: 'map',
            iconAllowOverlap: true,
          }}
        />
      </MapboxGL.UserLocation>
```

**Comment by tinmar33** [comment]
Thanks @ethaqnix, i'll try this

**Comment by tinmar33** [comment]
@ethaqnix it works, but i don't have the transparent blue circle indicating the accuracy of the gps.
Do you know how to have it on a custom icon ?

**Comment by lpfunding** [comment]
What is the best way to use magnetometer in React Native?

**Comment by SethArchambault** [comment]
Looking forward to this feature too - we'll need this before we make the move from the old react mapbox library!

**Comment by rdgomt** [comment]
Would be a nice feature!

**Comment by SethArchambault** [comment]
Any update here? We're moving from the old repo:
https://github.com/nitaliano/react-native-mapbox-gl#master

.. to the new one, and it'd be a shame if users had to lose an important feature during the upgrade.. 

Anything I can help with? Here's some of the old code:
https://github.com/nitaliano/react-native-mapbox-gl/blob/master/ios/RCTMGL/MGLUserLocationHeadingArrowLayer.m

**Comment by SethArchambault** [comment]
Oh no you don't stale bot!

**Comment by SethArchambault** [comment]
Hey, who wants to work on this with me? This would be my first big feature add, would be helpful if someone wants to jam on it a little..

**Comment by mfazekas** [comment]
@SethArchambault i think we need to finish https://github.com/react-native-mapbox-gl/maps/pull/215

**Comment by SethArchambault** [comment]
@mfazekas I see progress on that has stalled.. Is #215 a requirement for this task you think? Or just a nice to have?

**Comment by tinmar33** [comment]
> Oh no you don't stale bot!

**Comment by sauhardar** [comment]
Is `renderMode={'custom'}` not a prop of `UserLocation` yet? I'm on `"@react-native-mapbox-gl/maps": "^8.1.0-beta.1",` and it doesn't seem to be a valid prop.

**Comment by mfazekas** [comment]
@sauhardar we've removed renderMode is now either `native` or `normal`
`custom` was same as `normal`, so we've removed it.

To custom location icon just supply a children to `UserLocation` in `normal` render mode

**Comment by sauhardar** [comment]
@mfazekas , but renderMode is not a valid prop for `UserLocation`?

**Comment by mfazekas** [comment]
@sauhardar it should be there on 8.1 beta.

**Comment by RichardLindhout** [comment]
Maybe Typescript issue?

**Comment by tinmar33** [comment]
<img width="158" alt="image" src="https://user-images.githubusercontent.com/7252474/84003289-15777800-a96a-11ea-8932-64bb8f71c6d7.png">
@mfazekas Is the arrow direction a native feature or i need to use the @ethaqnix solution to display it ?

**Comment by sauhardar** [comment]
@mfazekas I'm using 8.1 beta, and I'm having issues. Giving UserLocation the prop `renderMode="normal"` with a child component of SymbolLayer does not work for me on Android. Actually, the app just crashes almost instantly.
