### ISSUE TITLE
CustomHTTPHeaders Swizzle Method: Undeclared Identifier Error

### ISSUE THREAD

**Issue by systemlevel** [react-native-mapbox-gl/maps#440]
**Describe the bug**

When I include the [MGLCustomHeaders initHeaders] as per the documentation here https://github.com/react-native-mapbox-gl/maps/blob/master/docs/CustomHttpHeaders.md

```
  // *** Init headers, add swizzle method
  [MGLCustomHeaders initHeaders];
  // *** Optionally you can add some global headers here
  [[MGLCustomHeaders sharedInstance] addHeader:@"IP" forHeaderName:@"X-For-Real"];
```

I get the following error messages in xcode:

<img width="972" alt="Screen Shot 2019-10-01 at 4 50 40 PM" src="https://user-images.githubusercontent.com/894983/66006451-f08e4500-e46b-11e9-930c-9d3773026602.png">

**To Reproduce**
Steps to reproduce the behavior

Simply add the required code to AppDelegate.m per the documentation:

```
  // *** Init headers, add swizzle method
  [MGLCustomHeaders initHeaders];
  // *** Optionally you can add some global headers here
  [[MGLCustomHeaders sharedInstance] addHeader:@"IP" forHeaderName:@"X-For-Real"];
```

**Expected behavior**

Able to use Custom Headers on WMS calls without issue.

**Screenshots**

<img width="972" alt="Screen Shot 2019-10-01 at 4 50 40 PM" src="https://user-images.githubusercontent.com/894983/66006503-14518b00-e46c-11e9-8eff-9152961625a9.png">

**Versions (please complete the following information):**

 - Platfrom: [ iOS]
"react-native": "0.59.9",
"@react-native-mapbox-gl/maps": "^7.0.1",

**Additional context**

**Comment by systemlevel** [comment]
@yavosh I think your custom method implementation is going to come in really useful. For some reason I'm getting the error message above when I attempt to implement it. 

Thank you for your contribution to this repository!

**Comment by systemlevel** [comment]
I also tried to import:  

`#import <react-native-mapbox-gl/MGLCustomHeaders.h>`

in the AppDelegate.m file as well.  After doing that I got another error message about the initHeaders:

<img width="789" alt="Screen Shot 2019-10-01 at 5 00 12 PM" src="https://user-images.githubusercontent.com/894983/66006746-f59fc400-e46c-11e9-88f0-8a990f1a2982.png">

@yavosh If I'm using this new addition incorrectly let me know.

**Comment by yavosh** [comment]
Looks like this was merged in 7.0.2.
Can you try with latest version (7.0.6).

Also if this does not work:
#import <react-native-mapbox-gl/MGLCustomHeaders.h>

can you try:
#import "MGLCustomHeaders.h"

If you confirm this solves it for you I'll update the readme to include min required version.

**Comment by systemlevel** [comment]
@yavosh Thank you! That suggestion you made seems to be working. As of right the error is gone I was getting. 

I used:

`#import "MGLCustomHeaders.h"`

`[[MGLCustomHeaders sharedInstance] initHeaders];`

Error is gone.

Now I'll test the headers to make sure the Bearer token authentication is being sent through the header of the WMS calls.

**Comment by yavosh** [comment]
Is this working now, can you close if yes.

**Comment by systemlevel** [comment]
@yavosh Yes it is.  Thank you for this contribution to the library!

**Comment by ansarikhurshid786** [comment]
I tried same. it is not working for me. 
react-native: 0.59.10
"@react-native-mapbox-gl/maps": "^7.0.8",
