### ISSUE TITLE
[Android] followHeading is missed in RCTMGLCameraManager.java

### ISSUE THREAD

**Issue by winseyli** [react-native-mapbox-gl/maps#447]
**Describe the bug**
followHeading works on iOS but not Android
Found it does not exist in `android/rctmgl/src/main/java/com/mapbox/rctmgl/components/camera/RCTMGLCameraManager.java`

**To Reproduce**
Run on Android with followHeading set.

**Expected behavior**
Hmm... it should work, just like on iOS

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: Asus Zenfone 4
 - React Native Version 0.59.9

**Comment by horva** [comment]
@winseyli from looking at examples there are 2 ways to deal with heading. One is to set `heading` prop directly on Camera 
```
<MapboxGL.Camera heading={this.state.heading} />
```
other is to set heading auto update by settings `followUserMode` to value `compass`.
```
<MapboxGL.Camera followUserMode="compass" />
```
But yeah, I agree it is a bit odd followHeading is implemented for iOS while not for Android.

**Comment by winseyli** [comment]
Thanks for reply.

`<MapboxGL.Camera heading={this.state.heading} />`
This won't take effect if `followUserLocation` is `true`

So it only can use
`<MapboxGL.Camera followUserMode={MapboxGL.UserTrackingModes.FollowWithHeading} />`

**Comment by winseyli** [comment]
Still need this to be fixed as we need to set a threshold on the compass heading
