### ISSUE TITLE
Markers (MapboxGL.ShapeSource, using MapboxGL.Images) disappear when styleURL changes

### ISSUE THREAD

**Issue by winseyli** [react-native-mapbox-gl/maps#450]
**Describe the bug**
The markers disappear when styleURL changes.

**To Reproduce**
Switch between two different styleURL. It doesn't always happen but it does usually happen.

**Expected behavior**
The markers should always be there.

**Screenshots**
<img width="200" alt="Screen Shot 2019-10-04 at 2 03 47 PM" src="https://user-images.githubusercontent.com/7858565/66174133-0c822880-e6b0-11e9-81a6-19310f09eae3.png"><img width="200" alt="Screen Shot 2019-10-04 at 2 03 50 PM" src="https://user-images.githubusercontent.com/7858565/66174134-0c822880-e6b0-11e9-958f-188bc263817b.png">
<img width="200" alt="Screen Shot 2019-10-04 at 2 04 00 PM" src="https://user-images.githubusercontent.com/7858565/66174135-0d1abf00-e6b0-11e9-9fef-00c9e4ce1b75.png"><img width="200" alt="Screen Shot 2019-10-04 at 2 04 07 PM" src="https://user-images.githubusercontent.com/7858565/66174137-0d1abf00-e6b0-11e9-96ad-a1e2737a8e23.png">

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: Emulator
 - OS: iOS13.0
 - SDK Version 13
 - React Native Version 0.59.9
 - react-native-mapbox-gl 7.0.6

**Comment by kristfal** [comment]
Sounds like a race condition. Can you fork the repo and create an example in the example app with a reproduction case?

**Comment by gmaclennan** [comment]
We have had this reported by users a lot too, running Android. I haven't been able to reproduce on any phone that I have. Apparently it happens on some phones, but not others. If I do manage to reproduce consistently then I will post here.

**Comment by maiSkura** [comment]
Good morning, someone solved this??, I am having the same problem on android. on ios it works fine.

**Comment by maiSkura** [comment]
with this I solved it
https://github.com/react-native-community/react-native-maps/issues/578#issuecomment-249256791
