### ISSUE TITLE
[Android] [IOS] Mapbox Show Custom Component onPress Symbol Layer with Images

### ISSUE THREAD

**Issue by saurabh-nandan** [react-native-mapbox-gl/maps#452]
**Describe the bug**
How to show custom React Component in map onPress of Symbol Layer.

**To Reproduce**
We used the Bubble example and PointofView example but could not see the View of the Bubble as there was no Symbol Layer in this example

**Expected behavior**
Need to show custom React Compoenent onPress of Symbol Layer (where we are showing Marker images) which should be anchored at that geoco-ordinates and should be dismiss when click outside.

**Versions (please complete the following information):**
 - Platfrom: [e.g. Android, iOS]
 - Device: Ios ,Android
 - OS: ios 10, android 8
 - SDK Version 26
 - React Native Version 0.60

**Additional context**

**Comment by kristfal** [comment]
This is not a bug report. See example app for examples and use stackoverflow for general usage questions.
