### ISSUE TITLE
doc ?

### ISSUE THREAD

**Issue by CyrusZei** [react-native-mapbox-gl/maps#454]
**Describe the bug**
the doc's are shallow and leave much uncleared

**To Reproduce**
a simple question like "How do I add an icon to the map with shape?". when you go to the doc for shapes it only shows what props it can get, not any example at all.

**Expected behavior**
in the doc's there should be examples of how to use those components.
 - React Native Version [e.g. 0.59]

**Additional context**
I am more than happy to make Pr for the docs, but if I don't understand them then that would be hard. The examples that this repo has does not cover the stuff people want to do with a map. I love the MapBox and what you have done, but the docs are something that could be improved. If you want me to help you guys out with the doc's please tell me and I need to understand what and how those components works and then I will be able to make a nice doc

**Comment by kristfal** [comment]
Docs are auto generated and need to be this way to keep up with mapbox
style changes etc.

The example app is full of examples, including the one you mention. Have
you seen this?

**Comment by CyrusZei** [comment]
Okej, I didn't know that they were auto-generated, by bad.

Yes, I did look at the examples, but there are some parts that do not explain stuff.

**Comment by kristfal** [comment]
No issue. Happy to see PRs for new examples btw, if you feel something is
lacking :)

**Comment by CyrusZei** [comment]
Awesome man, I will be more than happy to do that.
Thank you for your quick reply.
