### ISSUE TITLE
Compass shrinks when compassViewMargins is greater than half of device height/width

### ISSUE THREAD

**Issue by emilefleming** [react-native-mapbox-gl/maps#461]
**Describe the bug**
If you set a high value to either 'x' or 'y' in the compassViewMargins prop of the MapView the compass begins to shrink in size into nothing as the value exceeds half the width or height (depending if x or y) of the device.

I was doing this to position the compass bottom right on the map on Android since compassViewPosition is iOS only.

**To Reproduce**
Pass the prop compassViewPosition={{x: deviceWidth / 2, y: deviceHeight / 2}} to MapView, rotate the device so that the compass is visible.

**Expected behavior**
The compass position changes but size remains the same.

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: LGV20
 - OS: 7
 - SDK Version: 7.07
 - React Native Version: 59.9

**Comment by ansarikhurshid786** [comment]
I am facing same issue. did you got solution?
