### ISSUE TITLE
Failing to add app navigation on top of map?

### ISSUE THREAD

**Issue by MuzavaziTawa** [react-native-mapbox-gl/maps#467]
Hello. Mine is not really a bug. The docs are not so clear when  it comes to adding your app navigation or buttons on top of the map. Also getting place info on click etc. It was easy with react-native-maps as they had example and even a beginner can learn. Could you please help me know how to get place info on click, getting poi(points of interest) and also how to put buttons on top of maps or a footer. 

The example app shows an error '. is not recognized a an internal command' when you run npm install,

**Comment by ferdicus** [comment]
Please check out the [`/example`](https://github.com/react-native-mapbox-gl/maps/tree/master/example) folder.

I would recommend to compile it and get it on a device and then play around with the different examples, lots of them are with a UI to trigger events. 


@kristfal, ticket can be closed I believe
