### ISSUE TITLE
Attach a popup to a marker instance

### ISSUE THREAD

**Issue by lmyEsther** [react-native-mapbox-gl/maps#475]
Is this feature available for RN?

In order to do something like this: https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/

**Comment by ethaqnix** [comment]
it's a [Callout](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Callout.md), if that can help you. I never succed to make it work on Android, however, it should work on iOS.

**Comment by lmyEsther** [comment]
Is it working on the layers (symbolLayer)? Thanks!

**Comment by Dkokkonas** [comment]
I am also trying to do this. Have you did it?

**Comment by FarmersReact** [comment]
I am also trying to do this. Have you did it?

**Comment by tejassonar** [comment]
Is there anyone who could implement this?

**Comment by ferdicus** [comment]
Have you folks checked out the [Custom Callout](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/Annotations/CustomCallout.tsx) file in the `example` project?

**Comment by tejassonar** [comment]
> Have you folks checked out the [Custom Callout](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/Annotations/CustomCallout.tsx) file in the `example` project?

Not yet. Currently referring to [This](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/Annotations/ShowPointAnnotation.js) example. I was able to create a popup (custom callout) but was not able to load the image inside the callout.
