### ISSUE TITLE
Feature request: Add scale bar

### ISSUE THREAD

**Issue by gmaclennan** [react-native-mapbox-gl/maps#482]
The native Android SDK [supports a scale bar](https://docs.mapbox.com/android/plugins/overview/scalebar/) (unfortunately it doesn't seem the iOS SDK has a scale bar yet). It would be really useful to expose this in React Native, many of our users have been requesting a scale bar on the map - the alternative being to draw it with React Native, which might have a performance overhead.

**Comment by felixgourdeau** [comment]
https://www.npmjs.com/package/react-native-scale-bar

**Comment by NathanNovak** [comment]
Why won't you add this feature? It would be very useful.
