### ISSUE TITLE
How to setPaintProperty

### ISSUE THREAD

**Issue by fbambusi** [react-native-mapbox-gl/maps#484]
Good morning everybody, I would like to mimic this example https://docs.mapbox.com/mapbox-gl-js/example/change-building-color-based-on-zoom-level/. 

**In particular, I would like markers to maintain their relative size with respect to the map (i.e., get bigger when I zoom in).**
 
I wasn't able to find a class which supports this behaviour; do you think it is possible to achieve this goal? 
Best regards,
Fulvio

**Comment by kristfal** [comment]
Please look at the examples in the example app. This use case is covered there. 

Also a general note: This is an issue tracker. Please use stackoverflow for open questions.
