### ISSUE TITLE
Null is not an object error

### ISSUE THREAD

**Issue by MuneebSarfraz94** [react-native-mapbox-gl/maps#493]
I'm getting error below when i tried to use mapbox in my react native android app. Error appears right after i open app.

null is not an object (evaluating 'MapboxGL.StyleURL')
<unknown>
    Camera.js:57:19
loadModuleImplementation
    require.js:331:6
<unknown>
    index.js:5
loadModuleImplementation
    require.js:331:6
<unknown>
    detailscard.js:197:52
loadModuleImplementation
    require.js:331:6
<unknown>
    ReactFabric-prod.js:6593:31
loadModuleImplementation
    require.js:331:6
<unknown>
    
loadModuleImplementation
    require.js:331:6
<unknown>
    index.js:7
loadModuleImplementation
    require.js:331:6
guardedLoadModule
    require.js:197:45
global code

**Comment by mfazekas** [comment]
See #359
