### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by ivari** [react-native-mapbox-gl/maps#494]
I would ever so humbly request a new release of this package some time soon. I'm especially interested in https://github.com/react-native-mapbox-gl/maps/issues/462 which is currently blocking our production release, and managing dependencies on a commit level is a pain.

CC: @kristfal

**Comment by kiljee** [comment]
+

**Comment by kristfal** [comment]
Hey, sorry for the slow releases lately.

I'll push out 7.0.8 based on latest master now.
