### ISSUE TITLE
[Docs] Camera documentation needs updates

### ISSUE THREAD

**Issue by alexiri** [react-native-mapbox-gl/maps#50]
In [MapView.js#L50](https://github.com/react-native-mapbox/maps/blob/d1688fdf74cba210e438303b8719440f2befa6d4/javascript/components/MapView.js#L50), is userTrackingMode really supposed to be a number? The modes are defined as strings in [Camera.js#L332](https://github.com/react-native-mapbox/maps/blob/d1688fdf74cba210e438303b8719440f2befa6d4/javascript/components/Camera.js#L332).

This makes the "User Location Updates" example show a warning.

**Comment by mfazekas** [comment]
@alexiri i think userTrackingMode is removed from MapView and replaced with Camera#followUserMode. We need to update examples and docs.

**Comment by kristfal** [comment]
The [camera doc](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Camera.md) still needs a refurb. PRs are more than welcome.

Renaming ticket.
