### ISSUE TITLE
ld: framework not found Mapbox

### ISSUE THREAD

**Issue by Oz-on** [react-native-mapbox-gl/maps#503]
**Describe the bug**
After upgrading from RN v.0.59 to RN v.0.62 I ended up with following bug `"ld: framework not found Mapbox"`

**To Reproduce**
1. update RN version from 0.59 to 0.62 using [react-native upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.59.0&to=0.61.2)
2. Remove all configuration related with manual instruction for iOS
3. Use pod install

**Expected behavior**
Everything should work fine, when using autolinking.

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: iPhone8, physical device
 - OS:  iOS13.2
 - SDK Version: 7.0.8
 - React Native Version 0.62

**Additional context**
Before that update I had added Mapbox manually but after an update because of autolinking feature I deleted all configurations required for manual steps, hoping that it will work.
I tried also with manual linking react-native-mapbox-gl/maps but then it shows `fatal error: 'React/RCTComponent.h' file not found`.

**Comment by kristfal** [comment]
Hey. This is very likely an issue with your setup and not a lack of support for autolinking or RN62 in this library. 

Migration from a manually linked to autolinked dependency + cocoapods has multiple steps and they are dependent on how you set things up on your end. For instance, if you haven’t used pods before, you must run pod install and make sure you open the project via the workspace file. 

If you can reproduce the issue in the example app by moving it to RN62, please provide a sample repo and reopen this ticket. In the interim, I’ll close this ticket.
