### ISSUE TITLE
Cant trace a directions between two points

### ISSUE THREAD

**Issue by schmem55** [react-native-mapbox-gl/maps#507]
**Describe the bug**
Hi ,
i am a new in using mapbox gl on react native , i am trying to find an example that drag a linedirection from a point A to a point B on the map .I just want to check if i can display something with hard code 
The only Think that i can make appear is a map

Secondly i want to use MapboxGL.Camera and this make me have an error (i think because there is no md file like this in my node_modules but i dont know the reason 
Could someone can help me ? 

here is my code 

import React from 'react';
import {StyleSheet, View } from 'react-native';
import MapboxGL from '@mapbox/react-native-mapbox-gl';

MapboxGL.setAccessToken(MY_TOKEN)// removed for the screenshot;

const featureCollection = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4552',
      properties: {
        icon: 'example',
      },
      geometry: {
        type: 'Point',
        coordinates: [-73.989,40.733],
      },
    },
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4552',
      properties: {
        icon: 'airport-15',
      },
      geometry: {
        type: 'Point',
        coordinates: [-74,40.733],
      },
    },
    {
      type: 'Feature',
      id: '9d10456e-bdda-4aa9-9269-04c1667d4552',
      properties: {
        icon: 'pin',
      },
      geometry: {
        type: 'Point',
        coordinates: [-74,40.733],
      },
    },
  ],
};

export default class Maps extends React.Component {

  render() {
    return (
      <View style={{ flex: 1 }}>
        <MapboxGL.MapView style={{ flex: 1 }}  >
          <MapboxGL.ShapeSource
            shape={featureCollection}
            
          >
            <MapboxGL.SymbolLayer style={{iconColor:'red'}} minZoomLevel={25}/>
          </MapboxGL.ShapeSource>
        </MapboxGL.MapView>
      </View>
    );
  }
}

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: Pixel 2 XL API 28
 - OS: Android 9.0
 - SDK Version 
 - React Native Version 0.59.10

**Additional context**

**Comment by kristfal** [comment]
Hey schmem55, this issue tracker is for bug reports and not general support. I do recommend using stackoverflow for general questions.

If you find a reproducible bug in the library do not hesitate to re-open this ticket or post a new one. If this is the case, providing a [minimum reproducible example](https://robjhyndman.com/hyndsight/minimal-reproducible-examples/) helps a lot in locating the issue.
