### ISSUE TITLE
PointAnnotation displaying under all other layers

### ISSUE THREAD

**Issue by tholhubner** [react-native-mapbox-gl/maps#516]
**Describe the bug**
Point Annotations are being rendered behind both a ShapeSource/FillLayer and an ImageSource/RasterLayer. This only occurs on Android, but not on iOS. I know that PointAnnotation is going to be deprecated or has already been deprecated, but as of now we have not been able to get any alternatives working as we need them.

**Expected behavior**
Display the Point annotation above all layers before it.

**Screenshots**
![Screenshot_20191107-150823](https://user-images.githubusercontent.com/5454253/68479041-61f5ac00-01ff-11ea-8cb6-efd39d05962f.png)

**Versions (please complete the following information):**
 - Platform: At least Android 5.0 plus
 - Device: Samsung S6, S7, S9 and Nexus Tablet
 - SDK Version 28
 - React Native Version 60.10

**Comment by Mrxpj** [comment]
Excuse me, I had the same problem. Could you solve it by other way?

**Comment by mfazekas** [comment]
On android we're using Annotation plugin, it doesn't seems to have support ofr zindex. https://docs.mapbox.com/android/plugins/overview/annotation/

The new MarkerView in 8.* should support this

**Comment by Mrxpj** [comment]
> 在android上，我们使用的是Annotation插件，它似乎不支持zindex。https://docs.mapbox.com/android/plugins/overview/annotation/
> 
> 8. *中的新MarkerView应该支持此功能
Thank you，I try it。

**Comment by Mrxpj** [comment]
@mfazekas Excuse me，I use MarkerView in 8.0.0-beta1,but marker can not draggable.  I want to use MarkerView like PointAnnotation on Android (PointAnnotation displaying under all other layers). How should I do？Thank you.

**Comment by kunal886496** [comment]
+1 exactly

**Comment by ansarikhurshid786** [comment]
facing same issue

**Comment by ansarikhurshid786** [comment]
I am using raster base map so i can't able see pointannotation.
