### ISSUE TITLE
Mapbox Studio SVGs not appearing on map

### ISSUE THREAD

**Issue by juanjsebgarcia** [react-native-mapbox-gl/maps#517]
**Describe the bug**
I have added a few SVGs for styling in Mapbox studio but they are not rendering in my app.

**To Reproduce**
Add an SVG pattern to Mapbox Studio. Link the style to Mapview. Notice SVGs are not rendered.

**Expected behavior**
I expected the SVG images to render in the app.

**Screenshots**
## Mapbox (Desired)
![Screenshot 2019-11-08 at 14 01 45](https://user-images.githubusercontent.com/16254139/68481936-59699980-0230-11ea-9f9f-e4d01111a6cf.png)

## Actual
![Untitled](https://user-images.githubusercontent.com/16254139/68481876-3808ad80-0230-11ea-87d6-05711ce02eea.png)

**Versions (please complete the following information):**
 - Platfrom:Android
 - Device: OnePlus 7T
 - OS: Android 10
 - SDK Version 28
 - React Native Version 0.61.4

**Comment by juanjsebgarcia** [comment]
I would have thought this was common scenario and should be fixed! Perhaps it's a misconfiguration on my end? Any help very welcome!

**Comment by mfazekas** [comment]
@juanjsebgarcia this sounds like an upstream issue, ideally, it needs to be submitted against that repo: https://github.com/mapbox/mapbox-gl-native-android 

Also can you verify that the issue happens with the current master, as it uses later version of android libs.

I'm closing this will reopen on further input.

**Comment by juanjsebgarcia** [comment]
I just went back to try this again, to see if I could work out the issue. Applying the changes I had git stashed made it work. As in, changing nothing (except perhaps the version? - Lost track of this). Happy for it to remain closed now its working. Thanks!
