### ISSUE TITLE
Android X support

### ISSUE THREAD

**Issue by marudy** [react-native-mapbox-gl/maps#518]
**Describe the bug**
Cannot compile and build existing React-Native application migrating from `0.59.9` to `0.60.5`. Use of jetifier does not solve the problem.

**Expected behavior**
Application should build successfully.

**Screenshots**
As issue #245 

**Versions (please complete the following information):**
 - Platfrom: Android
 - SDK Version: latest at the time
 - React Native Version 0.60.5

**Comment by kristfal** [comment]
We have a lot of users (including my team) running this repo under RN60+, so this is an issue with your project setup and not this repo. 

Make sure you are using the latest version (7.0.8) and that your native code is updated.

**Comment by marudy** [comment]
@kristfal I don't doubt that; It doesn't mean though that it's not an issue and that this project should not be upgraded properly to AndroidX or provide a README guidance at least.

**Comment by kristfal** [comment]
The challenge with upgrading to Android X is that it would force everyone onto RN60+. As such, we want to delay as long as we can to do the migration within this repo. This doesn’t apply to just this package. You’ll see a fair share of other RN dependencies not moving over either. 

We’ll likely move over To AndroidX when it is mainstream amongst the most used RN dependencies. 

In the interim: RN 60 runs the jetifier by default when you run react-native run-android, so unless you have a special build process that is based around gradlew (say use AppCenter), things should work out of the box.

**Comment by marudy** [comment]
@kristfal, thanks for the reply and the info, appreciate it. Yeah jetifier is run by default but didn't really worked out with my project. And yes we do use appcenter for building in this project. All right, will work towards workarounds with use of jetifier

**Comment by rphlmr** [comment]
Can confirm that the last version (7.0.8) work with : 
````
  "react": "16.9.0",
  "react-native": "0.61.4",
```

7.0.7 was not building for us (a simple ./gradlew bundleRelease + jetify postinstall script in package.json)

**Comment by marudy** [comment]
yeah also have `7.0.8` working with jetifier by now :) thanks for the post

**Comment by ericanthonywu** [comment]
so, should we downgrade our react native version to 0.59?
