### ISSUE TITLE
[QUESTION] - Fullscreen support of mapbox

### ISSUE THREAD

**Issue by kmkrtich** [react-native-mapbox-gl/maps#521]
Is there any way for supporting fullscreen view of the map by clicking appropriate icon on the small portion of the map. If yes is fullscreen view customizable so that you can add additional buttons on fullscreen view ?

**Comment by kristfal** [comment]
Map size is defined by the style of the MapView. Updating the style will resize the map. 

In short, map resize logic should be handled by the parent application and not by the map library itself, so this is something we will not implement here.
