### ISSUE TITLE
Upgrade android and iOS SDK to allow increase in downloaded tile size

### ISSUE THREAD

**Issue by L-Yeiser** [react-native-mapbox-gl/maps#523]
**Describe the bug**
for iOS versions lower than 5.3.0 and android version lower than 8.3.0 It is against the Mapbox terms of service to raise the tile limit of downloaded tiles. This causes `Mapbox tile count limit exceeded` errors when attempting to download larger maps. This error cannot be circumnavigated by increasing the allowed limit.

**To Reproduce**
Download an offline area larger than 6,000 tiles.

**Expected behavior**
Companies that use this library should be able to increase the tile size limit.

**Comment by kristfal** [comment]
iOS was just updated to 5.5.0 in master. Latest stable for Android is 8.4.0, happy to see a PR, I believe its a few lines of code changes [here](https://github.com/react-native-mapbox-gl/maps/blob/master/android/rctmgl/build.gradle#L35), but we should at least manually run through the examples after update and make sure we match version updates for the plugins.

**Comment by L-Yeiser** [comment]
I closed this by accident. Will open a PR shortly and run through the examples.

**Comment by fernandocanizo** [comment]
We were waiting for this change to happen and were thinking even to jump into, but saw @L-Yeiser comment, are you still working on that PR or got more complicated?

In case I need to jump in, what does mean to "run through the examples" ? Just get the demo and see if it runs ok?
