### ISSUE TITLE
[Android] The onUserTrackingModeChange event handler reports  the tracking mode

### ISSUE THREAD

**Issue by andrei-tofan** [react-native-mapbox-gl/maps#530]
**Describe the bug**
When the the followUserMode and followUserLocation options are changed for the Camera from none to normal for example, the `onUserTrackingModeChange` callback is first called with none and then with the normal mode (the handler is called twice). 

**To Reproduce**
The issue can be reproduced with the example app by switching the tracking mode.

**Expected behavior**
The onUserTrackingModeChange callback to be called once with the correct tracking mode.

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: Nexus 5X
 - OS: Android 9.0
 - SDK Version 28
 - React Native Version 0.60.5
- React Native Mapbox GL Version 7.0.8

**Comment by dmlitvinov** [comment]
The same behavior is observed on version 8.1.0 on iOS
