### ISSUE TITLE
UserLocation hidden behind ShapeSource

### ISSUE THREAD

**Issue by jlo1** [react-native-mapbox-gl/maps#534]
**Describe the bug**
UserLocation will show a blue dot on the map. However, that dot will get covered by `ShapeSource` markers on the map.

**To Reproduce**
If trying to render:
```
<MapboxGL.MapView
    logoEnabled={false}
    onDidFinishLoadingMap={this.onLoadingFinished}
    onPress={this.unselectMarker}
    rotateEnabled={false}
    pitchEnabled={false}
    onRegionDidChange={this.regionDidChange}
    style={styles.container}>
    {this.renderCamera()}
    {this.renderUserLocation()}
    {this.renderImages()}
    {this.renderMarkers()}
</MapboxGL.MapView>
```

where `this.renderMarkers()` returns
```
if (this.state.someState) { return null ; }

return (
	<MapboxGL.ShapeSource
	    shape={featureCollection}
	    onPress={this.onMarkerPress}>
	    <MapboxGL.SymbolLayer />
	</MapboxGL.ShapeSource>
);
```
and `renderUserLocation()` returns
```
<MapboxGL.UserLocation visible={true} animated={false} />
```

UserLocation's dot will actually appear underneath the `ShapeSource` markers.

If we force `UserLocation`'s `visible` to be false, then set to true once `onDidFinishLoadingMap` is triggered, then the location dot will appear above the markers.

However, if you zoom out far enough such that no markers are shown, and then zoom back in such that markers are shown at that zoom level, then user location's dot is yet again buried by the markers.

**Expected behavior**
The UserLocation blue dot should always appear on top, above the `ShapeSource` markers.

**Versions (please complete the following information):**
 - Platfrom: Android and iOS
 - Device: Emulator (Pixel 3, API 28), and Simulator (iPhone SE, XCode 10.3)
 - React Native Version 0.59.10

**Additional context**

- When using nitaliano/react-native-mapbox-gl's library, the location would consistently appear above the ShapeSource, I believe because the logic for `UserLocation` was implemented differently (see [source code](https://github.com/nitaliano/react-native-mapbox-gl/blob/6.1.2/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java#L135))
- Logic was added in the past / old library to add layers underneath User Location layer [[source code](https://github.com/nitaliano/react-native-mapbox-gl/commit/5e79678db982e09a6345aec5bdc819b7449bd403)]
- Other user-location-related features are hitting similar issues and need weird hacks (see [commit](https://github.com/react-native-mapbox-gl/maps/pull/215/commits/db2bdb3533501cb2002d7877231e9d0edf5eeaf4))
- If the app is hot reloaded, then the user location will properly show on top of the markers.

**Comment by jlo1** [comment]
Discovered that when `ShapeSource` gets rendered afterwards, `UserLocation` will be hidden underneath. So if I remove `renderUserLocation()` from the main `render()` function, and replace `renderMarkers` with snippet below, user location will properly show on top.

```
if (this.state.someState) { return this.renderUserLocation() ; }

return (
  <React.Fragment>
	<MapboxGL.ShapeSource
	    shape={featureCollection}
	    onPress={this.onMarkerPress}>
	    <MapboxGL.SymbolLayer />
	</MapboxGL.ShapeSource>
    {this.renderUserLocation()}
  </React.Fragment>
);
```

But ideally, the initial implementation should still work, of directly adding `UserLocation` as a child to `MapView`. Will this be fixed in a upcoming release? (Thank you for the great library btw!)

**Comment by ferdicus** [comment]
Elements will be rendered according to their order.
First elements will be rendered and then the subsequent once will be rendered afterwards/ on top.
Same way as react components.

You can play around with layer orders to have another order within your map view.

I would see this issue as a shortcoming of the current implementation and you are right, the userlocation should always be on top of everything else.

**Comment by devthejo** [comment]
The best solution I've found is to to reimplement UserLocation (getting location myself), as children of `ShapeSource` and using `aboveLayerID`, in my sample `markerPoints` is the higher level of my other `ShapeSource` children, of course, you need to add a `Feature` in shape that is your user location, that way I can have the user location point always on top but capture the onPress event through it and get below points:

```js
const onMarkerSelected = async (event) => {
  const features = event.features
    .filter(({ properties }) => !properties.isUserLocation) // remove user location from points pressed
    .sort(({ properties: x }, { properties: y }) => {
      // compare points properties here to select what point is higher priority
      // ...
    });
    // act here on the previously selected as higher or all feature touched by the onPress event
  }
}
```

```js
const userLocationFeature = {
  type: "Feature",
  properties: {
    isUserLocation: true,
  },
  geometry: {
    type: "Point",
    coordinates: [userCoords.longitude, userCoords.latitude],
  },
};
const shape = {
  type: "FeatureCollection",
  features: [...clusterFeature, userLocationFeature]
}
```

```jsx
<MapboxGL.ShapeSource shape={shape} onPress={onMarkerSelected}>
      <MapboxGL.CircleLayer
        filter={["==", "isUserLocation", true]}
        key="mapboxUserLocationPluseCircle"
        id="mapboxUserLocationPluseCircle"
        style={layerStyles.pluse}
        aboveLayerID="markerPoints"
      />
      <MapboxGL.CircleLayer
        filter={["==", "isUserLocation", true]}
        key="mapboxUserLocationWhiteCircle"
        id="mapboxUserLocationWhiteCircle"
        style={layerStyles.background}
        aboveLayerID="markerPoints""
      />
      <MapboxGL.CircleLayer
        filter={["==", "isUserLocation", true]}
        key="mapboxUserLocationBlueCicle"
        id="mapboxUserLocationBlueCicle"
        aboveLayerID="mapboxUserLocationWhiteCircle"
        style={layerStyles.foreground}
      />

     ...
</MapboxGL.ShapeSource>
```
