### ISSUE TITLE
Change shapeSource url on the fly

### ISSUE THREAD

**Issue by jeremybarbet** [react-native-mapbox-gl/maps#541]
**Describe the bug**
When changing the url props of the `MapboxGL.ShapeSource` component, it doesn't refresh.

**To Reproduce**
- Create a ShapeSource
- Create a button to switch between two geojson source urls
- Pass down this geojson state to the url props of the ShapeSource
- After pressing the button, the map still keeps the first source url

**Expected behavior**
Map should refresh and get new data source.

**Versions (please complete the following information):**
 - Platfrom: Android, iOS
 - OS: iOS13.1.3
 - SDK Version Mapbox iOS 5.3.2
 - React Native Version 0.61.4

**Additional context**
The only workaround I found so far, is to add a key props to the ShapeSource that forces to reload the map, but it's not good enough, and make the whole layer disappears and reappears again.

Using react-map-gl on the web, works perfectly for the exact same example.

**Comment by kylebarron** [comment]
A workaround could be trying to change `visibility` on the associated Layer style

**Comment by jeremybarbet** [comment]
Unfortunately, this is a simple reproduction case I submitted, but in my app, I'm switching between 66 different geojson so I can't afford to have 66 differents Shape Source

**Comment by Alaa-Ben** [comment]
Same issue ! I'm using a workaround for now but not scalable :/

**Comment by jeremybarbet** [comment]
What kind of workaround are you using?

**Comment by Alaa-Ben** [comment]
as @kylebarron said, i'm using conditionnal rendering. Not scalable though, specially in your use case.

**Comment by kylebarron** [comment]
I haven't gotten around to testing it yet, but I'm curious if it re-renders correctly when the `shape` prop is passed instead of the `url`.

**Comment by kristfal** [comment]
I don’t follow this:

“Pass down this geojson state to the url props of the ShapeSource” 

1) Is the shapesource a remote geojson?
2) Can you show an example with code? 
3) If 1 is true, have you tried to fetch the geojson and set it as a geometry directly? This approach gives you full control over caching, rendering, etc.

**Comment by jeremybarbet** [comment]
Hi @kristfal, sure thing, here is the reproduction repository: https://github.com/jeremybarbet/mapbox-shapesource-issue

1. Yes it's a url
2. https://github.com/jeremybarbet/mapbox-shapesource-issue
3. Do you mean, fetching the url, setting in a state returned as a FeatureCollection, and passing to using `shape` props to the `ShapeSoure`?

**Comment by Craytor** [comment]
This is also an issue with the RasterSource layer. There's no way to update the URL and have the layer update.

**Comment by Craytor** [comment]
I just figured it out! @jeremybarbet try also putting the key on the SourceLayer to force the layer to rerender. For example, this finally got my RasterSource layer to rerender:
```
<MapboxGL.RasterSource
    key={this.state.radarScan}
    id={this.state.radarScan}
    tileSize={256}
    tileUrlTemplates={[this.state.url]}
>
    <MapboxGL.RasterLayer key={this.state.radarScan} id={this.state.radarScan} style={{ rasterOpacity: 0.60 }} />
</MapboxGL.RasterSource>
```

**Comment by jeremybarbet** [comment]
@Craytor Yes, I mentioned it in my initial post. But using the `key` props force a whole render of the `MapboxGL.XSource` component which is not ideal.

**Comment by jeremybarbet** [comment]
@kristfal Any news about that?

**Comment by jeremybarbet** [comment]
Hi @mfazekas, I tried with the reproduction repository I created (https://github.com/jeremybarbet/mapbox-shapesource-issue) using the latest version of the package `"@react-native-mapbox-gl/maps": "react-native-mapbox-gl/maps#master"` and it still not update the ShapeSource.

I still need to use the `key` props to make it works

**Comment by mfazekas** [comment]
@jeremybarbet sorry there was a typo in `setURL` it should be corrected now to `setUrl` can you retry?!

https://github.com/react-native-mapbox-gl/maps/commit/21a8af9c1b7602acd6f3f949e38584bfe787f346

**Comment by jeremybarbet** [comment]
Yes it works lovely, thanks @mfazekas!

**Comment by victor0402** [comment]
After changing the URL, is it possible to know when the shape source is ready? 
I would like to show to the user an indicator that the new source is still loading, like a Spinner. I'm facing delays of a few seconds when loading bigger geojsons
