### ISSUE TITLE
RasterSource  can't  work fine with Geoserver TMS 

### ISSUE THREAD

**Issue by unionTime** [react-native-mapbox-gl/maps#559]
`
  <MapboxGL.RasterSource 
            id='stamenWatercolorSource'
            tileUrlTemplates={[
              'http://ip:8080/geoserver/gwc/service/tms/1.0.0/tanwan%3Agis_osm_roads_free_1@EPSG%3A900913@png/{z}/{x}/{y}.png'
            ]}
            tileSize={256}
           >
            <MapboxGL.RasterLayer
              id="stamenWatercolorLayer"
              sourceID="stamenWatercolorSource"
            />
          </MapboxGL.RasterSource>
`
 android (react-native)
![image](https://user-images.githubusercontent.com/19386499/70391391-97b0cf00-1a0f-11ea-987d-7c7dc138d788.png)
but I use Qgis , It work !
![image](https://user-images.githubusercontent.com/19386499/70391403-b2834380-1a0f-11ea-98f5-b5fb9f8aaff3.png)

can you help me?

**Comment by unionTime** [comment]
@unionTime 
```
"react": "16.9.0",
 "react-native": "0.61.3",
"@react-native-mapbox-gl/maps": "^7.0.8",
```

**Comment by lin-mengxin** [comment]
I have the same problem, have you solved it?
