### ISSUE TITLE
StyleURL TrafficDay and TrafficNight is missing in iOS

### ISSUE THREAD

**Issue by Shehzad10p** [react-native-mapbox-gl/maps#564]
in iOS MGLModule, implementation of TrafficDay and TrafficNight URLs are missing. It is available in android:
        styleURLS.put("TrafficDay", Style.TRAFFIC_DAY);
        styleURLS.put("TrafficNight", Style.TRAFFIC_NIGHT);

Issue is traffic Layer is not appearing on iOS. 
It was available in old versions. I have checked in nitaliano version as well, it is available https://github.com/nitaliano/react-native-mapbox-gl/blob/master/ios/RCTMGL/MGLModule.m

Is there any other way to show traffic Layer other than using StyleURL?

**Comment by mccooll** [comment]
You can specify the map style url using a custom string, for example "mapbox://styles/mapbox/light-v10"
