### ISSUE TITLE
Call PBF tile data is not displayed

### ISSUE THREAD

**Issue by duanzjun** [react-native-mapbox-gl/maps#567]
The PBF tile data is generated through geoserver. The call is not displayed, but the PNG format is show.

```
"@mapbox/mapbox-sdk": "^0.9.0",
"@react-native-mapbox-gl/maps": "^7.0.8",
"react": "16.9.0",
"react-native": "0.61.4",
````

```
<MapboxGL.MapView
    ref={c => (this._map = c)}
    style={{flex: 1}}
    styleURL={MapboxGL.StyleURL.Satellite}
>
    <MapboxGL.Camera
        followPitch={15}
        duration={300}
        zoomLevel={12}
        centerCoordinate={[112.922, 21.8455]}
    />
    <MapboxGL.VectorSource
        id={'rasterSource'}
        tileUrlTemplates={[
'http://192.168.0.39:18082/geoserver_bxonline/gwc/service/tms/1.0.0/bxonline%3AWD_GHTD_2018-06-24@EPSG%3A900913@pbf/{z}/{x}/{y}.pbf',
        ]}
        // tileSize={256}
        tms={true}
        scheme={'tms'}
    >
        <MapboxGL.RasterLayer
            id={'rasterLayer'}
            sourceID={'rasterSource'}
        />
    </MapboxGL.VectorSource>
</MapboxGL.MapView>
```

**Comment by kristfal** [comment]
The library fully supports custom sources, be it localhost and remote.

As such, this is an issue with your setup and not something we can debug with the code you provided.

**Comment by ansarikhurshid786** [comment]
have you got solution?

**Comment by punov** [comment]
@ansarikhurshid786 Have you found your way to make it work? Struggling with PBF rendering, nothing shows up, and logs like:
` LOG  Mapbox [info] Request failed due to a permanent error: Canceled  {"level": "warning", "message": "Request failed due to a permanent error: Canceled ", "tag": "Mbgl-HttpRequest"}`
for all the requests

**Comment by ansarikhurshid786** [comment]
@punov I am fetching it from remote https. can you post your code as well here

**Comment by ansarikhurshid786** [comment]
Yes sourlayerid require. so, is it working now right ?
