### ISSUE TITLE
Error Last location unavailable

### ISSUE THREAD

**Issue by arnaudambro** [react-native-mapbox-gl/maps#569]
I have this exception sometimes, on production (I can't reproduce in dev mode)

```
Error
Last location unavailable
node_modules/@react-native-mapbox-gl/maps/javascript/modules/location/locationManager.js in call at line 21:63
    this.onUpdate = this.onUpdate.bind(this);
  }
  async getLastKnownLocation() {
    if (!this._lastKnownLocation) {
      const lastKnownLocation = await MapboxGLLocationManager.getLastKnownLocation();
      if (!this._lastKnownLocation && lastKnownLocation) {
        this._lastKnownLocation = lastKnownLocation;
      }
    }
    return this._lastKnownLocation;
```

Full log here: https://sentry.io/share/issue/8037c6ed509a496aaa969bc23698ab04/

I actually happens quite often, Android only.

Any idea ? I think it might be related to when GPS is unavailable but location permission is given or something...

**Comment by mertozylmz** [comment]
Maybe you can try react-native-geolocation?
You can read this documents.

https://github.com/react-native-community/react-native-geolocation
https://github.com/Agontuk/react-native-geolocation-service

**Comment by L-Yeiser** [comment]
We are also seeing this quite often.

**Comment by zanaviska** [comment]
I've solved this by somehow. Few days try to solve it, that just run my project for iOS and voila, my android app works as it meant to be

**Comment by ivari** [comment]
Possibly related / for more information: https://github.com/mapbox/mapbox-events-android/issues/419

**Comment by ferdicus** [comment]
Yeah, it's a native error that bubbles up to the JS side.
Will wrap 
```js
const lastKnownLocation = await MapboxGLLocationManager.getLastKnownLocation();
```
in a `try...catch` block to prevent crashes

Any wishes, what it should log out :)
Should it log at all? 🤷‍♂
