### ISSUE TITLE
Feature request: sideload offline packs

### ISSUE THREAD

**Issue by kylebarron** [react-native-mapbox-gl/maps#574]
[This wiki](https://github.com/mapbox/mapbox-gl-native/wiki/Sideloading-offline-maps) explains how to create offline packs of a given area ahead of time, that are then bundled into a single file, so that for downloading large areas you only need to make one HTTP request.

It doesn't appear that there's currently support for merging prebuilt offline region packs, but from that wiki it would seem that it's not too hard to implement.

It looks like the only function that would have to be wrapped is
```
OfflineManager.mergeOfflineRegions(path, callback)
```
for android. I can't find the right function for iOS. The wiki claims it's
```
-[MGLOfflineStorage addContentsOfFile:withCompletionHandler:]
```
though I don't see that listed in the [OfflineStorage docs](https://mapbox.github.io/mapbox-gl-native/macos/0.6.0/Classes/MGLOfflineStorage.html).

**Comment by tsemerad** [comment]
Hi @kylebarron, I was just about to make a PR adding this functionality. I implemented it last week in my app, tested and working on iOS and Android. I'll post back here when I have the PR up.
