### ISSUE TITLE
Image is not show on top of the Map view on android

### ISSUE THREAD

**Issue by sajidit** [react-native-mapbox-gl/maps#575]
I want to build location picker similar as shown on the mapbox sdk example https://docs.mapbox.com/android/maps/examples/location-picker/.

Code seems to work find on IOS but on Android I can not see location picker image, following is my example

export default function MapComponent(): ReactElement {
  let _map: MapboxGL.MapView;
  let iconCoordinate: any;
  const [loading, setLoading] = useState(true);

  const locationButton = (): ReactElement => (
    <View style={{ justifyContent: 'center', alignItems: 'center', flex: 1 }}>
      <Image
        style={{
          justifyContent: 'center',
          alignItems: 'center',
          alignSelf: 'center',
          marginBottom: 2,
        }}
        source={require('../../../assets/icons8-marker.png')}
      />
    </View>
  );

  return (
    <View style={styles.container}>
      <MapboxGL.MapView
        style={styles.map}
        ref={c => (_map = c)}
        styleURL={'asset://empty.json'}
        attributionEnabled={false}
        logoEnabled={false}
        onDidFinishLoadingMap={(): void => {
          setTimeout(() => setLoading(false), 1000);
        }}
      >
        <MapboxGL.Camera
          centerCoordinate={[100.508223, 13.763486]}
          zoomLevel={14}
        />
        {!loading && locationButton()}
        <MapboxGL.RasterSource
          id="azureMaps"
          // ref={rasterRef}
          tileSize={512}
          tileUrlTemplates={[AZURE_TILE_URL_TEMPLATE]}
        >
          <MapboxGL.RasterLayer id="azureMapLayer" />
        </MapboxGL.RasterSource>
      </MapboxGL.MapView>
      <AppButton
        title="common.selectLocation"
        onPress={(): void => {
          _map
            .getCoordinateFromView([iconCoordinate.x, iconCoordinate.y])
            .then(res => console.log(res));
        }}
      />
    </View>
  );
}

Following is my environment 
"@react-native-mapbox-gl/maps": "^7.0.8",
"react": "16.11.0",
"react-native": "0.61.4",

Output on IOS
![Screen Shot 2562-12-18 at 14 40 22](https://user-images.githubusercontent.com/3327390/71065734-6620cc00-21a4-11ea-9c21-393582c97b72.png)

Output on Android
![image](https://user-images.githubusercontent.com/3327390/71065878-b26c0c00-21a4-11ea-99fb-090519d36ca8.png)

**Comment by kristfal** [comment]
You need to put the view outside <MapView> at the bottom of the JSX and position it by using `position: absolute`. Something like:

```jsx
const absoluteStyle = {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  height: '100%',
  width: '100%',
}

<MapView />
<View style={absoluteStyle}>
  <Icon />
</View>
```
