### ISSUE TITLE
Wrong calculation of coordinates from `getCoordinateFromView()` on Android

### ISSUE THREAD

**Issue by anfriis** [react-native-mapbox-gl/maps#576]
**Describe the bug**
When using the `getCoordinateFromView()` on a `MapView`, the returned lat/lng coordinates are correct on iOS but wrong on Android. 
![Mapbox](https://user-images.githubusercontent.com/1019341/71075142-dec36080-2183-11ea-8c55-60a6502a24c2.png)

**To Reproduce**
I have a drawing-on-map feature in my app, so to illustrate the issue I have drawn a diamond that touches each side of the device screen. The x/y screen points from the drawing are then calculated to lat/lng coordinates using `getCoordinateFromView()` which is put into a `Feature` that is displayed on map using `ShapeSource`, `FillLayer` and `LineLayer`. iOS places the feature correctly, touching each side of the screen but on Android it is placed in the top left corner, whereas it should be placed the same as on iOS. 

**Expected behavior**
Android should place the feature in the same place as iOS does. 

**Screenshots**
See above

**Versions (please complete the following information):**
 - Platform: Android
 - Device: [iPhone8,Pixel 2]
 - OS: [iOS13.3, Android 9.+ API 29]
 - React Native Version [e.g. 0.61.2]
- react-native-mapbox-gl/maps: 7.0.8

**Comment by jaceee** [comment]
Same is happening to us, we dont have an iOS app
![80469938_2165771233730808_7422447586277064704_n](https://user-images.githubusercontent.com/5000478/71385732-382df400-25b7-11ea-97b7-5be7fafb55dc.jpg)

**Comment by kristfal** [comment]
This is very likely a lack of applying device pixel density when passing the RN view dimensions to mapbox when requesting bounds. 

Should be fairly easy to trace the calls and multiply pixel density value prior to passing to mapbox.

**Comment by anfriis** [comment]
Thanks for the input @kristfal. 
I will try to look into this and make a PR

**Comment by anfriis** [comment]
PR up now #619
