### ISSUE TITLE
iconImage:['get','icon'] doesn't seem to work with uri Android

### ISSUE THREAD

**Issue by ZamirAmiri** [react-native-mapbox-gl/maps#580]
**Describe the bug**
Hello, I'm kind of new to react-native and to mapbox-gl, so I'm not sure if this is actually a bug or not.
My main goal is to display multiple icons on the map with each icon having a different image which i get as a uri.
To do that i use ShapeSource and SymbolLayer in the following way.

`
<MapboxGL.ShapeSource
  id="symbolLocationSource"
  hitbox={{width: 20, height: 20}}
  shape={featureCollection}>
  <MapboxGL.SymbolLayer
    id="symbolLocationSymbols"
    style={
     {
      iconImage:['get','image'],
      iconSize:2,
     }
    }
  />
</MapboxGL.ShapeSource>
`

**Comment by ZamirAmiri** [comment]
Never mind i found my mistake.

**Comment by EyadAyman658** [comment]
> Never mind i found my mistake.

what was it ?
