### ISSUE TITLE
UserLocation indicator is blocking touches - can't press a marker behind it

### ISSUE THREAD

**Issue by dancherb** [react-native-mapbox-gl/maps#584]
My UserLocation indicator doesn't have an onPress event and isn't going to. However, when there's a marker behind the indicator that does have an onPress event, tapping the marker doesn't work because the user indicator is "blocking" it. Is there a way around this? Thanks!

Android (not tested on iOS) / SDK 28 / RN 0.60.0 / react-native-mapbox-gl 7.0.4

**Comment by kristfal** [comment]
We already have a ticket about it with a workaround. Please search it up. Closing.
