### ISSUE TITLE
Animation duration use seconds instead of milliseconds on iOS

### ISSUE THREAD

**Issue by Hless** [react-native-mapbox-gl/maps#586]
**Describe the bug**
It appears that iOS expects number values as seconds on layer properties like `circleRadiusTransition.duration`, while Android uses milliseconds. This results in very slow animations on iOS if you initially tested on android.

**To Reproduce**
Create a circle layer with the following  style and animate it's size:
```
<MapboxGL.CircleLayer
          key={`circle`}
          id={`circle`}
          style={{
            circleRadius: this.state.circleVisible ? 100 : 0,
            circleRadiusTransition: {
              delay: 0,
              duration: 1000 
            },
            circleOpacity: 0.5,
            circleColor: "#000000"
          }}
        />
```

**Expected behavior**
Android and iOS should have the same behaviour.

**Versions (please complete the following information):**
 - Platfrom: Android & iOS
 - Device: Huwei Mate  20 Lite and iPhone 7 (also Simulator iPhone 11)
 - OS: Android 9.1.0,  iOS 13.2.3
 - SDK Version: @react-native-mapbox-gl/maps@7.0.8
 - React Native Version: 0.61.4

**Comment by mertozylmz** [comment]
if you duration make 1 it works. For iOS.

**Comment by Hless** [comment]
@mertozylmz Yes, I understand. This is what I stated in the bug description.

I opened this issue because it's an inconsistency that is not documented elsewhere and may need to be adressed.

**Comment by kristfal** [comment]
Happy to see a PR here. This change should be done on the native side and comment that it is done for platform parity in the code. I'd say we should use milliseconds for both platforms.

**Comment by Hless** [comment]
Can definitely take a look at it soon-ish. The strange thing about this is that the Mapbox SDK itself is really vague about the transition parameters:
https://docs.mapbox.com/ios/api/maps/5.5.0/Structs/MGLTransition.html#/c:@S@MGLTransition@FI@duration

@kristfal Quick question, since there are alot of transition style properties over various components, what would be a good way to implement this? Seems rather tedious to have to implement it manually across the whole code base.

**Comment by kristfal** [comment]
I’ll have a look. Likely it makes sense to pick it up as soon as it has passed over the bridge. If that is not convenient, we can ofc do it on the JS side.

**Comment by mertozylmz** [comment]
@kristfal SymbolLayer needs these animations. Can you add animation for SymbolLayer? Because I need rotate animation urgently.

**Comment by ferdicus** [comment]
valid issue, go away stalebot
