### ISSUE TITLE
How to disable location permission request ?

### ISSUE THREAD

**Issue by arnaudambro** [react-native-mapbox-gl/maps#589]
Hi there,

I am asking for location permission on an other part of my App, and I am not requesting for `LOCATION_ALWAYS` but only for `LOCATION_WHEN_IN_USE`.
When the map loads, it always request the `LOCATION_ALWAYS` permission, which is annoying.
How can I disable the map to request location permission ?
I actually tried to find in the code base but I couldn't find...

Thanks !

**Comment by kristfal** [comment]
This is part of the underlying native SDKs. I'm not sure if they expose some properties for us to set permission type. I'd recommend you look upstream in https://github.com/mapbox/mapbox-gl-native-ios abd https://github.com/mapbox/mapbox-gl-native-android and see if they expose something for us to hook into.

**Comment by mfazekas** [comment]
@arnaudambro  is this ios or android?!
Also which rnmgl version and which native libraries.
Looking at the code on ios they prefer whenInUse.

We also request when in use on ios:
https://github.com/react-native-mapbox-gl/maps/blob/0c85984fdc6333334ed12fd34ada143c8a07ca73/ios/RCTMGL/RCTMGLLocationManager.m#L54

https://github.com/mapbox/mapbox-gl-native-ios/blob/e62a7cade38134c9807fbf3e0428d647fb0b77d8/platform/ios/src/MGLMapView.mm#L5445-L5469

**Comment by mfazekas** [comment]
Closing will repoen when we have details

**Comment by arnaudambro** [comment]
Sorry, getting back on my MapBox project a few days ago, and I didn't see the evolution of the feature...
This is especially happening in iOS, I didn't test Android yet.
And it's happening in iOS 10.3.1, but not in iOS > 13, so it's not an issue anymore !

**Comment by Stophface** [comment]
Yes, how to disable this? Requesting permissions is something, UIX Designer and Developer should have in their hands!

**Comment by mahipalsingh-syt** [comment]
how to disable location permission request? we are not requesting any user location permission but sdk is promoting alert on screen.
