### ISSUE TITLE
[Android]: Map zoom isn't smooth like iOS, very choppy?

### ISSUE THREAD

**Issue by spotelf13** [react-native-mapbox-gl/maps#59]
We've been using react native mapbox for awhile and still haven't quite figured out to why the android map experience is pretty subpar to how the iOS experience handles zoom on the map. 

When users zoom with the iOS version it's smooth. However on android it seems like it has slow fps and the zoom doesn't seem to be elastic. 

What I mean by elastic is when you zoom out or zoom in on say react native maps, the action of zooming doesn't stop when you take your fingers off the screen. But with mapbox is seems to perform some sort of elastic animation then abruptly stops (on android), making the zooming experience feel a bit choppy and not as good as iOS...

**Comment by systemlevel** [comment]
@spotelf13 We've experienced the same issue on Android platform.

**Comment by ferdicus** [comment]
We're using `6.1.4` from the old repo and are exclusively on android (atm).
I've never experienced any choppiness or lag in map zooms I have to admit. Maybe it's just the lack of comparison...

Neither programmatic zooms nor manual zooms cause any lags.

Disclaimer:
* we're using HERE map tiles to render our map.
* we're `FollowingWithCourse`
* we're rendering three layers that draw an individual circle for the destination & a linePath for the route

**Comment by mfazekas** [comment]
It would be great to clarify those:
1.) is this issue only affects the new repo?
2.) is this issue only affects the RN version of mapbox-gl-native or can it be reproed on the [android mapbox gl native example app](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/android)?

**Comment by jliebrand** [comment]
I've also noticed a delay in starting the zoom... it's like a threshold of pinching needs to happen before it then "kicks in" which adds to the perceived jutter/lag for zooming... is that something anyone else has noticed?  (this is on android)

**Comment by alexiri** [comment]
Yes, I see that as well.

**Comment by noway** [comment]
I've browser mapbox-gl-native repo, and I have a hypothesis that it's a combination of https://github.com/mapbox/mapbox-gl-native/issues/14136 and just low FPS.

**Comment by noway** [comment]
i think this should be reopened 😢

**Comment by Balasnest** [comment]
Yes. It's very choppy. Any solution or workaround?

**Comment by kristfal** [comment]
There is no workarounds for us on this side. Any requests for enhancements should be posted at https://github.com/mapbox/mapbox-gl-native/
