### ISSUE TITLE
Update native iOS library version and download endpoints

### ISSUE THREAD

**Issue by lgzajac** [react-native-mapbox-gl/maps#592]
Hi!

This is not exactly a bug (tho related to #388, btw, i am using npm version 7.0.8), but dependency issue.

Mapbox splitted core repos (https://github.com/mapbox/mapbox-gl-native/issues/15971) and looks like dep-fu is not tracking it. 

Current version of android lib is 8.6.0 (https://github.com/mapbox/mapbox-gl-native-android/releases/tag/android-v8.6.0), with a lot of changes since 8.2.1.

Would it be possible to update it asap? I will try to fix it on my own and create a pull request, but since this can be not trivial change, i could be not able to.

Regards and thanx for great work

**Comment by mfazekas** [comment]
@lgzajac pls do a PR, i don't think depfu has ever tracked native deps. I think only npm deps from pacakge.json.

See https://github.com/react-native-mapbox-gl/maps/pull/196 for an example PR that updated versions

**Comment by ferdicus** [comment]
> I think only npm deps from pacakge.json.

Right, depfu only checks js (&/or ruby deps).

**Comment by kristfal** [comment]
Updated Android is in master. I'll change this title to iOS.

**Comment by mfazekas** [comment]
iOS was updated to 5.6 with podfile
