### ISSUE TITLE
How I can show zoom button and compass?

### ISSUE THREAD

**Issue by antropovAlexandr** [react-native-mapbox-gl/maps#595]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

Hi, I use Mapview and Camera components and set all properties in true. But, I really dont understand, how I can show/hide zoom button and ather controls elements on map. Its doesnt work for me((
Maybe somebody can help me((

**Screenshots**
![123](https://user-images.githubusercontent.com/35536883/71660520-597fa480-2d5c-11ea-8fbc-ac27873110f4.png)

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: Pixel 3
 - OS: Android 9
 - SDK Version 28
 - React Native Version 0.61

**Additional context**

**Comment by ferdicus** [comment]
hey there, did you also try on a real device? 
I know, that the emulator is a bit flaky when it comes to rendering mapbox

**Comment by kristfal** [comment]
This library is a map rendering library. UI elements, such as zoom buttons is something you need to implement yourself. The prop `zoomEnabled` is there to enable/disable user zoom via gestures, and doesn't have anything to do with UI.

**Comment by ferdicus** [comment]
Yes kristfal is right, having said that compass should display when enabled.

**Comment by sauhardar** [comment]
Is there a way to customize the compass?

**Comment by alex83130** [comment]
So we don't have any way of include the `mapboxgl.NavigationControl()` :   https://docs.mapbox.com/mapbox-gl-js/example/navigation/  ?

**Comment by ferdicus** [comment]
JS != Java/Obj-C 

This is a wrapper around the native Android and iOS SDKs of Mapbox. 
Unfortunately, there is no feature parity in those libs.
