### ISSUE TITLE
PointAnnotation or SymbolLayer with lottie

### ISSUE THREAD

**Issue by C4i81** [react-native-mapbox-gl/maps#598]
**Describe the bug**
Hi,guys,I want to display some animated label points on the map, but these label points are not displayed at all, or they are displayed but not animated.need help~

**my  first code(displayed but not animated.)**
{<View style={styles.container}>
        <MapboxGL.MapView
          style={styles.map}
          ref={mapView => (this._mapView = mapView)}
          onPress={this.onPress}
          onRegionWillChange={() => {
            console.log('moving start');
          }}
          onRegionDidChange={() => {
            console.log('moving ended');
          }}
          styleURL="http://xxx.xxx.x.xxx:xxxx/mapBoxLayer/getLocalStyle/"
          onDidFinishLoadingMap={this.onDidFinishLoadingMap}
          logoEnabled={false}
          attributionEnabled={false}>
          {this.renderAnnotations()}
          {/* 背景色 */}
          <MapboxGL.BackgroundLayer
            id={'background-layer'}
            belowLayerID={'baseMap'}
            style={styles.back}
          />
          <MapboxGL.Camera
            maxBounds={bounds}
            ref={camera => (this.camera = camera)}
            zoomLevel={15}
            minZoomLevel={13}
          />

          {
            <MapboxGL.PointAnnotation
              // onSelected={feature => {
              //   this.onAnnotationSelected(i, feature);
              // }}
              id={'pointAnnotation'}
              //onDeselected={() => this.onAnnotationDeselected(i)}
              coordinate={[110.43206630556807, 21.040148152209852]}>
              {
                <View
                  style={{
                    flex: 1,
                    justifyContent: 'center',
                    alignItems: 'center',
                    backgroundColor: 'transparent',
                  }}>
                  <Point />
                </View>
              }
            </MapboxGL.PointAnnotation>
          }
        </MapboxGL.MapView>
      </View>
}

***point.js****
import React from 'react';
import LottieView from 'lottie-react-native';

export default class point extends React.Component {
  componentDidMount() {
    this.animation.play();
    // Or set a specific startFrame and endFrame with:
  }

  render() {
    return (
      <LottieView
        ref={animation => {
          this.animation = animation;
        }}
        style={{
          width: 80,
          height: 80,
        }}
        autoPlay={true}
        loop
        source={require('../../android/app/src/main/res/assets/alarm.json')}
      />
    );
  }
}

*****did not show the point at all ****
{
<MapboxGL.ShapeSource
              id="markersShape"
              shape={{
                type: 'Feature',
                properties: {
                  id: 'asd',
                },
                geometry: {
                  type: 'Point',
                  coordinates: [110.45156770056178, 21.048534543403022],
                },
              }}>
              <MapboxGL.SymbolLayer
                id="asd"
                sourceID="markersShape"
                minZoomLevel={1}
                style={{
                  iconSize: 10,
                  iconAllowOverlap: true,
                }}>
                <View
                  style={{height: 100, width: 100, backgroundColor: 'gray'}}
                  pointerEvents="none" // this is important for the onPress prop of ShapeSource to work
                >
                  {/* ... place what you want as a marker here, even SVG from react-native-svg for instance */}
                  <Image source={require('../assets/imgs/info.png')} />
                </View>
              </MapboxGL.SymbolLayer>
            </MapboxGL.ShapeSource>
}

**Expected behavior**
displayed and animated.

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: Redmi Note 8
 - OS: android 9
 - SDK Version :{
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28}
 - "react": "^16.9.0",
    "react-native": "^0.61.4",
 "@react-native-mapbox-gl/maps": "^7.0.8",
   "lottie-ios": "3.1.3",
    "lottie-react-native": "^3.3.2",

**Comment by kristfal** [comment]
Lottie doesn't work within the context of mapbox-gl-native. For advanced animations, your best bet is to provide a GL surface that you sync with the viewport of the map. This is outside the scope of this library.

**Comment by C4i81** [comment]
> Lottie在mapbox-gl-native的上下文中不起作用。对于高级动画，最好的选择是提供一个与地图视口同步的GL曲面。这超出了此库的范围。

thanks

**Comment by pelayomartinez** [comment]
Is there a property/method that can help with syncing to the viewport? One that doesn't involve setting state and lots of rerenders?
