### ISSUE TITLE
Entire map (including layers) darkens after some time and stays that way

### ISSUE THREAD

**Issue by dancherb** [react-native-mapbox-gl/maps#600]
Hard to pin down exactly what's going on, but I've noticed often during sessions the map will have a dark layer. This appears a few seconds to a few minutes after loading the map. In the screenshot you can see a white square rendered on top of the map by React Native, and then the same image file rendered as part of a symbol layer within a shape source.

![darken_demo](https://user-images.githubusercontent.com/32280121/71778461-0305a680-2fa6-11ea-8f14-69e803bcad08.png)

Android
React Native: 0.61.5
@react-native-mapbox-gl/maps: 7.0.4

**Comment by kristfal** [comment]
This sounds like an issue with the upstream map engine and it is not something we can fix here. 

I'd recommend you post [there](https://github.com/mapbox/mapbox-gl-native) as we just use those map engines as is.

You may also want to try the upcoming 7.0.9 which contains the latest underlying android SDK to see if it reproduces there.
