### ISSUE TITLE
Map symbols and compass not rendering correctly (android)

### ISSUE THREAD

**Issue by pranavpandey1998official** [react-native-mapbox-gl/maps#601]
<img width="437" alt="Screenshot 2020-01-06 at 2 12 37 PM" src="https://user-images.githubusercontent.com/44601530/71806399-b9dd5180-308e-11ea-8ed6-3526ca4c016c.png">

can you see that many of the highway icons and railway station icons are black even the background of compass is black(i am assuming it shouldn't be that way)

**Comment by mattijsf** [comment]
Please try it on a physical Android Device. Unfortunately android Emulator is still very flaky when it comes to rendering certain OpenGL content. You can configure the emulator to use "SwiftShader" for OpenGL rendering, that'll improve the appearance but with a large performance hit.  

Let's hope they can fix this upstream: See also https://github.com/mapbox/mapbox-gl-native/issues/10829
