### ISSUE TITLE
Mapbox Navigation

### ISSUE THREAD

**Issue by John0x** [react-native-mapbox-gl/maps#604]
Hey there,
I'm working on a project right now that required in-app turn by turn based navigation and I'm aware that Mapbox has a module for that which isn't part of this package. My question is whether or not it's in the scope of this package?
I'm willing to implement it, just wondering if I should create a separate package or just contribute to this one

**Comment by ferdicus** [comment]
I think that question came up several times already and I think it was usually answered with: Not in scope of this repo.

Having that said, I think a separate package that place nice with this one would definitely be cool.

**Comment by mfazekas** [comment]
@John0x i agree with @ferdicus, it's likely a new package built on top of rnmbgl and rnmbnavigation. In case you need any supporting stuff implemented in this package let us know.
