### ISSUE TITLE
ETA on new version

### ISSUE THREAD

**Issue by chrisparton1991** [react-native-mapbox-gl/maps#606]
Hi, sorry to be a pain, but do we have an idea on when the next version will be released?

It's not much, but I'd be more than happy to PayPal USD$20 to whoever gets a release out.

I have workarounds in place for the things I'm waiting for, so all good if now's not a good time for a release. If that's the case, feel free to close this issue.

**Comment by ferdicus** [comment]
Hey Chris, is there something specific you're waiting for?
At the end of the day, you could point at a specific commit instead of choosing a released version.

**Comment by kristfal** [comment]
Hey, sorry for the slow response here. Between Christmas holidays and life, I haven't been as attentive as I'd like to. New version will arrive in 20-30 min, just need it to pass CI.

As for PayPal, hold off on that, as there is no need. 

I'll pick up more stuff and look at a few improvements I'd like to get in the coming weeks.

Closing ticket.

**Comment by chrisparton1991** [comment]
Thanks a bunch @kristfal, appreciate you getting this out for us during such a busy time!
