### ISSUE TITLE
gecoding react native

### ISSUE THREAD

**Issue by hash86** [react-native-mapbox-gl/maps#607]
is there any package or solution to use forward geocoding and reverse geocoding of mapbox for react-native ?

https://docs.mapbox.com/api/search/#geocoding

**Comment by ferdicus** [comment]
As far as I can see it's just a mapbox endpoint one can query.
I don't understand how that would be in the scope of this repo.

This repo takes care of this: `An unofficial React Native library for building maps with the Mapbox Maps SDK for iOS and Mapbox Maps SDK for Android`

Please check the documentation you linked in your post - it explains what and how to use it.

**Comment by ferdicus** [comment]
@kristfal, can be closed
