### ISSUE TITLE
Application crashes when running with react-native run-android within x86 android emulator

### ISSUE THREAD

**Issue by LukeSilva** [react-native-mapbox-gl/maps#613]
**Describe the bug**

After installing this package, the application will crash if it is built with `react-native run-android`. If the application is built with android studio, the application will not crash.

Initial error:

             System.err  W  java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.localz.technician.local/lib-main/libc++_shared.so" has unexpected e_machine: 40 (EM_ARM)
                         W      at java.lang.Runtime.load0(Runtime.java:928)
                         W      at java.lang.System.load(System.java:1633)
                         W      at com.facebook.soloader.SoLoader$1.load(SoLoader.java:393)
                         W      at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:77)
                         W      at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:458)
                         W      at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:731)
                         W      at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
                         W      at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:587)
                         W      at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:111)
                         W      at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
                         W      at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:458)
                         W      at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:731)
                         W      at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
                         W      at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:587)
                         W      at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:111)
                         W      at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
                         W      at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:458)
                         W      at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:731)
                         W      at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
                         W      at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
                         W      at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
                         W      at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:304)
                         W      at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:279)
                         W      at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:88)
                         W      at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
                         W      at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:91)
                         W      at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:80)
                         W      at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:52)
                         W      at com.technician.MainActivity.onCreate(MainActivity.java:28)
                         W      at android.app.Activity.performCreate(Activity.java:7136)
                         W      at android.app.Activity.performCreate(Activity.java:7127)
                         W      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
                         W      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
                         W      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
                         W      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                         W      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                         W      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                         W      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
                         W      at android.os.Handler.dispatchMessage(Handler.java:106)
                         W      at android.os.Looper.loop(Looper.java:193)
                         W      at android.app.ActivityThread.main(ActivityThread.java:6669)
                         W      at java.lang.reflect.Method.invoke(Native Method)
                         W      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                         W      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
               SoLoader  E  couldn't find DSO to load: libc++_shared.so caused by: dlopen failed: "/data/data/com.localz.technician.local/lib-main/libc++_shared.so" has unexpected e_machine: 40 (EM_ARM)

Which finally crashes with: 

               SoLoader  E  couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libglog_init.so caused by: couldn't find DSO to load: libglog.so caused by: APK was built for a different platform
         AndroidRuntime  E  FATAL EXCEPTION: OkHttp Dispatcher
                         E  Process: com.localz.technician.local, PID: 5912
                         E  java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: couldn't find DSO to load: libglog_init.so caused by: couldn't find DSO to load: libglog.so caused by: APK was built for a different platform
                         E      at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
                         E      at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
                         E      at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
                         E      at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
                         E      at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:31)
                         E      at com.facebook.react.bridge.Inspector.<clinit>(Inspector.java:20)
                         E      at com.facebook.react.bridge.Inspector.getPages(Inspector.java:27)
                         E      at com.facebook.react.devsupport.InspectorPackagerConnection.getPages(InspectorPackagerConnection.java:152)
                         E      at com.facebook.react.devsupport.InspectorPackagerConnection.handleProxyMessage(InspectorPackagerConnection.java:72)
                         E      at com.facebook.react.devsupport.InspectorPackagerConnection$Connection.onMessage(InspectorPackagerConnection.java:223)
                         E      at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
                         E      at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
                         E      at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
                         E      at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
                         E      at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
                         E      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
                         E      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         E      at java.lang.Thread.run(Thread.java:764)```

Adding the following to the defaultConfig in the application's build.gradle will fix the issue:

        ndk {
                abiFilters "x86"
        }

However, this prevents the application from working on arm devices. Adding `"armeabi-v7a"` to the list above will reintroduce the crash.

**To Reproduce**
Install the dependency in existing project, run with `react-native run-android` instead of using android studio, while using an x86 android emulator.
The application crashes.

(Uncertain if this is reproducible from a minimal react native setup)

**Expected behavior**
Application should run without crashing

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: x86 emulator, Nexus5X api 28[e.g. iPhone6]
 - OS:  android 9
 - SDK Version 28
 - React Native Version 0.60.5

**Additional context**

Full crash log: https://hastebin.com/iwodotehas.pl
build.gradle: https://hastebin.com/dupefiqafu.rb

**Comment by ivari** [comment]
Seconded, and it seems this release also had some side-effects on the production release.

**Comment by systemlevel** [comment]
@LukeSilva What version of react-native-mapbox-gl are you using?

**Comment by LukeSilva** [comment]
I was using 7.0.9. Looking at the recent issues, I tried downgrading to 7.0.8, which worked correctly without a crash.

**Comment by LukeSilva** [comment]
FYI: I've just tried using the latest git version (with #627 merged in), and this crash still occurs.

**Comment by mfazekas** [comment]
@LukeSilva  can you try with current master. It has now 9.0.0 on android. Not sure why we don't see this issue with our example app.

**Comment by HY1221** [comment]
I ran the example app and crashed immediately. Also I downgrade it to 7.0.8 and follow the instruction here -
https://github.com/react-native-mapbox-gl/maps/blob/master/android/install.md

skip step 4. It runs well with some minor adjustment. 
Good luck.

**Comment by mfazekas** [comment]
@HY1221 what version are you talkin about, the one which crashed?!

**Comment by ferdicus** [comment]
> skip step 4. It runs well with some minor adjustment.
Good luck.

Since when do we have autolinking?!

**Comment by ferdicus** [comment]
closing this due to lack of response - please follow these steps before opening a new issue:
* try building the `example` project from `master`

**Comment by jlo1** [comment]
@ferdicus @mfazekas , this seems related to the native android library issue here: https://github.com/mapbox/mapbox-gl-native-android/issues/111

**Comment by 3bugs** [comment]
Add this inside `android` in app/build.gradle.

```
configurations.all {
    resolutionStrategy {
        force "com.facebook.soloader:soloader:0.8.2"
    }
}
```

ref: [](https://github.com/facebook/react-native/issues/28489)
