### ISSUE TITLE
Feature Request: Arc Layer

### ISSUE THREAD

**Issue by safaiyeh** [react-native-mapbox-gl/maps#616]
## Support for Arc Layer
To achieve parity between our web implementation and React Native, we would want Arc Layer similar to deck.gl's https://deck.gl/#/examples/core-layers/arc-layer.

What would be needed to get this supported implementation wise?

**Comment by kristfal** [comment]
This is a deck-gl feature, and not a underlying mapbox-gl feature. Mapbox doesn’t have any primitives for arch layers (neither for web nor mobile), so I am afraid we can’t support it at this time. 

The proper solution here would be to expose deck-gl inside react native and sync it with the native maps, which would a rather large undertaking.
