### ISSUE TITLE
feat(map-options): Expose foregroundLoadColor to react-native

### ISSUE THREAD

**Issue by ferdicus** [react-native-mapbox-gl/maps#621]
### Problem
Each time a new MapView is loaded, a black surface will be visible before any map content is rendered.

See this upstream ticket: https://github.com/mapbox/mapbox-gl-native/issues/10990

### Solution
It is possible to pass a color option to replace the black surface with another color instead.
See documentation: https://docs.mapbox.com/android/api/map-sdk/8.6.1/com/mapbox/mapboxsdk/maps/MapboxMapOptions.html#foregroundLoadColor-int-

**Comment by heron2014** [comment]
A little hack to solve the black flash, set opacity state to 0 and on onDidFinishLoadingMap set it to 1

```
<MapboxGL.MapView
    style={[styles.container, { opacity: mapOpacity }]}
    onDidFinishLoadingMap={() => setMapOpacity(1)}>
```

Not the proper solution but it fixes temporarily

**Comment by hexadecy** [comment]
That wasn't enough, I've added:
```javascript    
const onWillStartLoadingMap = () => {
   setMapOpacity(0.5);
};
```
