### ISSUE TITLE
App crashes when mounting `<UserLocation />` (RCTMGLLocationModule.start got 0 arguments, expected 1)

### ISSUE THREAD

**Issue by hanpama** [react-native-mapbox-gl/maps#622]
**Describe the bug**
App crashes when mounting `<UserLocation />`

**To Reproduce**
Use `<UserLocation />` component  as a child of `<MapView />` component("@react-native-mapbox-gl/maps": "7.0.9")

**Expected behavior**
Expected to show a dot on the device location

**Screenshots**
<img width="536" alt="스크린샷 2020-01-16 오후 5 25 39" src="https://user-images.githubusercontent.com/7418482/72506575-8025fb00-3885-11ea-9b1d-2ee2dd91402c.png">

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: Emulator Nexus 5X API 29 x86 (1080 × 1920: 420dpi) |  | 3.9 GB
 - OS: Android 10.0 (Google APIs) | x86
 - SDK Version 28
 - React Native Version "react-native": "0.61.5"

**Additional context**

RCTMGLLocationModule.start got 0 arguments, expected 1

It raises the error saying it hasn't passed 1 argument required.
And I am guessing the missing argument is `minDisplacement`, which has been recently added to `RCTMGLLocationModule.java`. 

https://github.com/react-native-mapbox-gl/maps/pull/546/files#diff-44868fc4ad781b211fd026ed6a88bd38L73-R75

Are they related?
When using 7.0.8, it works fine.

**Comment by ferdicus** [comment]
hey there, sorry for the report.
I can not reproduce this behavior with my setup.
`minDisplacement` will pass a default value of `0` if it isn't defined in your setup.

Two questions:
* did you encounter this also on a physical device
* could you share your MapView code snippet

Thanks

**Comment by hanpama** [comment]
Thanks, @ferdicus !
I will try and share the result soon

**Comment by ferdicus** [comment]
Any update on this - also did you try the current master?
It has an updated android dependency

**Comment by ErikTillberg** [comment]
Received this error on a real device on v7.0.9, upgrade to v7.2.0 and the error persists.

**Comment by kristfal** [comment]
Sounds like you have a mismatch between JS and native code. Make sure to clean build and verify that both JS and native code is updated.

**Comment by hanpama** [comment]
After removing android/app/build directory, the latest version works fine on my Android emulator.

`package-lock.json`:

```
"@react-native-mapbox-gl/maps": {
      "version": "7.2.0",
```

Currently I cannot reproduce the error.

**Comment by kristfal** [comment]
Good. It was a partial upgrade issue then. Closing.
