### ISSUE TITLE
Build errors for iOS example

### ISSUE THREAD

**Issue by DavidStummer** [react-native-mapbox-gl/maps#623]
**Describe the bug**
Build error when trying to build iOS example

**To Reproduce**
Follow the instructions to build the example for iOS. When it comes to the build there are errors. I tried building from xcode, same issue.

**Screenshots**
<img width="1477" alt="Screenshot 2020-01-16 at 09 43 04" src="https://user-images.githubusercontent.com/4497624/72513123-ac6d5780-3844-11ea-8e36-b7b350830913.png">

**Versions (please complete the following information):**
 - Platfrom: iOS
 - React Native Version 0.61.1

**Comment by mfazekas** [comment]
i guess pod install had not been run or the xcode project was opened not the workspace
