### ISSUE TITLE
Polygons partly not rendered on higher zoomLevels

### ISSUE THREAD

**Issue by fvieira** [react-native-mapbox-gl/maps#624]
**NOTE:** Just before submitting this issue I found out why it was happening and how to easily fix it. I decided to open the issue anyway because the mistake seems easy to make and someone else might be experiencing the same problem and this makes the fix more googlable. If you're looking for the fix, just skip to my first comment.

**Describe the bug**
Polygon features in a ShapeSource with FillLayer and/or LineLayer, ofter get cut off on higher zoomLevels. It often happens after level 14, but I've seen it happen after 12 too.

Example of Polygon at zoomLevel 13.99:
![Screenshot_20200116-173656](https://user-images.githubusercontent.com/390867/72549641-fb3ce080-3888-11ea-8207-c922efb16c4e.png)

Example of Polygon at zoomLevel 14:
![Screenshot_20200116-173416](https://user-images.githubusercontent.com/390867/72549628-f546ff80-3888-11ea-9126-e3abe3da4d23.png)

**To Reproduce** 
Just replace your App's main render method with the following:
```typescript
<MapboxGL.MapView style={{flex: 1}}>
      <MapboxGL.Camera
        centerCoordinate={[-7.946227, 39.589127]}
        zoomLevel={14}
      />

      <MapboxGL.ShapeSource
        id="source"
        shape={{
          type: 'Feature',
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [-7.941227, 39.584127],
                [-7.951227, 39.584127],
                [-7.951227, 39.594127],
              ],
            ],
          },
        }}>
        <MapboxGL.FillLayer id="fill" style={{fillColor: 'blue'}} />
        <MapboxGL.LineLayer
          id="line"
          style={{lineColor: 'red', lineWidth: 2}}
        />
      </MapboxGL.ShapeSource>
    </MapboxGL.MapView>
```

**Expected behavior**
Polygons show correctly on all zoomLevels.

**Versions (please complete the following information):**
 - Platfrom: Android (haven't tested iOS, no idea if it has same problem)
 - Device: Moto G7 Power
 - OS: Android version 9
 - react-native-mapbox-gl/maps Version: 7.0.9
 - SDK Version: ???
 - React Native Version: 0.61.5

**Additional context**
What gets cut from the polygon varies depending on where it is.
For example, just replacing the polygon's coordinates with these below
```
[-7.941227 + 0.1, 39.584127],
[-7.951227 + 0.1, 39.584127],
[-7.951227 + 0.1, 39.594127],
```
results in the triangle being cut in two places (see below).

![Screenshot_20200116-173346](https://user-images.githubusercontent.com/390867/72549648-fed06780-3888-11ea-941b-525af7843e15.png)

**Comment by fvieira** [comment]
So, the mistake here is that a proper Polygon must have the first coordinate repeated at the end.
If we replace these coordinates
```
[
    [-7.941227, 39.584127],
    [-7.951227, 39.584127],
    [-7.951227, 39.594127],
],
```
with these
```
[
    [-7.941227, 39.584127],
    [-7.951227, 39.584127],
    [-7.951227, 39.594127],
    [-7.941227, 39.584127],
],
```
everything works properly.

This mistake is very easy to make because 1) the repetition seems unecessary and 2) this actually works for most zoomLevels.
I think `react-native-mapbox-gl/maps` could do a better job here, either by actually working without the repeated coordinate, or at least warning the user if the repeated coordinate is not there.

Anyway, feel free to close this issue, it's googlable purpose has been fulfilled.

**Comment by kristfal** [comment]
We (and mapbox), and really any well used GIS library are following the [GeoJSON specification](https://geojson.org/) for polygon definitions. 

We should not deviate from it as it a well established and widely accepted specification. If you want convenience methods for creating polygons, I'd recommend turf.js.

**Comment by kobagapu** [comment]
Hi @kristfal @fvieira @cheeaun can we have any examples for draw a polyline in Reactnative App using mapbox

**Comment by ferdicus** [comment]
@kobagapu, there are several examples in the `/example` app with polylines. 
Please have a look there.

**Comment by kobagapu** [comment]
@ferdicus Example app is not working build failed with message env.json file missing

**Comment by ferdicus** [comment]
> @ferdicus Example app is not working build failed with message env.json file missing

Did you check the README.md?

**Comment by kobagapu** [comment]
@ferdicus  Added accesstoken.js  file with my access token
![Screenshot 2020-10-06 at 11 18 18 AM](https://user-images.githubusercontent.com/61305724/95165372-7a809480-07c9-11eb-9d48-97933b6058b8.png)
 in root folder it comes error with below attachment

**Comment by mfazekas** [comment]
@kobagapu have you also ran `npm install` after adding `accesstoken` as describe bellow?!

https://github.com/react-native-mapbox-gl/maps/tree/master/example#installation

**Comment by kobagapu** [comment]
@fvieira  is it possible to  draw a polygon dynamically with out using JSON or static Coordinates only onpress method pick coords and draw the polygon
