### ISSUE TITLE
error in offlineManager.createPack(..) styleURL

### ISSUE THREAD

**Issue by alextorn** [react-native-mapbox-gl/maps#629]
**Describe the bug**
I've saved style.json on documentsDir then trying to path this file to styleURL in offlineManager.createPack to create an offline pack. What did I miss? Any chance to set styles dynamically in runtime?

**To Reproduce**
```
await MapboxGL.offlineManager.createPack({
  styleURL: `file://${dirs.DocumentDir}/offlineConfig.json`,
  ...config,
},
  progressListener,
  errorListener,
);
```

Error: 

```
Error Domain=MGLErrorDomain Code=-1 "Response class is not NSHTTPURLResponse" UserInfo={NSLocalizedFailureReason=Response class is not NSHTTPURLResponse}
```

I saw comments from maintainers @nitaliano in old repo that we can use two types of styleURL:

1. External resource (http://, https://)
2. Internal resource - absolute path to file in the native file system.

What I did wrong?

**Comment by mfazekas** [comment]
See https://docs.mapbox.com/ios/api/maps/5.7.0/Classes/MGLTilePyramidOfflineRegion.html#/c:objc(cs)MGLTilePyramidOfflineRegion(im)initWithStyleURL:bounds:fromZoomLevel:toZoomLevel:

> URL of the map style for which to download resources. The URL may be a full HTTP or HTTPS URL or a Mapbox style URL (mapbox://styles/{user}/{style}). Specify nil for the default style. Relative file URLs cannot be used as offline style URLs. To download the online resources required by a local style, specify a URL to an online copy of the style.

**Comment by yilakt** [comment]
@mfazekas 
I'm able to save specifying the styleURL when using method .createPack() but  I'm unable to see the styleURL when I getPack()

  const options = {
        name: this.state.packageName,
        styleURL: "mapbox://styles/{myUserName}/ck7exeill2qxb1irr2lhwsdpz",
        bounds: [[bounds[0], bounds[1]], [bounds[2], bounds[3]]],
        minZoom: 5,
        maxZoom: 7,
      };

When I run offlineManager.getPack({packName}) I get this response:

**Comment by mfazekas** [comment]
@yilakt  i don't think we return `styleURL` at the moment. AS a workaround you can probably insert into name.

**Comment by yilakt** [comment]
How do we rerender map when offline then?
