### ISSUE TITLE
[7.0.9] Images/SymbolLayer not displaying images on Android

### ISSUE THREAD

**Issue by sweatherall** [react-native-mapbox-gl/maps#630]
**Describe the bug**
We just updated to 7.0.9 from 7.0.8 and our `MapboxGL.Images`/`MapboxGL.SymbolLayer` are no longer appearing. Downgrading back to 7.0.8 solves the issue - but I'm wondering if we can get this to work on 7.0.9.

**Code Example**
```
...
<MapboxGL.Images images={image ? { [imageId]: image } : {}} />
<MapboxGL.ShapeSource
    id={`placeIconHolder:${id}`}
    shape={centerPoint}
    onPress={this.onPress}>
          {image && (
            <MapboxGL.SymbolLayer
              id={`placeIcon:${id}`}
              style={{
                iconImage: imageId,
                iconSize,
                iconAllowOverlap: true
              }}
            />
          )}
    </MapboxGL.ShapeSource>
```

**Expected behavior**
`MapboxGL.Images`/`MapboxGL.SymbolLayer` should display as they do on 7.0.8

**Versions (please complete the following information):**
 - Platfrom: Android
 - Device: Pixel 3
 - OS: Android 10
 - SDK: Version 28
 - React Native Version: 0.61.5

Did something change in 7.0.9 that requires doing this process differently on Android?
This behavior does not happen on iOS - images display fine on iOS on 7.0.9

**Comment by kristfal** [comment]
Can you replicate it on master? There was seemingly some issues in the underlying Android SDK that we included in 7.0.9.

**Comment by lrpinto** [comment]
Hi

I am running Android, too. In order to rule out issues in my code, I got the team's example https://github.com/react-native-mapbox-gl/maps/blob/master/docs/SymbolLayer.md. When I tap the map the first image is displayed properly (with expected color). Past that the icons are added, but they appear to have lost style. They display in dark tones. I even tried to also set style properties for opacity and color of the icon, but the issue remains.

![image](https://user-images.githubusercontent.com/2735779/72804027-6ef33a80-3c47-11ea-8ea4-a4a5203ae31f.png)

![image](https://user-images.githubusercontent.com/2735779/72804066-829ea100-3c47-11ea-9aec-3c36eaaa9df4.png)


```
import React from 'react'
import MapboxGL from '@react-native-mapbox-gl/maps'
import { MAPBOX_MAPS_SDK_TOKEN } from 'react-native-dotenv'
import { Text } from 'react-native'
import sheet from '../styles/sheet'
import exampleIcon from '../assets/example.png'
import BaseExamplePropTypes from '../common/BaseExamplePropTypes'
import Page from '../common/Page'
import Bubble from '../common/Bubble'

MapboxGL.setAccessToken(MAPBOX_MAPS_SDK_TOKEN)

const styles = {
	icon: {
		iconImage: exampleIcon,
		iconAllowOverlap: true,
		iconOpacity: 1,
		iconColor: '#314ccd',
		iconHaloColor: '#314ccd'
	}
}

export default class MapScreen extends React.Component {
	static propTypes = {
		...BaseExamplePropTypes
	}

	constructor(props) {
		super(props)

		this.state = {
			featureCollection: MapboxGL.geoUtils.makeFeatureCollection()
		}

		this.onPress = this.onPress.bind(this)
		this.onSourceLayerPress = this.onSourceLayerPress.bind(this)
	}

	async onPress(e) {
		const feature = MapboxGL.geoUtils.makeFeature(e.geometry)
		feature.id = `${Date.now()}`

		this.setState({
			featureCollection: MapboxGL.geoUtils.addToFeatureCollection(
				this.state.featureCollection,
				feature
			)
		})
	}

	onSourceLayerPress(e) {
		const feature = e.nativeEvent.payload
    	console.log('You pressed a layer here is your feature', feature); // eslint-disable-line
	}

	render() {
		console.log(this.state.featureCollection)

		return (
			<Page {...this.props}>
				<MapboxGL.MapView
					ref={c => (this._map = c)}
					onPress={this.onPress}
					style={sheet.matchParent}
				>
					<MapboxGL.Camera zoomLevel={9} centerCoordinate={[-73.970895, 40.723279]} />

					<MapboxGL.ShapeSource
						id='symbolLocationSource'
						hitbox={{ width: 20, height: 20 }}
						onPress={this.onSourceLayerPress}
						shape={this.state.featureCollection}
					>
						<MapboxGL.SymbolLayer id='symbolLocationSymbols' minZoomLevel={1} style={styles.icon} />
					</MapboxGL.ShapeSource>
				</MapboxGL.MapView>

				<Bubble>
					<Text>Tap to add an icon</Text>
				</Bubble>
			</Page>
		)
	}
}

MapScreen.navigationOptions = {
	title: 'Map'
}

```

Any idea what could be causing this issue? I had a similar issue when I tried adding PointAnnotations with Callouts. On the first render my point annotations displayed the right style, as soon I clicked one of them they all went dark, too. I think both issues might be related. https://github.com/react-native-mapbox-gl/maps/issues/532, and the code and screen shots for this one are in Gitter (I will paste here if requested)

**Comment by kristfal** [comment]
This is an emulator issue with rendering sprites, and will not reproduce on device. 

AFAIK, there is nothing we can do here, as it has been a long-standing issue with mapbox-gl-android and the standard android emulator.

**Comment by lrpinto** [comment]
@kristfal Ok, that is great to know. I have been banging my head for days, and it didnt cross my mind to run in on a device yet. Thank you so much for feedback. I will have a go on real device, now.

**Comment by sweatherall** [comment]
@kristfal I uninstalled the library and re-installed using "git+https://github.com/react-native-mapbox-gl/maps.git" to test from master. After installing this way, the `package.json` says `"version": "7.0.10"` - I am wanting to confirm that this is the correct version to be testing on. The results: images still not displaying on Android, and build fails on iOS with an `Image not found` error

**Comment by sweatherall** [comment]
@kristfal thanks for the quick reply.
The full stack for iOS from XCode:
```
dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents
  Referenced from: /Users/steph/Library/Developer/CoreSimulator/Devices/94698548-FB72-406F-94B1-334D2B199F56/data/Containers/Bundle/Application/8AFC0293-9C05-4771-8250-1BE914F842F2/TruckMap.app/Frameworks/Mapbox.framework/Mapbox
  Reason: image not found
(lldb) 
```

As for the Android issue, good to know and we will continue to use 7.0.8 until this issue is fixed upstream - is that the suggested solution?

**Comment by sweatherall** [comment]
update: when I install with `npm install @react-native-mapbox-gl/maps --save` it installs `7.0.9` and builds fine on iOS and Android (but images not displaying on Android). So I think you are probably right about the `image not found` error being a result of `7.0.10` not being published yet. 
Again, our solution for now will be to stay on `7.0.8` - lmk if you suggest otherwise. Thank you for all your help!

**Comment by janicduplessis** [comment]
I can also confirm this issue. Still present in 7.2.0, 7.0.8 works fine, 7.0.9 doesn't.

**Comment by ansarikhurshid786** [comment]
I also facing similar issue. 

I have multiple images added as below: 
```
const imgs = {
    "1137161928": require("../assets/inspectors/1137161928.png"),
    "1829187133": require("../assets/inspectors/1829187133.png")
...
}
<MapboxGL.Images images={imgs} onImageMissing={(key) => alert(key)} />

<MapboxGL.ShapeSource id="idtest" onPress={(res) => { alert(JSON.stringify(res.features[0].properties)); }} url="pointgeojsonUrl">
                                <MapboxGL.SymbolLayer
                                    id="SM_inspection11"
                                    sourceID="SM_inspection11"
                                    style={{
                                        iconImage: [
                                             "match",
                                             ["get", "OBJECTID"],
                                             1147237248, "1147237248",
                                             1137161928, "1137161928"
defaultimgPath
]}} />

```
It is working fine in ios but in android only showing first and default img

**Comment by ansarikhurshid786** [comment]
Anyone have solution or workaround ?

**Comment by akunal1** [comment]
```
import icon from '../assets/iconName.png';

 <MapboxGL.SymbolLayer
                id="singlePoint"
                filter={['!', ['has', 'point_count']]}
                // style={layerStyles.icon}
                style={{
                  iconImage: icon,
                  iconSize: 0.15, 
                  iconAllowOverlap: true,
                }}
     />
```
