### ISSUE TITLE
onPress and symbol layer with text, icon and iconTextFit: "both"

### ISSUE THREAD

**Issue by zanaviska** [react-native-mapbox-gl/maps#634]
**Describe the bug**
If you create symbolLayer with textField and some Icon pinned and set iconTextFit: "both", onPress will be called on the whole icon area before scaling

**To Reproduce**
``` 
<MapboxGL.ShapeSource onPress={() => console.log('I.ve been pressed')}>
  <MapboxGL.SymbolLayer
    style={{
      textField="someText"
      iconImage: ['get', 'icon],
      iconTextFit: 'both'
    }} 
  />
</MapboxGL.ShapeSource>
<MapboxGL.Images images={{example: exampleIcon, assets: ['pin']}} />
```

**Expected behavior**
If you press outside of a scaled image or text, but inside of a non-scaled image(which can't be seen), nothing happens.

**Actual behavior**
After pressing outside of a scaled image or text, but inside of a non-scaled image onPress is called

**Versions (please complete the following information):**
 - Platfrom: [Android]
 - Device: [Xiaomi mi8 lite]
 - OS: [Android 9, miui 11]
 - React Native Version [0.60.5]
 - react-native-mapbox-gl version [^7.0.4]

**Additional context**

**Comment by mfazekas** [comment]
> If you press outside of a scaled image or text, but inside of a non-scaled image(which can't be seen), nothing happens.

What do you mean by `scaled` ?!

**Comment by mfazekas** [comment]
On android we use:

https://github.com/react-native-mapbox-gl/maps/blob/master/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java#L547

So it must be an an upstream queryRenderedFeatures issue with iconTextFit `both`.

**Comment by vadim312** [comment]
I can see this issue as well
here is the issue video
https://user-images.githubusercontent.com/75946509/203498379-83ddac9a-0b83-4fa4-8f22-03fb65e7d34a.mov
