### ISSUE TITLE
Lines from linelayer becomes stripped on higher zoom levels

### ISSUE THREAD

**Issue by kmkrtich** [react-native-mapbox-gl/maps#636]
**Describe the bug**

If I use layerIndex for layering then on higher zoom levels the lines becomes horizontally stripped (doubled).
This issue only happens only when using layerIndex for having multiple layers. 
But if I use belowLayerID it renders line perfectly, but that triggers another issue if the specified belowLayerID is with lazy loading. It doesn't render lines at all if at the moment of rendering specified belowLayerID layer doesn't exist.

      <MapboxGL.ShapeSource id={idShape} shape={route} onPress={onPress}>
        <MapboxGL.LineLayer
          style={{ ...stylesMap.route, lineColor: color }}
          id={idLine}
          layerIndex={1}
          // belowLayerID={parentLayerId}
        />
      </MapboxGL.ShapeSource>

**Expected behavior**
Enable proper rendering of lines when using layerIndex.

**Screenshots**
![Screenshot from 2020-01-23 00-45-46](https://user-images.githubusercontent.com/48594915/72933783-d9a59280-3d7b-11ea-82d2-3ba031ef11ab.png)

**Versions (please complete the following information):**
 - Platform: [e.g. Android, iOS]
 - Device: Android emulator (at least Pixel2)
 - react-native-mapbox-gl/maps: 7.0.10
 - React Native Version [e.g. 0.60.6]

**Comment by kristfal** [comment]
Not sure I understand what is happening here based on SS. What is expected vs actual visual output?

**Comment by mfazekas** [comment]
Closing this, will reopen on clarification - and full example
