### ISSUE TITLE
[Question] Camera _setCamera naming convention

### ISSUE THREAD

**Issue by HPieters** [react-native-mapbox-gl/maps#64]
I have started tested the 7.0 library in some of my apps. Some of the changes include the new Camera Component. I was wondering if there was a reason for renaming MapView#setCamera to Camera#_setCamera and not Camera#setCamera? Even though MapView#setCamera throws a warning `MapView.setCamera is deprecated - please use Camera#setCamera`.

**Comment by mfazekas** [comment]
@HPieters I think the idea was to not to use `setCamera` but updating the camera via the `centerCoorinate, bounds` etc. properties. So i guess `Camera#_setCamera` wasn't meant to be really used.

But i think that the properties has many limitations, ideally we could follow react's controlled input's approach, but we're very far from that. Until updating via procedural api is desired, so i guess we should remove the underscores.

**Comment by HPieters** [comment]
I currently use it to "flyTo" different locations based on user input, e.g. user selects different company location from a menu, map will change location to the lat/lng of the company. If there is another way to implement this using properties alone then I would happily do this, I guess we just need to document how this would work. 

Also updating typescript definitions to match the result of this conversation.

**Comment by mfazekas** [comment]
@HPieters you can check the builtin flyTo example implementation. 

https://github.com/react-native-mapbox/maps/blob/master/example/src/examples/FlyTo.js

There are couple of issues with this however:
1.) there is not initialCenterCoordinate, so for first render you'd want to set animationDuration to 0.
2.) if you set `centerCoordinate` to a coordinate user moves the map and you try to reset the coords it's not possible.

So i'd say that `setCamera` is much better for such `flyTo`
