### ISSUE TITLE
[7.2.0] Using string as iconImage style value no longer works

### ISSUE THREAD

**Issue by fvieira** [react-native-mapbox-gl/maps#640]
**Describe the bug**
In version 7.0.8 I used to be able to do this:

```javascript
const mapStyles: MapStyles = {
  item: {
    iconImage: 'itemType', // set itemType here
  }
};

...

<MapboxGL.Images
   images={{
     itemType: itemImg, // match it to corresponding image here
   }}
/>
```

This stopped working when I upgraded to 7.2.0, the images stopped appearing. I now have to use an expression like this:

```javascript
const mapStyles: MapStyles = {
  item: {
    iconImage: ['get', 'type'], // tell iconImage where to get the type (redundant)
  }
};

...

const getFeature = item => {
  return {
    type: 'Feature',
    id: 'id',
    properties: {
      type: 'itemType', // set itemType here
    },
    geometry: {
      type: 'Point',
      coordinates: item.coord,
    },
  };
};

...

<MapboxGL.Images
   images={{
     itemType: itemImg, // match it to corresponding image here
   }}
/>
```

**Expected behavior**
The original behaviour was expected. In my use case, all of my features were using the same image, so having the `iconImage` hardcoded worked perfectly.

**Versions (please complete the following information):**
 - Platform: Android
 - Device: Moto G7 Power
 - Emulator/ Simulator: no
 - React Native Version: 0.61.5

**Comment by kristfal** [comment]
Apparently this was finally deprecated on the iOS side natively with the underlying SDK update. 

FYI, we officially stopped supporting the string syntax in 7.0.0 with the introduction of expressions, so you need to migrate all your code to using expressions.
