### ISSUE TITLE
Typescript discrepancy in addToFeatureCollection

### ISSUE THREAD

**Issue by cjduncana** [react-native-mapbox-gl/maps#641]
**Describe the bug**
The function `addToFeatureCollection` expects an array of `FeatureCollection` according to Typescript, yet if you check the code, it expects a single collection.

Typescript definition:
``` typescript
function addToFeatureCollection<G = Geometry, P = Properties>(newFeatureCollection: Array<FeatureCollection<G, P>>, newFeature: Feature<G, P>): FeatureCollection<G, P>;
```

Function definition:
``` javascript
export function addToFeatureCollection(newFeatureCollection, newFeature) {
  return {
    ...newFeatureCollection,
    features: [...newFeatureCollection.features, newFeature],
  };
}
```

**Versions (please complete the following information):**
 - "@react-native-mapbox-gl/maps": "^7.2.0"

**Comment by kristfal** [comment]
Hey! This function will be removed in 8.0.0, so we will not fix the TS declaration. Please use turf.js for general geo untils. Turf got got TS coverage :) I’ll keep this open till 8.0.0 is out.

**Comment by cjduncana** [comment]
Do we know when 8.0.0 will be released?

**Comment by ferdicus** [comment]
Unfortunately no ETA yet.

Closing this issue
