### ISSUE TITLE
how to add layers to maps

### ISSUE THREAD

**Issue by pm02446** [react-native-mapbox-gl/maps#643]
It is not clear anywhere I look on how to add a layer to my map in react native. It is a simple task that I can not find help anywhere, please help

**Comment by kristfal** [comment]
We have an example app that contains a lot of these. Closing.

**Comment by pm02446** [comment]
where then, I would not be asking if I did not see it clearly

**Comment by kristfal** [comment]
https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/ShowAndHideLayer.js 

This is one example of adding a layer. Honestly, your request is too broad to narrow down the exact use case that you want to solve. 

Keep in mind that Github issues is an issue tracker, not a Q/A. Please use stackoverflow for those things.
