### ISSUE TITLE
MapView.md styling issue

### ISSUE THREAD

**Issue by Sergiiivzhenko** [react-native-mapbox-gl/maps#644]
Could you please make the readme.md doc description for https://github.com/react-native-mapbox-gl/maps/blob/master/docs/MapView.md fully visible?
Here is what I see on full hd monitor http://joxi.ru/bmogZe4u99aXqm

Regards.

**Comment by kristfal** [comment]
Hey,

This is a limitation with Github’s document viewer. We would have to quite drastically change the documentation if we want it to fit. I’d honestly be more interested in publishing it on GitHub pages or a similar place where we control it all. Happy to see a PR for something like this. 

In the interim, you could view raw or open the file locally in your favorite markdown enabled text editor.

**Comment by Sergiiivzhenko** [comment]
Thanks, got about a temporary solution. But about publishing on GitHub pages, I think you as a creator could do that. 
Actually don't understand about what kind of PR you told, as I understand all is needed is README.md and it's possible to do that following such instruction https://hackernoon.com/use-custom-domain-with-github-pages-2-straightforward-steps-cf561eee244f

**Comment by ferdicus** [comment]
What he means is, if you're so passionate about this particular problem - feel free to help and open a PR :)

**Comment by kristfal** [comment]
Hey, only maintainers can publish it, yes, but that doesn’t prevent anyone else from testing a few solutions and proposing something. I’d look into https://github.com/docsifyjs/docsify if I had the time. We use .md across the board, so as far as I can tell, it should be very easy to plug in.
