### ISSUE TITLE
the project does not install the dependency

### ISSUE THREAD

**Issue by Massmaker** [react-native-mapbox-gl/maps#647]
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@react-nativ-mapbox-gl%2fmaps - Not found
npm ERR! 404 
npm ERR! 404  '@react-nativ-mapbox-gl/maps@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Describe the bug**
after cloning the project from github, trying to yarn add, or npm install
neither of options work

**To Reproduce**
clone the repository, 
move to the project folder,
try to add mapboxGL module by performing command in terminal

**Expected behavior**
mapboxGL library installs and project launches on ios/android simulators

**Screenshots**

**Versions (please complete the following information):**
 - Platform: [e.g. Android, iOS]
 - Emulator/ Simulator: [yes/ no]
 - SDK Version [e.g. 22]
 - React Native Version [e.g. 0.59]

**Additional context**

**Comment by Massmaker** [comment]
![Screenshot 2020-02-03 at 15 51 55](https://user-images.githubusercontent.com/4262898/73658556-34ed5400-469d-11ea-9191-4aca860a7ee2.png)

**Comment by ferdicus** [comment]
Please use the correct name of the repo.
It's `yarn add @react-native-mapbox-gl/maps`
Not `yarn add @reat-native-mapbox-gl/maps`

**Comment by Massmaker** [comment]
sorry. my bad.
