### ISSUE TITLE
Use Animated Value for SymbolLayer iconRotate

### ISSUE THREAD

**Issue by EricPKerr** [react-native-mapbox-gl/maps#649]
Is it possible to have the iconRotate property of a SymbolLayer support/track animated values?

Setting the initial value to Animated.Value(90) works, but it doesn't rotate when you start an animation.

**Comment by mfazekas** [comment]
@EricPKerr  at the moment it's broken. 
There is 2 issue:
1.) Symbol layer doesn't set "nativeLayer" ref, so `setNativeProps` will do nothing. (unlike RasterLayer for example.)

https://github.com/react-native-mapbox-gl/maps/blob/987541be3fe09b788ed62b147a5ef5f1c0c9347d/javascript/components/SymbolLayer.js#L103

https://github.com/react-native-mapbox-gl/maps/blob/987541be3fe09b788ed62b147a5ef5f1c0c9347d/javascript/components/RasterLayer.js#L81

2.) 'style' props are not converted to 'reactStyle' in updateNativeProps unlike in `getProps`

https://github.com/react-native-mapbox-gl/maps/blob/987541be3fe09b788ed62b147a5ef5f1c0c9347d/javascript/components/AbstractLayer.js#L60-L64

https://github.com/react-native-mapbox-gl/maps/blob/987541be3fe09b788ed62b147a5ef5f1c0c9347d/javascript/components/AbstractLayer.js#L16


With both fixed i was able to get icon rotated, but there were some refresh issues:

![animated_rotation](https://user-images.githubusercontent.com/52435/73943291-cbfe1a00-48f0-11ea-8c37-89d73907b11c.gif)

**Comment by EricPKerr** [comment]
@mfazekas awesome, thanks - that looks great. Want to make a PR?

**Comment by EricPKerr** [comment]
Similar error (and likely solution) for `CircleLayer` with `circleRadius` and `circleOpacity` etc

**Comment by mfazekas** [comment]
@EricPKerr i've added a PR #653. Can you try and report back it should fix style animation for CircleLayer and SymbolLayer.
