### ISSUE TITLE
iconImage does not work with ["get", "image"] expression if image attribute is the uri

### ISSUE THREAD

**Issue by vovka-s** [react-native-mapbox-gl/maps#652]
**Describe the bug**
I need to load iconImage from uri that stored in feature properties.
It works fine If I pass an uri directly to iconImage attribute, like this
`iconImage: 'http://my.server.com/images/image1.jpg'`
But it does not work if I try to get uri from attribute:
`iconImage: ['get', 'iconUri']`
I also tried to use image expression but it seems not implemented
`iconImage: ['image', ['get', 'iconUri']]`

**To Reproduce**
Create a ShapeSource with SymbollLayer
```
const markers = {
    type: "FeatureCollection",
    features: [{
        geometry: {
            type: "Point",
            coordinates: [37.6090439796016, 55.7199091654129],
       },
       type: "Feature",
       properties: {
           iconUri: 'http://my.server.com/images/image1.jpg',
       }
    }]
};

const layerStyles = {
    imageLevel1: {
        iconImage: ['get', 'iconUri'],
        iconSize: 0.8,
        iconAllowOverlap: true,
        iconIgnorePlacement: true,
    },
};

<MapboxGL.ShapeSource
    id='allMarkers'
    onPress={this.onPressMarker}
    shape={markers}
>
    <MapboxGL.SymbolLayer
        id="imagesInMarkersLevel1'
        filter={['==', 'isRecommended', 1]}
        style={layerStyles.imageLevel1}
    />
</MapboxGL.ShapeSource>
```

**Expected behavior**
Image is visible

**Versions (please complete the following information):**
 - Platform: Android
 - Device: Mi 9 SE
 - Emulator/ Simulator: yes
 - OS: Android 9
 - SDK Version: 28
 - React Native Version: 0.61.5

**Comment by mfazekas** [comment]
We don't support this currently. `iconImage` should resolve to a key specified in an [`Images`](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Images.md) component.

So if you have a list of used url-s you can add the to `Images`.

**Comment by mfazekas** [comment]
In the future, we could implement this feature using `addMissingImageToStyle` to load images from URL then display them once downloaded.

**Comment by mattijsf** [comment]
If I'm not mistaken fetching images from a url is also not available from the mapbox style spec of iconImage. The image has to come from the map sprite or added images.

**Comment by vovka-s** [comment]
> In the future, we could implement this feature using `addMissingImageToStyle` to load images from URL then display them once downloaded.
It would be great! How much time do you need for this?
I have no a list of url-s, all of them stored on server.
Moreover their number is large enough and it will be suboptimal to add all of them into Images

**Comment by vovka-s** [comment]
> If I'm not mistaken fetching images from a url is also not available from the mapbox style spec of iconImage. The image has to come from the map sprite or added images.
But not it works if a specify uri directly into iconImage
`iconImage: 'http://my.server.com/images/image1.jpg'`

**Comment by mfazekas** [comment]
> But not it works if a specify uri directly into iconImage
> `iconImage: 'http://my.server.com/images/image1.jpg'`

That is something we implement in RNMBGL, it's not a feature from MBGL.

https://github.com/react-native-mapbox-gl/maps/blob/42dc467105886295b2ddfc8148440d1269ff5507/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFactory.java#L225-L230

https://github.com/react-native-mapbox-gl/maps/blob/1f3719b2ac4d376b18d48095b10921acaa3ce651/ios/RCTMGL/RCTMGLStyle.m#L199-L213

**Comment by mfazekas** [comment]
With current master images has a new `onImageMissing` callback. You can use like this to download extra images as needed:

https://github.com/react-native-mapbox-gl/maps/blob/0c85984fdc6333334ed12fd34ada143c8a07ca73/example/src/examples/ShapeSourceIcon.js#L99-L106

**Comment by vovka-s** [comment]
> With current master images has a new `onImageMissing` callback. You can use like this to download extra images as needed:
> 
> https://github.com/react-native-mapbox-gl/maps/blob/0c85984fdc6333334ed12fd34ada143c8a07ca73/example/src/examples/ShapeSourceIcon.js#L99-L106

Good! It's useful feature for local storage of images if one of them is not specified
But I have other case.
- I have no local storage of images
- I have only urls that stored into geojson properties
- and I want to show image by that url
This fix won't help me
I made a patch to solve my issue. Only for android.
```
diff --git a/node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSource.java b/node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSource.java
index 64753bb..49c94be 100644
--- a/node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSource.java
+++ b/node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLShapeSource.java
@@ -21,6 +21,7 @@ import com.mapbox.rctmgl.utils.ImageEntry;
 
 import java.net.URL;
 import java.util.ArrayList;
+import java.util.AbstractMap;
 import java.util.Collections;
 import java.util.List;
 import java.util.Map;
@@ -213,6 +214,16 @@ public class RCTMGLShapeSource extends RCTSource<GeoJsonSource> {
                 }
             }
         }
+        if (id != null) {
+            try {
+                Map.Entry<String, ImageEntry> image = new AbstractMap.SimpleEntry<String, ImageEntry>(id, new ImageEntry(id, 1.0));
+                addRemoteImages(Collections.singletonList(image), mMap);
                             +                return true;
+            }
+            catch(Exception e) {
+                return false;
+            }
+        }
 
         return false;
     }

```
So function `addMissingImageToStyle` now looks like:
```
public boolean addMissingImageToStyle(@NonNull String id) {
        if (mMap == null) return false;

        if (mNativeImages != null) {
            for (Map.Entry<String, BitmapDrawable> entry : mNativeImages) {
                if (entry.getKey().equals(id)) {
                    addNativeImages(Collections.singletonList(entry), mMap );
                    return true;
                }
            }
        }
        if (mImages != null) {
            for (Map.Entry<String, ImageEntry> entry : mImages) {
                if (entry.getKey().equals(id)) {
                    addRemoteImages(Collections.singletonList(entry), mMap);
                    return true;
                }
            }
        }
        if (id != null) {
            try {
                Map.Entry<String, ImageEntry> image = new AbstractMap.SimpleEntry<String, ImageEntry>(id, new ImageEntry(id, 1.0));
                addRemoteImages(Collections.singletonList(image), mMap);
                return true;
            }
            catch(Exception e) {
                return false;
            }
        }

        return false;
    }
```
Last `if` is responsible for loading images by url stored in properties

**Comment by mfazekas** [comment]
@vovka-s You should be able to do it with `onImageMissing` too.

```es6
 <MapboxGL.Images 
   images={images} 
   onImageMissing={url => 
     this.setState({ 
       images: {...this.state.images, [url]: url}, 
     }) 
   } 
 /> 
```

But `onImageMissing` has other usecases too. Like if the image url requires some extra cookies/  processing then it can be done there. 

Your solution is not compatible with onImageMissing, as an alternative we could allow a constant like `download` to be provided for onImageMissing, then use the logic you've implemented.

**Comment by vovka-s** [comment]
I didn't try to specify 'url' as a key.
I'll try it and answer
Thanks!

**Comment by vovka-s** [comment]
@mfazekas 
I spent some time to understand what doesn't wor and now can explain in details
- There are two markers.
- One of them has attribute `markerImage` with an url of remote picture. In this example it is a random picture from random cdn.
- second marker have no `markerImage` attribute, url is specified directly in layer's styles.
```
const markers = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          37.6682134636,
          55.7212578101
        ]
      },
      "properties": {
        isRecommended: 2,
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          37.5754213632249,
          55.6972729735166
        ]
      },
      "properties": {
        isRecommended: 1,
        markerImage: 'https://cdn.onlinewebfonts.com/svg/img_525159.png',
      }
    },
  ]
};
```
And map with two layers. Markers situated in separate layers.
```
<MapboxGL.MapView
    ref={(ref) => {
        this.map = ref;
    }}
    style={styles.map}
    styleURL={MAPBOX_STYLE}
    rotateEnabled={false}
    zoomEnabled={true}
    regionDidChangeDebounceTime={0}
>

    <MapboxGL.Images
        images={this.state.images}
        onImageMissing={(url) => {
            this.setState({images: ...this.state.images, [url]: url});
            console.info(this.state.images);
        }}
    />

    <MapboxGL.ShapeSource
        id='allMarkers'
        shape={markers}
    >
        <MapboxGL.SymbolLayer
            id='markersLevel2'
            style={{
                filter={['==', 'isRecommended', 2]}
                iconImage: 'https://cdn.onlinewebfonts.com/svg/img_525159.png', //'https://cdn.onlinewebfonts.com/svg/img_525160.png'
                iconSize: 0.05,
            }}
        />          

        <MapboxGL.SymbolLayer
            id='markersLevel1'
            style={{
                filter={['==', 'isRecommended', 1]}
                iconImage: ['get', 'markerImage'],
                iconSize: 0.09,
            }}
        />

    </MapboxGL.ShapeSource>
</MapboxGL.MapView>
```
And now the most interesting:
- if I specify the same urls for two markers - it works fine
- but if i change url in layer `markersLevel2` to another(ex. https://cdn.onlinewebfonts.com/svg/img_525160.png) - picture for the marker from other layer disappears.
As I think, `onImageMissing` can't download new picture. It can only link missing id to one of previously downloaded or local pictures

**Comment by mfazekas** [comment]
> As I think, onImageMissing can't download new picture. It can only link missing id to one of previously downloaded or local pictures

Thanks, i'll try to repro, was it iOS or Android?! Note that `onImageMissing` doesn't download any images. It just a state change. `Images` component should download new images on state change.

**Comment by vovka-s** [comment]
Android. I didn't try on iOS.
> Note that onImageMissing doesn't download any images. It just a state change. Images component should download new images on state change
Understood. If so then `Images` component can't download image if url stored in an attribute.

**Comment by mfazekas** [comment]
@vovka-s this should be addressed by #769 

On current version pls use:

```es6
onImageMissing={(url) => {
            this.setState({images: ...this.state.images, [url]: {uri: url} });
        }}
```

**Comment by vovka-s** [comment]
@mfazekas
Hello! Thanks for the update!
Now it works, but there is one case:
- there are some markers in the initial map view
- markers consist of text and images (as here https://user-images.githubusercontent.com/9987233/77314488-cb8dd700-6d16-11ea-869b-20cc1e41acba.jpg)
- at the initial loading of the map, I see only text
- when I start moving the map, pictures appear
- when I move the map to an area outside the visible boundaries, new markers do not load completely the first time: 
 -- at the first step the text appears
 -- then the next time I move map, the picture appears

**Comment by vovka-s** [comment]
@mfazekas
Did you see my previous comment?

**Comment by mfazekas** [comment]
@vovka-s pls open a ticket with a simple but complete example ReactNative component, and steps to reproduce the issue with that sample.

**Comment by vovka-s** [comment]
done #813

**Comment by nikola1970** [comment]
> We don't support this currently. `iconImage` should resolve to a key specified in an [`Images`](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Images.md) component.
> 
> So if you have a list of used url-s you can add the to `Images`.

Can you give a better explanation? I really struggle ti understand this. Thanks!
