### ISSUE TITLE
Metro bundler not starting after updating to 7.2.0

### ISSUE THREAD

**Issue by jochemjanssens** [react-native-mapbox-gl/maps#654]
**Describe the bug**
After updating to version 7.2.0 my metrobundler is not starting anymore when I build the app. When I remove the "@react-native-mapbox-gl/maps" package the builds works fine. Does somebody knows how to fix this problem? I only have this issue on iOS.

**Versions (please complete the following information):**
 - Platform: iOS
 - Emulator/ Simulator: both
 - React Native Version: 0.61.5

**Comment by mfazekas** [comment]
@jochemjanssens please include full details, try to reproduce on an empty react native project, and include all details (like what is `not starting` means?! are the any errors, etc.)

Here is an example of detailed steps:
https://github.com/react-native-mapbox-gl/maps/issues/458#issuecomment-540310973

Closing this now, will reopen when you've added more details.
