### ISSUE TITLE
[QUESTION] How to use the GeoLocateControl in react native?

### ISSUE THREAD

**Issue by ShaharyarMaroof** [react-native-mapbox-gl/maps#655]
I would like to display a button to locate the current user location and center the map on those coordinates. On the web API there is an example for this, but I can't find a component for this in the lib.

![image](https://user-images.githubusercontent.com/10959027/74220091-73ec5c80-4cd0-11ea-8ed5-236f587ef721.png)

**Expected behavior**
There should be a button to load the user's location

**Versions (please complete the following information):**
 - Platform: Android, iOS
 - SDK Version 7.0.9
 - React Native Version 0.60.6

**Comment by ferdicus** [comment]
Hey there, 
you gotta do this on you own - this repo just provides js bindings to the iOS and Android SDKs.

What you can do is save the incoming gps positions, render a button over the MapView and call `setCamera` with the last saved coordinates.

See components: 
https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Camera.md
https://github.com/react-native-mapbox-gl/maps/blob/master/docs/UserLocation.md

For more info

**Comment by mfazekas** [comment]
Also see https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/SetUserTrackingModes.js

**Comment by ShaharyarMaroof** [comment]
Thanks! I'll take a look at this, but shouldn't the lib provide this functionality like the web API does?

**Comment by mfazekas** [comment]
@ShaharyarMaroof unlike the web API neither the native ios nor android provides such a component directly. We try to cover what the native SDK's implements.

**Comment by ShaharyarMaroof** [comment]
Ah I see. thanks for clearing it up.

**Comment by ShaharyarMaroof** [comment]
@mfazekas I have a little confusion in using the component methods, so for the Camera component, how can I call setCamera? I tried using ref, as done in the examples for the MapView component, but get an error setCamera is not a function.

**Comment by ferdicus** [comment]
In the `Camera` component set the ref
```js
<MapboxGL.Camera ref={setCamRef} zoomLevel={16} />
```

```js
  const setCamRef = (ref) => {
    camRef = ref;
  };
```

and then you can use `setCamera` on that ref
```js
  const setCamera = (cameraConfig) => {
    if (!camRef) return;
    camRef.setCamera(cameraConfig);
  };
```

**Comment by ShaharyarMaroof** [comment]
```
const MapView = (props) => {
  let cameraRef;

  const moveCamera = (cameraConfig) => {
    if (!cameraRef) return
    // ---> this log is printed but the camera does not move
    console.log('moving camera')
    cameraRef.setCamera(cameraConfig)
  }

  // invoke the geo location service to get the current locaiton of the user
  const getCurrentUserPosition = () => {
    const onPositionUpdate = (locationInfo) => {
      const currentLongitude = pathOr(0, ['coords', 'longitude'], locationInfo)
      const currentLatitude = pathOr(0, ['coords', 'latitude'], locationInfo)
      // moveCamera({ centerCoordinate: [currentLongitude, currentLatitude] })
      // --> call the moveCamera function with the updated coordinates
      moveCamera({ centerCoordinate: [0, 0] })
    }

    GeoLocationService.getCurrentPosition({
      successHandler: onPositionUpdate
    })
  }

  React.useEffect(() => {
    setTelemetryEnabled(false);
    askAndroidPermission();

    // getCurrentUserPosition();
  }, [])

  return (
    <View style={{ flex: 1 }}>
      <MapBoxMapView
        style={{ flex: 1 }}
        logoEnabled={false}
        // attributionEnabled={false}
        compassEnabled
      >
        <Camera
          ref={(ref) => cameraRef = ref}
          zoomLevel={16}
          followZoomLevel={8}
          followUserLocation
          followUserMode='normal'
        />
        <UserLocation />
        <View style={{ zIndex: 100 }}>
          {props.children}
          <MyLocationButton onPressHandler={() => getCurrentUserPosition()} />
        </View>
      </MapBoxMapView>
    </View>
  )
}
```
@mfazekas I have followed your example to pass the current location to the setCamera method. the function gets called but the camera doesn't reset to the new location passed in. I've tried ```moveTo([0,0])``` and ```flyTo([0,0])``` as well.
Any ideas?

**Comment by mfazekas** [comment]
@ShaharyarMaroof You have `followUserLocation` set, so we'll not allow you to change the camera. Try to set it to false.

**Comment by ShaharyarMaroof** [comment]
@mfazekas thanks, now its working fine.

**Comment by zaidmunir11s** [comment]
<MapboxGL.Camera
   
             zoomLevel={16}
             animationMode={'flyTo'}
             animationDuration={6000}
            
             followUserMode={'normal'}
             followUserLocation={this.state.follow}
  defaultSettings={{
    centerCoordinate: [0, 0],
    zoomLevel: 14
  }}
 
  centerCoordinate={this.state.markerCoords}
/>

onPress={()=>{
this.setState({follow:true})
this.setState({follow:false})
}}
this will Fly you to current location , when ever you press button

**Comment by RodolfovMoreira** [comment]
Hello! 

I've tried different approaches (using 'Geolocation' library and @zaidmunir11s  solution) but somehow the library was'nt working properly and the second solution was something like a workaround to me, so me and my team came up with the following solution:

We went on the mapbox library code to discover how it gets the user position to display  like when we use 'MapboxGL.UserLocation'. So this was the solution applied, returning latitude and longitude of user's location.

Imports and declaration of function
```javascript
import {  NativeModules } from 'react-native'
...
const MapboxGLLocationManager = NativeModules.MGLLocationModule

const getLastKnownLocation = async () => {
  try {
    return await MapboxGLLocationManager.getLastKnownLocation()
  } catch (error) {
    console.log('locationManager Error: ', error)
  }
}

```

And the function that fires when user click on button is:

```javascript
const goToUserLocation = async () => {
    const {
      coords: { latitude, longitude },
    } = await **getLastKnownLocation**()

    // Call your function to update camera with above coordinates here
  }
```

With this solution you can  use the user location coordinates wherever you want without other libs.

**Comment by francescocretti** [comment]
> Hello!
> 
> I've tried different approaches (using 'Geolocation' library and [@zaidmunir11s](https://github.com/zaidmunir11s) solution) but somehow the library was'nt working properly and the second solution was something like a workaround to me, so me and my team came up with the following solution:
> 
> We went on the mapbox library code to discover how it gets the user position to display like when we use 'MapboxGL.UserLocation'. So this was the solution applied, returning latitude and longitude of user's location.
> 
> Imports and declaration of function
> 
> import {  NativeModules } from 'react-native'
> ...
> const MapboxGLLocationManager = NativeModules.MGLLocationModule
> 
> const getLastKnownLocation = async () => {
>   try {
>     return await MapboxGLLocationManager.getLastKnownLocation()
>   } catch (error) {
>     console.log('locationManager Error: ', error)
>   }
> }
> 
> And the function that fires when user click on button is:
> 
> const goToUserLocation = async () => {
>     const {
>       coords: { latitude, longitude },
>     } = await getLastKnownLocation()
> 
>     // Call your function to update camera with above coordinates here
>   }
> 
> With this solution you can use the user location coordinates wherever you want without other libs.

This works but the native module that exposes the method is changed now:


```js
const MapboxGLLocationManager = NativeModules.RNMBXLocationModule;
```
