### ISSUE TITLE
Consider adding the mock-file to the release

### ISSUE THREAD

**Issue by timomeh** [react-native-mapbox-gl/maps#657]
To run jest tests, the mapbox-gl NativeModule needs to be mocked. There already exists a mock inside this repo: https://github.com/react-native-mapbox-gl/maps/blob/master/__tests__/__mocks__/react-native-mapbox-gl.mock.js

## Problem

Currently I just copy-pasted the mock into my project. But if some internal implementation of mapbox-gl changes, my tests will break, and I need to re-copy-paste the mock into my project.

## Proposal

It would be much nicer if you could add this to the release, so it can be used inside `setupFilesAfterEnv`. Maybe just call is `setup-jest.js`.

```json
  "jest": {
    "preset": "react-native",
    "setupFilesAfterEnv": [
      "@react-native-mapbox-gl/maps/setup-jest",
      "<rootDir>/jest.setup.js"
    ]
  },
```

**Comment by ferdicus** [comment]
sounds like a good idea, want to open a PR for it?

**Comment by timomeh** [comment]
Sure!

**Comment by timomeh** [comment]
-> #657
