### ISSUE TITLE
How to stop gps icon blinking to save battery usage

### ISSUE THREAD

**Issue by Anahita-Fakhravar** [react-native-mapbox-gl/maps#660]
**Describe the bug**
I have used <MapboxGL.UserLocation /> to show user location and because  of this  my GPS icon starts to flashing continuously. 

**Expected behavior**
I want to stop its blinking when I leave the page to save battery usage. Please help me how to do this. 

**Versions (please complete the following information):**
 - Platform:  Android
 - Emulator/ Simulator:  no
 - React Native Version 59.9

**Comment by ferdicus** [comment]
Please respect the issue template.
