### ISSUE TITLE
error install 

### ISSUE THREAD

**Issue by HoseinAsadi** [react-native-mapbox-gl/maps#661]
Hi,

**### gradle file  **
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion="28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:3.4.0')

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

**### error below after install error in gradle:**

ERROR: Unable to resolve dependency for ':@react-native-mapbox-gl_maps@debug/compileClasspath': Could not resolve com.android.support:support-vector-drawable:28.0.0.
Show Details
Affected Modules: @react-native-mapbox-gl_maps

ERROR: Unable to resolve dependency for ':@react-native-mapbox-gl_maps@debug/compileClasspath': Could not resolve com.android.support:appcompat-v7:28.0.0.
Show Details
Affected Modules: @react-native-mapbox-gl_maps

ERROR: Unable to resolve dependency for ':@react-native-mapbox-gl_maps@debug/compileClasspath': Could not resolve androidx.vectordrawable:vectordrawable:{strictly 1.0.0}.
Show Details
Affected Modules: @react-native-mapbox-gl_maps

ERROR: Unable to resolve dependency for ':@react-native-mapbox-gl_maps@debug/compileClasspath': Could not resolve androidx.appcompat:appcompat:{strictly 1.0.0}.
Show Details
Affected Modules: @react-native-mapbox-gl_maps

ERROR: Unable to resolve dependency for ':@react-native-mapbox-gl_maps@debug/compileClasspath': Could not resolve androidx.core:core:{strictly 1.0.0}.
Show Details
Affected Modules: @react-native-mapbox-gl_maps

ERROR: Unable to resolve dependency for ':@react-native-mapbox-gl_maps@debug/compileClasspath': Could not resolve androidx.appcompat:appcompat:1.0.2.
Show Details
Affected Modules: @react-native-mapbox-gl_maps

ERROR: Unable to resolve dependency for ':@react-native-mapbox-gl_maps@debug/compileClasspath': Could not resolve androidx.appcompat:appcompat:1.0.0.
Show Details
Affected Modules: @react-native-mapbox-gl_maps

ERROR: Unable to resolve dependency for ':@react-native-mapbox-gl_maps@debug/compileClasspath': Could not resolve androidx.core:core:1.0.1.
Show Details
Affected Modules: @react-native-mapbox-gl_maps

ERROR: Unable to resolve dependency for ':@react-native-mapbox-gl_maps@debug/compileClasspath': Could not resolve androidx.vectordrawable:vectordrawable:1.0.1.
Show Details
Affected Modules: @react-native-mapbox-gl_maps

ERROR: Unable to resolve dependency for ':@react-native-mapbox-gl_maps@debug/compileClasspath': Could not resolve androidx.core:core:1.0.0.
Show Details
Affected Modules: @react-native-mapbox-gl_maps

ERROR: Unable to resolve dependency for ':@react-native-mapbox-gl_maps@debug/compileClasspath': Could not resolve androidx.vectordrawable:vectordrawable:1.0.0.
Show Details
Affected Modules: @react-native-mapbox-gl_maps

**Comment by ferdicus** [comment]
Please respect the issue template - thanks.

Closing
