### ISSUE TITLE
How to stop gps icon blinking to save battery usage 

### ISSUE THREAD

**Issue by Anahita-Fakhravar** [react-native-mapbox-gl/maps#662]
**Describe the bug**
I have used <MapboxGL.UserLocation /> to show user location and because of this my GPS icon starts to flashing continuously.

**Expected behavior**
I want to stop its blinking when I leave the page to save battery usage. Please help me how to do this.

**Versions:**

Platform: Android
Emulator/ Simulator: no
React Native Version 59.9

**Comment by ferdicus** [comment]
What exactly do you mean by GPS icon flashing.
What device are you on?
What's a page in this context.

Can you please provide a video or at least a screenshot

Thanks

**Comment by Anahita-Fakhravar** [comment]
> What exactly do you mean by GPS icon flashing.
> What device are you on?
> What's a page in this context.
> 
> Can you please provide a video or at least a screenshot
> 
> Thanks

Thank you for your answer. When I use  <MapboxGL.UserLocation /> feature my location icon will appear on top of the  android mobile (Galaxy note 3) ribbon and it starts to blink. It shows that my location services is on and it is active. It should stop blinking and go away from top ribbon when I go to another page that does not need location services so It seems that I should call a function or something in componentWillUnmount()  maybe to stop it to reduce battery usage.

**Comment by Anahita-Fakhravar** [comment]
> > What exactly do you mean by GPS icon flashing.
> > What device are you on?
> > What's a page in this context.
> > Can you please provide a video or at least a screenshot
> > Thanks
> 
> Thank you for your answer. When I use <MapboxGL.UserLocation /> feature my location icon will appear on top of the android mobile (Galaxy note 3) ribbon and it starts to blink. It shows that my location services is on and it is active. It should stop blinking and go away from top ribbon when I go to another page that does not need location services so It seems that I should call a function or something in componentWillUnmount() maybe to stop it to reduce battery usage.

**Comment by Anahita-Fakhravar** [comment]
Why my issue has been closed? I didn't close it! :(

**Comment by ferdicus** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/26439946/74320613-3eec1280-4d81-11ea-8ff0-4ca57ca65ba5.png">

You did - 8 mins ago

**Comment by Anahita-Fakhravar** [comment]
> <img alt="image" width="522" src="https://user-images.githubusercontent.com/26439946/74320613-3eec1280-4d81-11ea-8ff0-4ca57ca65ba5.png">
> 
> You did - 8 mins ago

It was accidentally, How I can open it? :(

**Comment by mfazekas** [comment]
Should be covered by: #663
