### ISSUE TITLE
feat(user-location): locationManager is not stopped on unmount

### ISSUE THREAD

**Issue by ferdicus** [react-native-mapbox-gl/maps#663]
**Describe the bug**
I've noticed that within the `UserLocation` components method `#setLocationManager` `locationManager` is never really stopped.

https://github.com/react-native-mapbox-gl/maps/blob/9e76f32063762d43a8b8c43b1b7e8aa784f65da6/javascript/components/UserLocation.js#L128-L143

On `componentWillUnmount` we're passing `{ running: false }`, however this will simply prevent a restart of `locationManager`

https://github.com/react-native-mapbox-gl/maps/blob/9e76f32063762d43a8b8c43b1b7e8aa784f65da6/javascript/components/UserLocation.js#L155-L158

Not sure, however this might cause the `locationManager` running when the map/ userlocation is unmounted.

**To Reproduce**
Have a MapView mount  UserLocation component and unmount it again.
Notice, that the GPS indicator is still visible in the devices statusbar.

**Expected behavior**
GPS tracking/ indicator is gone once the UserLocation component is unmounted.

**Screenshots**
na

**Versions (please complete the following information):**
 - Platform: `OS X`
 - Device: `LG Q7`
 - Emulator/ Simulator: `no`
 - OS: `Android`
 - SDK Version: `Android 9` 
 - React Native Version: `7.2.0`

**Comment by ferdicus** [comment]
@mfazekas, can you have a quick look - maybe I missed something?

Thanks

**Comment by mfazekas** [comment]
So we've used to have `locationManger.stop()` in an else but it got removed at https://github.com/react-native-mapbox-gl/maps/pull/258/files as there is no locationManager stop.

We might have wanted to do a pause there instead?!

**Comment by ferdicus** [comment]
Ah, my bad, should've checked the history.

Would `#dispose` be an option?

https://github.com/react-native-mapbox-gl/maps/blob/9e76f32063762d43a8b8c43b1b7e8aa784f65da6/javascript/modules/location/locationManager.js#L73-L84

Seems to stop the underlying `MapboxGLLocationManager`

**Comment by mfazekas** [comment]
> Ah, my bad, should've checked the history.
> 
> Would `#dispose` be an option?

Looking at native codes on ios and android there doesn't seems to be a difference in pause and dispose. 

`.pause` is buggy as it should be calling `removeListener` if it sets `isListening` to false

https://github.com/react-native-mapbox-gl/maps/blob/9e76f32063762d43a8b8c43b1b7e8aa784f65da6/javascript/modules/location/locationManager.js#L66-L71

**Comment by ferdicus** [comment]
I'll try give this a chance in the coming weeks - seems like an oversight which might cause people headaches with active GPS, when they're no longer on the map/ have no userlocation shown.

Thanks for the feedback!
