### ISSUE TITLE
[QUESTION] Can we restrict map box to a specific region?

### ISSUE THREAD

**Issue by ShaharyarMaroof** [react-native-mapbox-gl/maps#665]
I was wondering if there any way to restrict the map show to a specific area. Let's suppose i just want to show the map of the United States. how would that be achieved?

**Comment by mfazekas** [comment]
@ShaharyarMaroof please use stackoverflow or gitter for such questions. If you attempt something that does not work and you think should works, you might post it here. But how do I do X, does not belong here.
