### ISSUE TITLE
Android App crash when using MapView v7.0.9

### ISSUE THREAD

**Issue by ShaharyarMaroof** [react-native-mapbox-gl/maps#666]
**Describe the bug**
Using mapview to render a map, working fine on iOS. but on android the app crashes.

**To Reproduce**
```
<MapView
      style={{ flex: 1 }}
      logoEnabled={false}
      // attributionEnabled={false}
      compassEnabled
      onRegionDidChange={async (data) => {onRegionDidChange}
      onDidFinishRenderingMapFully={onMapRenderComplete}
    >
      <Camera
        zoomLevel={14}
      />
      <UserLocation />
</MapView>
``` 

**Expected behavior**
Map should render successfuly

**Screenshots**
![image](https://user-images.githubusercontent.com/10959027/74521061-95e91780-4f3a-11ea-9772-cefe0ec72f9a.png)

**Versions (please complete the following information):**
 - Platform: android 
 - Device: pixel 3
 - Emulator/ Simulator: yes
 - OS: android 9
 - SDK Version 28
 - React Native Version 0.60.1

**Comment by ferdicus** [comment]
```
<MapBoxMapView
      style={{ flex: 1 }}
      logoEnabled={false}
      // attributionEnabled={false}
      compassEnabled
      onRegionDidChange={async (data) => {onRegionDidChange}
      onDidFinishRenderingMapFully={onMapRenderComplete}
    >
      <Camera
        zoomLevel={14}
      />
      <UserLocation />
</MapView>
```

I see two things already:
`<MapBoxMapView>` and `</MapView>`

And not quite sure, that you can comment out props on a component like that in JSX.
`// attributionEnabled={false}`

**Comment by ShaharyarMaroof** [comment]
@ferdicus fixed typo in the pasted code. So the commented part is working as expected, when I run the code I get the exception as shown above.

**Comment by ferdicus** [comment]
Are you on current master?

**Comment by ShaharyarMaroof** [comment]
"@mapbox/mapbox-sdk": "^0.9.0",

**Comment by ferdicus** [comment]
Ehm, that's a completely different repo:
`@react-native-mapbox-gl/maps: 7.2.0`

**Comment by ShaharyarMaroof** [comment]
Ah. sorry about that..... I've got 7.0.9. I'll try to update it to the version you mentioned and try again. Thanks!

**Comment by ShaharyarMaroof** [comment]
@ferdicus I have updated the lib to 7.2.0, and followed the iOS installation instructions to install the pods

now I can't even run it on ios, as I am getting the following error now
```
Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents
```

**Comment by ShaharyarMaroof** [comment]
![image](https://user-images.githubusercontent.com/10959027/74548935-93091980-4f70-11ea-9f49-ee3a223f6fdd.png)
Mapbox framework is added to Embed Pods Framework as well.

**Comment by ShaharyarMaroof** [comment]
@ferdicus I wasn't able to get the project running on 7.2.0, but I managed to get 7.0.9 to work on ios and android.

Steps I followed:
1. ```npm i @react-native-mapbox-gl/maps@7.0.9 --save```
2. ```cd ios``` and add the ```pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'``` **only**. Then run ```pod install```. Adding ```use_frameworks!``` was messing up other dependencies.
3. Then go to the [android installation](https://github.com/react-native-mapbox-gl/maps/blob/master/android/install.md) section and manually link the dependencies. 

Now running fine on both platforms. My react-native version is 0.60.6.

**Comment by ferdicus** [comment]
Good to hear 🎉 

I think your best bet is `7.0.10` though.
It has an update of the Android SDK that fixed a major crash bug yet is before the breaking iOS install changes that were introduced with `7.2.0`.

Issue about the crash bug: #625 

Link to release / changelog: https://github.com/react-native-mapbox-gl/maps/releases/tag/7.0.10.2

**Comment by ferdicus** [comment]
Closing

**Comment by ShaharyarMaroof** [comment]
thanks! will take a look at this as well.
