### ISSUE TITLE
Custom GL layers?

### ISSUE THREAD

**Issue by jliebrand** [react-native-mapbox-gl/maps#67]
Is there a plan to support custom GL layers/shaders?

**Comment by mfazekas** [comment]
I assume you're asking https://docs.mapbox.com/mapbox-gl-js/example/custom-style-layer/ 

I don't think the android or ios native sdk supports it. Android seems to have a [CustomLayer](https://docs.mapbox.com/android/api/map-sdk/7.2.0/com/mapbox/mapboxsdk/style/layers/CustomLayer.html) labelled with do not use. There seems to be an [example with cpp](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/src/example_custom_layer.cpp).

I havent found anything like that for ios docs there is an undocumened [MGLOpenGLStyleLayer](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/src/MGLOpenGLStyleLayer.h) - see [LimeGreenStyleLayer example](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/app/LimeGreenStyleLayer.m)

I guess limited usecases could be implemented, but full support doesn't seems to be possible. (Or at least would be very very hard to implement)

**Comment by jliebrand** [comment]
Hmm ok, thanks! we'll need to think of a different solution then

**Comment by mfazekas** [comment]
@jliebrand what is the usecase?

**Comment by jliebrand** [comment]
We use it to animate a wind layer:

![image](https://user-images.githubusercontent.com/23407884/58619691-4a63e000-82bd-11e9-98d7-bf30627e8fc5.png)

**Comment by kristfal** [comment]
This (syncing a native GL context with the map) requires changes in the core library I believe. It should be requested upstream. Closing for now.

**Comment by mfazekas** [comment]
Most of RN native callbacks is currently async. This would require sync commands, also this would require C++ on android. Might be easier once Fabric in RN is implemented.

**Comment by mahipalsingh-syt** [comment]
@jliebrand  @mfazekas can you help me in this wind animation, i'm searching from last 2 weeks for solution. Any link or sample , please

**Comment by MichaelDanielTom** [comment]
Does anyone know if there is a way in the newest version to add a 3d model to the map at a point? It seems somewhat convoluted to do on iOS and is unclear on android based on [this example using SceneKit](https://github.com/mapbox/mapbox-maps-ios/blob/main/Apps/Examples/Examples/All%20Examples/SceneKitExample.swift), at least compared to on the web with libraries like [threebox](https://github.com/jscastro76/threebox). Wondering if there's any way to somehow use [expo-three](https://github.com/expo/expo-three).

**Comment by nthh** [comment]
@MichaelDanielTom were you able to figure anything out? I'm working on the same, currently overlaying a GLView but it would be nice to have access to the projection matrix from the MapView.

**Comment by Dosbodoke** [comment]
> [@jliebrand](https://github.com/jliebrand) [@mfazekas](https://github.com/mfazekas) can you help me in this wind animation, i'm searching from last 2 weeks for solution. Any link or sample , please

Did you got something? I'm struggling with it.
