### ISSUE TITLE
[QUESTION] Can we dynamically change the image for a shape source?

### ISSUE THREAD

**Issue by ShaharyarMaroof** [react-native-mapbox-gl/maps#670]
I am trying to have an active and inactive state for a a map marker which I add to the map. So that when the user presses the marker I can display a different image. But I don't see anything in the document which can help me to achieve it. 

Is there any way to achieve this?

**Comment by mfazekas** [comment]
@ShaharyarMaroof sorry this is an issue tracker, not for questions. Please use stackoverflow or gitter for such questions.

**Comment by ShaharyarMaroof** [comment]
@mfazekas this is a library specific question. There should be some example or documentation available for such functionalities, which isn't available. That's why I had to ask a question here.
