### ISSUE TITLE
Not able to upload build to App Store, getting error code signing "Mapbox.framework" failed. 

### ISSUE THREAD

**Issue by saurabh-nandan** [react-native-mapbox-gl/maps#671]
**Describe the bug**
I am unable to upload build on App Store its getting error code signing "Mapbox.framework" failed.

**Expected behavior**
Should upload to app store
![Screenshot 2020-02-17 at 1 35 20 PM](https://user-images.githubusercontent.com/47634223/74635129-5a915780-518b-11ea-8a37-bba91ce8f9fe.png)

**Versions (please complete the following information):**
 - Platform: iOS
 - Device: iPhone11
 - Emulator/ Simulator: yes
 - OS: iOS 11.0
 - SDK Version: 7.2.0
 - React Native Version: 0.61.2

**Additional context**
Mapbox-iOS-SDK and MapboxMobileEvents are added in pod install automatocally. After click show logs getting this output.

![Screenshot 2020-02-17 at 1 51 14 PM](https://user-images.githubusercontent.com/47634223/74635923-fc657400-518c-11ea-8641-890818b7a67c.png)

**Comment by foyarash** [comment]
I have the same error. It was working on iOS 13.3.0, but the app fails to run on 13.3.1 with error

`Library not loaded: @rpath/Mapbox.framework/Mapbox`

**Comment by mfazekas** [comment]
please check https://github.com/react-native-mapbox-gl/maps/issues/296

**Comment by saurabh-nandan** [comment]
> please check #296

Followed but not working.

**Comment by mfazekas** [comment]
> Followed but not working.

Please include what you did, what not working means and also include relevant logs.

**Comment by saurabh-nandan** [comment]
While i am installing the app in device, its working perfectly but while i am uploading the app on App store it's getting an error message (attached screenshot above) 

Code signing "Mapbox.framework" failed. 
View distribution logs for more information.

I am attaching logs file along it. PFA

[IDEDistributionPipeline.log](https://github.com/react-native-mapbox-gl/maps/files/4213919/IDEDistributionPipeline.log)
[IDEITunesSoftwareService.log](https://github.com/react-native-mapbox-gl/maps/files/4213920/IDEITunesSoftwareService.log)
[IDEDistribution.verbose.log](https://github.com/react-native-mapbox-gl/maps/files/4213921/IDEDistribution.verbose.log)
[IDEDistribution.standard.log](https://github.com/react-native-mapbox-gl/maps/files/4213923/IDEDistribution.standard.log)

IDEDistribution.critical.log and IDEDistributionProvisioning.log file having no data.



Thanks & Regards!
Saurabh Nandan

**Comment by mfazekas** [comment]
@saurabh-nandan  you've still not included what have you tried from #296

**Comment by saurabh-nandan** [comment]
In my Project there is armv7s, armv7, arm64, arm64e available in valid architectures.
I have tried with armv7s, armv7, arm64 but its not working.

**Comment by mfazekas** [comment]
There was an other suggestion there about chaning bitcode settings, also you can try stripping extra architectures - https://stackoverflow.com/questions/53050451/xcode-10-code-signing-my-appframework-fails-because-of-failure-signing-3rd-pa

In order for us to look into we need full reproduction steps from `react-native create...`

**Comment by saurabh-nandan** [comment]
If i don't use "use_frameworks!" in podfile then can it  be any issue ? because i am using "react-native": "0.61.5". so i think there should not be any linking issue.

I don't want to use "use_framework" because i already have another libraries which does not support "use_framework".

Please clarify i am stuck.

**Comment by mfazekas** [comment]
> If i don't use "use_frameworks!" in podfile then can it be any issue ? because i am using "react-native": "0.61.5". so i think there should not be any linking issue.
> 
> I don't want to use "use_framework" because i already have another libraries which does not support "use_framework".
> 
> Please clarify i am stuck.

Sorry this is not the right forum to get such help

**Comment by reyalpsirc** [comment]
In my case the Archive was failing because I have a different scheme name and the variable "CONFIGURATION_BUILD_DIR" on XCode was set to "$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)" instead of "$(BUILD_DIR)/ReleaseProd$(EFFECTIVE_PLATFORM_NAME)"

**Comment by gregoryalary** [comment]
<img width="751" alt="Screenshot 2025-01-15 at 22 44 25" src="https://github.com/user-attachments/assets/95625f0f-ae43-4397-838c-36188f808e11" />

> Invalid Signature. Code failed to satisfy specified code requirement(s). The file at path "VirtualHike.app/Frameworks/MapboxCoreMaps.framework/MapboxCoreMaps" is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/support/code-signing. (ID: b4abd8f7-0b65-4d92-8329-d979f3f737c2)

So i stumbled the same problem when trying to publish a app, the issue was that i wasn't signing my app properly.

Generating a certificate and provisioning profile in a more traditional way, fixed my issue. I followed theses ChatGPT instructions : https://gist.github.com/gregoryalary/471d1f321829ee34852d95c97873d579.
