### ISSUE TITLE
Local Map Tiles

### ISSUE THREAD

**Issue by sfreeman28** [react-native-mapbox-gl/maps#673]
Hi I am simply trying to render local map files from the device storage (not assets).
I have found a few closed issues regarding this but nothing has worked so far.

https://github.com/react-native-mapbox-gl/maps/issues/370
https://github.com/react-native-mapbox-gl/maps/issues/253
https://github.com/react-native-mapbox-gl/maps/blob/7.0.8/example/src/examples/IndoorBuilding.js
https://github.com/nitaliano/react-native-mapbox-gl/issues/1248
https://stackoverflow.com/questions/39045059/how-can-i-use-asset-for-non-apk-files-on-android-in-a-mapbox-gl-style

The different component names are quite confusing (RasterSource, BackgroundLayer, MapView.styleURL) and I'm not sure exactly what one I should be using.

Has anyone got a working example of using local tiles on the map view, or know which components to use?

My current goal is to even get one single tile showing for the max zoom (0/0/0.png)

Any advice is greatly appreciated =]
Thanks

Edit: using version "7.0.8"

**Comment by mfazekas** [comment]
I'm sorry but this an issue tracker and your submission sound more like a question. Gitter or StackOverflow might be a better place to ask such questions. Also please avoid using `does not work` here, describe the concrete issue, and what have you tried in detail. Please understand that the project is run by volunteers in their own free time, and we need to focus our attention to be able to move forward.
