### ISSUE TITLE
Telemetry settings not reflected or updated on Android

### ISSUE THREAD

**Issue by SamCummins** [react-native-mapbox-gl/maps#675]
**Describe the bug**
- A user opens the mapbox menu and selects the header 'Telemetry settings'
- message reads 'You are helping to make OpenStreetMap and Mapbox maps better by contributing anonymous usage data: **More info**, **Agree**, **Disagree** Options are presented.
- if disagree is selected and the menu reopened it doesn't reflect this change and still shows the same message (as if the user has agreed to share their data)
- if you call `MapboxGL.setTelemetryEnabled(false);` it also doesnt reflect this in the menu.
 
happens on a the basic ootb map:

I think to be gdpr compliant the map should not collect data by default, even if it does once **Disagree** is selected it should be then reflected both in the data sent and in the menu options.
`setTelemetryEnabled(false)` should update the menu option too. 

**Versions (please complete the following information):**
 - Platform: Android
 - Device: Multiple devices
 - Emulator/ Simulator: also yes
 - OS: multiple androids including 9
 - cersion number 7.2.0
 - React Native Version 0.60.5

**Comment by mfazekas** [comment]
@SamCummins thanks for the report. Right now there seems to be no feedback, if telemetry is disabled.

Please report to upstream repo:
https://github.com/mapbox/mapbox-gl-native-android

I'm closing as we cannot do much about that here.

https://github.com/mapbox/mapbox-gl-native-android/blob/18264df98db09a3588966981d22d06fed95da9be/MapboxGLAndroidSDK/src/main/java/com/mapbox/mapboxsdk/maps/AttributionDialogManager.java#L110-L142

**Comment by SamCummins** [comment]
Thanks for the reply
