### ISSUE TITLE
Automation Testing with appium for selecting pins.

### ISSUE THREAD

**Issue by praveenkumargjll** [react-native-mapbox-gl/maps#678]
Is the library supports automation testing? Our team is doing automation testing with Appium. Tester has to select a pin on the map. How to achieve this functionality for both iOS and Android.

I have attached a screenshot of iOS UI View Hierarchy.

<img width="1680" alt="Screenshot 2020-02-19 at 5 52 37 PM" src="https://user-images.githubusercontent.com/14681378/74900520-08467580-53db-11ea-8b0c-a491bcd53c02.png">

**Comment by mfazekas** [comment]
@praveenkumargjll Mapbox has some accessibility, see

https://github.com/mapbox/mapbox-gl-native/blob/e27055ff21be1bb7215c3304c65daf0a1fa6e176/platform/ios/src/MGLMapView.mm#L2864-L2894

we don't implement anything extra on top of that. I was able to see some map features like roads/pois but not symbol layers, I haven't debugged it. Sorry we don't have answer for this. 

I'm closing this, but we do wellcome PR-s to improve this.
