### ISSUE TITLE
App Crashes At starting Android 

### ISSUE THREAD

**Issue by Merrick17** [react-native-mapbox-gl/maps#686]
I Cloned the Example to try it out but it crashes always .. 
here is My Info 
info Fetching system and libraries information...
System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 347.50 MB / 11.60 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/bin/node
    npm: 6.14.0 - ~/maps/example/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 25, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Google Play Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1

<*------------------------------------------Crash ScreenShot ----------------------->
![Screenshot_1582725813](https://user-images.githubusercontent.com/25400839/75351931-33ccd280-58a9-11ea-889d-22df738733c3.png)

**Comment by ferdicus** [comment]
hey there 👋 , please explain step by step how you installed and compiled it.

Also, there was an issue template - which you clearly ignored - not cool, next time I will close the ticket without reply.

Sorry to be so harsh, however the template is there for a reason.

**Comment by Merrick17** [comment]
Hey Thanks for the reply , anyways i found out the problems after looking into too much issues and tickets .. I will close it but i will say what i did at least if someone faces the same issue as me he can do it .. 
- first problem i enabled multidex 
- second it was a problem with X86 Emulator  
anyways thank you for the reply ...
