### ISSUE TITLE
refactor(locationManager): clean up stop/ pause/ dispose methods

### ISSUE THREAD

**Issue by ferdicus** [react-native-mapbox-gl/maps#691]
locationManager could need a refactor pass.
Methods like `.stop`, `.pause` and `.dispose` are outdated.

Have a look at duplications and outdated code.

Notice #690 should be done before this is started.

**Comment by mfazekas** [comment]
@ferdicus any ETA on this?! As this is a change affecting interface it would be great to be done before 8.0.0 rc released

**Comment by ferdicus** [comment]
I could have a look today - do we have a ETA for `8.0.0 rc release`?

**Comment by mfazekas** [comment]
I think it's ready, i don't know any outstanding issues - as soon as you ready we can do an 8.0.0 rc

**Comment by ferdicus** [comment]
resolved by #691
