### ISSUE TITLE
Missing MakerView component

### ISSUE THREAD

**Issue by hieunguyendut** [react-native-mapbox-gl/maps#692]
**Describe the bug**
I try to use MakerView but I got error forget to export and I check index.js in lib of react-native-mapbox-gl module in my local node_modals and I realize It doesn't exist. I use custom mapbox module but I also checked with lastest verson 7.2.0 also doesn't exist after install. I also downloaded zip file from this repos of 7.20 verson and checked it, It's not there
I took screenshot of index.js file of @react-native-mapbox-gl/maps/javascript
Any one got the same problem?

**Screenshots**
![Screenshot 2020-02-28 at 10 40 02](https://user-images.githubusercontent.com/30219446/75508504-f8e8ad00-5a16-11ea-964a-9fcdf65baae0.png)

**Versions (please complete the following information):**
mapbox version: "@react-native-mapbox-gl/maps": "react-native-mapbox-gl/maps#f53000547ba5b64ee86551b18080fcb85b3f9489",
node version: v10.16.3
yarn: 1.19.0

**Comment by mfazekas** [comment]
@hieunguyendut #f53000547ba5b64ee86551b18080fcb85b3f9489 doesn't have MarkerView yet, nor 7.2.0. Please use master for that.

**Comment by hieunguyendut** [comment]
Hey @mfazekas , I also downloaded and checked 7.2.0 source release. It doesn't exist.

**Comment by ferdicus** [comment]
As mfazekas said, please use latest `master` not the release `7.2.0`

**Comment by hieunguyendut** [comment]
Hi @ferdicus, thank for your response. Can you show me how to do that? Thanks a lot

**Comment by hieunguyendut** [comment]
Thank @ferdicus, @mfazekas, I figured it out.

**Comment by Mrxpj** [comment]
@hieunguyendut Excuse me，I did, but it still couldn't work。

**Comment by hieunguyendut** [comment]
@Mrxpj  It work but you got another problem. You can see the error when you build app by Xcode I decided to not use that any more.

**Comment by Mrxpj** [comment]
> @Mrxpj It work but you got another problem. You can see the error when you build app by Xcode I decided to not use that any more.
Thank you. I use Visual Studio Code to build my app. Can I use MakerView on Android?
