### ISSUE TITLE
User Location onUpdate don't work as expected

### ISSUE THREAD

**Issue by kozer** [react-native-mapbox-gl/maps#699]
**Describe the bug**
User location `onUpdate` gets fired more than once when I press to reload app on emulator.
Also the `minDisplacement` doesn't seem to be respected as it seems to get fired periodically.

**To Reproduce**
check with this component:
```          
  <MapboxGL.MapView
              ref={c => (this._map = c)}
              onPress={e => {
                this.setState({test:true})
              }}
              style={{ flex: 1, width: '100%', height: '100%' }}
              styleURL={MapboxGL.StyleURL.Street}
              minZoomLevel={6}
              maxZoomLevel={16}
              showUserLocation={true}
              logoEnabled={false}
              attributionEnabled={false}
              compassEnabled={false}
              rotateEnabled={false}
            >
              <MapboxGL.Camera
                zoomLevel={currentZoomLevel}
                animationMode={'flyTo'}
                followUserLocation={true}
                followUserMode={'normal'}
                animationDuration={700}
                centerCoordinate={cameraCenter}
              />
              <MapboxGL.UserLocation
              onUpdate={this.handleLocationChange}
              minDisplacement={300}>
              </MapboxGL.UserLocation>
            </MapboxGL.MapView>
```

**Expected behavior**
Not firing too often and especially if I'm in the same spot

**Versions (please complete the following information):**
 - Platform: Android
 - Emulator/ Simulator: yes
 - SDK Version 28
 - React Native Version 0.61.5

**Comment by ferdicus** [comment]
Hey @kozer, could you please test on a real device and update the ticket.

Thanks

**Comment by kozer** [comment]
I don't know how to find if the update method called many times on the device. Is there any guide to do this? ( Right now on emulator just do console.log with and see the logs on metro server. You know js debugging)

**Comment by ferdicus** [comment]
Are you on current `master`?

Add a `View` somewhere on top of the map and log the amount of location updates there, that way you have an idea about the amount of updates.

**Comment by kozer** [comment]
No I'm on `7.2.0`. This has been resolved on master?

**Comment by ferdicus** [comment]
yeah, there was a fix after the release concerning minDisplacement: https://github.com/react-native-mapbox-gl/maps/commit/6bf3ded3e7e1d62abfd76eeee7b721e2c51808bd

Please try `master`

**Comment by ferdicus** [comment]
closing this, will reopen if there is a response about this after the fix commit
