### ISSUE TITLE
[Discussion] Getting started guide

### ISSUE THREAD

**Issue by ferdicus** [react-native-mapbox-gl/maps#7]
Hey, wanted to start the discussion on what everyone would like to see in a "getting started" guide.

So first of all, do you think this would be something useful to beginners?
I felt a bit lost in the beginning with just the api docs and the examples, so I think a guided `getting started` section that explains how to set everything up would be helpful to get more people in.

Would probably start picking up right from installation: 
* Setting up accessToken
* showing specific map area
* showing user location
* using rasterLayer to render different tiles

Feedback welcome!

**Comment by sfratini** [comment]
I would add something about the offline management. The packs can actually be paused and resumed in a way, but that is not in the docs. You can see it in the examples tho. 

Also I feel a lot of people have questions or problems regarding custom styles. It should be clear to everyone what native SDK version the repo is using at that time so they can adapt accordingly.

**Comment by bigsassy** [comment]
Yes, I think it would be useful and I agree with the topics already brought up.

Assuming the docs are for v7, it should also include something on expressions and how to use them.

@ferdicus Were you planning on writing these, or have you already started?  I can take on this task if nobody else has staked claim to it yet 👍

**Comment by ferdicus** [comment]
thanks for the feedback!

@bigsassy: I was planning on tackling this, bit by bit and concentrate on adding value to the readme as fast as possible. So I would start tomorrow, and see where it goes from there. 
However feel free to join in, expression guides would be more than appreciated!

As for v7, I would want to wait till it has properly landed and then adjust/ add guides afterwards.

**Comment by alexichristakis** [comment]
what's the eta on this package being published to the new namespace? after v7 is finished?

**Comment by bigsassy** [comment]
> So I would start tomorrow, and see where it goes from there.

Works for me 👍

**Comment by ferdicus** [comment]
> what's the eta on this package being published to the new namespace? after v7 is finished?
sorry, no clue..

**Comment by systemlevel** [comment]
> Hey, wanted to start the discussion on what everyone would like to see in a "getting started" guide.
> 
> So first of all, do you think this would be something useful to beginners?
> I felt a bit lost in the beginning with just the api docs and the examples, so I think a guided `getting started` section that explains how to set everything up would be helpful to get more people in.
> 
> Would probably start picking up right from installation:
> 
> * Setting up accessToken
> * showing specific map area
> * showing user location
> * using rasterLayer to render different tiles
> 
> Feedback welcome!

I’d love to contribute.  I have gone through this process a number of times and may be able to add content.  However my understanding is much will change so I’m waiting to confirm any new changes.

**Comment by ferdicus** [comment]
> I’d love to contribute. I have gone through this process a number of times and may be able to add content. However my understanding is much will change so I’m waiting to confirm any new changes.

True, however documentation is always in a state of flux, so why not have a baseline which we can edit later, instead of not helping newbies at all?

**Comment by systemlevel** [comment]
> > I’d love to contribute. I have gone through this process a number of times and may be able to add content. However my understanding is much will change so I’m waiting to confirm any new changes.
> 
> True, however documentation is always in a state of flux, so why not have a baseline which we can edit later, instead of not helping newbies at all?

It’s a valid point. My understanding was that these changes are coming out fairly soon. Perhaps that’s not the case?  My only concern was that these changes were around the corner.

**Comment by ferdicus** [comment]
> It’s a valid point. My understanding was that these changes are coming out fairly soon. Perhaps that’s not the case? My only concern was that these changes were around the corner.

Not sure when and even so, I would assume that some things will stay the way they are.
The things that change can be adjusted in the guides. Just like they have to be adjusted in the Docs.

**Comment by systemlevel** [comment]
iOS Installation Docs updated and enhanced as part of this effort.  Feedback welcome on #9

**Comment by systemlevel** [comment]
@kristfal @nitaliano When you guys get a min check out the new docs updates by @ferdicus and #9 .  

Also, it looks like there is some activity going on at the nitaliano/react-native-mapbox-gl repository.  Should we make it more clear on that repo to encourage moving to this one? Maybe? There might be some confusion as to which repository is intended to be the "official" unofficial repo for the react-native-mapbox-gl efforts?

**Comment by kristfal** [comment]
@systemlevel thanks for your contributions, it is now merged. I haven't heard anything from Nick in a while. As soon as we get the V7 rebase into master here and battle test it a bit, we'll do an "official" unofficial migration of the repo (unless Nick gets back and objects for any reason). 

I'll keep this issue open for now in case of more Doc improvements are wanted

**Comment by kristfal** [comment]
Docs are better than ever, thanks for your contributions. I'll close this issue, but feel free to open issues for specific topics. PRs are more than welcome.
