### ISSUE TITLE
SymbolLayer filter property data type error; unable to pass filter array

### ISSUE THREAD

**Issue by systemlevel** [react-native-mapbox-gl/maps#70]
**Describe the bug**
SymbolLayer filter property docs specify passing a type array.  When I pass an array to the filter property an exception is thrown saying "filter property must be a string".

**To Reproduce**

```
       <Mapbox.ShapeSource>
          <Mapbox.SymbolLayer 
            id="guz" 
            style={{ visibility: "visible" }}
            filter={[
                'all',
                ['==', '$type', 'Point'],
                ['in', 'type', 'Blue Project', 'WFW Project']
            ]}
          />
        </Mapbox.ShapeSource>
```

**Expected behavior**
The symbol layer should filter by the array passed into the SymbolLayer object.

**Screenshots**
<img width="584" alt="Screen Shot 2019-05-29 at 8 52 13 PM" src="https://user-images.githubusercontent.com/894983/58605009-a7c34700-8253-11e9-85a0-a17c1d5e1e99.png">

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: XR Simulator
 - React Native Version 0.59

**Additional context**

In the project examples an array appears to be successfully used.  For example, in the EarthQuakes.js example the CircleLayer appears to use an array filter:

```
            <MapboxGL.CircleLayer
              id="clusteredPoints"
              belowLayerID="pointCount"
              filter={['has', 'point_count']}
              style={layerStyles.clusteredPoints}
            />
```

Not sure why the SymbolLayer array I'm passing in is having the issue.

**Comment by mfazekas** [comment]
@systemlevel seems to be an upstream  mapbox-native-gl / ios issue. The expression is converted to NSPredicate then back to mapbox expression.
```js
[
                'all',
                ['==', '$type', 'Point'],
                ['in', 'type', 'Blue Project', 'WFW Project']
            ]
```
Becomes `NSPredicate predicateWithMGLJSONObject`
```js
"$type" == "Point" AND MGL_FUNCTION("in", "type", "Blue Project", "WFW Project") == 1
```

Which becomes  `predicate mgl_jsonExpressionObject`
```js

[
                'all',
                ['==', '$type', 'Point'],
                ['==', ['in', 'type', 'Blue Project', 'WFW Project'], 1],
            ]
```

And then it fails to parse this expression.

**Comment by mfazekas** [comment]
Bug was reported to upstream repo: https://github.com/mapbox/mapbox-gl-native/issues/14805

**Comment by systemlevel** [comment]
@mfazekas thanks so much for reporting that upstream.

**Comment by lpfunding** [comment]
Would this issue hinder the EarthQuakes.js example from working? I tried to build it in the exact same way, but the app crashes everytime I launch...

Any idea how long this bug will take to fix?

**Comment by lpfunding** [comment]
I believe this issue also exists for SymbolLayer

**Comment by mfazekas** [comment]
@lpfunding it seems that ios mapbox-gl-native have trouble with `!has` too - to be reported on upstream repo.

instead of
```js
filter={['!has', 'point_count']}
```
you can try:
```js
filter={['!', ['has', 'point_count']]}
```

**Comment by mfazekas** [comment]
The `"!has"` issue was reported to upstream: https://github.com/mapbox/mapbox-gl-native/issues/14861

**Comment by mfazekas** [comment]
It turns out `in` and `'==',$type` is legacy filter syntax, and it's no longer supported. Use the new expression syntax to get it work:

```js
["all",
    ["==",["geometry-type"], "Point"],
    ["match",
       ["get", "type"],
       ["Blue Project", "WFW Project"], true,
        false]
]
```

`"!has"` is legacy filter syntax too use `["!", ["has" ...]`
