### ISSUE TITLE
Error while building: Module 'Mapbox' not found

### ISSUE THREAD

**Issue by rzig** [react-native-mapbox-gl/maps#701]
**Describe the bug**
When I try to build an iOS application from a fresh clone followed by `npm install` and `pod install`, I get an error saying "Module 'Mapbox' not found."

**To Reproduce**
1. Clone repository
2. `npm install`
3. `pod install`
4. `react-native run-ios`

**Expected behavior**
The application should build without error.

**Error Output**
```
In file included from 
/Users/Ryan/Documents/weatherApp/node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL/RCTMGLVectorSourceManager.m
:
12
:
In file included from 
/Users/Ryan/Documents/weatherApp/node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL/RCTMGLVectorSource.h
:
9
:
In file included from 
/Users/Ryan/Documents/weatherApp/node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL/RCTMGLTileSource.h
:
6
:
In file included from 
/Users/Ryan/Documents/weatherApp/node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL/RCTMGLSource.h
:
10
:
/Users/Ryan/Documents/weatherApp/node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL/RCTMGLLayer.h
:
15
:
9
: fatal error
: 
module 'Mapbox' not found
@import Mapbox;

 ~~~~~~~^~~~~~
```

**Versions (please complete the following information):**
 - Platform: iOS
 - Device: iPhone X Simulator
 - Emulator/ Simulator: yes - cannot try on a physical device as build fails
 - OS: iOS 12.1, macOS 10.13.6
 - SDK Version: 5.7.0 (this is the Mapbox SDK version)
 - React Native Version 0.61.5

**Comment by mfazekas** [comment]
@rzig pls include version of rn mapbox sdk, and repro steps from `react-native create`.

**Comment by hanafiqp** [comment]
Hi, how you solved this error ? 
It's will be help me, if you want tell me about. 
Thanks
