### ISSUE TITLE
[QUESTION] Do you supporting overlay image on the map

### ISSUE THREAD

**Issue by MiroslavJag** [react-native-mapbox-gl/maps#704]
Is there is a way to make an overlay image on the map with coordination as on mabox-gl-js ?https://docs.mapbox.com/mapbox-gl-js/example/image-on-a-map/

**Comment by mfazekas** [comment]
See RasterLayer

I'm sorry but this an issue tracker and your submission sound more like a question. Gitter or StackOverflow might be a better place to ask such questions. 

Please understand that the project is run by volunteers in their own free time, and we need to focus our attention to be able to move forward.
