### ISSUE TITLE
offlineManager.getPack() is not returning the pack styleURL 

### ISSUE THREAD

**Issue by yilakt** [react-native-mapbox-gl/maps#705]
**Describe the bug** 
I have a bit of an issue when trying rerender a downloaded map.

The styleURL is missing when I run offlineManager.getPack().

I'm able to save/download a map successfully using offlineManager.createPack() as such

const options = {
name: this.state.packageName,
styleURL: "mapbox://styles/{myUserName}/ck7exeill2qxb1irr2lhwsdpz",
bounds: [[bounds[0], bounds[1]], [bounds[2], bounds[3]]],
minZoom: 5,
maxZoom: 7,
};
MapboxGL.offlineManager.createPack(options, this.onDownloadProgress, this.errorListener);

But when I run offlineManager.getPack({packName}) to get the saved package,  I get this response:

{"_metadata": {"name": "map 20"}, "pack": {"bounds": [[Array], [Array]], "metadata": "{"name":"map 20"}"}}

I'm trying to rerender the saved map when the user is offline, so I need to get the styleURL.

I thought it was an issue caused by tile limit, so I tried offlineManager.resetDatabase() and then createPack -> getPack but got the same json object as above w/o styleURL

Any ideas why I cant see the styleURL it was saved under?

Thanks

**To Reproduce**
npm react-native-mapbox-gl/maps 
set up the basic component
create a button with onPress saveMap()
inside async saveMap() ->include the 'const options...' written above and createPack() method written above.
create another button named loadMap()
inside async loadMap() -> include  
const offlinePack = await MapboxGL.offlineManager.getPack("package name")
console.log the offlinePack to see the returned json
it will look like the one above missing the styleURL even though it was included in 'options' variable before running offlineManager.createPack()
{"_metadata": {"name": "map 20"}, "pack": {"bounds": [[Array], [Array]], "metadata": "{"name":"map 20"}"}}

**Expected behavior**
I was expecting there to be a 'styleURL' property inside the returned JSON object from running MapboxGL.offineManager.getPack()

**Screenshots**
No screen shot at the moment. 

**Versions (please complete the following information):**
 - Platform: [e.g. Android, iOS] both (react native)
 - Device: [e.g. iPhone6] (all iPhones / Androids)
 - Emulator/ Simulator: [yes/ no] yes
 - OS: [e.g. iOS8.1] Windows 7 
 - SDK Version [e.g. 22] 7.0.9
 - React Native Version [e.g. 0.59] ~0.61.4

**Additional context**
FYI, i did revert back to a prior version of MapboxGL because the SDK's required use of 'use_frameworks!' which made my program crash. I dont know if this a version related issue, but I hope it's not!

**Comment by mfazekas** [comment]
@yilakt you don't need a styleUrl to use the offline pack. Once you donwloaded an offlinePack, then mapbox will use it automatically, just use the same url you've used to create the packs.

**Comment by yilakt** [comment]
So in that case how would I be able to have multiple offline packs
downloaded?
