### ISSUE TITLE
Question: [Android] Cluster Size Is Very Small and clusterRadius Doesn't Change

### ISSUE THREAD

**Issue by deerek** [react-native-mapbox-gl/maps#706]
**Describe the bug**
The size of my clusters is correct on iOS, but on Android they are very small – only big enough to contain the text of the cluster count number. When I change the clusterRadius prop, the size of the cluster does not change.

**To Reproduce**
`const layerStyles1 = {
  singlePoint: {
    iconImage: ['get', 'icon'],
    iconSize: 1
  },
  clusteredPoints: {
    circleColor: [
      'interpolate',
      ['exponential', 1.5],
      ['get', 'point_count'],
      25, 'white',
      50, 'white',
      75, 'white',
      100, 'white',
      300, 'white',
      750, 'white',
    ],
    circleRadius: [
      'interpolate',
      ['exponential', 50],
      ['get', 'point_count'],
      [0, 25],
      [100, 30],
      [750, 35],
    ],
    circleOpacity: 0.84,
    circleStrokeWidth: 2,
    circleStrokeColor: '#45F3C5',
  },
  clusterCount: {
    textField: ['get', 'point_count'],
    textSize: 12,
  },
}`

**Expected behavior**
I expect the cluster size to match the clusterRadius I set, and to change accordingly when I edit the clusterRadius.

**Screenshots**
![IMG_7429](https://user-images.githubusercontent.com/15710430/76116742-c8b98500-5fa7-11ea-8b0c-30e32c94a51a.JPG)
![IMG_7430](https://user-images.githubusercontent.com/15710430/76116772-ce16cf80-5fa7-11ea-8f77-0d4f0fd6ee78.PNG)

**Versions:**
 Android
 All Android devices
 Occurs on emulator and physical device
 All Android versions
 Using mapbox-gl 7.0.9
 Using React Native 61.5

**Comment by mfazekas** [comment]
@deerek thanks for the report, could you provide a single file, stand-alone example?! 
Something like we have in our examples app:
https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/EarthQuakes.js

No need for a full app, just a self contained view is fine. It would make reproducing and therefore fixing the bug  much easier for us.

**Comment by deerek** [comment]
@mfazekas thanks for the quick response. I'll try to extract a view that will work for reproducing.

**Comment by mfazekas** [comment]
@deerek any update on this?! You can use our BugReport template from here as a starting point:

https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/BugReportExample.js

**Comment by mfazekas** [comment]
I'm closing this pls comment with details or open a new issue with reproduction
