### ISSUE TITLE
Cannot read property 'StyleURL' of undefined

### ISSUE THREAD

**Issue by gokugen** [react-native-mapbox-gl/maps#710]
**Describe the bug**

First of all, sorry for my bad english...
I got every time the same error on my physical device using Expo which is **_Cannot read property 'StyleURL' of undefined_** when I want to import @react-native-mapbox-gl/maps. I followed carefully the instruction for the installation. I used:

> npm install @react-native-mapbox-gl/maps --save

And then I added this in my Podfile:
```
pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'
use_frameworks!
```

and then run `pod install` (I saw that pod installed react-native-mapbox and others things) . I reproduce it on a clean install of this app but get always the same error.

**Screenshots**
https://user-images.githubusercontent.com/14259676/76264349-db5ee300-6261-11ea-88c0-d4ce5cb001ef.PNG

**Versions (please complete the following information):**
 - Platform: [e.g. iOS]
 - Device: [e.g. iPhone7]
 - Emulator/ Simulator: [no]
 - OS: [e.g. iOS13.3.1]
 - SDK Version [e.g. 22]
 - React Native Version [e.g. 0.61.4]

**Comment by mfazekas** [comment]
I think you're trying to load your app from the prebuilt expo app, which doesn't have Mapbox.
You need to run the app version you've compiled from XCode.
