### ISSUE TITLE
add "@react-native-community/cli-platform-ios": "3.0.0" to package.json

### ISSUE THREAD

**Issue by kk12837** [react-native-mapbox-gl/maps#711]
when I followed the steps.

There is an error in step - pod install.

After debugging, it is fine when I add "@react-native-community/cli-platform-ios": "3.0.0" to package.json, rm -rf node_modules and npm install agian.

Then run pod install, works fine.

**Comment by mfazekas** [comment]
@kk12837 what was the error?!

Also `@react-native-community/cli-platform-ios` doesn't seems to have a readme, i don't think it meant to direct consumption.

I'm closing this now, please clarify and will reopen.
