### ISSUE TITLE
Can't build iOS 

### ISSUE THREAD

**Issue by snuuve** [react-native-mapbox-gl/maps#713]
**Describe the bug**
Can't build iOS app (via fastlane).
Here is error:

`error: exportArchive: ipatool failed with an exception: #<CmdSpec::NonZeroExitException: $ /Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool -v -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk -o /var/folders/ds/sjhq63c16_77ckk2wzlmc5780000gn/T/ipatool20200310-54703-f2hobo/thinned-out/armv7/Payload/Cititok.app/Frameworks/Mapbox.framework/Mapbox --generate-dsym /var/folders/ds/sjhq63c16_77ckk2wzlmc5780000gn/T/ipatool20200310-54703-f2hobo/thinned-out/armv7/Payload/Cititok.app/Frameworks/Mapbox.framework/Mapbox.dSYM --strip-swift-symbols /var/folders/ds/sjhq63c16_77ckk2wzlmc5780000gn/T/ipatool20200310-54703-f2hobo/thinned-in/armv7/Payload/Cititok.app/Frameworks/Mapbox.framework/Mapbox
Status: pid 54952 exit 1
Stdout:
Debug: SDK path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk
    Debug: SDK version: 13.1
    Debug: PATH: ['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin', '/Applications/Xcode.app/Contents/Developer/usr/bin']
    Debug: Using: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo
    MachoInfo: cd /
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo" "-info" "/var/folders/ds/sjhq63c16_77ckk2wzlmc5780000gn/T/ipatool20200310-54703-f2hobo/thinned-in/armv7/Payload/Cititok.app/Frameworks/Mapbox.framework/Mapbox"
    -= Output =-
    Non-fat file: /var/folders/ds/sjhq63c16_77ckk2wzlmc5780000gn/T/ipatool20200310-54703-f2hobo/thinned-in/armv7/Payload/Cititok.app/Frameworks/Mapbox.framework/Mapbox is architecture: armv7
    Exited with 0

(...)
     Debug: Command took 0 seconds
    Debug: Found framework/dylib: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk/usr/lib/libz.1.tbd
    Debug: Found framework/dylib: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk/usr/lib/libsqlite3.tbd
    Debug: Search Path: "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/lib/darwin", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk/usr/lib", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.1.sdk/System/Library/Frameworks"
    error: MapboxMobileEvents not found in dylib search path`

**Versions (please complete the following information):**
 - Platform: iOS
- SDK version: 13.1
 - Mapbox version: 7.2.0
 - React Native Version 0.61.5

**Additional context**
On Android is everything fine. Also running on iOS simulator stuck on splash screen.

**Comment by mfazekas** [comment]
@snuuve  do you have `use_frameworks!` in your Podfile?!

**Comment by jeveloper** [comment]
Wasn't "MapboxMobileEvents" removed?

**Comment by mfazekas** [comment]
I'm closing as it's likely a setup issue. If not please provide full repro steps from `react-native init`
