### ISSUE TITLE
React-native 0.59 support

### ISSUE THREAD

**Issue by ansarikhurshid786** [react-native-mapbox-gl/maps#717]
I am using react native v0.59.10. As per documentation need react native 0.60+. 

Many application developed using 0.59. You have give support for 0.59 also and documentation for that version. It is really very difficult install this library in my application.

**Comment by mfazekas** [comment]
8.0.0 is AndroidX so RN 0.60+, but you might get it running using [jetifier in reverse mode](https://github.com/mikehardy/jetifier#to-reverse-jetify--convert-node_modules-dependencies-to-support-libraries). You can also use older version of rnmbgl.

We're happy to accept documentation PR-s, but we don't plan to support 0.59. 

Please understand that the project is run by volunteers in their own free time, and we need to focus our attention to be able to move forward.

**Comment by ansarikhurshid786** [comment]
I will check jetifier in reverse mode.

**Comment by ansarikhurshid786** [comment]
I tried reverse mode but still getting same error : 

```
* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :@react-native-mapbox-gl_maps.
     Required by:
         project :app
      > Unable to find a matching configuration of project :@react-native-mapbox-gl_maps:
          - None of the consumable configurations have attributes.
```

can you please give me idea how to resolve this issue.

**Comment by ansarikhurshid786** [comment]
Otherwise can you tell me which version support react native 0.59?

**Comment by mfazekas** [comment]
@ansarikhurshid786 7.2 should work AFAIK.  The errors you're getting doesn't seems to be android x related, it's more likely a linking issue, maybe 0.59 doesn't have autolink?! 

Sorry we don't have resources to support older RN, thanks for the understading.

**Comment by ansarikhurshid786** [comment]
@mfazekas Thanks for your response. I have linked it properly. I will check again linking steps and i will 7.2 also.

**Comment by ansarikhurshid786** [comment]
7.2 working perfectly in android. now i am facing issue in ios.

**Comment by ansarikhurshid786** [comment]
@mfazekas : I am using 7.2 it is working fine in android. I tried very for ios but still fail cocoapods error. 

can you give suggestion me for ios? it will be really help me alot.
