### ISSUE TITLE
Mapbox framework issue on ios device

### ISSUE THREAD

**Issue by amittri** [react-native-mapbox-gl/maps#719]
dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents
  Referenced from: /private/var/containers/Bundle/Application/6DBF1572-8316-48FC-8CBA-A279F7EA4BD2/appname.app/Frameworks/Mapbox.framework/Mapbox
  Reason: image not found
(lldb) 

Environment:
Host: Mac mini (Mac OS X 10.15.3 (19D76))
Operating System: macOS Catalina 10.15.3 (19D76)
Xcode: Version 11.3.1 (11C504)
React Native: 0.61.5
React: 16.9.0
Node: 10.18.1
Npm: 6 13.4
Homebrew: 2.2.5
Homebrew/homebrew-core: (git revision 028f1; last commit 2020-02-10)
CocoaPods: 1.8.4

**Comment by mfazekas** [comment]
Please search for MapboxMobileEvents in the existing issues
