### ISSUE TITLE
[Question]User tracking

### ISSUE THREAD

**Issue by zanaviska** [react-native-mapbox-gl/maps#722]
Does MapboxGL.UserLocation and MapboxGL.Camera::UserTrackingMode use HighAccuracy?

![Screenshot_2020-03-13-23-17-52-015_com android settings](https://user-images.githubusercontent.com/31745527/76660469-3df00180-6536-11ea-855a-6afc18125f1a.jpg)

**Comment by ferdicus** [comment]
yes
