### ISSUE TITLE
index 1, size 0 Error in React-Native Android and Custom View is not working in android 10

### ISSUE THREAD

**Issue by rsiuli001** [react-native-mapbox-gl/maps#723]
Hi, i am having a weird issue with the mapbox. Same code is behaving differently in iOS 13.3 and Android 10.

React-Native: 0.61.3
mapbox: "@react-native-mapbox-gl/maps": "^8.0.0-rc1",

I have used 
<Mapboxgl.MapView>
   <MapboxGL.Camera>

    <CustomView for searchBox>

      <MapboxGL.PointAnnotation onSelected={() => {}>
          ..... custom view for rendering Marker icons.
      </MapboxGL.PointAnnotation>
   </MapboxGL.Camera>
</Mapboxgl.MapView>

In iOS 13.3 the code is woring as expected, but in Android 10 the onSelected event is not getting triggered and the custom view is also not rendering.

Also, in android for <CustomView for searchBox> its throwing error of "index 1, size 0 ".

Please help me fix this issue.

🚨🚨🚨
* Please respect and fill out the issue template
* Before you report, please make sure you tested on a physical device
* For build issues: Can you reproduce it on a clean install of the example app?
* Please make sure, that code examples are formatted.

If you want others to spend time on your issue, please make sure to first spend some time on the ticket.

Not following the above will lead to the ticket being closed.
Thanks for understanding.

🚨🚨🚨

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Platform: [e.g. Android, iOS]
 - Emulator/ Simulator: [yes/ no]
 - SDK Version [e.g. 22]
 - React Native Version [e.g. 0.59]

**Additional context**

**Comment by ferdicus** [comment]
Closing - use the template correctly

**Comment by FSNagel** [comment]
I had the same problem, where on IOS it worked perfectly and on Android not, I found that the problem came from a text that I had inside my map, it seems that there cannot be any other component besides the map inside MapView and if it does, it needs to be placed after the markers on the map, I hope I helped!

**Comment by shivenj** [comment]
please remove view component from map view , issue fixed
