### ISSUE TITLE
Add text clipping option on symbol layers

### ISSUE THREAD

**Issue by sean-spacer** [react-native-mapbox-gl/maps#736]
When we migrated to Mapbox last year, we were told that they'd be refactoring the shaders for their text and symbol layers to prevent the issue noted in https://github.com/mapbox/mapbox-gl-js/issues/4064 which appears to affect RN Mapbox GL as well. They said this would be worked on in the second half of 2019, which clearly didn't happen.

Can someone confirm that this issue affecting RN Mapbox GL is simply inherited from Mapbox GL JS? Or is it a separate issue?

Have people found any workarounds?

We often have a large number of closely grouped map markers overlapping, with each marker having a label displaying price (which varies considerably, so integrating this into the symbol would involve generating literally hundreds of symbols). I've been putting lots of work into trying to refine our app, but this simple issue continues to make us look incredibly bad to our users.

![image](https://user-images.githubusercontent.com/55733981/77022968-0aeab980-69df-11ea-9101-2f07e4e71e64.png)

**Comment by ferdicus** [comment]
Hey there, have you seen the linked issue in the one you mentioned? https://github.com/mapbox/mapbox-gl-native/issues/8235

It mentioned a [solution via](https://github.com/mapbox/mapbox-gl-native/issues/8235): `"symbol-sort-key"` 


Also, please consider respecting the issue template, thanks

**Comment by sean-spacer** [comment]
Sorry @ferdicus I'm not a dev or regular Github user.

Re: the suggested solution, unfortunately it's doesn't entirely fix the issue, just improves it in some circumstances.

**Comment by mfazekas** [comment]
As a workaround you can try to use SymbolLayer with images only and use the new `Images#onImageMissing`. This allows you to generate images on the fly as needed.

**Comment by mfazekas** [comment]
@sean-spacer can you do a simple example reproducing your issue with `symbol-sort-key`?!

**Comment by mfazekas** [comment]
I'm closing the issue, please include a simple reproducible example with `symbol-sort-key`
