### ISSUE TITLE
Multiple commands produce '[...]/Frameworks/Mapbox.framework'

### ISSUE THREAD

**Issue by magnusburton** [react-native-mapbox-gl/maps#74]
I wanted to switch from [nitaliano/react-native-mapbox-gl](https://github.com/nitaliano/react-native-mapbox-gl) to here but after installing and linking etc. I realize I didn't remove the old framework from ios and android. With no experience, how do I get rid of this build error?

`Multiple commands produce '/.../Frameworks/Mapbox.framework': 1) Target 'app' has copy command from '/Users/magnusburton/Projects/Lisa/app/node_modules/@react-native-mapbox-gl/maps/ios/Mapbox.framework' to '/.../Frameworks/Mapbox.framework'
2) That command depends on command in Target 'app': script phase “[CP] Embed Pods Frameworks”`

My script phases look like this:
![Skärmklipp 2019-05-31 16 32 41](https://user-images.githubusercontent.com/3188613/58712968-ec6cf080-83c1-11e9-9d41-fa2f7240fdd8.png)
![Skärmklipp 2019-05-31 16 34 47](https://user-images.githubusercontent.com/3188613/58713011-0575a180-83c2-11e9-92a7-2d5743dc7b69.png)

Let me know if I missed supplying any information. Thanks a lot!

**Comment by systemlevel** [comment]
@magnusburton This is with the cocoapods installation? If anyone has any feedback that uses cocoapods that would be great.  

Our install instructions are here:  https://github.com/react-native-mapbox-gl/maps/blob/master/ios/install.md

Feedback welcome.

**Comment by magnusburton** [comment]
@systemlevel I eventually solved it simply by checking ‘Copy only when installing’

**Comment by fcandi** [comment]
> Copy only when installing

Hi @magnusburton I have the same problem while trying to switch from mapbox to maplibre. Can you please tell me where exactly i can find this setting? Thx!
