### ISSUE TITLE
Prop localizeLabels is a noop prop

### ISSUE THREAD

**Issue by samufort** [react-native-mapbox-gl/maps#740]
**Describe the bug**
Prop localizeLabels does not localize labels

**To Reproduce**
- Launch application using the library in a device using a different language than english
- In Map mode, zoom out until you see countries labels
- Countries labels are in english

**Expected behavior**
Labels are localized

**Versions (please complete the following information):**
 - Platform: Android, iOS

**Additional context**

In my research I found these commits related to localization but they have been removed from the library.
Android : https://github.com/react-native-mapbox-gl/maps/commit/aef6a25fdd0d53ba5a07c8b58ea076847826d61b
IOS : https://github.com/react-native-mapbox-gl/maps/commit/f88ff18b9fe9211624cf0f5ab9b974d8e0517ddd

Do you have plans to re-integrate this functionality soon ?

**Comment by mfazekas** [comment]
@samufort i guess it was removed as native methods changed and some of that stuff lost during migration to recent mapbox libraries.

For example on ios we have to use: https://docs.mapbox.com/ios/api/maps/5.7.0/Classes/MGLStyle.html#/c:objc(cs)MGLStyle(im)localizeLabelsIntoLocale.

We'd like to support it - PR-s welcome.
