### ISSUE TITLE
Android build issue on: RN 0.60.5 - receiveCommand

### ISSUE THREAD

**Issue by gallgall** [react-native-mapbox-gl/maps#742]
**Describe the bug**
My project builds failed on Android with message:
`../node_modules/@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/annotation/RCTMGLPointAnnotationManager.java:79: error: method does not override or implement a method from a supertype
    @Override
    ^`

If remove this line `@Override` of `RCTMGLPointAnnotationManager.java`, my project was built successfully.
I'm using react-native-mapbox-gl/maps version 8.0.0-rc1.

**Versions:**
 - Platform: Android
 - Device: Vsmart Joy 3
 - Emulator/ Simulator: no
 - OS: 9
 - SDK Version 28
 - React Native Version 0.60.5

**Screenshots**
![Screen Shot 2020-03-22 at 17 58 11](https://user-images.githubusercontent.com/3960588/77247848-8f4f6d80-6c67-11ea-8ec3-bde698cf44d3.png)

**Comment by oleksiikiselov** [comment]
I'm facing the same issue when updated to the latest version.

**Comment by mfazekas** [comment]
It looks like `receiveCommand` with string is RN 0.61+, need to change back to the int version.

**Comment by Axel-Girard** [comment]
Same, my team and I can't build anymore since the last upgrade. Our project is in RN 0.61.

**Comment by Siyavoshi** [comment]
@mfazekas Any updates on this, sir?

**Comment by mfazekas** [comment]
@Siyavoshi pls test master

**Comment by JoaoMosmann** [comment]
I had the same issue. I've tested on master and it's working.
