### ISSUE TITLE
iOS crash with MultilineString with geometries #1679

### ISSUE THREAD

**Issue by ansarikhurshid786** [react-native-mapbox-gl/maps#743]
Drawing line in map using data multinestring data from web service. Getting data like :

```
{
  "type": "FeatureCollection",
  "totalFeatures": 1,
  "features": [
    {
      "type": "Feature",
      "id": "streets.fid--54d835f0_170f233714b_-42f7",
      "geometry": {
        "type": "GeometryCollection",
        "geometries": [
          {
            "type": "MultiLineString",
            "coordinates": [
              [
                [54.37577522, 24.46179556],
                [54.37567198,  24.46167702],
                [54.37560638, 24.46162656],
                [54.375445,24.46148218]
              ],
              [
                [54.37559877,24.46141407],
                [54.37560356,24.46141777],
                [54.37565904,24.46146109]
             ]
        ]
    }
}]}; 
```

Data is something like this working fine in android and crashing in ios.

anyone facing same issue?

**Comment by mfazekas** [comment]
Can you please provide a reproducible example?! A simple screen, like we have in examples is more than enough:

https://github.com/react-native-mapbox-gl/maps/blob/1d59a6faa07e2d7a8d2705d98d82dcea77764370/example/src/examples/QueryAtPoint.js#L1-L98

**Comment by ansarikhurshid786** [comment]
Thanks for example. I will check this.

**Comment by mfazekas** [comment]
Closed the issue, will reopen when we standalone example to reproduce the issue.

**Comment by ansarikhurshid786** [comment]
@mfazekas : after updating sdk. I am facing [https://github.com/mapbox/mapbox-gl-native/issues/12562](url) issue with same situation.
