### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by magax** [react-native-mapbox-gl/maps#747]
Hi, I'm having some issues with the library on versions later than `7.0.8`. Does anyone have the same issue?

**Describe the bug**
The app crashes with no error message when I try to launch both on iOS and Android.

**To Reproduce**
After following the installation guides...
On iOS: `npm install && cd ios && pod install && cd .. && npx react-native run-ios`
On Android: `npm install && npx react-native run-android`

I work on a clean repository with

**Expected behavior**
On `7.0.8` and earlier, the app launches perfectly with no errors.

**Versions (please complete the following information):**
 - Platforms: [Android, iOS]
 - Emulator/ Simulator: `Android emulator 30.0.0`, `iOS simulator/Xcode 11.3.1`
 - SDK Version `Android SDK 28`,`sdk iphonesimulator13.2`
 - React Native Version [0.61.5]

package.json
`"dependencies": {
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/datetimepicker": "^2.1.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.5",
    "@react-native-mapbox-gl/maps": "github:react-native-mapbox-gl/maps#8.0.0-rc1",
    "@react-navigation/bottom-tabs": "^5.0.0-alpha.29",
    "@react-navigation/native": "^5.0.0-alpha.22",
    "@react-navigation/stack": "^5.0.0-alpha.54",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-reanimated": "^1.4.0",
    "react-native-safe-area-context": "^0.6.2",
    "react-native-screens": "^2.0.0-alpha.22",
    "react-native-snap-carousel": "^3.8.4",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.2"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "eslint-plugin-react": "^7.17.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  }`

**Comment by mfazekas** [comment]
@magax you need to include more details, so we can identify the crash. Running from XCode/Android Studio should show you the native crash, but there might be other means too.

On iOS do you have `use_frameworks!` see #714 ?! On android you might be hitting: #737
