### ISSUE TITLE
iOS: RCTConvert.h file not found

### ISSUE THREAD

**Issue by ansarikhurshid786** [react-native-mapbox-gl/maps#749]
I followed ios installation steps. 
After successful installation. I am getting following error in xcode. 
'React/RCTConvert.h' file not found

can anyone face same issue?

**Comment by mfazekas** [comment]
I'm sorry but this an issue tracker and your submission sound more like a question. Gitter or StackOverflow might be a better place to ask such questions.  

This looks like a setup issue, but you've not included steps to reproduce, from `react-native init`.
Also this sounds like a general React Native issue not related to mapbox

Please understand that the project is run by volunteers in their own free time, and we need to focus our attention to be able to move forward.
