### ISSUE TITLE
Installation stuck

### ISSUE THREAD

**Issue by ansarikhurshid786** [react-native-mapbox-gl/maps#750]
Latest version is working with my react native version 0.59.10. As per documentation i read use 1.0.8. I tried install : 
`npm install @react-native-mapbox-gl/maps@7.0.8 --save`
 
But installation is stuck on : 

```
> @react-native-mapbox-gl/maps@7.0.8 preinstall /Users/mac1/Users/Khurshid/Projects/MyLand/React-Native/MyLand/node_modules/@react-native-mapbox-gl/maps
> npm run fetch:ios:sdk


> @react-native-mapbox-gl/maps@7.0.8 fetch:ios:sdk /Users/mac1/Users/Khurshid/Projects/MyLand/React-Native/MyLand/node_modules/@react-native-mapbox-gl/maps
> node ./scripts/download-mapbox-gl-native-ios-if-on-mac.js 5.3.2
```

**Comment by mfazekas** [comment]
This downloads the sdk from mapbox server it might take long time, or stuck if there is network issue.

**Comment by ansarikhurshid786** [comment]
I am waiting last 30 mins
