### ISSUE TITLE
iOS : crash with geoson GeometryCollection

### ISSUE THREAD

**Issue by ansarikhurshid786** [react-native-mapbox-gl/maps#756]
**Describe the bug**
iOS app crashing when geojson data contain GeometryCollection. 

**To Reproduce**
When I update geojson data in shape. 

**Versions (please complete the following information):**
 - Platform: iOS]
 - Device: [iPhone x, iPhone 7 Plus]
 - Emulator/ Simulator: Both (simulator iPhone X), Device iPhone 7 Plus
 - OS: iOS 13.4, iOS 13.3
 - react-native-mapbox-gl Version : 7.0.8
 - React Native Version 0.59.10

In XCode error log : 
```
libc++abi.dylib: terminating with uncaught exception of type mapbox::util::bad_variant_access
(lldb) 
```
cc: @mfazekas

**Comment by mfazekas** [comment]
@ansarikhurshid786 Please include an example to reproduce, we cannot fix bugs if we cannot reproduce them

**Comment by ansarikhurshid786** [comment]
ok sure i will put my geojson code

**Comment by ansarikhurshid786** [comment]
Code : 
 <MapboxGL.MapView> 
 <MapboxGL.ShapeSource id="idStreetLayer" shape={this.state.streetFeatures}>
                        <MapboxGL.LineLayer id="idStreetLayer" style={{ lineJoin: "round", lineCap: "round", lineWidth: 5, lineColor: "#2b307e" }} />
                    </MapboxGL.ShapeSource>

**Comment by ansarikhurshid786** [comment]
Code : 
```
<MapboxGL.MapView> 
 <MapboxGL.ShapeSource id="idStreetLayer" shape={this.state.streetFeatures}>
   <MapboxGL.LineLayer id="idStreetLayer" style={{ lineWidth: 5, lineColor: "#2b307e" }} />
</MapboxGL.ShapeSource>
</MapboxGL.MapView> 
```

**Comment by ansarikhurshid786** [comment]
GeoJSON Data : 
`{"type":"FeatureCollection","totalFeatures":1,"features":[{"type":"Feature","id":"streets.fid--54d835f0_171267cf330_-7d43","geometry":{"type":"GeometryCollection","geometries":[{"type":"MultiLineString","coordinates":[[[54.73164967,24.44591212],[54.73161352,24.4459961],[54.73158341,24.44606027],[54.73156484,24.44609993],[54.73156183,24.44610582],[54.73151238,24.44620221],[54.73145622,24.44630282],[54.73139641,24.44640167],[54.73133301,24.44649862],[54.73126611,24.44659358],[54.73119577,24.44668643],[54.73112209,24.44677707],[54.73104513,24.44686541],[54.73096497,24.44695134],[54.73095868,24.44695765],[54.73088172,24.44703476],[54.73079547,24.4471156],[54.73070632,24.44719373],[54.73061435,24.4472691]],[[54.73061435,24.4472691],[54.73051788,24.44734294],[54.73041872,24.44741372],[54.73031698,24.44748137],[54.73021277,24.4475458]],[[54.7285504,24.44807716],[54.72842958,24.44808584],[54.7283085,24.4480909],[54.72818731,24.4480923],[54.72806614,24.44809006],[54.72794511,24.44808417],[54.72782436,24.44807466],[54.72774282,24.44806574],[54.72770402,24.4480615],[54.72758421,24.44804474],[54.72746507,24.44802438],[54.72734672,24.44800045],[54.7272293,24.44797298],[54.72719354,24.44796345],[54.72711293,24.44794198],[54.72699773,24.4479075]],[[54.73188359,24.44454023],[54.73188423,24.44455184],[54.73188483,24.44456347],[54.73188539,24.44457509],[54.7318859,24.44458672],[54.73188636,24.44459834],[54.73188679,24.44460997],[54.73188717,24.4446216],[54.7318875,24.44463322],[54.7318878,24.44464484],[54.73188804,24.44465649],[54.73188825,24.44466813],[54.73188841,24.44467977],[54.73188852,24.44469139],[54.7318886,24.44470303],[54.73188863,24.44471465],[54.73188862,24.44472629],[54.73188856,24.44473794],[54.73188846,24.44474958],[54.73188831,24.4447612],[54.73188812,24.44477284],[54.73188789,24.44478448],[54.73188761,24.44479611],[54.73188729,24.44480774],[54.73188692,24.44481935],[54.73188652,24.44483098],[54.73188606,24.44484262],[54.73188557,24.44485423],[54.73188503,24.44486585],[54.73188444,24.44487748],[54.73188382,24.44488909],[54.73188315,24.44490072],[54.73188244,24.44491234],[54.73188168,24.44492394],[54.73188087,24.44493556],[54.73188003,24.4449472],[54.73187914,24.44495878],[54.7318782,24.44497039],[54.73187723,24.444982],[54.73187621,24.44499357],[54.73187514,24.44500517],[54.73187403,24.44501678],[54.73187289,24.44502835],[54.73187169,24.44503993],[54.73187045,24.44505151],[54.73186917,24.44506307],[54.73186784,24.44507466],[54.73186646,24.44508624],[54.73186506,24.44509779],[54.73186361,24.44510935],[54.7318621,24.4451209],[54.73186056,24.44513244],[54.73185897,24.44514399],[54.73185734,24.44515553],[54.73185567,24.44516707],[54.73185394,24.44517859],[54.73185219,24.4451901],[54.73185039,24.44520164],[54.73184853,24.44521314],[54.73184664,24.44522465],[54.73184471,24.44523615],[54.73184274,24.44524764],[54.73184072,24.44525912],[54.73183865,24.4452706],[54.73183654,24.44528206],[54.73183439,24.44529352],[54.73183221,24.44530499],[54.73182997,24.44531644],[54.73182768,24.44532789],[54.73182536,24.44533934],[54.731823,24.44535076],[54.73182058,24.44536221],[54.73181814,24.4453736],[54.73181564,24.44538502],[54.73181311,24.44539642],[54.73181053,24.44540782],[54.7318079,24.4454192],[54.73180524,24.44543057],[54.73180252,24.44544195],[54.73179977,24.4454533],[54.73179697,24.44546465],[54.73179414,24.44547598],[54.73179126,24.44548731],[54.73178834,24.44549864],[54.73178538,24.44550996],[54.73178236,24.44552125],[54.73177931,24.44553256],[54.73177623,24.44554382],[54.73177309,24.44555511],[54.73176991,24.44556637],[54.73176669,24.44557762],[54.73176342,24.44558889],[54.73176012,24.44560011],[54.73175678,24.44561134],[54.73175339,24.44562254],[54.73174996,24.44563374],[54.73174648,24.44564492],[54.73174297,24.44565611],[54.73173941,24.44566728],[54.73173581,24.44567844],[54.73173217,24.44568958],[54.73172848,24.44570071],[54.73172475,24.44571184],[54.73172099,24.44572295],[54.73171718,24.44573405],[54.73171333,24.44574514],[54.73170943,24.44575622],[54.7317055,24.44576728],[54.73170152,24.44577833],[54.73169751,24.44578936],[54.73169345,24.44580038],[54.73168936,24.44581139],[54.73168521,24.44582238],[54.73168102,24.4458334],[54.7316768,24.44584435],[54.73167254,24.4458553],[54.73166823,24.44586624],[54.73166388,24.44587719],[54.73165949,24.44588809],[54.73165506,24.445899],[54.73165059,24.4459099],[54.73164967,24.44591212]],[[54.73021277,24.4475458],[54.73010517,24.44760753],[54.72999531,24.44766583],[54.72988331,24.44772063],[54.72976932,24.44777187],[54.72965347,24.4478195],[54.72955886,24.44785485],[54.7295359,24.44786343],[54.72941674,24.44790364],[54.72929615,24.44794006],[54.72917425,24.44797267],[54.72905121,24.44800141],[54.72897719,24.44801624],[54.72892715,24.44802626],[54.72880223,24.44804718],[54.72874382,24.44805508],[54.72869016,24.4480623],[54.7286766,24.44806415],[54.7285504,24.44807716]]]}]},"geometry_name":"shape","properties":{"objectid":7642,"adrroadid":137,"streetnumber":null,"internalid":null,"municipality_en":"Abu Dhabi","municipality_ar":"أبوظبي","roadname_pop_en":null,"roadname_pop_ar":null,"roadname_en":"Al Lahim St","roadname_ar":"شارع اللاَّحِم","roadguid":"e2fd484a-0d35-41bb-b8b8-4934ab870e99","geonnameguid":"{AC7114B1-C8CE-4EC2-ABCE-660AC566F890}","districtguid":"C8A38E71-24E4-4C42-8394-926EBCF01F61","approved":null,"roadtype":"internalRoad","shape_len":null}}],"crs":{"type":"name","properties":{"name":"urn:ogc:def:crs:EPSG::4326"}}}`

**Comment by ansarikhurshid786** [comment]
@mfazekas if i pass geojson url instead of shape props it is working but not url update not working. can you please and let me know. i am waiting for your response.

**Comment by mfazekas** [comment]
@ansarikhurshid786  i could repro the crash. But i cannot suggest a workaround. You can try removing stuff from the geojson to figure out which part causes the crash.

**Comment by ansarikhurshid786** [comment]
@mfazekas same thing if i pass url props then it is working fine. url props update not working.

**Comment by ansarikhurshid786** [comment]
I just tried very simple geojson data with geometrycollection(multiline) but still crashing 

```
{
    "type": "FeatureCollection",
    "totalFeatures": 1,
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "GeometryCollection",
                "geometries": [
                    {
                        "type": "MultiLineString",
                        "coordinates": [
                            [
                                [
                                    -105.021443,
                                    39.578057
                                ],
                                [
                                    -105.021507,
                                    39.577809
                                ],
                                [
                                    -105.021572,
                                    39.577495
                                ],
                                [
                                    -105.021572,
                                    39.577164
                                ],
                                [
                                    -105.021572,
                                    39.577032
                                ],
                                [
                                    -105.021529,
                                    39.576784
                                ]
                            ],
                            [
                                [
                                    -105.019898,
                                    39.574997
                                ],
                                [
                                    -105.019598,
                                    39.574898
                                ],
                                [
                                    -105.019061,
                                    39.574782
                                ]
                            ],
                            [
                                [
                                    -105.017173,
                                    39.574402
                                ],
                                [
                                    -105.01698,
                                    39.574385
                                ],
                                [
                                    -105.016636,
                                    39.574385
                                ],
                                [
                                    -105.016508,
                                    39.574402
                                ],
                                [
                                    -105.01595,
                                    39.57427
                                ]
                            ],
                            [
                                [
                                    -105.014276,
                                    39.573972
                                ],
                                [
                                    -105.014126,
                                    39.574038
                                ],
                                [
                                    -105.013825,
                                    39.57417
                                ],
                                [
                                    -105.01331,
                                    39.574452
                                ]
                            ]
                        ]
                    }
                ]
            },
            "properties": {}
        }
    ]
}
```
GeoJson refenece : 
[http://geojsonlint.com/#sample-GeometryCollection](url)

**Comment by ansarikhurshid786** [comment]
Thanks for your suggestion if remove as below then it is working in : 
```
{
    "type": "FeatureCollection",
    "totalFeatures": 1,
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "GeometryCollection",
                "geometries": [
                    {
                        "type": "MultiLineString",
                        "coordinates": [
                            [
                                [  -105.021443, 39.578057],
                                [ -105.021507, 39.577809],
                                [ -105.021572, 39.577495],
                                [ -105.021572, 39.577164],
                                [ -105.021572, 39.577032],
                                [ -105.021529, 39.576784]
                            ]
                        ]
                    }
                ]
            },
            "properties": {}
        }
    ]
} 
```
To 
```
{
                        "type": "MultiLineString",
                        "coordinates": [
                            [
                                [  -105.021443, 39.578057],
                                [ -105.021507, 39.577809],
                                [ -105.021572, 39.577495],
                                [ -105.021572, 39.577164],
                                [ -105.021572, 39.577032],
                                [ -105.021529, 39.576784]
                            ]
                        ]
                    }
                ]
            
}
```

**Comment by mfazekas** [comment]
FWIW this is a simple example to reproduce:

```js
import React from 'react';
import {
  MapView,
  Camera,
  ShapeSource,
  LineLayer,
} from '@react-native-mapbox-gl/maps';

/* Works */
const streetsFeatureOk = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'LineString',
        coordinates: [[0,0], [1,1]],
      },
    }
  ]
};

/* Crashes */
const streetsFeature = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'GeometryCollection',
        geometries: [
          {
            type: 'LineString',
            coordinates: [[0,0], [1,1]],
          }
        ]
      }
    }
  ]
};

class MapBug extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <ShapeSource id="idStreetLayer" shape={streetsFeature}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
      </MapView>
    )
  }
}
```

```js
libc++abi.dylib: terminating with uncaught exception of type mapbox::util::bad_variant_access
```

**Comment by ansarikhurshid786** [comment]
Yes exactly but i was not aware exact issue. As you suggest remove some stufs and try then i tried to remove and test. i found above solution. 

Thanks alot for you support and quick response.

**Comment by Taakn** [comment]
Just for the record, if coordinates is empty app crashes as well

```
const streetsFeatureOk = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'LineString',
        coordinates: [],
      },
    }
  ]
};
```
