### ISSUE TITLE
implement compassViewPosition on android

### ISSUE THREAD

**Issue by ansarikhurshid786** [react-native-mapbox-gl/maps#757]
**Describe the bug**
I want compass visible in bottom right so i am using compassViewMargins props and compassViewPosition(iOS) is not working in android. 

**To Reproduce**
 <MapboxGL.MapView
                    ref={(e) => { this.oMap = e }}
                    animate={true}
                    style={{ flex: 1 }}
                    compassEnabled={true}
                    compassViewMargins={{x: 20, y: devicheight-200)}}
/>

**Expected behavior**
The compass position changes but size remains the same.

**Screenshots**

**Versions (please complete the following information):**
 - Platform: Android
 - Device: Samsung S8
 - Emulator/ Simulator:  no
 - OS: android 
 - react-native-mapbox-gl Version 7.0.8
 - React Native Version [e.g. 0.59.10]
![Screenshot_20200330-125842_MyLand Dev](https://user-images.githubusercontent.com/20280498/77894664-a228fa00-7286-11ea-963f-b8be1c3a3d86.jpg)

**Comment by mfazekas** [comment]
We should implement `setCompassGravity` on android to allow to position the compass. Android also supports Margins in left/right/top/bottom not only horizontal/vertical. Not sure the best way to expose it in a cross platform way.


https://docs.mapbox.com/android/api/map-sdk/9.0.0/com/mapbox/mapboxsdk/maps/UiSettings.html#setCompassMargins-int-int-int-int-

https://docs.mapbox.com/android/api/map-sdk/9.0.0/com/mapbox/mapboxsdk/maps/UiSettings.html#setCompassGravity-int-

Flutter mapbox seems to implement this correclty
https://github.com/tobrun/flutter-mapbox-gl/blob/16439ed8da46576b9af537aa8424d0abf08268e4/android/src/main/java/com/mapbox/mapboxgl/MapboxMapController.java#L909-L946

**Comment by ansarikhurshid786** [comment]
@mfazekas thanks for your response. do you have any workaround to place bottom right which support both platform.
