### ISSUE TITLE
centerCoordinate and zommLevel not found

### ISSUE THREAD

**Issue by The0ld** [react-native-mapbox-gl/maps#758]
Good day

Currently, I am trying to make the basic settings for a personal project with mapbox and react-native, but reading the documentation of this plugin, when using the zoomLevel and centerCoordinate parameters as they tell me I cannot make it react to those changes, I leave you that part of the code:

```
render() {
      return (
        <View style={styles.page}>
          <View style={styles.container}>
            <MapboxGL.MapView
              style={styles.map}
              showUserLocation={true}
              styleURL={'mapbox://styles/mapbox/light-v10'}
              zoomLevel={16}
              centerCoordinate={[-123.1118716, 49.2847564]}
            />
          </View>
        </View>
      );
}
```

**Comment by ferdicus** [comment]
Hey there,
please make sure to respect the issue template for your next ticket.

We're taking the time to maintain this project - please take the time to write a proper issue ticket.


With that being said, you're using solely `MapView` - wherein you should be using additional components - mainly `Compass` and `UserLocation`.

Check out the docs for further info.


Closing this
