### ISSUE TITLE
PointAnnotation onDragEnd screen position is (0,0) on Android

### ISSUE THREAD

**Issue by aimroboticsbying** [react-native-mapbox-gl/maps#760]
**Describe the bug**
Dragging a Point Annotation moves to wrong location on map due to the screen location always (0,0). It works on iOS.

**To Reproduce**
const loc = await this._map.getCoordinateFromView([
      e.properties.screenPointX,
      e.properties.screenPointY,
]);
e.properties.screenPointX and e.properties.screenPointY are always 0.

**Expected behavior**
I expect the point annotation shows up at the location where I drop it.

**Versions (please complete the following information):**
 - Platform: Android
 - Device: Pixel 3 XL, Huawei P20
 - Emulator/ Simulator: yes
 - react-native-mapbox-gl Version 7.2.0
 - React Native Version 0.61

**Comment by mfazekas** [comment]
@aimroboticsbying please post full example. I don't know what is e.

**Comment by aimroboticsbying** [comment]
Hi,

This the component:
`<MapboxGL.PointAnnotation
                id="icon"
                draggable={true}
                onDragEnd={this.onDragEnd}
                coordinate={this.state.location}>
                <Text style={{lineHeight: 88}}>
                  <Image source={icon} `/>`
                </Text>
              </MapboxGL.PointAnnotation>`

This is the event handler:
`async onDragEnd(e) {
    const loc = await this._map.getCoordinateFromView([
      e.properties.screenPointX,
      e.properties.screenPointY,
    ]);
   ...
}`

 (e.properties.screenPointX, e.properties.screenPointY) is always (0,0)

**Comment by aimroboticsbying** [comment]
The fix isn't quite right.
You need to calculate density in both makeEvent and makeDragEvent.

float density = getDisplayDensity();
screenPos.x /= density;
screenPos.y /= density;

**Comment by mfazekas** [comment]
@aimroboticsbying thanks, would you submit a PR to address this?!

**Comment by aimroboticsbying** [comment]
https://github.com/react-native-mapbox-gl/maps/pull/788
