### ISSUE TITLE
Discussion: Issue triage/labelling bots

### ISSUE THREAD

**Issue by mfazekas** [react-native-mapbox-gl/maps#767]
Probably the simplest way what RN uses.

![kép](https://user-images.githubusercontent.com/52435/78249984-7eb4b800-74ef-11ea-86e9-e3e5059a0ce8.png)

Human adds labels like "Needs: Issue Template" then a simple bot can write explanations/comments.

https://github.com/apps/label-actions

**Comment by ferdicus** [comment]
Thanks for creating the ticket Miklós 🙇 
FYI: wanted to tackle this starting next week, too busy this week unfortunately.

As a general idea, shall we consider moving away from travis to GH Actions as well?

**Comment by ferdicus** [comment]
Additionally, yes, I like the idea with the labeling, however I might would even go further, automating it to check if anything from the issue template is missing and it closing the issue automatically.
Too extreme? Wdyt?

**Comment by mfazekas** [comment]
On GH Actions, it has severe limits on OS X build minutes, so we might not be able to switch, we'd need to double check before.

I guess the first step could be manual labelling the we could find a bot that does some/all of the labelling.

**Comment by ferdicus** [comment]
nice, seems to work ☝️
