### ISSUE TITLE
App crashes when using invalid expression

### ISSUE THREAD

**Issue by magnusburton** [react-native-mapbox-gl/maps#77]
**Describe the bug**
Entering an unknown interpolation type causes the Mapbox framework to crash and the app to freeze.

**To Reproduce**
There might be various ways to achieve this but my course of action was:
1. Create a map
2. Create a `ShapeSource` and inside, a `CircleLayer`
3. Add the following style;

`circleRadius: ['interpolate', ['exponentisdsdsdfdfturvrgdal', 1.5], ['zoom'], 1, 1, 7, 2,11, 4]`

4. *crash*

**Expected behavior**
In my case the map went all grey and the app froze. Also got an exception in Xcode

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid property value: [1][0]: Unknown interpolation type exponentisdsdsdal'

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: iPhone8
 - OS: 12.4
 - SDK Version 7.0.0
 - React Native Version 0.57

**Additional context**
I entered the wrong interpolation type due to #76

**Comment by magnusburton** [comment]
Also, adding a lineDasharray (`lineDasharray: [1, 2]`) to a LineLayer produces a crash aswell.

> -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xab36f0d5c441b4b9
2019-05-31 19:47:13.310616+0200 app[30897:1790397] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0xab36f0d5c441b4b9'
*** First throw call stack:
(0x18510d27c 0x1842e79f8 0x185029ab8 0x185112ac4 0x18511475c 0x1073e3844 0x107410bb4 0x1054f0e90 0x1054ea0d4 0x1054d5b44 0x1054d3cc0 0x1054e8220 0x1054e58d4 0x1054e7f14 0x1054e1c68 0x1073c3c4c 0x1073ce0b0 0x10746ded4 0x1075b3ad4 0x1075b552c 0x10760686c 0x107427494 0x1075f9b10 0x1075f9ef4 0x18509f018 0x18509ef98 0x18509e880 0x1850997bc 0x1850990b0 0x18729a79c 0x1b240ea6c 0x104b6c0dc 0x184b5e8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by lpfunding** [comment]
+1 Same issue ^^

**Comment by mattijsf** [comment]
I just opened a new issue about the `lineDasharrray` error here: https://github.com/react-native-mapbox-gl/maps/issues/83

**Comment by kristfal** [comment]
Fixing broken features is good, but how do you guys thing we should treat actual invalid expressions? 

We could do some JS side validation and throw a warning instead, but I’m not sure if it’s worth the effort (native apps crash hard, so it’s sort of expected imo). Thoughts?
