### ISSUE TITLE
Thread kill on UserLocation

### ISSUE THREAD

**Issue by gabrielmoncea** [react-native-mapbox-gl/maps#772]
**Describe the bug**
This warning fires a lot of times until it kills the thread and blocks the app.
Animated `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`  in `Annotation` (at UserLocation.js:218)

**To Reproduce**
Steps to reproduce the behavior. 

[UserLocation example](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/UserLocationChange.js)

**Versions (please complete the following information):**
 - Platform: iOS
 - Device: iPhone6s
 - OS: 13.3
 - react-native-mapbox-gl Version 8.0.0-rc2
 - React Native Version 0.62

**Comment by baijii** [comment]
Same here. Adding `useNativeDriver: false` to the users location annotation animation seems to do the trick. 
```js
// javascript/components/annotations/Annotation.js:61
...
      this.state.shape
        .timing({
          coordinates: this.props.coordinates,
          easing: this.props.animationEasingFunction,
          duration: this.props.animationDuration,
          useNativeDriver: false, // true returns an error, that it can't be used natively
        })
        .start();
...
```

**Comment by mfazekas** [comment]
@baijii thanks, can you please open a PR with this change?!
Event better place would be to set those as default values at `AnimatedPoint`

https://github.com/react-native-mapbox-gl/maps/blob/fc5fd47a52d67397be9230159a3d330f7b68c911/javascript/utils/animated/AnimatedPoint.js#L78-L102

**Comment by baijii** [comment]
@mfazekas I try to.
