### ISSUE TITLE
[BUG]Offline pack manager crash on Android

### ISSUE THREAD

**Issue by zanaviska** [react-native-mapbox-gl/maps#773]
**Describe the bug**
Putting Offlinemanager's getPacks into code leads to crash of App

**To Reproduce**
1)react-native init AwesomeProject
2)follow installation guide of mapbox
3) Put some sample code with mapbox(example in [getting started](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/GettingStarted.md))
4)use MapboxGL.offlineManager.getPacks()
5)npx react-native run-android

Example:
from getting started page + some usage of getPacks in componentDidMount
```
import React, { Component } from "react";
import { StyleSheet, View } from "react-native";
import MapboxGL from "@react-native-mapbox-gl/maps";

MapboxGL.setAccessToken("<YOUR_ACCESSTOKEN>");
const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  container: {
    height: 300,
    width: 300,
    backgroundColor: "tomato"
  },
  map: {
    flex: 1
  }
});

export default class App extends Component {
  componentDidMount() {
    MapboxGL.setTelemetryEnabled(false);
    MapboxGL.offlineManager.getPacks().then(res => (console.log(res)));
  }

  render() {
    return (
      <View style={styles.page}>
        <View style={styles.container}>
          <MapboxGL.MapView style={styles.map} />
        </View>
      </View>
    );
  }
}
```

**Expected behavior**
App works fine and logging all available offline packs

**Versions:**
 - Platform: Android
 - Emulator/ Simulator: no
 - OS: Android 10
 - react-native-mapbox-gl Version 8.0.0
 - React Native Version 0.60.5, 0.62.2

Screenshot:

![Feedback](https://user-images.githubusercontent.com/31745527/78449938-9329b980-7683-11ea-831d-ab8621abd4bf.GIF)

**Comment by zanaviska** [comment]
Funny note: If add code with getPacks() after run-android(so by refreshing apps) nothing crash, and getPacks works well

**Comment by mfazekas** [comment]
@zanaviska what was the exact crash?!

**Comment by zanaviska** [comment]
@mfazekas suddenly stop working. Uploaded post with gif

**Comment by zanaviska** [comment]
The same for RN 0.62.2, and Mapbox 8.0.0

**Comment by L-Yeiser** [comment]
We ran into the same issue. 

Here is the crashing stack trace.
![Screen Shot 2020-04-24 at 8 51 57 AM](https://user-images.githubusercontent.com/6750498/80231890-e058d580-8608-11ea-896a-bfb47d016ea1.png)

It appears that the issue is called by calling `getPack` before the map has loaded.

**Comment by Misioka** [comment]
I have the same issue. After a while of investigation, I found out that one of the returned pack is completely invalid. It has invalid bounding box ([18, 112], [-18, -112]). When I omit it stops crashing. I hope it can help somebody.

**Comment by PontesVinicius** [comment]
> We ran into the same issue.
> 
> Here is the crashing stack trace.
> ![Screen Shot 2020-04-24 at 8 51 57 AM](https://user-images.githubusercontent.com/6750498/80231890-e058d580-8608-11ea-896a-bfb47d016ea1.png)
> 
> It appears that the issue is called by calling `getPack` before the map has loaded. Try
> 
> ```
>   render() {
>     return (
>       <View style={styles.page}>
>         <View style={styles.container}>
>           <MapboxGL.MapView
>             style={styles.map}
>             onDidFinishLoadingMap={() => {
>               MapboxGL.setTelemetryEnabled(false);
>               MapboxGL.offlineManager.getPacks().then(res => (console.log(res)));
>             }}
>           />
>         </View>
>       </View>
>     );
>   }
> ```

Hey bro, work for me, thanks..
