### ISSUE TITLE
Order of features in Layer onPress

### ISSUE THREAD

**Issue by bboure** [react-native-mapbox-gl/maps#781]
When several features overlap or are close to each other but have overlapping hitboxes, `onPress` returns them all.

When an element is hit, I want to perform some actions on one element only: the one that was meant to be hit. For that, I use the first one in the list.
This gives sometimes unexpected behaviours

For example:
![image](https://user-images.githubusercontent.com/7089997/78533075-9e4a2a00-77e8-11ea-8dac-9d8b98e35505.png)

The default hitbox (44x44) overlaps almost completely the "visible" features.

When trying to hit the right feature, the `onPress` event passes both features, becauses they both are in the hitbox. However, the first feature is the left one, because it has a higher `symbolSortKey`. 

Would it make sense to change the behaviour of `onPress()` and/or the underlying `map.queryRenderedFeatures()` so that they return elements in a predicted order (or try to).
For example elements whose center is closest to the hit point would be returned first. 

Or is that something I would need to implement myself in the callback?

A possible issue with that would be if 2 features overlap completely. In that case, returning the top one first makes sense, as you might not even see the one below. 

What do you think?

**Comment by mfazekas** [comment]
@bboure sure it would be great to be able to return the best feature, if there are multiple ones. 

Not sure about implementation. 

We can certainly try to test with smaller hitbox. Not sure about the one with closest one. Let's say closer it 4 pixel away but it has a 4x4 icon, so you just clicked the edge, if there is another one 8 pixel away but it has a 16x16 icon then you clicked in the middle, but the closer center would return the first.

https://docs.mapbox.com/android/maps/examples/query-a-map-feature/

**Comment by bboure** [comment]
@mfazekas Thank you for getting back on this.

Smaller hitboxes helps, sure, but it could generate "misses".
It recommended to have touchable elements to be 44 pixels wide/height at least (so a 44x44 hitbox, as default).

> Not sure about the one with closest one. Let's say closer it 4 pixel away but it has a 4x4 icon, so you just clicked the edge, if there is another one 8 pixel away but it has a 16x16 icon then you clicked in the middle, but the closer center would return the first.

This is kind of the kind of issues I was referring to.
Another idea could be: use the one with the hit closest relative to the center of the icon.

in your example: 4 pixels away of center, with a 4x4 icon would have a value of 1 (4/4) away from the center (the edge), the other one would be 0.5 away from the center (8/16).
For hitboxes bigger than the icon, values could become > 1 (outside the icon) example: 40/16.
A "perfect hit" would be 0.

- Smallest value is the best hit.

We could also prioritize direct hits. Especially if a smaller icon is on top of a bigger one. For example, hitting the small one directly should probably be prioritized somehow no matter the other criterias. 
Also hitting a bigger icon that completely covers a small one should be prioritized. 

Any solutions probably will have pros and cons anyway.

**Comment by mfazekas** [comment]
@bboure not that it's not trival/possible to get the rendered size of a feature, they can have different sizes on different zoom levels based on expressions for example.

I was not suggesting the change of default hitbox, but if we have more than one feature returned use queryFeaturesAtPoint with 1x1 hitbox, and see if it returns less items. 

But even that would be incorrect as you note. 

I don't think we can solve this properly at RN mapbox level. I think can be either solved at native level (mapbox-gl-native) where they know the rendered symbol, or at the application level, where they can have assumptions like every symbol has the same size, etc.
