### ISSUE TITLE
8.0.0-rc3 doesn't render a map inside MapboxGL.MapView

### ISSUE THREAD

**Issue by garydevenay** [react-native-mapbox-gl/maps#793]
**Describe the bug**
No map is being rendered inside the MapboxGL.MapView, but the logo and info icon are displaying.

**To Reproduce**

Example:
```sh
react-native init MapBoxTest && cd MapBoxTest
npm i --save @react-native-mapbox-gl/maps
cd ios/ && pod install && cd ../
react-native run-ios
```

Example:
```js
import React from 'react';
import MapboxGL from "@react-native-mapbox-gl/maps";

const App = () => {
  return (
    <MapboxGL.MapView style={{ flex: 1}}>
    </MapboxGL.MapView>
  );
};

export default App;
```

**Expected behavior**
Expect to see a functioning map inside the container. Instead, it just renders grey without any functionality.

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2020-04-07 at 14 06 57](https://user-images.githubusercontent.com/722306/78672820-14c65500-78d9-11ea-8ea5-87fca8199e60.png)

**Versions (please complete the following information):**
 - Platform: iOS
 - Device: iPhone 11
 - Emulator/ Simulator: Yes
 - OS: iOS 13.4
 - react-native-mapbox-gl Version: 8.0.0-rc3
 - React Native Version: 0.62.1

**Comment by mfazekas** [comment]
@garydevenay do you have an accesstoken set?!

**Comment by garydevenay** [comment]
@mfazekas I do indeed, I omitted it from the snippet for security! Should have mentioned.

**Comment by garydevenay** [comment]
@mfazekas Following your train of thought, I regenerated my accessToken and switched it out. This seems to have resolved the issue.

**Comment by lorenc-tomasz** [comment]
I have similar issue with 8.0.0-rc6. Grey screen. On 8.0.0-rc5 maps works OK.
