### ISSUE TITLE
Android: PointAnnotation renders underneath other layers

### ISSUE THREAD

**Issue by lukemcgregor** [react-native-mapbox-gl/maps#806]
When PointAnnotation is rendered in the same space as another layer (such as LineLayer, or RasterLayer) it shows underneath the other layer. This is almost never what you would want. 

It would be ideal if we could select where the PointAnnotation renders using something similar to aboveLayerID and belowLayerID, but as a default case I think it should render on top of all the other layers (I can't think of many cases where you wouldn't want this anyway).

### Repro

![image](https://user-images.githubusercontent.com/1284608/78832075-c6cb6180-7a3e-11ea-8390-b7dfc9e837ef.png)

```js
<MapboxGL.MapView style={{ flex: 1 }}>
  <MapboxGL.Camera
    bounds={{
      ne: [2, 2],
      sw: [-2, -2],
    }}
  />
  <MapboxGL.ShapeSource
    id="line-source"
    shape={
      {
        type: 'Feature',
        geometry: {
          type: 'LineString',
          coordinates: [[1, 1], [-1, -0.7]],
        },
      }
    }
  />

  <MapboxGL.LineLayer
    id="line-layer"
    sourceID="line-source"
  />
  <MapboxGL.PointAnnotation
    id="point"
    coordinate={[0, 0]}
  />
</MapboxGL.MapView>
```

Changing the order of the elements in code appears to have no effect.

Interestingly if you put content in the PointAnnotation it renders on top with iOS and under in android.

![image](https://user-images.githubusercontent.com/1284608/78833407-efecf180-7a40-11ea-96d9-7c96b5a75a97.png)

```js
        <MapboxGL.PointAnnotation
          id="point"
          coordinate={[-0.1, 0]}
        >
          <Text>test</Text>
        </MapboxGL.PointAnnotation>
```

By pushing it under one of the builtin layers on android this behaviour can be changed eg:

![image](https://user-images.githubusercontent.com/1284608/78833768-83262700-7a41-11ea-8220-400e3c28ec94.png)

```js
        <MapboxGL.LineLayer
          id="line-layer"
          sourceID="line-source"
          style={{ lineWidth: 8, lineColor: 'white' }}
          belowLayerID={Platform.OS === 'android' ? 'mapbox-android-symbol-layer-1' : undefined}
        />
```

**Versions:**
 - Platform: Both
 - Device: iPhone 11 13.4, Pixel 2 8.1
 - Emulator/ Simulator: have tried on both emulator and physical
 - react-native-mapbox-gl Version 8.0.0-rc1
 - React Native Version 0.62

**Comment by mfazekas** [comment]
PointAnnotation has a completely different implementation on iOS and Android.
MarkerView is much more comparable on the 2 platforms.

Adding bellow/aboveLayerID is not possible on iOS and on android it's only possible for SymbolManager, which is right now is a singleton (per MapView).

I'm suggesting the following 2 fixes:
1. Expose the SymbolManager's layer id with some method, this would be android only.(`mapbox-android-symbol-layer-1`)
2. Fix that SymbolManager is added as last to the map. So it's automatically above other layers. 

https://github.com/react-native-mapbox-gl/maps/blob/1f9ca418ba5b1d1f0b228171be4480db7ebc93e2/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/mapview/RCTMGLMapView.java#L423-L425

In the longer term we should be improving SymbolLayer so images can be drawn with ReactNative views.

I've made a table comparing various annotations:
https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Annotations.md

**Comment by lukemcgregor** [comment]
Yeah sounds good, I would actually prefer to be using SymbolLayer anyway but my icons have to be dynamically colored and rotated which I can only do with PointAnnotation at present.

**Comment by mfazekas** [comment]
@lukemcgregor you should be able to rotate using iconRotate. https://github.com/react-native-mapbox-gl/maps/blob/master/docs/SymbolLayer.md#name-13

We might have coloring once SDF images are implemented.

**Comment by lukemcgregor** [comment]
yeah I have rotation with it but not coloring. Ill take another look once they are implemented :) PointAnnotation is working pretty well at the moment for us except for a few little things like this layering one.

**Comment by lukemcgregor** [comment]
Not stale, still an issue

**Comment by Emex4gman** [comment]
Any fix for this yet.  mapbox-android-symbol-layer-1 seems to hide the layer

**Comment by cedriclinares** [comment]
This is still an issue for android and the above "fix" of setting belowLayerID={Platform.OS === 'android' ? 'mapbox-android-symbol-layer-1' : undefined} does not work. It makes the line layer disappear

**Comment by pradeep11** [comment]
> This is still an issue for android and the above "fix" of setting belowLayerID={Platform.OS === 'android' ? 'mapbox-android-symbol-layer-1' : undefined} does not work. It makes the line layer disappear

Facing same challenge with Android, did you get the fix?

**Comment by greifmatthias** [comment]
Any updates on this??

**Comment by roncodes** [comment]
+1 will try and use SymbolLayer for now, but would be nice if PointAnnotation could be rendered above LineLayer on android

**Comment by lin-mengxin** [comment]
+1

**Comment by ansarikhurshid786** [comment]
Any update on this?

**Comment by ombogdan** [comment]
Any update on this?

**Comment by ydhnwb** [comment]
any update of this?

**Comment by ghadeeraqraa1992** [comment]
any update on this?

**Comment by Taher-Dweikat-Mappo** [comment]
Is there any progress on this issue?
As I'm facing the same issue as well and using the fix of:
 setting belowLayerID={Platform.OS === 'android' ? 'mapbox-android-symbol-layer-1' : undefined} will make the line disappear.

**Comment by ajmalzyne** [comment]
any one got solutoin for this issue?

**Comment by Ammar-Ishfaq** [comment]
People coming here for Mapbox version 10 should use the below.

If the street name is below the line layer use this:
.withRouteLineBelowLayerId("road-label-street")

If the annotation layer is below the line layer use this:
.withRouteLineBelowLayerId("mapbox-android-pointAnnotation-layer-1")

**Comment by harishgupta01** [comment]
> [mfazekas](/mfazekas)

Hi @mfazekas  - This is not working for me and having this issue with both Android and iOS where point annotation rendering underneath the line layer. I did try to render Point Annotation after line layer rendering is complete for testing purpose but still facing the issue. Could you please recommend any solution since I have a use case where i need to change the shape of the polygon by dragging the veritces, hence cant replace the Point Annotation with Symbol layer.

**Comment by petertoth-dev** [comment]
@mfazekas ?

**Comment by XSpectrum** [comment]
> People coming here for **Mapbox version 10** should use the below.
> 
> If the _street name layer_ is below the line layer use this: .withRouteLineBelowLayerId("road-label-street")
> 
> If the _annotation layer_ is below the line layer use this: .withRouteLineBelowLayerId("mapbox-android-pointAnnotation-layer-1")
> 
> **NOTE**: This is the **kotlin** version but you can use the layer ID as it's the same for your case of **react-native**

Hi, are those a method from MapView or where can i get the "withRouteLineBelowLayerId()"?

**Comment by XSpectrum** [comment]
> [@mfazekas](https://github.com/mfazekas) ?

Hi @petertoth-dev , did you fin any solution for that ?

**Comment by mcastets** [comment]
For those who are still looking for a solution: 

```
belowLayerID={Mapbox.getAnnotationsLayerID('PointAnnotations')}
```

A PointAnnotation needs to be rendered first.

Kudos to @ourdudekyle (https://github.com/rnmapbox/maps/issues/3732#issuecomment-2643246578)
