### ISSUE TITLE
i tried to install map box in my react native project it shows like "Native part of Mapbox React Native libraries were not registered properly, double check our native installation guides." i installed in a way which is mention in documentation

### ISSUE THREAD

**Issue by jsathu** [react-native-mapbox-gl/maps#807]

**Comment by doyle-mark** [comment]
Did you solve this?

**Comment by jsathu** [comment]
nope

**Comment by awind** [comment]
Maybe this will help you https://stackoverflow.com/questions/58397237/react-native-mapbox-issue/62318576#62318576

**Comment by alex83130** [comment]
I have the same issue with the latest version of react-native-mapbox-gl
/

**Comment by usman22-afaq** [comment]
> I have the same issue with the latest version of react-native-mapbox-gl

can you find the solution?

**Comment by zifahm** [comment]
Any Idea guys?

**Comment by ferdicus** [comment]
There are literally hundreds of devs who are using this lib and are not reporting this issue. 
Please follow the instructions in the issue template and open a new ticket if you still encounter this problem. 

We can not help you with this little information on the issue.

**Comment by zifahm** [comment]
> There are literally hundreds of devs who are using this lib and are not reporting this issue.
> Please follow the instructions in the issue template and open a new ticket if you still encounter this problem.
> 
> We can not help you with this little information on the issue.

Sorry about that, I should Have said something when things started working,

I installed wix react native navigation first then Installed mapbox gl and then things didnt work properly, by inversing the order of installs, things seem to work like a charm.

If your installing it after instlaling react native navigtion by wix then it would be better of starting a project using expo's create react native app would give you intended results.

**Comment by Moonubanna** [comment]
Hello,
I'm facing same problem. anyone suggest what I do.

Thanks

**Comment by ferdicus** [comment]
On which version of RN are y'all?   
The installation guide only applies to version 0.6x and higher.  
If you have a version below that, you need to follow the manual installation steps.

**Comment by borshevsky** [comment]
Have same issue on RN 0.63

**Comment by AKACC** [comment]
I encounter this problem differently on IOS and Android, please make sure you are able to find the followings in your project:
env:
      "react-native": "^0.60.5",
      "@react-native-mapbox-gl/maps": "^8.1.0",

IOS & Android:
make sure you called `MapboxGL.setAccessToken(yourAccessToken)`

Autolink never works for me on Android, so I have to do manually:
1. in `android/settings.gradle`, add this
>   ```
>   include ':rctmgl'
>   project(':rctmgl').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-mapbox-gl/maps/android/rctmgl')
>   ```
2. in `android/app/build.gradle`, add this
> ```
> dependencies {
>     ...
>     implementation project(':rctmgl')
> }
> ```
3. in `MainApplication.java`, add this
> `import com.mapbox.rctmgl.RCTMGLPackage;`
> 
> ```
>  protected List<ReactPackage> getPackages() {
>         // Add additional packages you require here
>         // No need to add RnnPackage and MainReactPackage
>        return Arrays.<ReactPackage>asList(
>            ...
>            new RCTMGLPackage() <-Add this
>        );
>    }  
> ```

Hopefully this can help.

**Comment by Florian-crg** [comment]
Same here.

**Comment by ferdicus** [comment]
did you?

**Comment by forestman27** [comment]
I'm experiencing this issue. I copied and pasted everything from the repo on github react-native-mapbox-gl/maps
I'm using node v16.13.0. 
  "dependencies": {
    "@react-native-mapbox-gl/maps": "^8.5.0",
    "expo": "~44.0.0",
    "expo-status-bar": "~1.2.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-web": "0.17.1"
  }

**Comment by maurosoppelsa** [comment]
Any solution for this issue? I'm facing the same with the latest version of Mapbox and expo:
` "@rnmapbox/maps": "github:rnmapbox/maps#main",
    "@types/react-redux": "^7.1.24",
    "expo": "^45.0.6",
    "expo-camera": "~12.2.0",
    "expo-status-bar": "~1.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-paper": "^4.12.1",
    "react-native-reanimated": "~2.8.0",
    "react-native-safe-area-context": "4.2.4",
    "react-native-screens": "~3.11.1",
    "react-native-vector-icons": "^9.1.0",
    "react-native-web": "0.17.7",`

**Comment by amine-abdelli** [comment]
> I encounter this problem differently on IOS and Android, please make sure you are able to find the followings in your project: env: "react-native": "^0.60.5", "@react-native-mapbox-gl/maps": "^8.1.0",
> 
> IOS & Android: make sure you called `MapboxGL.setAccessToken(yourAccessToken)`
> 
> Autolink never works for me on Android, so I have to do manually:
> 
> 1. in `android/settings.gradle`, add this
> 
> > ```
> > include ':rctmgl'
> > project(':rctmgl').projectDir = new File(rootProject.projectDir, '../node_modules/@react-native-mapbox-gl/maps/android/rctmgl')
> > ```
> 
> 2. in `android/app/build.gradle`, add this
> 
> > ```
> > dependencies {
> >     ...
> >     implementation project(':rctmgl')
> > }
> > ```
> 
> 3. in `MainApplication.java`, add this
> 
> > `import com.mapbox.rctmgl.RCTMGLPackage;`
> > ```
> >  protected List<ReactPackage> getPackages() {
> >         // Add additional packages you require here
> >         // No need to add RnnPackage and MainReactPackage
> >        return Arrays.<ReactPackage>asList(
> >            ...
> >            new RCTMGLPackage() <-Add this
> >        );
> >    }  
> > ```
> 
> Hopefully this can help.

Did you finally managed to sort this out ?
