### ISSUE TITLE
Tapping map stops setCamera transition

### ISSUE THREAD

**Issue by dancherb** [react-native-mapbox-gl/maps#809]
If you set the camera to animate to a new configuration, tapping the map interrupts this and stops the transition. This occurs even when zoomEnabled, scrollEnabled etc. are false and in theory there should be no interactivity.

"react-native": "0.61.5"
"@react-native-mapbox-gl/maps": "^7.0.4"

❤️

**Comment by mfazekas** [comment]
pls include platform (iOS, android) info at least
