### ISSUE TITLE
iOS Crashes When Source for Layer is Missing

### ISSUE THREAD

**Issue by AustinHunt** [react-native-mapbox-gl/maps#816]
**Describe the bug**
Bad-Access abort when a layer references a source that has not been rendered.

**To Reproduce**
Steps to reproduce the behavior. 

1. Create a fresh app with react-native init
2. Install `@react-native-mapbox-gl/maps`
3. Add a layer and reference a source that does not exist.
4. Run it and you will immediately get a crash. (C Bad access error in iOS debugger)

Example:
```js
import React from 'react';
import {
  MapView,
  SymbolLayer,
} from '@react-native-mapbox-gl/maps';

class App extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <SymbolLayer id='test-source' sourceId='non-existant-source' />
      </MapView>
    );
  }
}
```

**Expected behavior**
I expected a warning that a layer cannot be rendered without a source or I expected the layer to just not render anything due to the missing source. It makes development a bit difficult when this is not the case. Often, having your app broken into several components, it is difficult to narrow down the crash.

**Versions (please complete the following information):**
 - Platform: iOS (did not test android)
 - Device: iPhone X, 11, etc
 - Emulator/ Simulator: both simulator and device
 - OS: iOS13.3.1
 - react-native-mapbox-gl Version @8.0.0-rc5
 - React Native Version 0.62.0

**Comment by ansarikhurshid786** [comment]
what about android?

**Comment by jeveloper** [comment]
try the final version, should be fine
