### ISSUE TITLE
pbf is not working in android

### ISSUE THREAD

**Issue by ansarikhurshid786** [react-native-mapbox-gl/maps#817]
I have added vectorsouce to load tms pfb. it is working in ios but getting error in android. 

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior. 

Please include a single standalone React Native component. Use [one of our example](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/BugReportTemplate.js) screens as a starting point.
Please simplify the example as much as possible.

Example:
```js
import React from 'react';
import MapboxGL from '@react-native-mapbox-gl/maps';


class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
         <MapboxGL.VectorSource id="idTestSoruce" tms={true} tileUrlTemplates={["pbfgeoserverurl/{z}/{x}/{y}.pbf"]}>
                            <MapboxGL.FillLayer id="idTestLayer" sourceID="idTestSoruce" sourceLayerID="idfromgeoserver"  style={{ visibility: "visible", fillColor: "red"}} minZoomLevel={12} maxZoomLevel={22} />
                        </MapboxGL.VectorSource>
      </MapView>
    );
  }
}
```

**Expected behavior**
Should show layer in map

**Screenshots**
![Screenshot_20200412-114738_SmartMakani](https://user-images.githubusercontent.com/20280498/79063586-a22bef80-7cb3-11ea-9386-ea74abb43cd8.jpg)

**Versions (please complete the following information):**
 - Platform: [Android]
 - Device: [Samsung Galaxy s8]
 - Emulator/ Simulator: [no]
 - OS: [android version 9]
 - react-native-mapbox-gl Version [e.g. 7.0.8]
 - React Native Version [0.59.10]

**Additional context**
I am getting this error in android only and in ios working perfectly. 

cc: @mfazekas

**Comment by ansarikhurshid786** [comment]
If i change following in android code : 
In 
`@react-native-mapbox-gl/maps/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/sources/RCTMGLTileSource.java`

```
@ReactProp(name="tms")
    public void setTMS(RCTMGLVectorSource source, boolean tms) {
        source.setTMS(tms);
    }
```

It is work with vector but get same error with raster tile. 

any proper solution?

**Comment by mfazekas** [comment]
```js
@ReactProp(name="tms")
    public void setTMS(T source, boolean tms) {
        source.setTMS(tms);
    }
```

**Comment by ansarikhurshid786** [comment]
Thanks, it is working perfectly. will it effect anywhere else ?

**Comment by mfazekas** [comment]
@ansarikhurshid786 nope i don't think so. Pls submit a PR with this change if possible

**Comment by ansarikhurshid786** [comment]
I did already
