### ISSUE TITLE
error Linking "@react-native-mapbox-gl/maps" failed. Run CLI with --verbose flag for more details.

### ISSUE THREAD

**Issue by naxir** [react-native-mapbox-gl/maps#819]
error Linking "@react-native-mapbox-gl/maps" failed. Run CLI with --verbose flag for more details.

"react": "16.9.0",
"react-native": "0.61.5",
"@react-native-mapbox-gl/maps": "^8.0.0",

any help?

**Comment by ansarikhurshid786** [comment]
What you tried and check ios and android installation documentation
