### ISSUE TITLE
fill-extrusion example 

### ISSUE THREAD

**Issue by ansarikhurshid786** [react-native-mapbox-gl/maps#820]
This is not is issue. I am trying to use fill-extrusion layers. But when i am adding following properties in fill-extrusion layer, app get crash. 

  ```
<MapboxGL.FillExtrusionLayer
                                id="bdms_floors_3d"
                                sourceID="bdms_floors_3d"
                                sourceLayerID="bdms_floors_3d"
                                minZoomLevel={9}
                                style={{
                                    fillExtrusionColor: "blue", 
                                    fillExtrusionOpacity: 0.5, 
                                    fillExtrusionBase: {
                                         type: "identity", 
                                         property: "heightval"
                                     }
                                }}
                            />
</MapboxGL.VectorSource>
```

When I am adding 
   ```
fillExtrusionBase: {
       type: "identity", 
       property: "heightval"
}
```
code ios app crashing. 

I just want any sample example or how to use fillExtrusionBase properties?

**Comment by ansarikhurshid786** [comment]
How to use 
`Expression Parameters: zoom, feature, feature-state`

Can you give me simple example please. i tried alot pass value. 

cc: @mfazekas

**Comment by mfazekas** [comment]
@ansarikhurshid786 pls see our Examples folder FlyTo should have sample code. I don't think `{
    type: "identity", 
    property: "heightval"
}` is an expression, and probably that's the reason for crash.

**Comment by ansarikhurshid786** [comment]
Thanks, i will check FlyTo example.
