### ISSUE TITLE
Expression style not working 

### ISSUE THREAD

**Issue by ansarikhurshid786** [react-native-mapbox-gl/maps#821]
**Describe the bug**
I have implement layers in web and now same layers adding in mobile application. 
Using expression to change layers color base on property. 

**To Reproduce**
```
{  
     "id": "landuse",
      "type": "fill",
      "paint": {
        "fill-color": {
          "property": "primaryuseeng",
          "type": "categorical",
          "stops": [
            [  "0", "#10af5f" ]
          ]
   }
}
```

In react native mapboxgl : 
 ```
<MapboxGL.VectorSource {...props}>
    <MapboxGL.FillLayer id="idLandUsage" sourceID="idPlots" sourceLayerID="plotm"
                                style={{
                                    fillOpacity: 0.7, 
                                    fillColor:
                                    [
                                        "step",
                                        ["get", "primaryuseeng"],
                                        '0', "#10af5f",
                                        '1', "#ee2f8d",
                                        '2', "#fd4a45" 
                                ]
                                }}
   />
 </MapboxGL.VectorSource>
```
Note : primaryuseeng value is string data type. 

**Expected behavior**
Different layers color base attribute value. 

**Versions (please complete the following information):**
 - Platform: [Android, iOS]
 - Device: [iPhone11, samsung galaxy s8]
 - Emulator/ Simulator: both
 - OS: [iOS13.3.4, android 9]
 - react-native-mapbox-gl Version [7.0.8]
 - React Native Version [0.59.10]

**Additional context**
Attribute value is number in string data type. like 
```
properties: {
primaryuseeng: "0", 
}
```

**Comment by mfazekas** [comment]
Pls check the EarthQuake example, that should be working, maybe '0', etc. should be a number not a string.

**Comment by ansarikhurshid786** [comment]
I found 'step' express require number. I can fixed to convert as follow: 
```
fillColor: [
"step",
["to-number", ["get", "primaryuseeng"]],
0, "#10af5f",
0, "#10af5f"
]
```

But I could not found solution for string attribute value : 

fillColor: [
"step"
["get", "servicetype"],
"available", "#10af5f"
"notavailabe", "#10af5f"
]

Getting error : 
![Simulator Screen Shot - iPhone 11 - 2020-04-13 at 12 22 50](https://user-images.githubusercontent.com/20280498/79105342-868f1a80-7d81-11ea-9fe7-6eb559e75411.png)

**Comment by ansarikhurshid786** [comment]
I got solution in example folder. 
Now I am using "match" instead of "step". 

@mfazekas thanks for your quick response.

**Comment by ansarikhurshid786** [comment]
I found solution. Now I am using following code for string : 
```
fillColor: [
"step"
["get", "servicetype"],
"available", "#10af5f"
"notavailabe", "#10af5f"
]
```
