### ISSUE TITLE
Camera animationDuration 0 doesn't work

### ISSUE THREAD

**Issue by xander18** [react-native-mapbox-gl/maps#827]
Hi all, with the update 
    "@react-native-mapbox-gl/maps": "^8.0.0-rc3",
MapView Zoom props got removed, since i'm trying to not have the animation loadout on the Camera but even with animationDuration to 0 i still got it.
I want to have the map already ready and zommed with the coordinate wihtout all the loading Camera animation but i don't know how to make it work.

My code :  

    <MapboxGL.MapView
      attributionPosition={{bottom: 8, left: 8}}
      logoEnabled={false}
      styleURL={MapboxGL.StyleURL.Dark}
      compassEnabled={false}
      zoomEnabled={true}
      centerCoordinate={userLocation}
      style={styles.map}>
      <MapboxGL.Camera
        zoomLevel={14}
        animationMode="flyTo"
        animationDuration={0}
        centerCoordinate={userLocation}
        followUserLocation={followUserLocation}
        followUserMode="normal"
        ref={(camera) => (_camera = camera)}
      />

thx for help

**Comment by mfazekas** [comment]
@xander18 also take a look at Camera#initialSettings
