### ISSUE TITLE
Camera animationDuration to 0 doesn't work

### ISSUE THREAD

**Issue by xander18** [react-native-mapbox-gl/maps#828]
**Describe the bug**
MapView Zoom props got removed, since 8.0 update i'm trying to not have the animation loadout on the Camera but even with animationDuration to 0 i still got it.
I want to have the map already ready and zommed with the coordinate wihtout all the loading Camera animation but i don't know how to make it work.

**To Reproduce**
Just install MapBox and use MapboxGL.MapView with MapboxGL.Camera
put your ZoomLevel as you want and animationDuration to 0 we still get the animation

Example:
```js
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@react-native-mapbox-gl/maps';

const IssueExemple = () => {
  return (
    <MapView
      style={{flex: 1}}
      styleURL={MapboxGL.StyleURL.Dark}
      compassEnabled={false}
      zoomEnabled={true}
      centerCoordinate={[-74.00597, 40.71427]}
    >
      <Camera
        zoomLevel={14}
        animationMode="flyTo"
        animationDuration={0}
        centerCoordinate={[-74.00597, 40.71427]}
        followUserLocation={followUserLocation}
        followUserMode="normal"
        ref={(camera) => (_camera = camera)}
      />
    </MapView>
  );
}
```

**Expected behavior**
I don't want the zoomAnimation from Camera 

**Screenshots**
![issue](https://user-images.githubusercontent.com/6272996/79375117-6796b100-7f58-11ea-8f59-79d99fc5efa4.gif)

**Versions (please complete the following information):**
 - Platform: [e.g. Android, iOS]
 - Device: [e.g. iPhone 11 Pro]
 - Emulator/ Simulator: [yes]
 - react-native-mapbox-gl Version [^8.0.0-rc3]
 - React Native Version [0.62.1]

**Comment by mfazekas** [comment]
@xander18 pls check `Camera#defaultSettings`

**Comment by xander18** [comment]
> @xander18 pls check `Camera#defaultSettings`

Thank u
