### ISSUE TITLE
UserLocation minDisplacement not limiting calls for onUpdate

### ISSUE THREAD

**Issue by mzu** [react-native-mapbox-gl/maps#831]
**Description of the issue/bug**
`UserLocation.minDisplacement` does not seem to limit the number of calls on `UserLocation.onUpdate`.

There is currently [no documentation available](https://github.com/react-native-mapbox-gl/maps/blob/master/docs/UserLocation.md), but I assume that the purpose of the property `minDisplacement` is to set the minimum distance (meters?) a user's location has to change before `UserLocation` will receive an update.

Setting `minDisplacement` to high values did not make any difference though.  `UserLocation.onUpdate ` was called by rotating my phone without moving anywhere.

```js
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
UserLocation,
} from '@react-native-mapbox-gl/maps';

const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  onUpdatePosition(location) {
    console.log('Updated position')
    // minDisplacement on UserLocation doesn't seem to limit the 
    // call for onUpdate. 
    this.setState({ location: location });
  }
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer id="idStreetLayer" />
        </ShapeSource>
          <UserLocation
            visible={true}
            renderMode={'normal'}
            minDisplacement={5}
            onUpdate={(location) => this.onUpdatePosition(location)}
            showsUserHeadingIndicator={true} />
      </MapView>
    );
  }
}
```

This might also be related to issue [#770](https://github.com/react-native-mapbox-gl/maps/issues/770)

I might just misunderstand the purpose of `minDisplacement`. If so then this would be a great feature to have.

**Versions:**
 - Platform:  iOS
 - Device: iPhone11
 - Emulator/ Simulator: no
 - OS: 13.4.1
 - react-native-mapbox-gl Version 8.0.0
 - React Native Version 0.62.2

**Comment by ferdicus** [comment]
hey there @mzu, you're right, it should only trigger an update callback when exceeding the threshold of `minDisplacement`. Maybe the android SDK changed something during updates - I can have a look this evening.

**Comment by ferdicus** [comment]
I've tried this on an LG Q7 with the Example app.
In there is an example scene `User Location` -> `Set Displacement`.

You can add an `onUpdate` callback here: https://github.com/react-native-mapbox-gl/maps/blob/452ce86355a6993e96617cf799b98876668b79e7/example/src/examples/SetDisplacement.js#L44

The feature was working as expected,
on `0` location updates where coming in fast, with `5` not so fast anymore and with `10` very few did come in.

I also updated the components state to see if that would affect it, however it was working as before. 

Can you check out the example app as well and let me know what you notice there.

I'll try to set up an iOS project as well - been mainly working with Android myself.

**Comment by Blind12** [comment]
I get the same issue concerning minDisplacement on Android, Samsung S7 with the latest version of this repo. Haven't tested on iOS yet. I am not expecting the onUpdate method to get fired if the user is not moving.

Just print the location from onUpdate(location) in console. It'll be a lot of and you will see that latitude, longitude, altitude are still the same but other values are not. Might be their update that trigger the onUpdate callback.

**Comment by mzu** [comment]
Hi @ferdicus. Thanks for checking!
I tried the Example app on my iPhone11. It's still the same issue for me. I am also logging the call to `setMinDisplacement` which works fine every time I set a new value: 
https://github.com/react-native-mapbox-gl/maps/blob/452ce86355a6993e96617cf799b98876668b79e7/javascript/modules/location/locationManager.js#L84

I also changed the initial value from 0 to 100, which didn't make a difference.

**Comment by ferdicus** [comment]
I just want to clarify, you won't get no location updates at all, especially with smaller displacements. 
Everything below 5m is unfeasible. 


I've been using the code you provided further up @mzu,
with the current release of this repo and a freshly init'ed react-native project.

Here are my results.

### Android, again with an LG Q7 (indoors, phone on desk)
#### Update without minDisplacement (default 0):
```c
[Wed Apr 22 2020 20:40:23.563]  LOG      Updated position
[Wed Apr 22 2020 20:40:24.559]  LOG      Updated position
[Wed Apr 22 2020 20:40:25.555]  LOG      Updated position
[Wed Apr 22 2020 20:40:27.730]  LOG      Updated position
[Wed Apr 22 2020 20:40:28.870]  LOG      Updated position
[Wed Apr 22 2020 20:40:29.870]  LOG      Updated position
[Wed Apr 22 2020 20:40:30.960]  LOG      Updated position
[Wed Apr 22 2020 20:40:31.910]  LOG      Updated position
[Wed Apr 22 2020 20:40:32.880]  LOG      Updated position
[Wed Apr 22 2020 20:40:33.950]  LOG      Updated position
```
~ 1 update per second

#### Update with minDisplacement 10:
```c
[Wed Apr 22 2020 20:43:50.175]  LOG      Updated position
[Wed Apr 22 2020 20:44:07.900]  LOG      Updated position
[Wed Apr 22 2020 20:44:22.442]  LOG      Updated position
[Wed Apr 22 2020 20:44:42.846]  LOG      Updated position
[Wed Apr 22 2020 20:45:06.900]  LOG      Updated position
[Wed Apr 22 2020 20:45:41.920]  LOG      Updated position
[Wed Apr 22 2020 20:46:02.651]  LOG      Updated position
[Wed Apr 22 2020 20:46:10.810]  LOG      Updated position
[Wed Apr 22 2020 20:46:23.170]  LOG      Updated position
[Wed Apr 22 2020 20:47:46.122]  LOG      Updated position
```
~ 1 update 20-30secs

#### Update with minDisplacement 100 (I stopped after 10 mins):
```c
[Wed Apr 22 2020 20:48:47.379]  LOG      Updated position
```
one update...



### iOS iPhone 11 Simulator (all with Location City Run)
#### Update without minDisplacement (default 0):
```c
[Wed Apr 22 2020 21:40:42.204]  LOG      Updated position
[Wed Apr 22 2020 21:40:42.938]  LOG      Updated position
[Wed Apr 22 2020 21:40:44.800]  LOG      Updated position
[Wed Apr 22 2020 21:40:44.926]  LOG      Updated position
[Wed Apr 22 2020 21:40:46.151]  LOG      Updated position
[Wed Apr 22 2020 21:40:47.120]  LOG      Updated position
[Wed Apr 22 2020 21:40:48.133]  LOG      Updated position
[Wed Apr 22 2020 21:40:49.640]  LOG      Updated position
[Wed Apr 22 2020 21:40:50.940]  LOG      Updated position
[Wed Apr 22 2020 21:40:50.897]  LOG      Updated position
```
~ 1 update per second

#### Update with minDisplacement 10:
```c
[Wed Apr 22 2020 21:42:58.883]  LOG      Updated position
[Wed Apr 22 2020 21:43:01.955]  LOG      Updated position
[Wed Apr 22 2020 21:43:04.937]  LOG      Updated position
[Wed Apr 22 2020 21:43:08.934]  LOG      Updated position
[Wed Apr 22 2020 21:43:12.942]  LOG      Updated position
[Wed Apr 22 2020 21:43:14.230]  LOG      Updated position
[Wed Apr 22 2020 21:43:16.959]  LOG      Updated position
[Wed Apr 22 2020 21:43:19.903]  LOG      Updated position
[Wed Apr 22 2020 21:43:22.919]  LOG      Updated position
[Wed Apr 22 2020 21:43:25.842]  LOG      Updated position
```
~ 1 update 4-5secs

#### Update with minDisplacement 100:
```c
[Wed Apr 22 2020 21:47:19.140]  LOG      Updated position
[Wed Apr 22 2020 21:47:47.803]  LOG      Updated position
[Wed Apr 22 2020 21:48:18.815]  LOG      Updated position
[Wed Apr 22 2020 21:48:46.838]  LOG      Updated position
[Wed Apr 22 2020 21:49:10.843]  LOG      Updated position
[Wed Apr 22 2020 21:49:34.828]  LOG      Updated position
[Wed Apr 22 2020 21:50:00.725]  LOG      Updated position
[Wed Apr 22 2020 21:50:23.750]  LOG      Updated position
[Wed Apr 22 2020 21:50:50.849]  LOG      Updated position
[Wed Apr 22 2020 21:51:16.847]  LOG      Updated position
```
~ 1 update 30secs



This looks fine to me.
Maybe I'm missing something?

**Comment by mzu** [comment]
It's working in the Simulator like you say, @ferdicus. 

With the phone I get updates by just slightly touching it. 
![mindisplacement](https://user-images.githubusercontent.com/254075/80032822-a215c600-84e3-11ea-9cda-7a8605ec9e03.gif)

I will try and have a closer look tomorrow. I hope it's not me missing something but I am just using the example code and logging to the console:

<img width="635" alt="Screenshot 2020-04-22 at 21 57 11" src="https://user-images.githubusercontent.com/254075/80033252-44ce4480-84e4-11ea-8ebe-09de19e8632f.png">

**Comment by Blind12** [comment]
Test this fn on real device. Plus just check the callback values. As said above. I get 3-4 updates at the same time with the exact same latitude, longitude, altitude.  Heading, speed  are different but are not supposed to be related to minDisplacement treshold if the user has'nt moved?

**Comment by mzu** [comment]
I run another test, this time on an iPhone 6 (iOS: 12.4.5), not moving, only rotating the phone. Same problem. When logging the location that comes in via onUpdate I can see that the coords haven't changed. The only thing that is different is the heading.


```
LOG  locationManager.onUpdate: {"coords":{"altitude":0,"accuracy":5,"longitude":-0.1337,"latitude":51.50998,"speed":-1,"heading":325.6942443847656},"timestamp":1587716407.5177588}
LOG  locationManager.onUpdate: {"coords":{"altitude":0,"accuracy":5,"longitude":-0.1337,"latitude":51.50998,"speed":-1,"heading":324.6914367675781},"timestamp":1587716407.5177588}
```

**Comment by ferdicus** [comment]
Thanks for extensively testing this @mzu - maybe this might be related to https://github.com/react-native-mapbox-gl/maps/pull/739 or https://github.com/react-native-mapbox-gl/maps/pull/825. I'm not quite sure, though.... 

I would need some more time to investigate. 
@mfazekas , maybe you can shed some light on this?

**Comment by mfazekas** [comment]
@ferdicus I think on iOS the issue is with 

https://github.com/react-native-mapbox-gl/maps/blob/fd4e030210ad126bdf0e36c66526a1b855a063ea/ios/RCTMGL/RCTMGLLocationManager.m#L115-L119


heading changes causes full location update.
Not sure if it's an issue on android and what's the cause.

**Comment by ferdicus** [comment]
Thanks for the hint @mfazekas - I did not observe this on Android.

Should I simply open a PR where I remove `_updateDelegate` on that method?

I'm never quite sure, if others expect that behaviour now, and it would be a detriments to their use cases 😅

**Comment by mfazekas** [comment]
The userLocation expects heading for displaying direction. Maybe we can skip calling delegate when minDisplacement is set.

**Comment by ferdicus** [comment]
Sorry didn't have much time the last few days - gonna carve out some tonight though.
@mzu , would you have time to test the branch when I'm done?

**Comment by mzu** [comment]
> @mzu , would you have time to test the branch when I'm done?

@ferdicus Yes, sure.

**Comment by ferdicus** [comment]
hey @mzu , took a while, sorry.
When you find the time, can you try with branch [`fix/min-displacement-heading`](https://github.com/react-native-mapbox-gl/maps/pull/864).
Thanks 🙇

**Comment by mzu** [comment]
Hi @ferdicus. Just tested the branch and `onUpdate` gets now called as expected, i.e. when `minDisplacement` is reached. Thanks for taking care of this!

I just wanted to note that when `showsUserHeadingIndicator={true}` is set, the indicator **arrow** is also affected. It only updates along with `minDisplacement`. I assume it's not possible with this fix to keep the `onUpdate` callback independent from the heading indicator updates. I just think that most use cases want to see the heading indicator continuously updating and see the displacement updates only in terms of 'moving a certain distance on the ground'. Maybe the only solution for this case is to keep the displacement at 0 and limit any state updates inside the `onUpdate` callback instead.

At least there is now a choice since before the `minDisplacement` value didn't have any effect on iOS. Thanks :)

**Comment by sebringj** [comment]
Here's a solution to get best of both tracking smooth while throttling your own update. MapBox is performant for updating user's point already so why limit it? Instead don't limit it and make your own accuracy filter that is performant. I cooked this up and did a timing loop to see perf and 1000 continuous hits to `coordChange` takes ~ 1 ms where < than that was sub ms.

```
function numChange(n1: number, n2: number, accuracy: number) {
  return Math.floor(Math.pow(10, accuracy) * n1) !== Math.floor(Math.pow(10, accuracy) * n2)
}

function coordChange(c1: [number, number], c2: [number, number], accuracy: number) {
  return numChange(c1[0], c2[0], accuracy) || numChange(c1[1], c2[1], accuracy)
}
```
where `accuracy` is  relating to the following table:

0 | 1.0 | 111 km
1 | 0.1 | 11.1 km
2 | 0.01 | 1.11 km
3 | 0.001 | 111 m
4 | 0.0001 | 11.1 m
5 | 0.00001 | 1.11 m
6 | 0.000001 | 0.111 m
7 | 0.0000001 | 1.11 cm
8 | 0.00000001 | 1.11 mm

So you would use it like so:
```
  const onUserLocationChange = (location: MapboxGL.Location): void => {
    const {longitude, latitude} = location.coords;
    const currentCoord: [number, number] = [longitude, latitude];
    if (coordChange(currentCoord, lastLocation, 4)) {
      setLastLocation(currentCoord);
      console.log('User location changed', location);
    }
  }
```
