### ISSUE TITLE
LineLayer not showing on android

### ISSUE THREAD

**Issue by reynacho** [react-native-mapbox-gl/maps#832]
I am using the driving directions api: https://api.mapbox.com/directions/v5/mapbox/driving

The resulting geojson that I'm creating from the route data looks like this (and is stored in state.route):
```
{ type: 'FeatureCollection',
      features: 
       [ { type: 'Feature',
           properties: { name: 'Directions' },
           geometry: 
              { coordinates: [], type: "LineString" },
           distance: 2483335.205
           duration: 91958.492
           weight: 91958.492 
         } ]
}
```

The render code looks like this:
```
<MapboxGL.ShapeSource id='line1' shape={this.state.route}>
	<MapboxGL.LineLayer id='linelayer1' style={{ lineCap: MapboxGL.LineJoin.Round, lineBlur: 1, lineWidth: 5, lineColor: 'green' }} />
</MapboxGL.ShapeSource>
```

This displays  great in iOS but on android, I get an error about geojson must have a type property.  I've tried a ton of different combinations of API options and settings in the render, but nothing seems to change this.  

I have some other maps that contains polygon info that runs like this:
```
<MapboxGL.ShapeSource id='cityBoundary' shape={this.state.cityBoundary} tolerance={0}>
	<MapboxGL.FillLayer id='cityLayer1' style={{ fillColor: 'blue', fillOpacity: .05 }} />
	<MapboxGL.LineLayer id='cityLineLayer1' style={{ lineCap: MapboxGL.LineJoin.Round, lineBlur: 1, lineWidth: 1, lineColor: 'blue' }} />
</MapboxGL.ShapeSource>
```

My only thought is that the sheer volume of data in the directions has over 16k coordinates and the polygon data doesn't have near that much data.  Any ideas on how to get around this?

**Comment by reynacho** [comment]
Update, I ran this in the simulator and did directions from only a few blocks away from the destination and still no line.  This only had about 50 coordinates.

**Comment by ansarikhurshid786** [comment]
Try : 
```
this.state. cityBoundary = { 
   type: 'FeatureCollection',
      features: 
       [ { type: 'Feature',
           properties: { name: 'Directions' },
           geometry: 
              { coordinates: [], type: "LineString" },
           distance: 2483335.205
           duration: 91958.492
           weight: 91958.492 
         } ]
}

```
To 
```
this.state. cityBoundary = { 

    
      type: 'Feature',
           properties: { name: 'Directions' },
           geometry: 
              { coordinates: [], type: "LineString" },
           distance: 2483335.205
           duration: 91958.492
           weight: 91958.492 
         
}
```

**Comment by reynacho** [comment]
The cityboundary actually works as expected.  However for the driving directions, I have tried removing the FeatureCollection layer since there's only one Feature in the array and just using the Feature object piece.  It does the same thing.  I tried again just now to be double sure and it still doesn't show the line.  I did a shorter directions array and am logging the route being used.  Here's the output from the console:

`{
  type: "Feature"
  properties:
    name: "Directions"
  geometry:
    coordinates: Array(67)
      0: (2) [-118.155319, 34.165592]
      1: (2) [-118.155029, 34.165554]
      2: (2) [-118.153648, 34.165363]
      3: (2) [-118.153587, 34.165356]
      4: (2) [-118.152473, 34.165226]
      5: (2) [-118.152168, 34.165188]
      6: (2) [-118.151558, 34.165184]
      7: (2) [-118.150635, 34.165184]
      8: (2) [-118.150635, 34.164837]
      9: (2) [-118.150642, 34.163616]
      10: (2) [-118.150642, 34.16309]
      11: (2) [-118.150642, 34.163029]
      12: (2) [-118.150627, 34.162315]
      13: (2) [-118.15062, 34.162075]
      14: (2) [-118.150612, 34.161808]
      15: (2) [-118.150612, 34.161472]
      16: (2) [-118.150604, 34.161129]
      17: (2) [-118.150604, 34.160835]
      18: (2) [-118.150597, 34.160194]
      19: (2) [-118.150589, 34.159885]
      20: (2) [-118.150589, 34.159657]
      21: (2) [-118.150589, 34.159569]     
      22: (2) [-118.150581, 34.158806]
      23: (2) [-118.150574, 34.158165]
      24: (2) [-118.150574, 34.157791]
      25: (2) [-118.150574, 34.15741]
      26: (2) [-118.150574, 34.157303]
      27: (2) [-118.150574, 34.157219]
      28: (2) [-118.150574, 34.156658]
      29: (2) [-118.150558, 34.156364]
      30: (2) [-118.150558, 34.155502]
      31: (2) [-118.150551, 34.154823]
      32: (2) [-118.150551, 34.154724]
      33: (2) [-118.150543, 34.15456]
      34: (2) [-118.150543, 34.15411]
      35: (2) [-118.15052, 34.153046]
      36: (2) [-118.15052, 34.152954]
      37: (2) [-118.150513, 34.152851]
      38: (2) [-118.150497, 34.152477]
      39: (2) [-118.150574, 34.15234]
      40: (2) [-118.150581, 34.151577]
      41: (2) [-118.150589, 34.151096]
      42: (2) [-118.150589, 34.150959]
      43: (2) [-118.150459, 34.15099]
      44: (2) [-118.149765, 34.151112]
      45: (2) [-118.148926, 34.151211]
      46: (2) [-118.147758, 34.151279]
      47: (2) [-118.146873, 34.151287]
      48: (2) [-118.146744, 34.151287]
      49: (2) [-118.146194, 34.151268]
      50: (2) [-118.145996, 34.151264]
      51: (2) [-118.145996, 34.151176]
      52: (2) [-118.145996, 34.150787]
      53: (2) [-118.145996, 34.150444]
      54: (2) [-118.145988, 34.150005]
      55: (2) [-118.145988, 34.149525]
      56: (2) [-118.145988, 34.149151]
      57: (2) [-118.145988, 34.148872]
      58: (2) [-118.145981, 34.148396]
      59: (2) [-118.145981, 34.148357]
      60: (2) [-118.145981, 34.148331]
      61: (2) [-118.145981, 34.147953]
      62: (2) [-118.145973, 34.147747]
      63: (2) [-118.145973, 34.147644]
      64: (2) [-118.145828, 34.147644]
      65: (2) [-118.144714, 34.14764]
      66: (2) [-118.144516, 34.14764]
      length: 67
    type: "LineString"`

**Comment by ansarikhurshid786** [comment]
I will suggest check geojson data. you can you geojson validator like geojson and geojsonlint. 
[http://geojsonlint.com/](url)
[http://geojson.io/#map=2/20.0/0.0](url)

**Comment by mfazekas** [comment]
@reynacho pls capture the GeoJSON returned from the server that's not displaying, then create a simple react component with that to reproduce the issue.

**Comment by reynacho** [comment]
As an update, I did create a new project with a single component and it worked there, so I am working through my larger project to see what is causing the issue

**Comment by rgouzal** [comment]
Anyone found a solution for this? I am having the same issue.

**Comment by mirzahayat** [comment]
I'm also trying a truf/helper to make a json of feature collection and also trying to make it manual, Same problem, the line is not render on android, but it work fine in ios, 
So i'm trying to display a Multiple polylines in single map,
i have already create an issue, So its still pending,
So anyone help me How i can resolve it for android,
