### ISSUE TITLE
components.imageBaseURL doesn't work anymore

### ISSUE THREAD

**Issue by nartjie101** [react-native-mapbox-gl/maps#833]
I don't know where to report the issue b/c it's the URL that returned from GET directions API: 
[Banner instruction object](https://docs.mapbox.com/api/navigation/#banner-instruction-object)
So please help me move it to correct place. 

Example: 
[png](https://s3.amazonaws.com/mapbox/shields/v3/ky-237@3x.png)
[svg](https://s3.amazonaws.com/mapbox/shields/v3/ky-237.svg)

**Comment by ansarikhurshid786** [comment]
Please follow bug template

**Comment by mfazekas** [comment]
I don't think it's react native mapbox related which is a community project, please contact mapbox
