### ISSUE TITLE
Android: draggable PointAnnotation moves slightly while tapping on it

### ISSUE THREAD

**Issue by aimroboticsbying** [react-native-mapbox-gl/maps#836]
**Describe the bug**
Point Annotation should be selected/deselected while tapping on it. However, it triggers the dragging events and position shifts slightly which is very annoying.

**To Reproduce**
Just use the official example: ShowPointAnnotation.js make the Point Annotation draggable.

```js
<MapboxGL.PointAnnotation
            draggable={true}
            key={id}
            id={id}
            coordinate={coordinate}
            title={title}>
            <View style={styles.annotationContainer} />
            <MapboxGL.Callout title="This is a sample with image" />
</MapboxGL.PointAnnotation>
```

**Expected behavior**
Point Annotation shouldn't move while tapping on it and no dragging event should be triggered.

**Versions (please complete the following information):**
 - Platform: Android
 - Device: any android device
 - Emulator/ Simulator: no
 - OS: Android 10
 - react-native-mapbox-gl Version 8.0.0
 - React Native Version 0.62.1

**Comment by kunal886496** [comment]
+1 for this

**Comment by mfazekas** [comment]
Looks like it's an issue with mapbox-annotation-plugin we use.

https://github.com/mapbox/mapbox-plugins-android/blob/master/plugin-annotation/src/main/java/com/mapbox/mapboxsdk/plugins/annotation/DraggableAnnotationController.java

ON thing we try is `mapboxMap.getGesturesManager().getMoveGestureDetector().setMoveThreshold()`

https://docs.mapbox.com/android/api/gestures/0.5.1/com/mapbox/android/gestures/MoveGestureDetector.html#setMoveThreshold-float-

**Comment by mfazekas** [comment]
Actually it seems the annotation plugin creates it's own gestureManager, and there seems to be no way to access/configure

https://github.com/mapbox/mapbox-plugins-android/blob/5c52f6676ec88c8a01b86cb7bea94bb8cdffa8a6/plugin-annotation/src/main/java/com/mapbox/mapboxsdk/plugins/annotation/DraggableAnnotationController.java#L33

**Comment by mfazekas** [comment]
I've submitted an upstream issue:
https://github.com/mapbox/mapbox-plugins-android/issues/1120

**Comment by aimroboticsbying** [comment]
@mfazekas awesome. Thanks for looking into it.

**Comment by kunal886496** [comment]
Go away stale[bot] its a lockdown.

**Comment by kunal886496** [comment]
Go away stale.

**Comment by gokugen** [comment]
Face the same issue, does someone find a solution ?

**Comment by nstele** [comment]
@tobrun is there any workaround or solution to avoid this issue on Android?
