### ISSUE TITLE
pod install - too long waiting for download

### ISSUE THREAD

**Issue by kmkrtich** [react-native-mapbox-gl/maps#837]
pod install is taking a whole life for this 2 dependencies:

- Installing @react-native-mapbox-gl-mapbox-static (5.7.0)
- Installing Mapbox-iOS-SDK (5.8.0)

Before I was on mapbox 7.0.3 version, similar issue was there but during npm install.

Any solutions for this ?

**Comment by mfazekas** [comment]
It's downloading SDK from mapbox server.  We need those libs to build.

https://mapbox.s3.amazonaws.com/mapbox-gl-native/ios/builds/mapbox-ios-sdk-5.8.0-dynamic.zip
