### ISSUE TITLE
is not showing the map

### ISSUE THREAD

**Issue by fabriciokjc** [react-native-mapbox-gl/maps#84]
**Describe the bug**
My template is not loading, but other map functions are working.

**Screenshots**
![image](https://user-images.githubusercontent.com/24959165/58848240-3113b880-865c-11e9-8547-47e251f9b1b2.png)

**Versions (please complete the following information):**
 - Platfrom: [Android]
 - Device: [Moto G 5 and Emulator from Android Studio]
 - OS: [Windows 10]
 - SDK Version [e.g. 22]
 - React Native Version [e.g. 0.59]

**Comment by ferdicus** [comment]
Could you please post some code or a link to repo to reproduce this.
Thanks

**Comment by fabriciokjc** [comment]
https://github.com/fabriciokjc/MapaCEFET
