### ISSUE TITLE
programmatic set pitch / tilt

### ISSUE THREAD

**Issue by ansarikhurshid786** [react-native-mapbox-gl/maps#844]
I tried to find set pitch / tilt programmatically to ease for user. 

I used in mapbox-gl-js
oMap.setPitch(pitchVal); //pitchVal from 0 to 60

I am looking for programmatically pitch/tilt map. is there any option do that?

**Comment by ferdicus** [comment]
https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Camera.md
