### ISSUE TITLE
How to make the map location update when app in background mode?

### ISSUE THREAD

**Issue by peterleng** [react-native-mapbox-gl/maps#855]
platform: iOS 13.4
"@react-native-mapbox-gl/maps": "^7.0.3"
"react-native": "0.59.9"

I need to upload the GPS to our backend service when the App is in background mode or screen is off. 
So how to make the map location update when app in background mode?

**Comment by mfazekas** [comment]
Hi i'm sorry but this is a feature request that's not in scope of this project.

Please try find other modules that implements this. I think expo has some support, but not sure if it can be used outside of expo or not and also this module:
https://github.com/mauron85/react-native-background-geolocation
