### ISSUE TITLE
UserLocation HeadingIndicator wrong if used with userFollowMode compass

### ISSUE THREAD

**Issue by baijii** [react-native-mapbox-gl/maps#857]
**Describe the bug**
I have turned on `showsUserHeadingIndicator` at my `UserLocation` and a `Camera` with `followUserMode="compass"`. If I look around with my device the arrow points to a different direction than the Camera.

The camera seems to be correct, but the arrow seems to calculate its angle wrong now. If I look to north, everything is fine. If I turn in any direction the arrow is moving faster, than it should, so that if I look south, the arrow is pointing north. The screenshots should make it clear.

Example:
```js
import React from 'react';
import {
  MapView,
  UserLocation,
  Camera,
} from '@react-native-mapbox-gl/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{ flex: 1 }}>
        <UserLocation
          visible={true}
          showsUserHeadingIndicator={true}
        />
        <Camera
          followUserLocation={true}
          followUserMode="compass"
        />
      </MapView>
    );
  }
}
```
**Expected behavior**
Both should be using the same `heading`-property and thereby pointing to the same direction.

**Versions**
 - Platform: iOS
 - Device: iPhone 8, iPhone XS
 - Emulator/ Simulator: no, actual device
 - OS: iOS 13.4, iOS 13.4.1
 - react-native-mapbox-gl Version 8.0.0, 8.1.0-beta.1 and current master
 - React Native Version 0.62.2

**Screenshots**
Here is a screenshot of my application to make it clearer. I'm holding the device in direction of the blue line.

Looking north: correct arrow
![IMG_3884](https://user-images.githubusercontent.com/4008857/80866352-74bcdb00-8c8e-11ea-8f6d-6d02c4ac76d6.png)

Looking east: ca. +90°
![IMG_3885](https://user-images.githubusercontent.com/4008857/80866414-cb2a1980-8c8e-11ea-99f6-78ed3a7271b3.png)

Looking south: ca. +180°
![IMG_3883](https://user-images.githubusercontent.com/4008857/80866449-00cf0280-8c8f-11ea-8d78-3fb650e6fef0.png)

Looking west: ca. -90°
![IMG_3882](https://user-images.githubusercontent.com/4008857/80866469-1b08e080-8c8f-11ea-8ffd-d16788f0e665.png)

**Comment by baijii** [comment]
With the newly `renderMode="native"` this bug is obsolete, as it now have the proper native heading indicator.

**Comment by sauhardar** [comment]
@baijii , `renderMode="native"` is throwing an error for me on Android?

**Comment by sauhardar** [comment]
@baijii Do you know why `renderMode="native"` prop may not be working for me on my UserLocation component? I'm on `"@react-native-mapbox-gl/maps": "^8.1.0-beta.1"`

**Comment by baijii** [comment]
@sauhardar Not working in general? If it is only on Android, it may be this: https://github.com/react-native-mapbox-gl/maps/issues/869

**Comment by sauhardar** [comment]
@baijii not working at all

**Comment by baijii** [comment]
@sauhardar Yes, I know. I have the same problem. For iOS this is no problem, but for Android I won't get it to work. The reason for this is: #869
