### ISSUE TITLE
map graphics artifacts and fragments when returning from background 

### ISSUE THREAD

**Issue by alexichristakis** [react-native-mapbox-gl/maps#86]
**Describe the bug**
When loading the app from a backgrounded/inactive state, sometimes (but not always) the map is completely incomprehensible from the native map layers (for land, road, water) fragmenting and streaking. Our added layers or annotations are removed. 

**To Reproduce**
Open an app with react native mapbox, exit the app, reload later. 

**Screenshots**
![IMG_5852](https://user-images.githubusercontent.com/21017729/58919410-01b48880-86fc-11e9-9935-81d4377c69ad.JPG)

![demo3](https://user-images.githubusercontent.com/21017729/58919489-4b9d6e80-86fc-11e9-9636-c4dbc399bf47.gif)

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: iPhone X, Xs
 - OS: 12
 - SDK Version: GitHub master branch
 - React Native Version: 0.59.2

**Additional context**

**Comment by kristfal** [comment]
Looks like an upstream issue. How do you style the map view? Can you try using absolute positioning?

**Comment by alexichristakis** [comment]
Yeah it's absolutely positioned, but it is then later wrapped in a component higher up the tree that is relatively positioned. Could that be the issue?

**Comment by kristfal** [comment]
Maybe, but on 6.X.X, positioning the view absolute fixed things. 

Could you try to reproduce with minimum example? For instance, take the example app as a baseline?
