### ISSUE TITLE
iOS Example crushes at start

### ISSUE THREAD

**Issue by Avadon** [react-native-mapbox-gl/maps#860]
**Describe the bug**
iOS example crushes while starting with error "dyld: Library not loaded: @rpath/Mapbox.framework/Mapbox"

**To Reproduce**
yarn install
pod install
open example/ios/RNMapboxGLExample.xcworkspace
then try to Run app on a physical device

**Expected behavior**
App runs correctly

**Screenshots**
![alt text](https://i.ibb.co/hCfq1FZ/Screen-Shot-2020-05-04-at-16-22-47.png)

**Versions (please complete the following information):**
 - Platform: iOS
 - Device: iPhone X
 - Emulator/ Simulator: no
 - iOS version: 13.3.1
 - React Native Version: 0.62.1
 - OS X: 10.13.6
 - Xcode: 10.1

**Comment by mfazekas** [comment]
@Avadon i think this is code signature error in 13.3.1, not related to mapbox.

Upgrading to `13.4` should solve. 

See: 
https://github.com/flutter/flutter/issues/49504#issuecomment-592767041
