### ISSUE TITLE
Style not applied 

### ISSUE THREAD

**Issue by TywinLannisterr** [react-native-mapbox-gl/maps#865]
Hello so it's my first time writing an issue so please forgive any shortcomings 
What I'm trying to do is to apply borderRadius to the map and its container, unfortunately, it seems that my style is being overwritten so can you tell me what is the problem down below is my code

 
const styles = {
  page: {
    flex: 1,
    backgroundColor: '#F5FCFF',
  },
  container: {
    flex: 8.5,
    borderTopEndRadius: scale(30),
    borderTopStartRadius: scale(30),
    backgroundColor: '#ECECEB',
  },
  map: {
    borderTopEndRadius: scale(30),
    borderTopStartRadius: scale(30),
    flex: 1,
  },
};

class Map extends Component {
  static navigationOptions = {
    header: null,
  };
  render() {
    return (
      <View style={styles.page}>
        <View style={{flex: 1.5}}>
          <Header
            Title={'Map'}
            hasBack={true}
            backPressed={this.headerBackPressed}
          />
        </View>
        <View style={styles.container}>
          <MapboxGL.MapView style={styles.map}>
            <MapboxGL.Camera
              zoomLevel={4}
              centerCoordinate={[53.688, 32.4279]}
            />
          </MapboxGL.MapView>
        </View>
        <View style={{flex: 1}} />
      </View>
    );
  }
}

**Comment by mfazekas** [comment]
@TywinLannisterr I'm not sure if we support that. Pls, put the MapView to a container View and and styling to that container.
