### ISSUE TITLE
Map does not load in release APK.

### ISSUE THREAD

**Issue by ravisojitrawork** [react-native-mapbox-gl/maps#868]
**Describe the bug**
Hi all, I am facing such a weird issue which is Map is not displaying in release APK(ShapeSources are placed perfectly where it needs to be). However Map displays completely fine in debug mode.

I also have tested using paid API token(for offline map usage) and free token, but that still doesn't work with any of those token.

Example:
```js
import React from 'react';
import MapboxGL from '@react-native-mapbox-gl/maps';
MapboxGL.setAccessToken('MY_FREE_OR_PAID_TOKEN');

//here is my feature collection
generateFeature(){
let temp = [];
pinList.map(pin => {
  pinList.map(pin => {
    if (pin.longitude && pin.latitude) {
      let exploded = splitByString(pin.name, '.,-');
      let parsed = parseInt(exploded[0]);
      temp.push({
        type: 'Feature',
        id: pin.id,
        properties: {
          ...
        },
        geometry: {
          type: 'Point',
          coordinates: [
            parseFloat(pin.longitude),
            parseFloat(pin.latitude),
          ],
        },
      });
    }
  });

  featureCollections.push({
    type: `FeatureCollection`,
    features: temp,
    id: Math.random(),
  });
}

class MapView extends React.Component {
  render() {
    return (
      <MapboxGL.MapView
                style={styles.map}
                styleURL={MapboxGL.StyleURL.Street}
                logoEnabled={false}
                attributionEnabled={false}
                rotateEnabled={false}
                onDidFinishRenderingMapFully={r => {
                  this.setState({ followUserLocation: true });
                }}>

                <MapboxGL.Images
                  images={{
                    ...
                  }}
                />

                {filteredCollections && filteredCollections.length > 0
                  ? filteredCollections.map(collection => {
                    let random = Math.floor(Math.random() * 90000) + 10000;
                    return (
                      <MapboxGL.ShapeSource
                        id={'symbolLocationSource' + random}
                        hitbox={{ width: 20, height: 20 }}
                        shape={collection}
                        cluster
                        clusterMaxZoomLevel={14}
                        clusterRadius={40}
                        onPress={e => {

                          let payload = e.nativeEvent.payload;
                          if (!payload.properties.cluster) {
                            this.props.navigation.navigate('PinView');
                          }
                        }}>
                        <MapboxGL.SymbolLayer
                          id={`singleNumberSelected${collection.id}`}
                          filter={['==', 'hasNumber', true]}
                          style={{
                            ...
                          }}
                        />

                      </MapboxGL.ShapeSource>
                    );
                  })
                  : null}
                {/* <MapboxGL.UserLocation visible animated /> */}
              </MapboxGL.MapView>
    );
  }
}
```

**Expected behavior**
It should display map even though it is in release mode

**Screenshots**
======= Debug mode =======
![WhatsApp Image 2020-05-10 at 11 12 27 AM (1)](https://user-images.githubusercontent.com/56555402/81491755-56b73200-92af-11ea-9086-d87776c1f43c.jpeg)

======= Release Mode =======
![WhatsApp Image 2020-05-10 at 11 12 27 AM](https://user-images.githubusercontent.com/56555402/81491771-78181e00-92af-11ea-85a9-f29b22671d1a.jpeg)

**Versions :**
 - Platform: [Android, iOS]
 - Device: [Realme 1]
 - Emulator/ Simulator: [no]
 - OS: [Android 9]
 - react-native-mapbox-gl Version [8.0.0]
 - React Native Version [0.61.2]

**Comment by mfazekas** [comment]
@ravisojitrawork thanks for the report, is this something you can repro in a brand new project, started with `react-native init`?! 
Have you taken a look at logcat output?! `adb logcat`
Also have you tested with 8.1.0.beta1?!

**Comment by ravisojitrawork** [comment]
hi @mfazekas , 
Actually it's solved.
Problem was that token was giving **forbidden** error in production. But it was quite confusing as it was not throwing any error in development.

**Comment by mfazekas** [comment]
@ravisojitrawork maybe it had titled cached on the debug app?! So it was dispalying titles. It could be improved in 8.1.0 where we show log messages from mapbox.

**Comment by mdNazmulHasan** [comment]
How did you detect that error ? @ravisojitrawork and whats the solution ?
