### ISSUE TITLE
Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents

### ISSUE THREAD

**Issue by kishansbs** [react-native-mapbox-gl/maps#872]
dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents
  Referenced from: /Users/machd/Library/Developer/CoreSimulator/Devices/7328A473-BA65-40A9-ACCE-4ADE8F62572A/data/Containers/Bundle/Application/BAD0924B-C189-4A85-9816-D03329E66CC3/Explored.app/Frameworks/Mapbox.framework/Mapbox
  Reason: image not found

 "@react-native-mapbox-gl/maps": "^7.2.0",
 "react": "16.8.6",
    "react-native": "0.60.4",

**Comment by mfazekas** [comment]
7.2.0 requires use_framework!

**Comment by kishansbs** [comment]
Also showing same error  when i am using version 7.0.0

**Comment by kishansbs** [comment]
"@react-native-mapbox-gl/maps": "^7.0.0",
 by it loading latest version 7.2.0.
