### ISSUE TITLE
Is there a way to set a feature-state on the map

### ISSUE THREAD

**Issue by SergueyPutilin** [react-native-mapbox-gl/maps#875]
Hi 
I see that we can use the feature-state expression in Layers, but I can't find a way to add a feature-state to the map in the docs.

Is this something that isn't documented in the docs?
I am trying to create something similar to this, but then onClick instead of onHover
https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/

**Comment by mattijsf** [comment]
I'm desperately waiting for this feature as well. Unfortunately it has not been ported fully to iOS and Android yet: https://github.com/mapbox/mapbox-gl-native/issues/12413
