### ISSUE TITLE
Runs on IOS Simulator but fails for device - bitcode

### ISSUE THREAD

**Issue by alew3** [react-native-mapbox-gl/maps#876]
**Describe the bug**
Cannot run on device, as compiling fails with the error:

ld: '/react_maps/maps/example/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a(bio_lib.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**To Reproduce**
Fails to build for device on Xcode the example project, but works for the Simulator.

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Platform: [iOS]
 - Device: [e.g. iPhone X]
 - OS: [e.g. iOS13.5 beta 5]
 - react-native-mapbox-gl Version 
 - React Native Version [e.g. 0.62.1]

**Additional context**
I've tried changing the bitcode settings on Xcode but couldn't get it running.

**Comment by mfazekas** [comment]
Thanks for the report, i don't think we have openssl dependency, i think the same happens if you dont use RNMBGL in the project. So it's a RN issue not RNMBGL

https://github.com/facebook/react-native/issues/27565

**Comment by alew3** [comment]
> Thanks for the report, i don't think we have openssl dependency, i think the same happens if you dont use RNMBGL in the project. So it's a RN issue not RNMBGL
> 
> [facebook/react-native#27565](https://github.com/facebook/react-native/issues/27565)

Thanks, I was actually looking at that issue right now :-)
