### ISSUE TITLE
setBounds zooms to incorrect location when over antemeridian

### ISSUE THREAD

**Issue by lukemcgregor** [react-native-mapbox-gl/maps#877]
If you call setting bounds on the camera with coordinates crossing the antemeridian (eg `{   ne: [150, 20], sw: [-179, -20] }` it zooms to the map as if the bounds had west and east swapped (eg {   ne: [-179, 20], sw: [150, -20] }`. Instead it should zoom the map to the area crossing the antemeridian (line at +-180 lon).  

**To Reproduce**
use the starter instructions, and the following map code
```
          <MapboxGL.MapView style={styles.map} >
            <MapboxGL.Camera bounds={{
              ne: [150, 20],
              sw: [-179, -20],
            }}/>
            </MapboxGL.MapView>
```
this zooms here:
![Simulator Screen Shot - iPhone 11 - 2020-05-15 at 09 19 27](https://user-images.githubusercontent.com/1284608/81987156-3ca19900-968d-11ea-82c0-6e794b7e3d3a.png)

**Expected behavior**
it should zoom to a region in the pacific eg 
![Simulator Screen Shot - iPhone 11 - 2020-05-15 at 09 20 08](https://user-images.githubusercontent.com/1284608/81987212-517e2c80-968d-11ea-91b6-50af455e0b3a.png)

**Versions (please complete the following information):**
 - Platform: both
 - Device: iPhone X
 - Emulator/ Simulator: yes
 - OS: iOS 13.4.1
 - react-native-mapbox-gl Version [e.g. 7.0.9]
 - React Native Version 0.62.2

This could be a problem inside of mapbox itself, im not too sure how the camera/zooming works

**Comment by prettydev** [comment]
any updates?

**Comment by ferdicus** [comment]
Reopening this, as it's a legitimate issue

**Comment by jaysquared** [comment]
In MapboxGL it's implemented with setVisibleCoordinatesBounds. Just add 360 to the Western Longitude.

e.g. to show Japan and Mexico:
LongitudeNE: 128.43
LongitudeSW: 273.19

So you just need a React Native Wrapper for that method. I did a quick and dirty version with custom data types for my project, but have a look for some inspiration: https://github.com/jaysquared/maps/commit/0cd53f89ed8bea9288db9a084134d96e9aeaa225

To calculate out of an array of Coordinates / CoordinateBounds I use this method:
```
const generateVisibleBounds = (mixedBounds: Array<CoordinateBoundsType | CoordinateType>): ?CoordinateBoundsType => {

  const latitudes = [];
  const longitudes = [];
  mixedBounds.forEach((mixedBound) => {
    if (mixedBound.latitude && mixedBound.longitude) {
      latitudes.push(mixedBound.latitude);
      longitudes.push(mixedBound.longitude);
    } else {
      latitudes.push(mixedBound.sw.latitude);
      longitudes.push(mixedBound.sw.longitude);
      latitudes.push(mixedBound.ne.latitude);
      longitudes.push(mixedBound.ne.longitude);
    }
  });

  const latitudeNE = Math.max(...latitudes);
  const latitudeSW = Math.min(...latitudes);

  const eastLongitudes = longitudes.filter(longitude => longitude >= 0);
  const westLongitudes = longitudes.filter(longitude => longitude < 0);
  const minEastLongitude = Math.min(...eastLongitudes);
  const maxEastLongitude = Math.max(...eastLongitudes);
  const minWestLongitude = Math.min(...westLongitudes);
  const maxWestLongitude = Math.max(...westLongitudes);

  const longitudeSpreadDefault = maxEastLongitude - minWestLongitude;
  const longitudeSpreadDateline = 360 - minEastLongitude + maxWestLongitude;

  let longitudeNE;
  let longitudeSW;
  if (longitudeSpreadDateline < longitudeSpreadDefault) {
    longitudeNE = minEastLongitude;
    longitudeSW = 360 + maxWestLongitude;
  } else {
    longitudeNE = maxEastLongitude;
    longitudeSW = minWestLongitude;
  }


  if (!latitudeNE || !latitudeSW || !longitudeNE || !longitudeSW) {
    return null;
  }
  return {
    sw: {
      latitude: latitudeSW,
      longitude: longitudeSW,
    },
    ne: {
      latitude: latitudeNE,
      longitude: longitudeNE,
    },
  };
};
```
