### ISSUE TITLE
Update documentation with new v7.0.0 features

### ISSUE THREAD

**Issue by EricPKerr** [react-native-mapbox-gl/maps#88]
Couple new things in `v7.0.0` that aren't documented yet:
- https://github.com/react-native-mapbox-gl/maps/blob/master/javascript/modules/location/locationManager.js
- https://github.com/react-native-mapbox-gl/maps/blob/master/docs/UserLocation.md (examples?)
- https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Camera.md
- any others?

**Comment by tylergaw** [comment]
This isn't a new 7.x thing, but I noticed today that telemetry methods added in https://github.com/nitaliano/react-native-mapbox-gl/pull/1096 aren't documented.

There are:
- `MapboxGL.isTelemetryEnabled = () => Promise<boolean>`
- `MapboxGL.setTelemetryEnabled = (enabled: Boolean) => void`

Started to open a PR, but I wasn't sure the best place to put them since they're not on a component, but the base object.

Happy to add them in a PR if someone can point me to the best place to put 'em

**Comment by kristfal** [comment]
FYI, think isTelemetryEnabled is no longer available in the native side. I
may be wrong, so please double check.

**Comment by karlguillotte** [comment]
<Mapbox.Images images={}>

**Comment by luisfuertes** [comment]
I have an offline map downloaded. Does anyone know how I can load it? I get it with the "getPack" but it will not be added to the MapView.

const offlinePack = await MapboxGL.offlineManager.getPack(OFFLINE_ZONE_NAME)
![Captura de pantalla 2019-07-08 a las 12 18 50](https://user-images.githubusercontent.com/18212615/60803230-0943d300-a17b-11e9-890e-ff26a27bc4d8.png)

I'm sorry if this should go on stackoverflow but I do not know if the API is specific to this component.

Thanks!

**Comment by AbdullahADhaim** [comment]
> I have an offline map downloaded. Does anyone know how I can load it? I get it with the "getPack" but it will not be added to the MapView.
> 
> const offlinePack = await MapboxGL.offlineManager.getPack(OFFLINE_ZONE_NAME)
> ![Captura de pantalla 2019-07-08 a las 12 18 50](https://user-images.githubusercontent.com/18212615/60803230-0943d300-a17b-11e9-890e-ff26a27bc4d8.png)
> 
> I'm sorry if this should go on stackoverflow but I do not know if the API is specific to this component.
> 
> Thanks!

I'm also curious how to load the offline pack in the MapView, I have my pack downloaded 100% but the mapview turns black when I'm in offline mode.
PS: in the deprecated version of RNMapBox it should work automatically when you're offline but doesn't seem to work in this verison.

**Comment by luisfuertes** [comment]
Thanks for clarification @AbdullahADhaim 

we will wait for @EricPKerr  's answer

**Comment by AbdullahADhaim** [comment]
@luisfuertes 
Finally it worked for me,currently maps is automatically working in offline mode, I was using a corrupted custom styleUrl and that's why the offline map wasn't working. I used MapBox's styleUrl and it's working now.

**Comment by luisfuertes** [comment]
It worked for me removed styleUrl too. Close it please
