### ISSUE TITLE
Has MarkerView been depreciated?

### ISSUE THREAD

**Issue by BestFromAbove** [react-native-mapbox-gl/maps#882]
Has <MapboxGL.MarkerView/> been depreciated? I cannot seem to find it when calling MapboxGL. 

Also on an unrelated question, When calling MarkerView or PointAnnotation, does it create the instance locally on the users Mapbox (only viewable to the user who created it) or does it make an API call and stores it on your style to be viewed by all users using given style/token?

**Versions (please complete the following information):**
 - Platform: [e.g. Android, iOS]: both
 - react-native-mapbox-gl Version: latest
 - React Native Version [e.g. 0.59]: latest
- Using Typescript rather than JS

**Comment by mfazekas** [comment]
@BestFromAbove pls use gitter or stackoverflow for such questions. 
`MarkerView` is a recent addition and was not deprecated, they are all client only

**Comment by kamiranoff** [comment]
`MarkerView` is in the latest version. We thought it was missing too but only the types are missing.
As stated in this [issue](https://github.com/react-native-mapbox-gl/maps/issues/829)
