### ISSUE TITLE
Component unmount and mount again when using with Stack-Navigation / React Navigation

### ISSUE THREAD

**Issue by fcandi** [react-native-mapbox-gl/maps#884]
**Describe the bug**
I am using the component together with Stack-Navigation to open a Detail Screen when pressing on the Map. When I navigate to the seconds screen, the Component dismounts, mounts again and is loading all styles and sources, resetting everything.

**To Reproduce**
I tested several ways, also with a single Button on thee screen with the Map. Every Change of the screen will unmount the Map as described.

When I use nested Navigation (a Stack on the Root Leven) and I navigate to this Screen, the unmount/mount does not happen.

**Expected behavior**
Map should stay mounted and come back exactly as it was after going back from seconds screen in Stack Navigator

**Versions (please complete the following information):**
 - 
 - Emulator/ Simulator: yes
 - OS:iOS 13.3
 - react-native-mapbox-gl Version 8.1.0-beta.1
    "@react-navigation/bottom-tabs": "^5.4.7",
    "@react-navigation/native": "^5.4.2",
    "@react-navigation/stack": "^5.3.9",
 - React Native Version [e.g. 0.62.2]

**Additional context**
I am new to Native (coming from regular React JS) so I may overlook something basic in Navigation. If needed, I could create a very small sample application.

Thanks in advance, 

Andreas

**Comment by mfazekas** [comment]
@fcandi pls fill out the form - it's not clear what the issue is and how to reproduce it

**Comment by fcandi** [comment]
> @fcandi pls fill out the form - it's not clear what the issue is and how to reproduce it

Sorry, for some reason I posted the form with some keyboard stroke, now its edited. Thanks for replying sooo fast ;)
