### ISSUE TITLE
I get this when run the example project

### ISSUE THREAD

**Issue by chamilacnb** [react-native-mapbox-gl/maps#889]
![image](https://user-images.githubusercontent.com/60600065/82887276-67c99980-9f65-11ea-96c1-eded88728232.png)

**Comment by chamilacnb** [comment]
Cleaned the cache and all but didn't helped

**Comment by mfazekas** [comment]
@chamilacnb thanks for the report.

I'm trying to track down this issue as it happens in our CI env too.


```
error Unable to resolve module `react-native/Libraries/Image/AssetRegistry` from `../assets/heading.png`: react-native/Libraries/Image/AssetRegistry could not be found within the project.
```


https://travis-ci.org/github/react-native-mapbox-gl/maps/jobs/688497563

Can you share some info about your environment?! Is this android?! On what OS?! What npm version?! 
Can your run 
`npx react-native info` and post the output here?!

**Comment by chamilacnb** [comment]
Sure will update that, I have a small problem, I need to implement clustering using this package, will you be able to share some doc to start on that

**Comment by chamilacnb** [comment]
> @chamilacnb thanks for the report.
> 
> I'm trying to track down this issue as it happens in our CI env too.
> 
> ```
> error Unable to resolve module `react-native/Libraries/Image/AssetRegistry` from `../assets/heading.png`: react-native/Libraries/Image/AssetRegistry could not be found within the project.
> ```
> 
> https://travis-ci.org/github/react-native-mapbox-gl/maps/jobs/688497563
> 
> Can you share some info about your environment?! Is this android?! On what OS?! What npm version?!
> Can your run
> `npx react-native info` and post the output here?!

Its Android
No changes to the code, repo as it is,
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 304.83 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/Documents/WorkDir/OutDoor_POC_Sample_mapbox/example/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_251 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.1 => 0.62.1 
  npmGlobalPackages:
    *react-native*: Not Found
