### ISSUE TITLE
Pitch not compatible with following the user location

### ISSUE THREAD

**Issue by sullix** [react-native-mapbox-gl/maps#891]
**Describe the bug**

When I put the attributes in order to follow the user location (followUserLocation to true, and followUserMode to FollowWithCourse/FollowWithHeading)  together with a pitch (even the value `0`), the follow does not work.

**To Reproduce**

```js
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@react-native-mapbox-gl/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapboxGL.MapView
              ref={c => (this._map = c)}
              onPress={this.onPress}
              logoEnabled={false}
              attributionEnabled={false}
              pitchEnabled={true}
              compassEnabled={true}
              styleURL={styleURL}
              style={styles.map}>
              
              <MapboxGL.UserLocation
                visible={this.state.showUserLocation}
                showsUserHeadingIndicator={this.state.showsUserHeadingIndicator}
                onUpdate={this.onUserLocationUpdate}
                minDisplacement={0}
              />

              <MapboxGL.Camera
                ref={c => (this._mapCamera = c)}
                defaultSettings={{
                  zoomLevel: zoom,
                  centerCoordinate: center ? [center.lng, center.lat] : CENTER_COORD,
                }}
                pitch={this.state.isTrackingRoute ? 50 : 0}
                animationDuration={0}
                followUserLocation={this.state.followUserLocation}
                followUserMode={this.state.followUserMode}
                onUserTrackingModeChange={this.onUserTrackingModeChange}
              />
            </MapboxGL.MapView>
    );
  }
}
```

When the line `pitch={this.state.isTrackingRoute ? 50 : 0}` is commented, the "follow" is working as expected. Whereas, when it's uncommented, it's not centering on the user location.

**Expected behavior**
Centering on the user location & following it.

**Versions (please complete the following information):**
 - Platform: Android
 - Device: Samsung S5
 - Emulator/ Simulator: no (but the same on emulator)
 - OS: Android 6.1
 - react-native-mapbox-gl 8.1.0-beta.1
 - React Native Version 0.61.5

Note : I use Fake GPS to simulate my position.

**Comment by virtumonde** [comment]
The same story using a real device. Please help.

**Comment by virtumonde** [comment]
Also, the bug is active only when ```followPitch``` is used.

**Comment by gokugen** [comment]
Same behavior here, any solutions ?
