### ISSUE TITLE
Markerview is visible outside of map view

### ISSUE THREAD

**Issue by Glassig** [react-native-mapbox-gl/maps#893]
**Describe the bug**
The Markerview component renders outside of map. If the map doesn't cover the entire screen, the Markerview can still be seen when the map is moved so the dot is outside the visible map.
I have checked on a physical device, and the problem remains.

**To Reproduce**
Create a map that isn't fullscreen, and then add a Markerview component that has some styling.

_(A sidenote: I could not get your example to work, it would not install or start, so I used the basic React Native starter project instead)_

Code:
```js
import React from 'react';
import {Dimensions, StyleSheet, View} from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

MapboxGL.setAccessToken('<TOKEN>');
MapboxGL.setConnected(true);

const App = () => {
  return (
    <>
      <View style={styles.page}>
        <View style={styles.container}>
          <MapboxGL.MapView style={styles.map}>
            <MapboxGL.MarkerView coordinate={[0, 0]}>
              <View style={styles.dot} />
            </MapboxGL.MarkerView>
          </MapboxGL.MapView>
        </View>
      </View>
    </>
  );
};

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  container: {
    height: Dimensions.get('window').height - 198 - 60,
    width: Dimensions.get('window').width - 40,
    backgroundColor: 'tomato',
  },
  map: {
    flex: 1,
  },
  dot: {
    width: 25,
    height: 25,
    backgroundColor: 'red',
    borderRadius: 25,
    opacity: 0.2,
  },
});

export default App;
```

**Expected behavior**
I only want the Markerview to be visible on the map.

**Screenshots**
![marker](https://user-images.githubusercontent.com/3449804/83049483-8a35e280-a04b-11ea-9a22-ac77c424b660.PNG)
![marker2](https://user-images.githubusercontent.com/3449804/83049491-8d30d300-a04b-11ea-841e-26d07fe0b31a.PNG)

**Versions:**
 - Platform: Android
 - Device:
   - Emulator: Pixel 3 XL, API level 28
   - Physical Phone: Samsung Galaxy s9+
 - Emulator/ Simulator: both
 - OS: 
   - Emulator: Android 9
   - Physical Phone: Android 10
 - react-native-mapbox-gl Version: 8.1.0-beta.1
 - React Native Version: 0.62.2

**Additional context**
I also kind of finds that the Markerview component drags behind when quickly moving the map. Like it is not actually "stuck" to the map. I can be okay with that, just saying.

**Comment by rickklaasboer** [comment]
I'm also having these issues, did you find any workarounds or solutions?

**Comment by Glassig** [comment]
Nope. I am hoping that a dev might have some insights.

**Comment by mfazekas** [comment]
So by definition marker view is not part of the map, but on top of the map. 
We can add logic to only display a markerview if the coordinates the are attached to are within the visible map bounds. But that still means some part of marker can render outside of the map, and in some cases that might be desirable and in other cases not.

**Comment by snuuve** [comment]
Add `overflow: 'hidden'` to MapView container styles.

**Comment by Ashna-softlets** [comment]
@snuuve 's solution fixed the issue

**Comment by FashionCStar** [comment]
@snuuve 
I am using markerview, but the markers are still visible during dragging.

```
            <MapboxGL.MapView
              ref={map => { this.map = map; }}
              style={{overflow: 'hidden'}}
              styleURL={mapType}
              compassEnabled={false}
              zoomEnabled={true}
              onPress={() => { this.setState({ followUserLocation: false }) }}
            >
                    <MapboxGL.MarkerView
                      coordinate={[parseFloat(item.longitude), parseFloat(item.latitude)]}
                      anchor={{ x: 0.5, y: 0.5 }}
                    >
```
Pointannotiation doesnt visible during dragging.
How could I fix it?
