### ISSUE TITLE
Multiple ALL and/or ANY expressions in case expressions causes crash

### ISSUE THREAD

**Issue by SergueyPutilin** [react-native-mapbox-gl/maps#894]
**Describe the bug**
I am trying to make a case expressions that uses multiple all expressions in a lineLayer, but I noticed that having more than 1 "all" or "any" expression in a case expression causes my app to crash without an error.

**To Reproduce**
here is a an example of the expression
```
"lineOpacity": [
	"case",
	["all", ["boolean", ["get", "ACTIVE"], false], otherExpression], 0.5,
	["all", ["boolean", ["get", "ACTIVE"], false], otherExpression], 0.4,
	1,
],
```
**Expected behavior**
I think this expression should work, because this works in on the website equivalent of our app. It should be able to use multiple any or all expressions.

**Versions (please complete the following information):**
 - Platform: iOS,(probably android aswell)
 - Device: iPhone 11
 - Emulator/ Simulator: yes
 - OS: iOS 13.2
 - react-native-mapbox-gl Version 8.0.0
 - React Native Version 0.61.2

**Additional context**

**Comment by mfazekas** [comment]
@SergueyPutilin can you try with latest version?! `8.1.0.rc1`?!

**Comment by mfazekas** [comment]
Code to reproduce:
```es
import React from 'react';
import {
  MapView,
  ShapeSource,
  LineLayer,
  Camera,
} from '@react-native-mapbox-gl/maps';


let otherExpression =  ['boolean', ['get', 'ACTIVE'], false];
const aLine = {
  type: 'LineString',
  coordinates: [
    [-74.00597, 40.71427],
    [-74.00697, 40.71527],
  ],
};

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
        <ShapeSource id="idStreetLayer" shape={aLine}>
          <LineLayer
            id="idStreetLayer"
            style={{
              lineOpacity: [
                'case',
                ['all', ['boolean', ['get', 'ACTIVE'], false], otherExpression],
                0.5,
                ['all', ['boolean', ['get', 'ACTIVE'], false], otherExpression],
                0.4,
                1,
              ],
            }}
          />
        </ShapeSource>
      </MapView>
    );
  }
}

export default BugReportExample;

```

**Comment by mattijsf** [comment]
I actually came across this one when implemention the `Style` component. I think it is an upstream problem with the JSON expression parser.

I haven't followed up at the time. I had a workaround and forgot about it.

**Comment by mfazekas** [comment]
I've filed and upstream bug about this: https://github.com/mapbox/mapbox-gl-native-ios/issues/316

**Comment by mfazekas** [comment]
> I think it is an upstream problem with the JSON expression parser.

Yes, the iOS expressions sound a bit strange to me, first, we convert JSON expression to NSExpression compatible expression, then in the second step they convert the NSExpression to something that the native C++ mapbox layer understands - which I assume is very close to the original JSON.

**Comment by mfazekas** [comment]
I'm closing this as this we're waiting for upstream fix
