### ISSUE TITLE
SymbolLayer component image flickering/fading after coordinate change

### ISSUE THREAD

**Issue by martis347** [react-native-mapbox-gl/maps#895]
**Describe the bug**
Image in `SymbolLayer` component flickers (has a visible change in opacity) when `ShapeSource` shape prop changes into a different value.
This happens only when MapView is zoomed in. If I zoom out up to a specific level - flickering stops.
That can be seen in the attached gif.

**To Reproduce**
```js
import React, {useEffect, useState} from 'react';
import MapboxGL from '@react-native-mapbox-gl/maps';
import {point} from '@turf/turf';
import dogIcon from './dog-icon.png';

const initialCoordinate = [-73.970895, 40.723279];
const PointInMapView = () => {
  const [currentCoordinate, setCurrentCoordinate] = useState(initialCoordinate);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentCoordinate((c) => [c[0], c[1] + 0.0001]);
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  }, []);

  return (
    <MapboxGL.MapView style={{flex: 1}}>
      <MapboxGL.Camera zoomLevel={12} centerCoordinate={initialCoordinate} />
      <MapboxGL.Images images={{dogIcon}} />
      <MapboxGL.Animated.ShapeSource
        id="shapeSource"
        shape={point(currentCoordinate)}>
        <MapboxGL.Animated.SymbolLayer
          id="shapePoint"
          style={{
            iconImage: 'dogIcon',
            iconAllowOverlap: true,
            textAllowOverlap: true,
          }}
        />
      </MapboxGL.Animated.ShapeSource>
    </MapboxGL.MapView>
  );
};

export default PointInMapView;
```

**Expected behavior**
`SymbolLayer` component should move smoothly without changing it's opacity or any other noticeable flickering.

**Screenshots**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10206279/83188757-db6fd000-a138-11ea-9a09-238e0cd8c594.gif)

**Versions (please complete the following information):**
 - Platform: Android
 - Device: Huawei Mate 20
 - Emulator/ Simulator: no
 - OS: Android 10
 - react-native-mapbox-gl Version: 8.1.0-beta.1 (tried 8.0.0 and 7.2.0)
 - React Native Version: 0.62.2

**Additional context**
What I'm trying to achieve is to have multiple markers (possibly up to ~20-30) on a map that will represent users with coordinates received in real time.
To make the marker moving smooth I will need to add animation to markers, I'm currently achieving that with `lineChunk` from `@turf/turf` and `requestAnimationFrame` (did not include that in example to keep it as simple a possible)

Just in case I will also attach a link to download the APK file with provided code: https://drive.google.com/file/d/1-KpuhBxNj5Ng31W4MFY-_79swjn1xx1D/view?usp=sharing

**Comment by martis347** [comment]
Yep, this is run on my actual device, Huawei Mate 20 with android 10.

**Comment by Appkidd** [comment]
Also experiencing this on iOS.

**Comment by Avadon** [comment]
Has anyone succeed solving this problem?

**Comment by bscheideldyrt** [comment]
I'm seeing the same issue when I add new markers to the map.  The markers basically blink into existence which is really distracting.

**Comment by ghitier** [comment]
I encounter the same issue as well on both Android and iOS physical devices

**Comment by lukemcgregor** [comment]
Possibly related to https://github.com/mapbox/mapbox-gl-native/issues/16471

**Comment by Avadon** [comment]
Any solution? I'm experiencing [the same blinking](https://www.youtube.com/watch?v=Q_JJ0HC5W1A) effect even with one marker (SymbolLayer). It seems like it happens on zoom levels >14

**Comment by Appkidd** [comment]
@Avadon Sadly not sorry. We dropped Mapbox support after experiencing too many issues like this.

**Comment by ferdicus** [comment]
might be related to https://github.com/mapbox/mapbox-gl-native/issues/16473

**Comment by ankitgauravapporio** [comment]
Hello Guys, so we have no solution  from smooth animation of single marker.

**Comment by VladMatvei** [comment]
Shouldn't be closed. This is still an issue in 8.1.0

**Comment by anlai2** [comment]
Shouldn't be closed. Still an issue.

**Comment by tr3v3r** [comment]
The same here.

**Comment by krakz999** [comment]
8.2.0-beta1 still an issue

**Comment by pkumarsharma** [comment]
i am facing same issue , is their any fix for it?

**Comment by vcebotari** [comment]
same here, version: `^8.6.0-beta.0`

**Comment by saeedghasemi72** [comment]
I have also same issue in android, do you have any think?
