### ISSUE TITLE
Unable to set a worldview (to change displayed borders)

### ISSUE THREAD

**Issue by dancherb** [react-native-mapbox-gl/maps#897]
Hello - I'm struggling from the documentation to see how to set a worldview for the map. I'm using a Mapbox map from a style URL, derived from one of the basic style templates.

Ideally, I'd like to change the country boundaries and labels based on whether a user is in India or the US. As a fallback, I'd be happy to set a fixed worldview (in this case IN) - e.g. from Mapbox Studio for the style itself.

This article suggests a "setFilter" method is available, though it's not clear if/how this is exposed via the package:
https://blog.mapbox.com/dynamically-change-disputed-national-borders-14c820cae923

Thanks!

**Comment by dancherb** [comment]
> 🤔 @dancherb, this is rather a question than an issue
> please use our [gitter](https://gitter.im/react-native-mapbox-gl/Lobby) or stackoverflow for this.

Hello robot. I'll check out Gitter but I'm a bit weirded out that you can only log in via GitHub (will this also bother any organizations I'm affiliated with?) and GitLab (why does this need read/write access to my projects?)

**Comment by dancherb** [comment]
Would still appreciate some input here, can consider this post as an issue with the documentation for worldview and similar filters even if it's not re-opened.

**Comment by mfazekas** [comment]
@dancherb We have the ability to set filter for layers created in RNMBGL. So if you add those layers yourself it should work. 

https://docs.mapbox.com/help/tutorials/get-started-mapbox-boundaries/

We don't have a way to refer to existing layers at the moment AFAIK, in future that could work like this:

```
<LineLayer id="admin-0-boundary" existing filter={[...]} />
```
