### ISSUE TITLE
Black tiles when using custom styleURL

### ISSUE THREAD

**Issue by lukemcgregor** [react-native-mapbox-gl/maps#907]
**Describe the bug**
When I have a map with a custom style url and some dynamically updating content I get black tiles on some android devices (including the sim).

![ezgif-6-dfb828a5ce3e](https://user-images.githubusercontent.com/1284608/83993543-d36d2700-a9a7-11ea-8c09-9475be27f844.gif)

**To Reproduce**
Ive put together a repro case to play with here https://github.com/lukemcgregor/mapbox-sdf-style

This loads a style with a simple sprite sdf image, and then rotates and switches its colour. It works nicely on iOS but on android it renders black tiles in the sim. On some devices it renders fine, others have the same black tiles on the sim.

It seems to only happen when using both a styleJSON and a symbol layer. It also only happens when the symbol layer is getting updated frequently (if you remove the two timers it no longer happens)

to run it 

- `yarn`
- `node server.js`
- `yarn android`

basic component:

```
function getRandomColor() {
    var letters = '0123456789ABCDEF';
    var color = '#';
    for (var i = 0; i < 6; i++) {
      color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
  }
const features = featureCollection([point([-10,-10])]);

const App = () => {
    const [rotation, setRotation] = useState(0);
    const [color, setColor] = useState('#fff');

  useEffect(()=>{
    setInterval(()=>{
      setRotation(r =>  (r + 1) % 360);
    }, 10);
    setInterval(()=>{
        setColor(getRandomColor())
    }, 1000)
  }, []);

    return (
      <View style={styles.page}>
        <View style={styles.container}>
          <MapboxGL.MapView style={styles.map} styleURL="http://localhost:3333/style.json" >
          <MapboxGL.Camera
            centerCoordinate={[0,0]}
            />
            <MapboxGL.ShapeSource id="icons" shape={features}>
              <MapboxGL.SymbolLayer
                id="clusters-layer"
                style={{
                  iconImage: "unknown",
                  iconColor: color,
                  iconRotate:rotation,
                }}
              />
            </MapboxGL.ShapeSource>
          </MapboxGL.MapView>
        </View>
      </View>
    );
  }
```
StyleURL contents: 

```
{
    "version":8,
    "glyphs":"mapbox://fonts/mapbox/{fontstack}/{range}.pbf",
    "sprite": "http://localhost:3333/sprite",
    "sources":{
      "tile-source":{
        "type": "raster",
        "url": "mapbox://mapbox.satellite",
        "tileSize": 256
      }
    },
    "layers":[
      {
        "id":"base-tiles",
        "type":"raster",
        "source":"tile-source"
      }
    ]
  }
```

**Versions :**
 - Platform: Android
 - Device: pixel 2
 - Emulator/ Simulator: yes
 - OS: pie
 - react-native-mapbox-gl Version 8.1.0-beta.1
 - React Native Version 0.62.2

**Comment by mfazekas** [comment]
Based on gitter my undestranding is that https://github.com/mapbox/mapbox-gl-native/issues/14604 fixes the issue
