### ISSUE TITLE
SymbolLayer fading out when zooming out of map

### ISSUE THREAD

**Issue by Appkidd** [react-native-mapbox-gl/maps#910]
**Describe the bug**
SymbolLayer is flickering/fading when zooming out (in sync with text labels on the map).

**To Reproduce**
Zoom out of the map. 

```js
const iconStyles =  {
  icon: {
    iconImage: ['get', 'icon'],
    iconSize: 1,
    iconAllowOverlap: true,
  }
};

return (
  <MapboxGL.MapView
    scrollEnabled={!this.initialFit}
    ref={(ref) => { this.map = ref; }}
    style={styles.flex}
    logoEnabled={false}
    contentInset={[16, 16, 200, 16]}
    onRegionDidChange={(region) => this.setState({ region })}
  >
    <MapboxGL.UserLocation onUpdate={(e) => this.setState({ userLocation: e ? e.coords : null })} />
    <MapboxGL.Images images={images} />
    <MapboxGL.ShapeSource
      id="buses"
      shape={vehiclesGeo}
    >
      <MapboxGL.SymbolLayer id="bus" iconImage="marker" style={mappyStyles.icon} />
    </MapboxGL.ShapeSource>
    <MapboxGL.Camera minZoomLevel={2} maxZoomLevel={18} />
  </MapboxGL.MapView>
);
```

**Expected behavior**
The SymbolLayer should not be flickering.

**Screenshots**
![Demo gif](https://i.stack.imgur.com/BJcD4.gif)

**Versions (please complete the following information):**
 - Platform: iOS
 - Device: iPhone 8
 - Emulator/ Simulator: No
 - OS: iOS 13.4.1
 - react-native-mapbox-gl Version 8.0.0
 - React Native Version 0.62.2

**Comment by Appkidd** [comment]
Downgrading SDK to mapbox-gl-native-ios@5.8.0 fixes the issue.

**Comment by karimb1** [comment]
I confirm this issue is still present in Mapbox-iOS-SDK (5.9.0)

**Comment by ferdicus** [comment]
Please make sure to update to the latest iOS/ Android SDKs - this is an upstream issue and was fixed in later versions

**Comment by krakz999** [comment]
Still an issue with 8.2.0-beta1

**Comment by ferdicus** [comment]
> This happens to me as well on the latest android version. I can post a video/code if need be?

yes, please post a short gif plus your apps specs - thanks

**Comment by ferdicus** [comment]
> @ferdicus that was what i was afraid of. Thanks for clarifying :)

If it makes you feel any better, I feel like this is more straight forward than the iOS part 😅
