### ISSUE TITLE
UserLocation stops update when an other UserLocation is unmounted

### ISSUE THREAD

**Issue by AlphaGolf33** [react-native-mapbox-gl/maps#915]
**Describe the bug**
When an `UserLocation` is unmounted, the others `UserLocation` stop updating

**To Reproduce**
Create two components like
```javascript
export const MyMap = () => (
    <MapboxGL.MapView>
        <MapboxGL.UserLocation />
    </MapboxGL.MapView>
);
```
When one component is unmonted, the user location icon stop moving on the other component.

**Expected behavior**
The user location icon should keep follow user position.

**Versions**
 - Platform: Android + iOS
 - Device: Samsung Galaxy Note 4 + iPhone 7
 - Emulator/ Simulator: no
 - OS: Android 6.0.1 + iOS 13.4.1
 - react-native-mapbox-gl Version: 8.1.0-beta.1
 - React Native Version: 0.62.2

**Details**
This is caused by https://github.com/react-native-mapbox-gl/maps/pull/689 as it stops the `locationManager` shared by all `UserLocation` instances:
https://github.com/react-native-mapbox-gl/maps/blob/cd9ab4c7a63f851e49c8fa5238da63a4cc4ca773/javascript/components/UserLocation.js#L161-L165
https://github.com/react-native-mapbox-gl/maps/blob/cd9ab4c7a63f851e49c8fa5238da63a4cc4ca773/javascript/components/UserLocation.js#L177-L189
And because each `UserLocation` keep a local a state of `locationManager` state (`this.locationManagerRunning`) it is not possible to manually restart the `locationManager` by using a ref on `UserLocation` with `setLocationManager()` because of:
https://github.com/react-native-mapbox-gl/maps/blob/cd9ab4c7a63f851e49c8fa5238da63a4cc4ca773/javascript/components/UserLocation.js#L178
Beacuse the instances of `UserLocation` dont know that the `locationManager` is stopped (`this.locationManagerRunning` is `true`).

`UserLocation` should only add/remove its listener on `locationManager` and **never** start of stop it. It the responsablity to the `locationManager` to start or stop itself depending on the number of listeners registered

**Comment by mfazekas** [comment]
@AlphaGolf33 thanks for the bugreport. 

Yeah I guess on solution would be to make start and stop could be reference counted in `LocationManager`

The other is to add an auto/start stop default to `LocationManager` where it's started if there is listeners and it's stopped if there are no listeners any more.

**Comment by soumyashisPR** [comment]
Hi @mfazekas Is anyone already working on this bug? Can I take this up?

**Comment by mfazekas** [comment]
@soumyashisPR It would be great if you could look, i'm not aware of anyone working on it.

**Comment by soumyashisPR** [comment]
@mfazekas Sure, looking into this. 
Thanks.

**Comment by ferdicus** [comment]
@rdgomt, there are some changes requested for the PR and @soumyashisPR hasn't replied yet. 
So unfortunately we have to wait, or someone else jumps in.

**Comment by soumyashisPR** [comment]
Hey @ferdicus, Apologies for the delay. Have addressed PR comments, please have a look.
https://github.com/react-native-mapbox-gl/maps/pull/999
