### ISSUE TITLE
Polygon is not draggable 

### ISSUE THREAD

**Issue by mahipalsingh7** [react-native-mapbox-gl/maps#916]
I drawn a polygon using **MapboxGL.ShapeSource** and added **MapboxGLView.PointAnnotation** on every point to make points draggable. 

But i'm facing issues  

1. When i finish the draw of Polygon , i'm not able to move or drag the complete polygon
2. Points of Polygon are draggable in iOS but not working in Android (only first point is draggable rest are not working)

can anyone please help me how can i make polygon draggable

**Comment by mfazekas** [comment]
Unlike annotations ShapeSoruce is not draggable. I guess one could implement dragging manually but it's not supported out of the box
