### ISSUE TITLE
[Discussion] Typescript

### ISSUE THREAD

**Issue by mfazekas** [react-native-mapbox-gl/maps#921]
1. Should we adopt typescript in the library? (pros/cons)
2. What would be a good way to implement typescript?

**Comment by mfazekas** [comment]
1.) I'm personally in favor of TS. The current `index.d.ts` separation is annoying.

Not sure about implementation. I guess the build process would change as we should transpile to plain js. I assume sourcemaps, etc tooling works fine.

2.) On the transition from js to typescript:  I prefer a gradual approach where we change a single or a few components to TS, then we convert all the components over time.

**Comment by ferdicus** [comment]
I used TS a bit, this is a hug topic though 😅 

Some questions: 
* Would it be all transpiled to one singular js file? Or Transpile the plain JS files next to the TS files?
* Would we be able to simply use the `index.d.ts` within our TS files for types declarations in the beginning or is that a no go?

**Comment by RichardLindhout** [comment]
I think it's a good idea. I agree with @mfazekas about the gradual approach. For some people this will make PR's harder but I feel like a lot of people are moving to Typescript lately.

**Comment by ClayC-WeatherBug** [comment]
We are currently in the process of converting from JS to TS at my company and are taking the gradual approach. I've taken this approach before at previous companies with a lot of success. It'd be great to see us move towards using typescript in this repo.

> Would it be all transpiled to one singular js file? Or Transpile the plain JS files next to the TS files?
I assume you mean the transpilation/build output? If that is the case, then yes it transpiles everything down into a single distributable. If you want you can extract the type definitions into their own package which is fairly common practice for libraries like this where people would add something like a `@types/react-native-mapbox-gl` package to get the types.

>Would we be able to simply use the index.d.ts within our TS files for types declarations in the beginning or is that a no go?
I don't think that there would be any issue with doing this. It would probably make sense to slowly migrate them into their own files in a `types` folder, but for the short term it'd probably be fine to use them as is.

One thing in particular that would be great if this project starts using typescript would be hooking in the typescript checks into circle CI or something similar. That way when PRs come in they get blocked if the typescript isn't valid.

**Comment by ferdicus** [comment]
go away, we're actively working on this now! See ##1067 you knob!
