### ISSUE TITLE
'MGLCustomHeaders.h' file not found

### ISSUE THREAD

**Issue by ansarikhurshid786** [react-native-mapbox-gl/maps#922]
I am trying add custom header. In android working fine and for ios i tried following docs 
https://github.com/react-native-mapbox-gl/maps/blob/master/docs/CustomHttpHeaders.md

Getting error : 'MGLCustomHeaders.h' file not found

AppDelegate.m: 
```
#import "MGLCustomHeaders.h"

// (2) Init headers, add swizzle method
  [[MGLCustomHeaders sharedInstance] initHeaders];
  // (3*) Optionally you can add some global headers here
  [[MGLCustomHeaders sharedInstance] addHeader:@"IP" forHeaderName:@"X-For-Real"];
```

React native: 0.59.10
"@react-native-mapbox-gl/maps": "^7.0.8"

**Comment by ansarikhurshid786** [comment]
@mfazekas please check my error.

**Comment by mfazekas** [comment]
@ansarikhurshid786 sound like an XCode project config issue, you need to add the folder containing `MGLCustomHeaders.h` to xcode header search path.

**Comment by ansarikhurshid786** [comment]
Thanks you reply. i have added following in Framework Search Paths
`$(PROJECT_DIR)/../node_modules/@react-native-mapbox-gl/maps/ios`

As per documentation. Mapbox library working perfectly

**Comment by ansarikhurshid786** [comment]
I just also tried following : 
`$(SRCROOT)/../node_modules/@react-native-mapbox-gl/maps/ios`

In Building setting - header search path

but still getting same issue. can yo please tell if i am wrong anywhere

**Comment by ansarikhurshid786** [comment]
i will try to add that folder which MGLCustomHeaders.h file and let you know.

**Comment by ansarikhurshid786** [comment]
Thanks for suggestion it's 
i have added following : 
$(SRCROOT)/../node_modules/@react-native-mapbox-gl/maps/ios/RCTMGL
