### ISSUE TITLE
App can not be launched

### ISSUE THREAD

**Issue by PentamapRainer** [react-native-mapbox-gl/maps#923]
**Describe the bug**
Error when running the App: "Native part of Mapbox React Native libraries were not registered properly, double check our native installation guides."

**To Reproduce**
```sh
react-native init AnimalProtect 
cd AnimalProtect
npm install react-native-mapbox-gl/maps --save
react-native run-ios
```

Example-Code:
```
import React, { Component } from "react";
import { StyleSheet, View } from "react-native";
import MapboxGL from "@react-native-mapbox-gl/maps";

MapboxGL.setAccessToken("my-key");

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5FCFF"
  },
  container: {
    height: 300,
    width: 300,
    backgroundColor: "tomato"
  },
  map: {
    flex: 1
  }
});

export default class App extends Component {
  componentDidMount() {
    MapboxGL.setTelemetryEnabled(false);
  }

  render() {
    return (
      <View style={styles.page}>
        <View style={styles.container}>
          <MapboxGL.MapView style={styles.map} />
        </View>
      </View>
    );
  }
}
```
**Expected behavior**
That the App does not crash

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2020-06-18 at 14 02 06](https://user-images.githubusercontent.com/6825724/85018067-d8329780-b16c-11ea-9870-dacef64c6798.png)

**Versions (please complete the following information):**
 - Platform:iOS
 - Device: iPhone 11
 - Emulator/ Simulator: yes
 - OS: 13.5
 - react-native-mapbox-gl Version: master
 - React Native Version 0.62.2

**Comment by mfazekas** [comment]
@PentamapRainer have you checked the native/iOS install guides?!

**Comment by AKACC** [comment]
My comment on another issue for the similar problem: https://github.com/react-native-mapbox-gl/maps/issues/807#issuecomment-786795180
