### ISSUE TITLE
Typescript Camera

### ISSUE THREAD

**Issue by matheus-gio** [react-native-mapbox-gl/maps#925]
I'm having problems with camera methods using typescript
`

      <MapboxGL.MapView
        ref={mapViewRef}
        styleURL={MapboxGL.StyleURL.Dark}
        style={{ flex: 1 }}
        attributionEnabled={false}
      >

        <MapboxGL.Camera ref={mapCameraRef} animationDuration={2000} followUserLocation={true} />

        <MapboxGL.UserLocation />

      </MapboxGL.MapView>
`
MapView methods work, but Camera does not.

mapCameraRef.current?.zoomTo(20, 100) (Not working)
mapViewRef.current?.getZoom() (Working)

Finally, test to create a javascript component with a MapView and a camera and the methods worked perfectly.

**Comment by mfazekas** [comment]
@matheus-gio pls post a full standalone example component and pls detail what's not working means - throws and error, raises an exception, etc..

Will reopen on input

**Comment by matheus-gio** [comment]
Sorry, my fault, I'll post the component in typescript :

```

const MapScreen = (props: Props) => {

  useEffect(() => {
    props.SetValidationNavigator(props.navigation)
    requestLocationPermission()
  }, [])

  const mapViewRef = useRef<MapboxGL.MapView>(null)
  const mapCameraRef = useRef<MapboxGL.Camera>(null)

  return (
    <View style={{ flex: 1 }}>
      <MapboxGL.MapView
        ref={mapViewRef}
        styleURL={MapboxGL.StyleURL.Dark}
        style={{ flex: 1 }}
        attributionEnabled={false}
      >
        <MapboxGL.Camera ref={mapCameraRef} animationDuration={2000} followUserLocation={true} />
        <MapboxGL.UserLocation />
      </MapboxGL.MapView>
      <TouchableOpacity
        style={styles(props.theme).CurrentLocation}

        onPress={async () => {
                console.log(await mapViewRef.current?.showAttribution()) // working
                await mapCameraRef.current?.zoomTo(20, 100) // not working
        }}
      >
        <IconMaterial size={SizeNormalizer(40)} color={Color(Colors.WHITE, props.theme)} name={'location-searching'} />
      </TouchableOpacity>
    </View>
  )
}
```

The MapView method works perfectly, but all Camera methods do not work.

**Comment by cladjidane** [comment]
Hi  @matheus-gio , I see the same thing, have you solved the problem since? Thank you!

**Comment by ferdicus** [comment]
The problem here being, that you use `followUserLocation` which will prevent most camera methods. 
Try using the ref methods with the Camera like this:
```
<MapboxGL.Camera ref={mapCameraRef} />
```

should work

**Comment by cladjidane** [comment]
@ferdicus indeed! Removing the followUserLocation property works great! Thanks :)
