### ISSUE TITLE
MarkerView in android not showing methods

### ISSUE THREAD

**Issue by mahipalsingh7** [react-native-mapbox-gl/maps#926]
Following methods are not available for  **MarkerView** in android but doc specifying **full**
https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Annotations.md

can some help me how can i use **onSelected** & **onDragEnd** in  **MarkerView**

*/
    onSelected: PropTypes.func,

    /**
     * This callback is fired once this annotation is deselected.
     */
    onDeselected: PropTypes.func,

    /**
     * This callback is fired once this annotation has started being dragged.
     */
    onDragStart: PropTypes.func,

    /**
     * This callback is fired once this annotation has stopped being dragged.
     */
    onDragEnd: PropTypes.func,
  };

**Comment by mfazekas** [comment]
@mahipalsingh7 MarkerView supports full interactivity in the sense that inside marker view you can place any RN VIew, which can be interacted with. We don't implement drag, selection for marker views. I guess you might be implement those in RN methods.
