### ISSUE TITLE
SetAccessToken does not change dynamically

### ISSUE THREAD

**Issue by fabriciomirandabr** [react-native-mapbox-gl/maps#933]
I have to tokens for different map types, when I use

MapboxGL.setAccessToken(MAXAR_TOKEN)

and try to update token in another map

MapboxGL.setAccessToken(MAPBOX_TOKEN)

the token of the map does not change.

---------

Versions:
 - Platform: Android, iOS
 - Device: Iphone 11, Samsung S10
 - Emulator/ Device: yes|yes
 - OS: IOS 13.1 | Android Pie API 28
 - react-native-mapbox-gl Version 8.0.0
 - React Native Version:

**Comment by mfazekas** [comment]
Are you sure it's not working on iOS?!

https://github.com/mapbox/mapbox-gl-native/blob/macos-v0.5.0/platform/darwin/src/MGLAccountManager.m#L62-L76

On android i can see the issue, but ios should work as is IMO.

**Comment by ferdicus** [comment]
@fabriciomirandabr, please add a comment when closing issues.
Others might have similar issues and it could help them. 

Thanks

**Comment by fabriciomirandabr** [comment]
The token doesn't change for me, I created a custom styleUrl with authorization in Tile URL.

After that, was possible to have different maps with distinct authorization
