### ISSUE TITLE
Examples are confusing

### ISSUE THREAD

**Issue by abdi4** [react-native-mapbox-gl/maps#935]
There's no documentation of how the examples work. Some of the code makes no sense without some context which they are lacking.
`const styles = {
  circles: {
    circleRadius: [
      'interpolate',
      ['exponential', 1.5],
      ['zoom'],
      12,
      2,
      22,
      180,
    ],`
This is an example. An array of values with no explanation to what they are?
Also there's data coming from mapbox://examples.8fgz4egr but no sample of what that data looks like? How do we effectively use this?

**Comment by ferdicus** [comment]
The examples are ... under construction :) 
We're happy for any contributions. 

At the moment they are in a state between coding example and visual example of the features (put on a phone an play around with it). 

Maybe I can shed some light on the array that you mentioned above:
Those are called `expressions` and are explained in the Changelog for release 7: https://github.com/react-native-mapbox-gl/maps/blob/master/CHANGELOG.md#700

https://github.com/react-native-mapbox-gl/maps/blob/master/docs/StyleSheet.md goes a bit deeper into detail


Hope this helps a bit :)
