### ISSUE TITLE
Map is not loading in Release build (Android )

### ISSUE THREAD

**Issue by mdNazmulHasan** [react-native-mapbox-gl/maps#938]
Describe the bug
Hi all, In my case Map is not displaying in release APK(Marker is showing properly). However debug build is ok.

I also have tested creating different token.

Example:

```
import React, {Component} from 'react';
import Mapbox, {MapView, Camera} from '@react-native-mapbox-gl/maps';
import {Dimensions, Alert, View, Image, Platform} from 'react-native';
const appConfig = require('../../../app.json');
Mapbox.setAccessToken(appConfig.mapboxAccessToken);

const {height, width} = Dimensions.get('window');
const styleURL='https://tilesv3.dingi.live/styles/TeamWork-English/style.json'

class Map extends Component {
  constructor(props) {
    super(props);
    this.state = {
      basicSetup: {
        showUserLocation: true,
        centerCoordinate: [],
        zoomLevel: 12,
        maxZoomLevel: 19,
        compassEnabled: true,
        logoEnabled: false,
        attributionEnabled: false,
      },
      disable: {
        zoomEnabled: false,
        scrollEnabled: false,
        pitchEnabled: false,
        rotateEnabled: false,
      },
    };
  }
  render() {

    return (
      <View style={[styles.map, style]}>
        <MapView
          styleURL={styleURL}
          style={{flex: 1}}
          ref={(ref) => {
            this.control = ref;
          }}>
          <Camera ref={(c) => (this.camera = c)} zoomLevel={14} />
          {children}
        </MapView>

        {hideLogo ? null : (
          <View style={[styles.logo, logoStyle]}>
            <Image
              resizeMode={'contain'}
              source={require('../../../resources/images/map_logo.png')}
              style={{flex: 1}}
            />
          </View>
        )}
      </View>
    );
  }
}

export default Map;

const styles = {
  map: {
    width,
    height,
  },
  logo: {
    position: 'absolute',
    bottom: Platform.OS == 'ios' ? 20 : 40,
    left: 20,
    shadowColor: '#37474f',
    shadowOpacity: 0.24,
    shadowOffset: {height: 2, width: 0},
    elevation: 3,
    shadowRadius: 3,
  },
  circle: {
    position: 'absolute',
    borderWidth: 1,
    borderColor: '#111',
    backgroundColor: '#03111111',
    justifyContent: 'center',
    alignItems: 'center',
  },
  circleCenter: {
    height: 4,
    width: 4,
    borderRadius: 4,
    backgroundColor: '#a1a5d1',
  },
  radiusText: {
    fontSize: 13.47,
    color: '#a1a5d1',
  },
};
```

Expected behavior
It should display map even though it is in release mode

Screenshots
======= Debug mode =======
![Screenshot_1593317565](https://user-images.githubusercontent.com/10530631/85937751-5b4fac80-b928-11ea-8a4f-da39e4ae5d73.png)

======= Release Mode =======
![Screenshot_20200628-101310](https://user-images.githubusercontent.com/10530631/85937769-83d7a680-b928-11ea-996e-e52e8468b46b.jpg)

Versions :

Platform: [Android]
Device: [One Plus 7T]
Emulator/ Simulator: [no]
OS: [Android 9]
react-native-mapbox-gl Version [8.1.0-rc.1]
React Native Version [0.62.2]

**Comment by mfazekas** [comment]
Thanks for the bugreport. Pls edit the example so that it contains all info (no accesstoken is neccesary), but styleurl is needed.

Have you checked logcat to see if there is any error/issue?!

**Comment by mdNazmulHasan** [comment]
updated the report with style url, @mfazekas , following error might be the cause behind it
<img width="1239" alt="Screenshot 2020-06-28 at 5 36 49 PM" src="https://user-images.githubusercontent.com/10530631/85946430-0cc10300-b966-11ea-9d12-b57cddd86f5d.png">

**Comment by mdNazmulHasan** [comment]
Issue was resolved. It seems the issue was not in mapbox. Android was blocking custom style url, that's why the map was not loading. Just had to add some network rule for that.

**Comment by leeprobert** [comment]
@mdNazmulHasan - how were you unblocking the style URL schema?
