### ISSUE TITLE
Release 8.x crashes on Android 4

### ISSUE THREAD

**Issue by tinmar33** [react-native-mapbox-gl/maps#950]
The release 8.x doesn't support Android 4. The app is crashing immediately.
It's working fine with the 7.0.8 version (i dont have tried with the 7.2.0)

Here's the logcat error: 

```
E/AndroidRuntime( 1471): FATAL EXCEPTION: main
E/AndroidRuntime( 1471): Process: com.test.test, PID: 1471
E/AndroidRuntime( 1471): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.test/com.test.test.MainActivity}: java.lang.RuntimeException: Requested enabled DevSupportManager, but DevSupportManagerImpl class was not found or could not be created
```

**To Reproduce**
Install the 8.x release on a react native app.
Run it with Android 4.x

**Expected behavior**
Running normally

**Versions (please complete the following information):**
 - Platform: Android 4
 - Device: Samsung Galaxy S3
 - Emulator/ Simulator: Both
 - OS: Android 4.4
 - react-native-mapbox-gl Version 8.1.0 rc2
 - React Native Version 0.61.2

**Comment by ferdicus** [comment]
Googling this issue results in this issue ticket for react-native:
https://github.com/facebook/react-native/issues/9043

Can you please try the mentioned solutions and report back? 
Thanks

**Comment by tinmar33** [comment]
@ferdicus I tried all the solution and it still doesn't works on Android 4

**Comment by ferdicus** [comment]
Hey @tinmar33, I'm sorry to hear that... to be quite frank, I don't think we're going to invest any dev time in looking into this though :S

We're talking after all about an android version, that is at best 7 years old.

If you manage to find a repro case, that works for newer version of Android feel free to update this issue. 
Also, feel free to contribute if you feel strongly about supporting Android 4.

**Comment by mfazekas** [comment]
I agree sorry we'll not be working on this. We're happy to accept PR addressing the issue!
