### ISSUE TITLE
MapBox Directions for React Native 

### ISSUE THREAD

**Issue by kunchalakiran** [react-native-mapbox-gl/maps#959]
We have been trying to use Mapbox directions , but we don't find answers from the last few days can any one help us with the MapBox directions?
Does it supports sea maps ?

**Comment by ferdicus** [comment]
Directions are outside the scope of this repo.
This is an open-source repo maintained by volunteer devs - it has no support from mapbox.
It provides a JS layer around the iOS and Android SDKs for Mapbox.

Having said that, this ticket talks about getting directions:
https://github.com/react-native-mapbox-gl/maps/issues/565


For future questions please use our gitter channel or stackoverflow
Tickets in the repo are for bugs/ issues.
