### ISSUE TITLE
[FEATURE] On POI click

### ISSUE THREAD

**Issue by hannojg** [react-native-mapbox-gl/maps#968]
Hello,

is there a feature like "on POI click"? react-native-maps offer this (Google Maps SDK) and it would be nice to have such functionality also here. Maybe there is already a functionality like this or a very similar one that could be used, and I would be so thankful if you could point them out.
I am aware that there is a `onPress` callback, but using this, we would need to request on every press whether there is a POI/Venue or not (which would be bad for UX). A detection that says "yes, the user has clicked at a POI at this location" would be very beneficial.

Thank you in advance.

https://github.com/react-native-community/react-native-maps/blob/master/docs/mapview.md#events

**Comment by WoodburyShortridge** [comment]
@hannojg see https://github.com/react-native-mapbox-gl/maps/discussions/1502
