### ISSUE TITLE
TypeError: null is not an object (evaluating 'arr[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]')

### ISSUE THREAD

**Issue by mustafaskyer** [react-native-mapbox-gl/maps#970]
**Describe the bug**
opening Camera lead to this error if location not granted yet, although coords exist
```js
TypeError: null is not an object (evaluating 'arr[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]')
```

**To Reproduce**
Steps to reproduce the behaviour. 

Example:
```js
<MapboxGL.MapView
	   styleURL={MapboxGL.StyleURL.Street}
	   style={styles.container}
	   onRegionIsChanging={onRegionIsChanging}
	   onRegionDidChange={onRegionDidChange}
	   onDidFailLoadingMap={onFail}
	   logoEnabled={false}
	   compassEnabled={false}
	>
		<MapboxGL.Camera
		followZoomLevel={17}
		zoomLevel={15}
		animationMode={'flyTo'}
		animationDuration={1000}
		centerCoordinate={[1,-1]}
		/>
</MapboxGL.MapView>
```

**Expected behaviour**
Expect it works as normal

**Screenshots**
![Simulator Screen Shot - iPhone Xs Max - 2020-07-26 at 10 32 14](https://user-images.githubusercontent.com/15132084/88473969-4a945580-cf2b-11ea-9edb-2c1d88fccceb.png)

**Versions**
 - Platform: iOS
 - Device: **iPhone XS Max 12.0**
 - Emulator/ Simulator: **Both**
 - OS: **Mac OS Catalina**
 - react-native-mapbox-gl Version: **^7.0.0-rc3**
 - React Native Version: **^0.59.10***

**Comment by mfazekas** [comment]
>     * react-native-mapbox-gl Version: **^7.0.0-rc3**


@mustafaskyer pls test and report on current version

**Comment by mustafaskyer** [comment]
same issue in @react-native-mapbox-gl/maps ^7.0.0-rc3
