### ISSUE TITLE
build(app): increase android min version to 6  

### ISSUE THREAD

**Issue by ferdicus** [react-native-mapbox-gl/maps#976]
Consider bumping up the minimum supported android version to 6 (API Level 23).

@mfazekas, what do you think?
I don't think that too many people are using older versions.

**Comment by mfazekas** [comment]
@ferdicus I'd say not to block android versions in gradle files. We can put to readme, that we don't support versions below x.

**Comment by ferdicus** [comment]
Added a note to our README, closing this ticket
