### ISSUE TITLE
Feature Request: Support Style JSON for <MapView />

### ISSUE THREAD

**Issue by gmaclennan** [react-native-mapbox-gl/maps#984]
Currently the <MapView /> component accepts a `styleURL` prop and will load the style from the given URL.

For our use-case we are using a custom Style JSON which we are managing in the app. Whilst it is possible to [pass an `asset://` URL](https://docs.mapbox.com/android/api/map-sdk/9.3.0/com/mapbox/mapboxsdk/maps/Style.Builder.html#fromUrl-java.lang.String-) to the `styleURL` prop in Android, it would be more convenient to be able to pass an object as a `styleObject` prop that would be set on the map using [`Style.Builder.fromJson()`](https://docs.mapbox.com/android/api/map-sdk/9.3.0/com/mapbox/mapboxsdk/maps/Style.Builder.html#fromJson-java.lang.String-).

**Comment by ferdicus** [comment]
hey @gmaclennan, totally agree - would you be willing to open a PR for this?

**Comment by mattijsf** [comment]
https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/StyleJson.js

I already did some work for this. But this needs some base map to work. With some extra effort we might get it to work the way you intended. 

It would be best if we would have a way to convert json to a style object natively though. The way I implemented it is not ideal. Suggestions are very welcome to improve this 👍

**Comment by ferdicus** [comment]
Looks great @mattijsf, shame on me for not spotting this in the `example/`...
Yeah, as you said the argument against this is really having to have a working base map :(

In the previous replies we're just talking about the android api, do you know from the top of your head, 
if there is a build in solution for iOS like there is with the android SDK ([Style.Builder.fromJson()](https://docs.mapbox.com/android/api/map-sdk/9.3.0/com/mapbox/mapboxsdk/maps/Style.Builder.html#fromJson-java.lang.String-))?

**Comment by mattijsf** [comment]
Setting the map style based on a JSON string or object is not supported on iOS unfortunately. The flutter-mapbox-gl also faced this API difference: 35effcd88e8c305d94776dc49c7b1fab0f18b3769fb186976a694403f2978e41R567

I haven't tested this by maybe you can prepare a local asset with an empty style such as:
```
{
    "version": 8,
    "sources": {},
    "layers": [],
}
```

And then you can add layers / sources using https://github.com/react-native-mapbox-gl/maps/blob/master/docs/Style.md

Note that since the base map is now empty you won't be able to reference sprites or glyphs from the added layers. If you want that you'll need to prepare the base style with a reference to them.

**Comment by ferdicus** [comment]
ah, that's a bummer, I don't really like single OS features :( 

But maybe it's a good way to get the foot in the door and make 50% of devs happy instead of none? 🤷

**Comment by ferdicus** [comment]
also, there is a flutter version?! nice 👍

**Comment by mattijsf** [comment]
https://docs.mapbox.com/ios/maps/api/6.2.1/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(im)initWithFrame:styleURL:
> The URL may be a full HTTP or HTTPS URL, a Mapbox style URL (mapbox://styles/{user}/{style}), or a path to a local file relative to the application’s resource path.

We could apply a trick on iOS to write custom JSON data to a temporary location and take the appropriate measures to cleanup these files afterwards.

**Comment by ferdicus** [comment]
@gmaclennan, I've opened a [PR for this on Android](https://github.com/react-native-mapbox-gl/maps/pull/1102) - feel free to take it for a test ride

**Comment by ferdicus** [comment]
merged
