### ISSUE TITLE
CircleLayer does not respect circleTranslateAnchor setting

### ISSUE THREAD

**Issue by naftalibeder** [react-native-mapbox-gl/maps#988]
**Describe the bug**
A `CircleLayer` that has a `circleTranslate` offset value and a `circleTranslateAnchor` value of `viewport` still sees the offset behave as though `circleTranslateAnchor` was set to `map` - that is, as the map pitch is changed, the circle's vertical offset changes with it.

**To Reproduce**
1. Clone [this repo](https://github.com/TruckMap/mapbox-pitch-bug-example).
2. Set a valid access token in `index.js`.
3. In `./ios`, run `pod install`.
4. Open the project in xcode and run.

**Expected behavior**
The smaller circle and the text, both of which are offset from the center by the same amount, should remain equally offset no matter how the map pitch is changed.

**Screenshots**
https://github.com/TruckMap/mapbox-pitch-bug-example/blob/master/screenshots/pitch.gif

**Versions (please complete the following information):**
 - Platform: iOS/Android
 - Device: multiple
 - Emulator/ Simulator: simulator and device
 - OS: multiple
 - react-native-mapbox-gl `7.0.8` and `8.1.0-rc.2`
 - React Native Version `0.63.2` and multiple earlier versions

**Comment by ferdicus** [comment]
Does the same happen for Android?
Just curious.

**Comment by naftalibeder** [comment]
Good question - yes, the same thing happens on Android.

**Comment by ferdicus** [comment]
dumb questions, did you try without expression?!

**Comment by ferdicus** [comment]
when checking this repos source, there isn't much that we actively do, it seems more, that we're just passing them through.
Android side:
https://github.com/react-native-mapbox-gl/maps/blob/ec0c63e1d46f2f152f0d9f8eb6242ce47fda5e8a/android/rctmgl/src/main/java/com/mapbox/rctmgl/components/styles/RCTMGLStyleFactory.java#L1693-L1699

https://github.com/react-native-mapbox-gl/maps/blob/ec0c63e1d46f2f152f0d9f8eb6242ce47fda5e8a/android/rctmgl/src/main/java/com/mapbox/rctmgl/modules/RCTMGLModule.java#L142-L144

But then again, what do I know 🤷

**Comment by naftalibeder** [comment]
Sorry, I'm not sure what that means?

**Comment by ferdicus** [comment]
> Sorry, I'm not sure what that means?

Sorry, I was just thinking loud, asking myself if this is maybe an issue upstream and me being unsure about it, because I'm not deep into the native parts...

**Comment by naftalibeder** [comment]
No worries, thanks for the thought! Hopefully someone else has an idea.

**Comment by mfazekas** [comment]
According to the style spec no expression (data drive styling) is supported for this:
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-circle-circle-translate-anchor

maybe our docs needs to be fixed?!
https://github.com/react-native-mapbox-gl/maps/blob/master/docs/CircleLayer.md#name-11

**Comment by ferdicus** [comment]
> According to the style spec no expression (data drive styling) is supported for this:
> https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-circle-circle-translate-anchor
> 
> maybe our docs needs to be fixed?!
> https://github.com/react-native-mapbox-gl/maps/blob/master/docs/CircleLayer.md#name-11

Hmm, yeah we don't seem to consume the full info from `v8.json` when generating the docs:
```
    "circle-translate-anchor": {
      "type": "enum",
      "values": {
        "map": {
          "doc": "The circle is translated relative to the map."
        },
        "viewport": {
          "doc": "The circle is translated relative to the viewport."
        }
      },
      "doc": "Controls the frame of reference for `circle-translate`.",
      "default": "map",
      "requires": [
        "circle-translate"
      ],
      "sdk-support": {
        "basic functionality": {
          "js": "0.10.0",
          "android": "2.0.1",
          "ios": "2.0.0",
          "macos": "0.1.0"
        }
      },
      "expression": {
        "interpolated": false,
        "parameters": [
          "zoom"
        ]
      },
      "property-type": "data-constant"
    },
```

I could have a go at this, if you'd like @mfazekas
