### ISSUE TITLE
MarkerView & PointAnnotation doesn't work on Android

### ISSUE THREAD

**Issue by johnneuland** [react-native-mapbox-gl/maps#993]
**Describe the bug**

Within my map, I need to mark a **single** coordinate. I have tried using PointAnnotations but it only worked in iOS and not Android. Every time, I opened the map screen on Android, I got an error **Index:2, size:1**. 

Now, I am trying to use MarkerView. I cloned the example app from this repo and tested it there (iOS). It worked fine for iOS. However, now I am trying to use it in my app (Android) and it doesn't work there. I get the same **Index:2, size:1** error.

**To Reproduce**
```
export const MapContainer: React.FunctionComponent = () => {
  const AnnotationContent = ({ title }: any) => (
    <View style={{ alignItems: 'center', width: 80 }}>
      <View
        style={{
          backgroundColor: 'white',
          borderRadius: 10,
          flex: 1,
        }}>
        <Text>{title}</Text>
      </View>
 <Icon name="map-marker" color="#31C283" size={45} />
    </View>
  );

  return (
    <MapboxGL.MapView
      style={styles.map}
      logoEnabled={false}
      localizeLabels={true}>
      <MapboxGL.Camera
        zoomLevel={15}
        animationMode={'flyTo'}
        animationDuration={2000}
        centerCoordinate={coordinates}
      />
      <MapboxGL.PointAnnotation
        id={favouritePlaceId.toString()}
        title={customisedName}
        coordinate={coordinates}>
        <MapboxGL.Callout title={customisedName} />
      </MapboxGL.PointAnnotation>
      {/* <MapboxGL.MarkerView id={favouritePlaceId.toString()} coordinate={coordinates}>
            <AnnotationContent title={'this is a marker view'} />
 </MapboxGL.MarkerView> */}
    </MapboxGL.MapView>
  );
};

export const styles = StyleSheet.create({
  map: {
    flex: 1,
  },
});
```

**Expected behavior**

I should be able to mark a point on both, Android and iOS.

**Versions:**

 - Device: [Samsung Galaxy Note 5]
 - Emulator/ Simulator: [no]
- "@react-native-mapbox-gl/maps": "^8.1.0-rc.2",
- React Native: 3.0.4

**Additional context**

I have also thought about using SymbolLayer but I couldn't figure out how to mark a **single** point using it.

![thumbnail_Screenshot_20200814-130228](https://user-images.githubusercontent.com/69582269/90481526-36aad080-e132-11ea-8502-fd05244db14a.png)

**Comment by ferdicus** [comment]
Question, because I didn't get it from your description.
You tried the example app and it didn't work, or you didn't try the example app?

Could it be, that any of your variables might not be defined?

**Comment by nhammad** [comment]
- For point annotations, I tried it in my own app. It worked on iOS but not on Android. If I comment out the point annotations part, and just leave the map view and camera view, that works on Android. But not the annotations.

For the MarkerView, I tried it in the example app and it worked (iOS). I used the same code in my own Android app but it doesn't work. It gives the index error again.

**Comment by johnneuland** [comment]
For point annotations, I tried it in my own app. It worked on iOS but not on Android. If I comment out the point annotations part, and just leave the map view and camera view, that works on Android. But not the annotations.

For the MarkerView, I tried it in the example app and it worked (iOS). I used the same code in my own Android app but it doesn't work. It gives the index error again.

**Comment by mfazekas** [comment]
@johnneuland pls share the full error, thanks!

**Comment by johnneuland** [comment]
> @johnneuland pls share the full error, thanks!

please see the attached screenshot

**Comment by mfazekas** [comment]
@johnneuland pls simplify your code until the error dissapears, for example not sure what `AddressTextBox` is doing there.

**Comment by johnneuland** [comment]
That's not what's causing the problem. If I remove the pointAnnotation/MarkerView, then it gives no error on android. But if I add either of them, it only works on iOS and not Android.

**Comment by mfazekas** [comment]
Also PointAnnotation and marker view should have child views to display.

```
<PointAnnotation coordinate={coordinates}>
<View>
 <Text>Hello</Text>
</View>
</PointAnnotaiton>
```

**Comment by johnneuland** [comment]
PointAnnotation doesn't work even if I wrap the content in a View. The MarkerView worked for a second but then I reloaded the app and it's not working ever since then. Same index error. Even when it worked, it only showed the logo (not the annotation like in iOS).

**Comment by johnneuland** [comment]
After making some minor changes in the MapContainer and annotationsContent, I am able to see It on Android too. 
```
export const MapContainer: React.FunctionComponent = () => {

  const AnnotationContent = ({ title }: TitleProps) => (
    <View
      style={{
        alignItems: 'center',
        width: 90,
        backgroundColor: 'transparent',
        height: 100,
      }}>
      <View
        style={{
          backgroundColor: 'white',
          borderRadius: 10,
          flex: 1,
          flexDirection: 'row',
          alignItems: 'center',
        }}>
        <Text
          style={{ textAlign: 'center', paddingHorizontal: moderateScale(5) }}>
          {title}
        </Text>
      </View>

      <Icon
        style={{
          paddingTop: 10,
        }}
        name="map-marker"
        color="#31C283"
        size={45}
      />
    </View>
  );

  return (
    <MapboxGL.MapView
      style={styles.map}
      logoEnabled={false}
      localizeLabels={true}>
      <MapboxGL.Camera
        zoomLevel={15}
        animationMode={'flyTo'}
        animationDuration={1100}
        centerCoordinate={coordinates}
      />
{Platform.OS === 'ios' &&  <AddressTextBox placeName={placeName} />}
      {/* <View>
      <AddressTextBox placeName={placeName} />
      </View> */}

      <View>
        <MapboxGL.MarkerView
          id={favouritePlaceId.toString()}
          coordinate={coordinates}>
          <View>
            <AnnotationContent title={customisedName} />
          </View>
        </MapboxGL.MarkerView>
      </View>
    </MapboxGL.MapView>
  );
};
```

However, I am still unable to use the AddressTextBox component in Android. It works perfectly in iOS but gives this index error in Android. Here's what the component looks like:
```
export const AddressTextBox: React.FunctionComponent<AddressTextBoxProps> = ({
  placeName,
}) => {
  return (
    <View style={styles.textBox}>
      <Text style={styles.text}>{placeName}</Text>
    </View>
  );
};

export const styles = StyleSheet.create({
  textBox: {
    backgroundColor: 'white',
    height: moderateScale(50),
    width: '70%',
    marginTop: moderateScale(40),
    alignSelf: 'center',
    borderRadius: moderateScale(20),
    borderColor: '#383838',
    borderWidth: 0.3,
    alignItems: 'center',
    flexDirection: 'row',
  },
  text: {
    fontSize: moderateScale(13),
    flex: 1,
    marginHorizontal: 10,
    textAlign: 'center',
  },
});
```

According to this, it's not possible to render a view inside mapView, but how does it work for iOS then? Does this still apply?
https://github.com/nitaliano/react-native-mapbox-gl/issues/1488

**Comment by ferdicus** [comment]
That is another issue though.

The answer to your other questions was also already answered in 
nitaliano/react-native-mapbox-gl#1488

Use a component outside of MapView and via position absolute move it wherever you like.


Closing this as resolved

**Comment by raazatul7** [comment]
`<MapboxGL.MapView
          ref={c => (this._map = c)}
          logoEnabled={false}
          style={{flex: 1}}>
          <MapboxGL.Camera
            ref={c => (this.camera = c)}
            zoomLevel={14}
            centerCoordinate={this.state.currentLatLng}
          />
          {/* User location */}
          <MapboxGL.PointAnnotation
            key={'9090'}
            id={'9090'}
            coordinate={this.state.currentLatLng}
            title="">
            <View style={styles.annotationContainer}>
              <Image
                source={location_pin}
                resizeMode={'contain'}
                style={{height: wp('10%'), width: wp('10%')}}
              />
            </View>
            <MapboxGL.Callout title={'You'} />
          </MapboxGL.PointAnnotation>
        </MapboxGL.MapView>`

What wrong with this? It is not working on Android.
iOS is working fine.
