### ISSUE TITLE
SymbolLayer don't work when we have an App Off-line

### ISSUE THREAD

**Issue by renanfmartins** [react-native-mapbox-gl/maps#994]
**Describe the bug**

After I created a package off-line related an region, when I tried to render the **MapView** with a **ShapeSource** the map don't show nothin related of ShapeSource, if I remove the **SymbolLayer**, the **Mapview** render the **ShapeSource**.

**To Reproduce**

1. Create an off-line package related a region, before to render the Mapview.
2. Access the Mapview with a ShapeSource and this ShapeSource need to  have an SymbolLayer and that SymbolLayer need to have an text.

**Screen shoot**

![screenshot](https://user-images.githubusercontent.com/64802419/90455771-4fcd6600-e0cd-11ea-9c9b-08d010acaaee.png)

**Expected behavior**

I should be able to see the map with a shapes and this shapes with text on the map.

**Versions (please complete the following information):**

 - Platform: [Android]
 - Device: [Asus ZenFone 5 (ZE620KL)]
 - Emulator/ Simulator: [ no]
 - OS: [Android 9]
 - react-native-mapbox-gl Version [8.1.0-rc.2]
 - React Native Version [0.61.5]

**Additional context**

On the SymbolLayer I don't specify a font, I tried to used the font of library.

**Comment by dedeco** [comment]
Same error!

**Comment by fabriciomirandabr** [comment]
I think we have a similar issue, but the guy doesn't  talked if this was resolved

https://github.com/react-native-mapbox-gl/maps/issues/774

**Comment by mfazekas** [comment]
I think this is #3 from https://github.com/react-native-mapbox-gl/maps/issues/774#issuecomment-609831147

> If a SymbolLayer has a symbol with text and the map is offline, and the font used to render the symbol label has not been cached then the symbols will not be displayed. It seems that even symbols without label will be omitted from such layer.

It's an upstream issue, not much we can do with that.
